#!/usr/bin/env bash

function echo_if_executable_test() (
	source "$DOROTHY/sources/bash.bash"

	eval-tester --name='no args' -- \
		echo-if-executable --

	eval-tester --name='empty args' -- \
		echo-if-executable -- '' ''

	eval-tester --name='missing' -- \
		echo-if-executable -- "$DOROTHY/this-does-not-exist"

	eval-tester --name='directory' --stdout="$DOROTHY" -- \
		echo-if-executable -- "$DOROTHY"

	eval-tester --name='file' --stdout="$DOROTHY/commands/dorothy" -- \
		echo-if-executable -- "$DOROTHY/commands/dorothy"

	eval-tester --name='file then missing then dir' --stdout="$DOROTHY/commands/dorothy"$'\n'"$DOROTHY" -- \
		echo-if-executable -- "$DOROTHY/commands/dorothy" "$DOROTHY/this-does-not-exist" "$DOROTHY"

	eval-tester --name='dir then missing then file' --stdout="$DOROTHY"$'\n'"$DOROTHY/commands/dorothy" -- \
		echo-if-executable -- "$DOROTHY" "$DOROTHY/this-does-not-exist" "$DOROTHY/commands/dorothy"

	# test working symlinks
	local root dir_target dir_symlink file_target file_symlink
	root="$(fs-temp --directory='dorothy' --directory='echo-if-executable' --directory='tests')"
	dir_target="$(fs-temp --root="$root" --directory='dir_target' --touch)"
	file_target="$(fs-temp --root="$root" --file='file_target' --touch)"
	dir_symlink="$(fs-temp --root="$root" --directory='dir_symlink' --no-touch)"
	file_symlink="$(fs-temp --root="$root" --file='file_symlink' --no-touch)"
	fs-link --quiet \
		--existing="$dir_target" --symlink="$dir_symlink" \
		--existing="$file_target" --symlink="$file_symlink"

	eval-tester --name='symlink dir' --stdout="$dir_symlink" -- \
		echo-if-executable -- "$dir_symlink"

	eval-tester --name='symlink file' -- \
		echo-if-executable -- "$file_symlink"
	fs-own --quiet --x -- "$file_target"
	eval-tester --name='symlink file' --stdout="$file_symlink" -- \
		echo-if-executable -- "$file_symlink"

	# test broken symlinks
	fs-rm --quiet --no-confirm -- "$dir_target" "$file_target"

	eval-tester --name='broken symlink dir' -- \
		echo-if-executable -- "$dir_symlink"

	eval-tester --name='broken symlink file' -- \
		echo-if-executable -- "$file_symlink"

	return 0
)
function echo_if_executable() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >&2
			ABOUT:
			Output <input>s that are paths that are executable (including that of symlinks, broken or otherwise).
			Companion to [is-executable].

			USAGE:
			echo-if-executable [...options] [--] ...<input>
			echo-lines ...<input> | echo-if-executable [...options]

			OPTIONS:
			--elevated=<elevated>
			--elevate=<elevate>
			--user=<user>
			--group=<group>
			--reason=<reason>
			    Forwarded to [eval-helper].

			$(__stdinargs__help_options --)

			EXAMPLES:

			echo-if-executable -- "$HOME"

			    $HOME
			    # exit status: 0

			echo-lines -- "$HOME" | echo-if-executable --stdin

			    $HOME
			    # exit status: 0
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_args=() option_elevated='' option_elevate='' option_user='' option_group='' option_reason=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		# <elevate>
		'--elevated='*) option_elevated="${item#*=}" ;;
		'--no-elevate'* | '--elevate'*) __flag --source={item} --target={option_elevate} --affirmative ;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--reason='*) option_reason="${item#*=}" ;;
		# </elevate>
		# forward to stdinargs, however support mixing and matching of our options, with stdinargs options
		'--')
			option_args+=("$item" "$@")
			shift $#
			break
			;;
		*) option_args+=("$item") ;;
		esac
	done

	# =====================================
	# Action

	function __on_piece {
		local path="$1"
		if is-executable --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- "$path"; then
			__print_lines "$path"
		fi
	}

	stdinargs "${option_args[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_if_executable_test
	else
		echo_if_executable "$@"
	fi
fi
