#!/usr/bin/env bash

function echo_escape_special_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- echo-escape-special --help
)

function echo_escape_special() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			For each input, output its escaped form.

			USAGE:
			echo-escape-special [...options] [--] ...<input>
			echo-lines ...<input> | echo-escape-special [...options]

			OPTIONS:
			$(__stdinargs__help_options --)

			EXAMPLES:

			echo-escape-special -- "\$(echo-style --green=sup)"

			    $'\E[32msup?\E[39m'
			    # exit status: 0

			echo-style --green=sup | echo-escape-special --stdin

			    $'\E[32msup?\E[39m'
			    # exit status: 0
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_line {
		printf '%q%s' "$1" "$'\n'"
	}
	function on_inline {
		printf '%q' "$1"
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_escape_special_test
	else
		echo_escape_special "$@"
	fi
fi
