#!/usr/bin/env bash

function echo_escape_special() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			For each input, output its escaped form.

			USAGE:
			echo-escape-special [...options] [--] ...<input>
			echo-lines ...<input> | echo-escape-special [...options]

			OPTIONS:
			$(stdinargs_options_help --)

			EXAMPLE:

			echo-escape-special -- "\$(echo-style --green=sup)"

			    $'\E[32msup?\E[39m'
			    # exit status: 0

			echo-style --green=sup | echo-escape-special --stdin

			    $'\E[32msup?\E[39m'
			    # exit status: 0

		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		printf '%q' "$1"
	}

	stdinargs "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_escape_special "$@"
fi
