#!/usr/bin/env bash

function echo_nonflags_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- echo-nonflags --help
)

function echo_nonflags() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Output all arguments that aren't flags.

			USAGE:
			\`echo-nonflags [...options] [--] ...<input>\`
			\`echo-lines ...<input> | echo-nonflags [...options]\`

			OPTIONS:
			$(__stdinargs__help_options --)

			EXAMPLES:
			\`\`\`
			echo-nonflags -- code -a --b c
			\`\`\`
			Outputs:
			\`\`\`
			code
			c
			\`\`\`
			Returns: [0]

			\`\`\`
			echo-lines -- code -a --b c | echo-nonflags --stdin
			\`\`\`
			Outputs:
			\`\`\`
			code
			c
			\`\`\`
			Returns: [0]

			QUIRKS:
			\`\`\`edit --dry | echo-nonflags --stdin\`\`\`
			Outputs: \`code --new-window\`
			Returns: [0]
			This is because it is all on one line, i.e.:
			\`\`\`printf '%s\n' 'code -a --b c' | echo-nonflags --stdin\`\`\`
			Outputs: \`code -a --b c\`
			Returns: [0]
			This is why this is a beta command.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function __on_piece {
		if [[ $1 != -* ]]; then
			__print_lines "$1" || return $?
		fi
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_nonflags_test
	else
		echo_nonflags "$@"
	fi
fi
