#!/usr/bin/env bash

function echo_if_directory() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output inputs that are directories.

			USAGE:
			echo-if-directory [...options] [---] ...<input>
			echo-lines ...<input> | echo-if-directory [...options]

			EXAMPLE:

			mkdir dir
			touch file

			echo-if-file -- dir file directory

			    dir
			    # exit status: 0

			echo-lines -- dir file missing | echo-if-directory --stdin

			    dir
			    # exit status: 0

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		if test -n "$1" -a -d "$1"; then
			print_line "$1"
		fi
	}

	stdinargs "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_if_directory "$@"
fi
