#!/usr/bin/env bash

function echo_nothing_or_fail_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- echo-nothing-or-fail --help
)

function echo_nothing_or_fail() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			If input is provided, fail.
			If no input was provided, success.

			USAGE:
			echo-nothing-or-fail [...options] [--] ...<input>
			echo-lines ...<input> | echo-nothing-or-fail [...options]

			OPTIONS:
			$(__stdinargs__help_options --)

			EXAMPLES:

			# success cases
			echo-nothing-or-fail ''
			echo-nothing-or-fail -- ''
			echo-nothing-or-fail -- 'sup'
			printf '%s\n' 'sup' | echo-nothing-or-fail --stdin

			    # exit status: 1

			# failure cases, no stdin, no arguments
			echo-nothing-or-fail --
			true | echo-nothing-or-fail --stdin

			    # exit status: 0
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	function __on_whole {
		return 1 # failure
	}

	function __on_nothing {
		return 0 # success
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_nothing_or_fail_test
	else
		echo_nothing_or_fail "$@"
	fi
fi
