#!/usr/bin/env bash

function ensure_trailing_slash() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function __help {
		cat <<-EOF >&2 || return $?
			ABOUT:
			Ensure directories have a trailing newline.
			Ensure files do not have a trailing newline.

			USAGE:
			ensure-trailing-slash [--] ...<path>
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@" || return $?
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_paths=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') __help || return $? ;;
		'--')
			option_paths+=("$@")
			shift "$#"
			break
			;;
		'--'*) __help 'An unrecognised flag was provided: ' --variable-value={item} || return $? ;;
		*) option_paths+=("$item") ;;
		esac
	done

	# check
	if [[ ${#option_paths[@]} -eq 0 ]]; then
		__help 'No <path>s was provided.' || return $?
	fi

	# =====================================
	# Action

	local path length
	for path in "${option_paths[@]}"; do
		if [[ -d $path ]]; then
			if [[ $path != */ ]]; then
				__print_lines "$path/" || return $?
			else
				__print_lines "$path" || return $?
			fi
		elif [[ -f $path ]]; then
			if [[ $path == */ ]]; then
				length="${#path}"
				__print_lines "${path:0:length-1}" || return $?
			else
				__print_lines "$path" || return $?
			fi
		else
			__print_error 'Not a file nor directory: ' --path="$path" || return $?
			return 1
		fi
	done
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	ensure_trailing_slash "$@"
fi
