#!/usr/bin/env bash

function is_audio_mono() (
	source "$DOROTHY/sources/bash.bash"

	ffprobe -i "$1" 2>&1 | grep mono
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_audio_mono "$@"
fi
