#!/usr/bin/env bash

function is_almalinux() (
	source "$DOROTHY/sources/bash.bash"

	# NAME="AlmaLinux"
	# ID="almalinux"
	# ID_LIKE="rhel centos fedora"
	is-linux --id='almalinux' || return $?
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_almalinux "$@"
fi
