#!/usr/bin/env bash

function is_fedora() (
	source "$DOROTHY/sources/bash.bash"

	# uname -n = 107d2f9bd11e
	# < /etc/os-release >
	# NAME="Fedora Linux"
	# ID=fedora
	# </ /etc/os-release >
	[[ -f /etc/os-release ]] && grep --quiet --ignore-case --regexp='ID=fedora' -- /etc/os-release 2>/dev/null || return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_fedora "$@"
fi
