#!/usr/bin/env bash

function is_fedora() (
	source "$DOROTHY/sources/bash.bash"

	# `uname -a` is `uname -mnrsv`
	# `uname -a` = `Linux fc3683127f08 6.11.0-1018-azure #18~24.04.1-Ubuntu SMP Sat Jun 28 04:46:03 UTC 2025 x86_64 GNU/Linux`
	# `ID=fedora`
	is-linux --id='fedora' || return $?
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_fedora "$@"
fi
