#!/usr/bin/env bash

function is_neither() (
	source "$DOROTHY/sources/bash.bash"

	local arg
	for arg in "${@:2}"; do
		if [[ $1 == "$arg" ]]; then
			return 1
		fi
	done

	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_neither "$@"
fi
