#!/usr/bin/env bash

function is_suffix() (
	source "$DOROTHY/sources/bash.bash"

	# act
	local needle haystack
	needle="${1:?"USAGE: is-suffix <NEEDLE> <HAYSTACK>"}"
	haystack="${2:?"USAGE: is-suffix <needle> <HAYSTACK>"}"

	# oldschool way:
	# echo-regexp -q "$needle\$" -- "$haystack"

	# better way:
	[[ $needle == "${haystack:${#needle}*-1}" ]]
	return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_suffix "$@"
fi
