#!/usr/bin/env bash

function pdf_decrypt() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Take PDF <input>s that have passwords, and save copies that have the passwords removed.

			USAGE:
			pdf-decrypt [--password=<password>] ...<input>

			EXAMPLE:
			pdf-decrypt -- *.pdf
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_inputs=() option_password=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--password='*) option_password="${item#*=}" ;;
		'--')
			option_inputs+=("$@")
			shift $#
			break
			;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) option_inputs+=("$item") ;;
		esac
	done

	# =====================================
	# Dependencies

	__command_required -- 'qpdf' || return

	# =====================================
	# Act

	local password path file outpath
	password="$(
		ask --required --password \
			--question='Enter the decryption password for the PDFs' \
			--question="$(echo-lines --columns -- "${option_inputs[@]}")" \
			--default="$option_password"
	)"
	for path in "${option_inputs[@]}"; do
		file="$(fs-path --no-parents --no-extensions -- "$path")"
		outpath="$file [decrypted].pdf"
		eval-helper --quiet --no-wrap \
			--pending="$(__print_style --bold='Decrypting ' --code="$path" --bold=' to ' --code="$outpath")" \
			--success="$(__print_style --bold+green='Decrypted ' --code="$path" --bold=' to ' --code="$outpath")" \
			--failure="$(__print_style --bold+red='Failed to decrypt ' --code="$path" --bold=' to ' --code="$outpath")" -- \
			qpdf -password="$password" -decrypt "$path" "$outpath" || :
	done

)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	pdf_decrypt "$@"
fi
