#!/usr/bin/env bash

function wallhaven_helper() (
	source "$DOROTHY/sources/bash.bash"
	__require_array 'mapfile'

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Enter your wallhaven details, and it'll download your wallpaper collections: https://wallhaven.cc

			USAGE:
			wallhaven-helper [--user=...] [--key=...]
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item username='' apikey=''
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--user='*) username="${item#*=}" ;;
		'--key='*) apikey="${item#*=}" ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# essentials
	if test -z "$username"; then
		username="$(
			ask --required \
				--question="Enter the wallhaven username."
		)"
	fi
	if test -z "$apikey"; then
		apikey="$(
			ask --required --password \
				--question="Enter the wallhaven API Key for $username. You can get this from: https://wallhaven.cc/settings/account"
		)"
	fi

	# =====================================
	# Dependencies

	setup-util-deno --quiet
	setup-util-jq --quiet

	# =====================================
	# Act

	# collections
	local collections collection
	mapfile -t collections < <(fetch "https://wallhaven.cc/api/v1/collections?apikey=$apikey" | jq -r '.data[] | (.id, .label)')
	collection="$(
		choose \
			--question='Which collection to download?' \
			--label --visual="\$LABEL [\$VALUE]" \
			-- "${collections[@]}"
	)"

	# run the deno script to fetch the wallpaper urls via the api and store them in a file
	local deno_script
	deno_script="$(command -v 'wallhaven-helper.ts')"
	deno run --allow-net --quiet "$deno_script" "$apikey" "$username" "$collection" | tee "$temp_list_file"

	# with that file, download each of them
	local url
	while read -r url; do
		down "$url"
	done <"$temp_list_file"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	wallhaven_helper "$@"
fi
