#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# Alias to Symlink
src="$(alias-verify "$1")"
if is-empty-string "$src"; then
	echo "skipped $1"
else
	out="$(alias-path "$1")"

	if is-file "$out"; then
		ln -nfs "$out" "$src"
		echo "converted $1 -> $out"
	elif is-dir "$out"; then
		ln -nfs "$out" "$src"
		echo "converted $1 -> $out"
	else
		echo "missing $1 -> $out"
	fi
fi