#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# inputs
path="$(
	ask --required \
		--question="Enter path where you want the macOS alias file to exist." \
		--default="${1-}"
)"
target="$(
	ask --required \
		--question="Enter path where you want the macOS alias file to target." \
		--default="${2-}"
)"

# prepare
targetAbsolute="$(fs-absolute "$target")"
pathAbsolute="$(fs-absolute "$path")"
pathDirectory="$(dirname "$pathAbsolute")"
pathFilename="$(basename "$pathAbsolute")"

# act
if test -d "$targetAbsolute"; then
	type="folder"
elif test -f "$targetAbsolute"; then
	type="file"
else
	stderr echo "Invalid path or unsupported type"
	exit 22 # Invalid argument
fi

if test -f "$pathAbsolute"; then
	rm -rfi "$pathAbsolute"
fi

osascript <<-EOF
	tell application "Finder"
		make new alias to $type (posix file "$targetAbsolute") at (posix file "$pathDirectory")
		set name of result to "$pathFilename"
	end tell
EOF

# make the alias's permissions the same as the target's
chmod "$(stat -f '%p' "$targetAbsolute")" "$pathAbsolute"
#chmod --reference="$targetPath" "$pathAbsolute"
