#!/usr/bin/env bash
source "$BDIR/sources/strict.bash"

# Is an Alias
osascript 2>/dev/null <<EOF
tell application "Finder"
set theItem to (POSIX file "${1}") as alias
if the kind of theItem is "alias" then
get the posix path of ((theItem) as text)
end if
end tell
EOF