#!/usr/bin/env bash
source "$BDIR/sources/strict.bash"

# Android Simulator
app=$(get-app "Android Studio.app")
if is-dir "app"; then
	"$app/sdk/tools/emulator" -avd basic
else
	echo "Android Studio is not installed"
fi