#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

needle="${1?:'USAGE: array-tuple-select key <[key, value], ...>'}"
found='no'

# cycle through the tuples
# remember @:0 is the command, @:1 is the needle, @:2:... is the tuples
for item in "${@:2}"; do
	if test "$found" = 'yes'; then
		echo "$item"
		exit 0
	elif test "$item" = "$needle"; then
		found='yes'
	fi
done

# needle not found
exit 1
