#!/usr/bin/env bash

function ask_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-segment --h1="TEST: $0"

	# ignore stderr as on CI, tty doesn't exist, so the menu is output to stderr
	local ci_args=()
	if is-ci; then
		ci_args+=('--ignore-stderr')
	fi

	eval-tester --name='default response -confirm' --stdout='a default response' \
		-- ask --question='What is your response?' --default='a default response'

	{
		# confirm to enter a value
		sleep 1
		echo
	} | eval-tester --name='default response +confirm' --stdout='a default response' \
		-- ask --question='What is your response?' --default='a default response' --confirm

	{
		# confirm to enter a value
		sleep 1
		echo

		# enter the custom response
		sleep 1
		print_line 'a custom response'
	} | eval-tester --name='custom response -default -confirm' --stdout='a custom response' "${ci_args[@]}" \
		-- ask --question='What is your response?'

	{
		# confirm to enter a value
		sleep 1
		echo

		# enter the custom response
		sleep 1
		print_line 'a custom response'

		# confirm the custom response
		sleep 1
		echo
	} | eval-tester --name='custom response -default +confirm' --stdout='a custom response' "${ci_args[@]}" \
		-- ask --question='What is your response?' --confirm

	{
		# move down and select custom response
		sleep 1
		printf $'\eOB'
		sleep 1
		echo

		# enter the custom response
		sleep 1
		print_line 'a custom response'

		# confirm the custom response
		sleep 1
		echo
	} | eval-tester --name='custom response +default +confirm' --stdout='a custom response' "${ci_args[@]}" \
		-- ask --question='What is your response?' --default='a default response' --confirm

	echo-segment --g1="TEST: $0"
	return 0
)
function ask_() (
	source "$DOROTHY/sources/bash.bash"
	source "$DOROTHY/sources/tty.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Prompt the user for an input value in a clean and robust way.

			USAGE:
			ask [...options]

			OPTIONS:
			--question=<string>
			    Specifies the question that the prompt will be answering.

			--default=<value>
				Specifies the default value if no user specified value is entered.

			--confirm
			    Specifies that the prompt should confirm the value before continuing.

			--password
			    Specifies that the prompt should hide the value when entering by using password mode.

			--required
			    Specifies that the prompt should not continue until a value is provided.

			--timeout=<seconds>
			    Specifies a custom timeout value in seconds.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item args=() option_question='' option_default='' option_password='no' option_required='no' option_confirm='no' option_timeout=''
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--question='*) option_question="${item#*--question=}" ;;
		'--default='*) option_default="${item#*--default=}" ;;
		'--timeout='*) option_timeout="${item#*--timeout=}" ;;
		'--no-password'* | '--password'*)
			option_password="$(get-flag-value password --missing="$option_password" -- "$item" | echo-affirmative)"
			;;
		'--no-required'* | '--required'*)
			option_required="$(get-flag-value required --missing="$option_required" -- "$item" | echo-affirmative)"
			;;
		'--no-confirm'* | '--confirm'*)
			option_confirm="$(get-flag-value confirm --missing="$option_confirm" -- "$item" | echo-affirmative)"
			;;
		'--')
			args+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	# prepare
	local RESULT ASKED='no' tty_target
	tty_target="$(is-tty --fallback)"
	if test -n "$option_default"; then
		RESULT="$option_default"
	else
		RESULT=''
	fi

	# helpers
	function on_timeout {
		if is-value "$RESULT"; then
			echo-style --notice="Ask timed out, using fallback value: " --code="$RESULT" >/dev/stderr
			sleep 5
			print_line "$RESULT"
			return 0
		elif test "$option_required" = 'no'; then
			echo-style --notice='Ask timed out, as the field was optional will use no value.' >/dev/stderr
			sleep 5
			return 0
		else
			echo-style --warning='Ask timed out, with no fallback.' >/dev/stderr
			sleep 5
			return 60 # ETIMEDOUT 60 Operation timed out
		fi
	}
	function do_ask { # has sideffects: RESULT, ASKED
		local read_status
		tty_auto
		ASKED='yes' # not local
		if test -n "${1-}"; then
			print_line "$1" >"$tty_target"
		fi
		while true; do
			read_status=0 && read -r -t 300 -r -p '> ' RESULT || read_status=$?
			if test "$read_status" -eq 142; then
				return 60 # ETIMEDOUT 60 Operation timed out
			fi
			if is-value "$RESULT"; then
				break
			elif test "$option_required" = 'no'; then
				RESULT=''
				break
			fi
		done
		do_validate
	}
	function do_validate {
		local choose_status ask_status choice choices=()
		if is-value "$RESULT"; then
			# we have a value, so go for it
			if test "$option_confirm" != 'yes'; then
				print_line "$RESULT"
				return 0
			fi
			# proceed with confirm
			if test "$ASKED" = 'yes'; then
				if test "$option_password" = 'yes'; then
					choices+=('existing' 'use the entered password')
				else
					choices+=('existing' "use the entered value: [$RESULT]")
				fi
			else
				if test "$option_password" = 'yes'; then
					choices+=('existing' 'use the preconfigured password')
				else
					choices+=('existing' "use the preconfigured value: [$RESULT]")
				fi
			fi
		fi
		if test "$ASKED" = 'yes'; then
			choices+=('custom' 'redo the entered value')
		else
			choices+=('custom' 'enter a value')
		fi
		if test "$option_required" = 'no'; then
			choices+=('none' 'use no value')
		fi

		# as need to confirm, adjust the timeout
		if test -z "$option_timeout" && (is-value "$RESULT" || test "$option_required" = 'no'); then
			# timeout of one minute for confirms of existing values, or optional values
			option_timeout=60
		fi

		# ask
		eval_capture --statusvar=choose_status --stdoutvar=choice -- \
			choose-option \
			--timeout="$option_timeout" \
			--question="$option_question" \
			--label -- "${choices[@]}"

		# check
		if test "$choose_status" -eq 60; then
			echo-style --error="Choose timed out: $choose_status" >/dev/stderr
			on_timeout
			return
		elif test "$choose_status" -ne 0; then
			echo-style --error="Choose failed: $choose_status" >/dev/stderr
			sleep 5
			return "$choose_status"
		fi

		# handle
		if test "$choice" = 'existing'; then
			# done, sucess
			print_line "$RESULT"
			return 0
		elif test "$choice" = 'custom'; then
			# ask
			eval_capture --statusvar=ask_status -- do_ask "$option_question"

			# check for failure
			if test "$ask_status" -ne 0; then
				# timeout probably
				on_timeout
				return
			fi

			# done, success
			return 0
		elif test "$choice" = 'none'; then
			# done, sucess
			echo
			return 0
		else
			# unknown error
			echo-style --error="Invalid choice: $choice" >/dev/stderr
			sleep 5
			return 14 # EFAULT 14 Bad address
		fi
	}

	# act
	do_validate
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	if test "$*" = '--test'; then
		ask_test
	else
		ask_ "$@"
	fi
fi
