#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if is-help-empty "$@"; then
	stderr echo "backup <destination-parent-path> <path-to-backup...>"
	exit 1
fi

for arg in "${@:2}"; do
	rsync -a --progress "$arg" "$1"
done
