#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
# we can assume [HOMEBREW_ARCH, HOMEBREW_PREFIX] have already been provided

# Without this command, using HOMEBREW_ARCH=x86_64 on Apple Silicon will fail with:
# ```
# Error: Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
# Please create a new installation in /opt/homebrew using one of the
# "Alternative Installs" from:
#   https://docs.brew.sh/Installation
# You can migrate your previously installed formula list with:
#   brew bundle dump
# brew on desired architecture
# ```

if test -x "${HOMEBREW_PREFIX}/bin/brew"; then
	arch "-${HOMEBREW_ARCH}" "${HOMEBREW_PREFIX}/bin/brew" "$@"
else
	stderr echo 'brew not installed'
	exit 1
fi
