#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/essentials.sh"

# brew on desired architecture
arch -${HOMEBREW_ARCH:-x86_64} ${HOMEBREW_PREFIX:-/usr/local}/bin/brew "$@"
