#!/usr/bin/env bash

# Without this command, using HOMEBREW_ARCH=x86_64 on Apple Silicon will fail with:
# ```
# Error: Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
# Please create a new installation in /opt/homebrew using one of the
# "Alternative Installs" from:
#   https://docs.brew.sh/Installation
# You can migrate your previously installed formula list with:
#   brew bundle dump
# brew on desired architecture
# ```

function __brew() (
	source "$DOROTHY/sources/bash.bash"

	# get the homebrew binary
	local brew_bin=''
	if [[ -n ${HOMEBREW_PREFIX-} ]]; then
		brew_bin="$HOMEBREW_PREFIX/bin/brew"
		if [[ ! -x $brew_bin ]]; then
			brew_bin=''
		fi
	fi
	function __brew {
		# if missing
		if [[ -z $brew_bin ]]; then
			if is-mac; then
				__print_style --error1='Homebrew is not installed.' --notice1=' Install it with: ' --code-notice1='setup-mac-brew' || return
			else
				__print_style --error1='Homebrew is not installed.' || return
			fi
			return 74 # EPROGUNAVAIL 74 RPC prog. not avail
		fi
		# execute
		if [[ -n ${HOMEBREW_ARCH-} ]]; then
			arch -"$HOMEBREW_ARCH" \
				"$brew_bin" "$@" || return
		else
			"$brew_bin" "$@" || return
		fi
	}

	# help
	function __help {
		__brew --help || return
		__print_line || return
		cat <<-EOF || return
			Dorothy extends the brew command to:
			- enforce the correct prefix on macOS and Linux via [HOMEBREW_PREFIX = ${HOMEBREW_PREFIX-}]
			    - this ensures brew invokes homebrew, even when PATH is incorrect and when default brew is not homebrew
			- enforce the appropriate architecture on macOS via [HOMEBREW_ARCH = ${HOMEBREW_ARCH-}]

			Dorothy shell environments are configured to:
			- ensure all homebrew environment variables are configured correctly
			- disable auto updates on macOS, as Dorothy handles that better via [setup-mac-brew]
			- disable brew environment hints, as Dorothy handles that better via [setup-environment-commands]
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# output help
	if [[ $* == '--help' ]]; then
		__help >&2 || return
	else
		__brew "$@" || return
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	__brew "$@"
fi
