#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/arrays.bash"
requires_array_support 'mapfile'

function choose-path() (
	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Select a basename from a series of paths, outputting the selection as an absolute path.

			USAGE:
			choose-path [...options forwarded to choose-option] -- ...<paths>
		EOF
		return 22 # Invalid argument
	}

	# process
	local item paths=() options=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--')
			paths+=("$@")
			shift "$#"
			break
			;;
		*) options+=("$item") ;;
		esac
	done

	# =====================================
	# Action

	# adjust args to paths and basenames
	local values=()
	mapfile -t values < <(echo-paths-and-basenames "${paths[@]}")

	# ask with label
	if test "${#options[@]}" -eq 0; then
		help "No options were provided."
	else
		choose-option --label "${options[@]}" -- "${values[@]}"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	choose-path "$@"
fi
