#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/splitlines.bash"

directories="$(expand-path "$1")"

select directory in $directories; do
	echo -n "$directory"
	exit 0
done

