#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/arrays.bash"
if test "$ARRAYS" = 'no'; then
	echo "Array support required for: $0 $*" >/dev/stderr
	exit 95 # Operation not supported
fi

# prepare
mapfile -t opts < <(echo-before-separator "$@")
mapfile -t args < <(echo-after-separator "$@")

# ask with label
mapfile -t values < <(echo-paths-and-basenames "${args[@]}")
choose-option "${opts[@]}" --label -- "${values[@]}"
