#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/splitlines.bash"

path="${1:?"USAGE: choose-path <PATH> [filter]"}"
filter="${2-}"

if test -n "$path"; then
	cd "$path" || exit 1
fi
if test -n "$filter"; then
	# dependencies
	env QUIET=y setup-util-ripgrep
	# perform filter
	lines="$(ls -1 | rg --smart-case "$filter")"
else
	lines="$(ls -1)"
fi

if test -z "$lines"; then
	exit 1
fi

select line in $lines; do
	fs-absolute "$line"
	exit "$?"
done
