#!/usr/bin/env bash

function command_exists() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Returns success exit code if all <command>s are available.

			USAGE:
			command-exists [--] ...<command>
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_commands=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--')
			option_commands+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) option_commands+=("$item") ;;
		esac
	done

	# check
	if test "${#option_commands[@]}" -eq 0; then
		help 'No <command> was provided.'
	fi

	# =====================================
	# Action

	local command
	for command in "${option_commands[@]}"; do
		if type -P "$command" &>/dev/null; then
			continue
		else
			return 1 # command missing
		fi
	done
	# all commands are present
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	command_exists "$@"
fi
