#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# 0=yes
# 1=no

function confirmer() {
	local ec

	# prompt the user
	# timeout one hour
	ec=0; read -t 3600 -r -n 1 -p "$1 (y/n) " answer || ec="$?"
	if test "$ec" -gt 128; then
		return 62 # Timer expired
	elif test "$ec" -ne 0; then
		return "$ec"
	fi

	# check for strange answers
	if test "$answer" = $'\x1b'; then
		# escape key should equal no
		return 1  # 1=n0
	elif test "$answer" = ''; then
		# no answer / enter key
		echo  # newline, otherwise everything on same line
		# ask again
		confirmer "$1"
		return "$?"  # return with the above on success and failure
	fi

	# check their answer
	ec=0; is-affirmative "$answer" || ec="$?"

	# check if indeterminate, if so, ask again
	if test "$ec" -eq 2; then
		echo  # newline, otherwise everything on same line
		confirmer "$1"
		return "$?"  # return with the above on success and failure
	fi

	# return if determinate
	echo # also add a newline as y/n do not
	return "$ec"
}

# confirm with the user
confirmer "$1"
exit "$?"  # exit with the above on success and failure