#!/usr/bin/env bash
# no strict, as read errors on timeout, so we need to capture that

# only yes should be yes
# anything that is not yes should no

# timeout, escape, enter, should be no
# y, Y should be yes

# yes being a success exit code (0)
# no being a failure exit code (1)

echo -ne "${1?"USAGE: confirm-negative <message>"} (y/N) "
read -t 60 -r -n 1 answer
if test "$?" -gt 128; then
	# timeout occured
	exit 1
fi
echo ""

test "$answer" = 'y' -o "$answer" = 'Y'
