#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=y setup-util-sd

# options
file="$1"      # /etc/systemd/resolved.conf
find="$2"      # Domains
pattern="^[#]?$find=.+?\n"
replace="$3"   # Domains=~.

# act, replacing at the end
sudo touch "$file"
contents="$(sd -p "$pattern" '' < "$file")"
if test -n "$contents"; then
	contents+="\n"
fi
echo -e "$contents$replace" | sudo tee "$file" &> /dev/null  # silent everything
