#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# @todo: what is the different between contains-string, contains-word, contains-line?

# https://stackoverflow.com/a/240181
grep -q "${2:?'USAGE: contains-string <string> <NEEDLE>'}" <<<"${1:?'USAGE: contains-string <STRING> <NEEDLE>'}"
