#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# @todo figure out how to make --eval compatible with paths that have spaces

# copy everything from one location to another preserving properties
if is-help "$@"; then
	stderr echo-lines \
		'ABOUT:' \
		'Copy everything from one location to another:' \
		'- preserves attributes' \
		'- progress updates' \
		'- local and remote sources' \
		'' \
		'USAGE:' \
		'cpr [...flags] -- <source> <destination>' \
		'cpr [...flags] <--source=...> <--destination=...>' \
		'' \
		'FLAGS:' \
		'Provide [--tool=...] to skip tool prompt.' \
		'Provide [--action=...] to skip action prompt.' \
		'Provide [--checksum] to have rsync compare by checksum instead of by the default of file size and mod time.' \
		'Provide [--remove] to have rsync remove source files as they are copied over.' \
		'Provide [--eval] to echo the command that would otherwise run, so that you can call it instead.' \
		'Provide [--sudo] to have the command run as sudo.' \
		'Provide [--no-confirm] to continue without trailing slashes if they are missing.'
	exit 22 # Invalid argument
fi

# options
mapfile -t options < <(echo-before-separator "$@")
mapfile -t args < <(echo-after-separator "$@")
_source="$(ask --question="Enter the source path." --default="${args[0]-}" --flag=source -- "${options[@]}")"
_destination="$(ask --question="Enter the destination path." --default="${args[1]-}" --flag=destination -- "${options[@]}")"
_action="$(get-flag-value action -- "${options[@]}")" # confirmed later
_tool="$(get-flag-value tool -- "${options[@]}")" # confirmed later
_remove="$(get-flag-value remove -- "${options[@]}")"
_sudo="$(get-flag-value sudo -- "${options[@]}")"
_eval="$(get-flag-value 'eval' -- "${options[@]}")"
_checksum="$(get-flag-value checksum -- "${options[@]}")"
_confirm="$(get-flag-value confirm -- "${options[@]}")"

# warn if given paths without trailing slashes
if test "${_source:(-1)}" != '/' -o "${_destination:(-1)}" != '/'; then
	if test "$_confirm" != 'no'; then
		confirm="$(choose-option --question="You have provided paths that do not have trailing slashes:\nsource: ${_source}\ndestination: ${_destination}\n\nThis is fine if they are files, however if they are directories, this means the source directory will go inside the destination directory. Using trailing slashes to ensure that the contents of the source directory go inside the destination directory.\n\nWhat do you want to do?" -- 'add trailing slashes' 'ignore trailing slashes (they are files)' 'exit and rethink')"
		if [[ "$confirm" = *'add'* ]]; then
			echo 'adjusted:' > /dev/tty
			if test "${_source:(-1)}" != '/'; then
				_source="${_source}/"
				echo "source: $_source" > /dev/tty
			fi
			if test "${_destination:(-1)}" != '/'; then
				_destination="${_destination}/"
				echo "destination: $_destination" > /dev/tty
			fi
		elif [[ "$confirm" = *'ignore'* ]]; then
			echo 'ignoring'
		else
			exit 1
		fi
		sleep 5
	fi
fi

# Prepare
actions=(
	copy
	verify
)
flags=()
tools=()
precmd=()

# Determine sudo
if test "$_sudo" = 'yes'; then
	precmd+=(sudo)
fi

# Determine action
action="$(choose-option --question='Which action do you wish to take?' --filter="${_action}" -- "${actions[@]}")"

# Determine available tools for the action
if test "$action" = 'verify'; then
	if command-exists rsync; then
		tools+=(rsync)
	fi
	if command-exists diff; then
		tools+=(diff)
	fi
	if command-exists git; then
		tools+=(git)
	fi
elif test "$action" = 'copy'; then
	if command-exists rsync; then
		tools+=(rsync)
	fi
	if command-exists gcp; then
		tools+=(gcp)
	fi
	if command-exists scp; then
		tools+=(scp)
	fi
	if command-exists cp; then
		tools+=(cp)
	fi
else
	stderr echo "unkown action, available actions are:"
	stderr echo-lines "${actions[@]}"
	exit 1
fi

# Determine tool
tool="$(choose-option --question='Which tool do you wish to use?' --filter="${_tool}" -- "${tools[@]}")"

function rethink {
	suggestion="$(silent-stderr get-local-to-remote "$1" || echo '')"
	if test -n "$suggestion"; then
		echo 'Using rsync with a remote directory that is mounted locally can be slow, you should probably try converting it to a local mount point.'
		echo
		echo "$suggestion"
		echo
		echo 'Alternatively, select copy via a different tool, as they can be faster are more reliable under these circumstances.'
		echo ''
		tangent="$(choose-option --question='What would you like to do?' --label -- \
			'exit' 'rethink and exit' \
			'ignore' 'ignore suggestion and continue anyway' \
			'different' 'try a different tool')"
		if test "$tangent" = 'ignore'; then
			echo 'Continuing as is...'
			return 0
		elif test "$tangent" = *'different'; then
			cpr --action="$action" --source="$_source" --destination="$_destination"
			return $?
		else
			# exit / default
			return 1
		fi
	fi
	return 0
}

# action
if test "$tool" = 'rsync'; then
	# via rsync, file by file progress

	# verify
	if test "$action" = 'verify'; then
		# -i, --itemize-changes       output a change-summary for all updates
		flags+=('--itemize-changes')
		# -n, --dry-run               show what would have been transferred
		flags+=('--dry-run')
	else
		# check if remote and destination are locally mounted remote folders
		rethink "$_source"
		rethink "$_destination"
	fi

	# --archive, -a: archive mode; equals -rlptgoD (no -H,-A,-X)
	#   --recursive, -r: recurse into directories
	#   --links, -l: copy symlinks as symlinks
	#   --perms, -p: preserve permissions
	#   --times, -t: preserve modification times
	#   --group, -g: preserve group
	#   --owner, 0o: preserve owner (super-user only)
	#   -D: same as --devices --specials
	#   --devices: preserve device files (super-user only)
	#   --specials: preserve special files
	flags+=('--archive')

	# --human-readable, -h: output numbers in a human-readable format
	flags+=('--human-readable')

	# --checksum, -c: skip based on checksum, not mod-time & size
	if test "$_checksum" = 'yes'; then
		flags+=('--checksum')
	fi

	# -P: same as --partial --progress
	# --partial: keep partially transferred files
	# --progress: show progress during transfer
	flags+=('-P')

	# linux
	if is-linux; then
		# --acls, -A: preserve ACLs (implies --perms)
		flags+=('--acls')

		# --xattrs, -X: preserve extended attributes
		flags+=('--xattrs')

		# --atimes, -U: preserve access (use) times
		flags+=('--atimes')

		# --crtimes, -N: preserve create times (newness)
		# --crtimes not supported on ubuntu server on arm, nor manjero on x86
		# flags+=('--crtimes')
	fi

	# remove
	if test "$_remove" = 'yes'; then
		flags+=('--remove-source-files')
	fi

	# run
	echo "${precmd[@]}" rsync "${flags[@]}" "$_source" "$_destination"
	if test "$_eval" != 'yes'; then
		"${precmd[@]}" rsync "${flags[@]}" "$_source" "$_destination"
	fi

elif test "$tool" = 'gcp'; then
	# via gcp, overall progress

	# verify
	if test "$action" = 'verify'; then
		stderr echo 'verify not supported with gcp'
		exit 1
	fi

	# -a, --archive: same as -dR --preserve=all
	# -d: same as --no-dereference --preserve=links
	# -R, -r, --recursive: copy directories recursively
	# --preserve PRESERVE: preserve specified attributes; accepted values: 'all', or one or more amongst {'ownership', 'timestamps', 'mode'}
	flags+=('--archive')

	# -v, --verbose: display what is being done
	flags+=('--verbose')

	# run
	echo "${precmd[@]}" gcp "${flags[@]}" "$_source" "$_destination"
	if test "$_eval" != 'yes'; then
		"${precmd[@]}" gcp "${flags[@]}" "$_source" "$_destination"
	fi

elif test "$tool" = 'scp'; then
	# via scp

	# verify
	if test "$action" = 'verify'; then
		stderr echo 'verify not supported with scp'
		exit 1
	fi

	# -A: Allows forwarding of ssh-agent(1) to the remote system.  The default is not to forward an authentication agent.
	flags+=('-A')

	# -p: Preserves modification times, access times, and modes from the original file.
	flags+=('-p')

	# -r: Recursively copy entire directories.  Note that scp follows symbolic links encountered in the tree traversal.
	flags+=('-r')

	# run
	echo "${precmd[@]}" scp "${flags[@]}" "$_source" "$_destination"
	if test "$_eval" != 'yes'; then
		"${precmd[@]}" scp "${flags[@]}" "$_source" "$_destination"
	fi

elif test "$tool" = 'cp'; then
	# via cp

	# verify
	if test "$action" = 'verify'; then
		stderr echo 'verify not supported with cp'
		exit 1
	fi

	# -a: Same as -pPR options. Preserves structure and attributes of files but not directory structure.
	# -P; If the -R option is specified, no symbolic links are followed.  This is the default.
	# -R: If source_file designates a directory, cp copies the directory and the entire subtree connected at that point.  If the source_file ends in a /, the contents of the directory are copied rather than the directory itself.  This option also causes symbolic links to be copied, rather than indirected through, and for cp to create spe- cial files rather than copying them as normal files.  Created directories have the same mode as the corresponding source direc- tory, unmodified by the process' umask.
	flags+=('-a')

	# -L: If the -R option is specified, all symbolic links are followed.
	flags+=('-L')

	# -p: Cause cp to preserve the following attributes of each source file in the copy: modification time, access time, file flags, file mode, user ID, and group ID, as allowed by permissions.  Access Control Lists (ACLs) and Extended Attributes (EAs), including resource forks, will also be preserved.
	flags+=('-p')

	# -f: If the destination file cannot be opened, remove it and create a new file, without prompting for confirmation regardless of its permissions.
	flags+=('-f')

	# -v: Cause cp to be verbose, showing files as they are copied.
	flags+=('-v')

	# run
	echo "${precmd[@]}" cp "${flags[@]}" "$_source" "$_destination"
	if test "$_eval" != 'yes'; then
		"${precmd[@]}" cp "${flags[@]}" "$_source" "$_destination"
	fi

elif test "$tool" = 'diff'; then

	# -q  --brief: Output only whether files differ.
	flags+=('--brief')

	# -r  --recursive: Recursively compare any subdirectories found.
	flags+=('--recursive')

	# run
	echo "${precmd[@]}" diff "${flags[@]}" "$_source" "$_destination"
	if test "$_eval" != 'yes'; then
		"${precmd[@]}" diff "${flags[@]}" "$_source" "$_destination"
	fi

elif test "$tool" = 'git'; then

	# --no-index: This form is to compare the given two paths on the filesystem. You can omit the --no-index option when running the command in a working tree controlled by Git and at least one of the paths points outside the working tree, or when running the command outside a working tree controlled by Git. This form implies --exit-code.
	flags+=('--no-index')

	# run
	echo "${precmd[@]}" git diff "${flags[@]}" "$_source" "$_destination"
	if test "$_eval" != 'yes'; then
		"${precmd[@]}" git diff "${flags[@]}" "$_source" "$_destination"
	fi

else

	stderr echo 'please select a tool'
	exit 1

fi
