#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# copy everything from one location to another preserving properties
_remote="${1:?"USAGE: cpr <REMOTE> <DESTINATION>"}"
_destination="${2:?"USAGE: cpr <remote> <DESTINATION>"}"
if test -d "${_destination}"; then
	if confirm-bool "Destination directory [${_destination}] exists, confirm its deletion"; then
		rm -Rf "${_destination}"
	fi
fi

if command-exists rsync; then
	# via rsync, file by file progress
	# --archive, -a: archive mode; equals -rlptgoD (no -H,-A,-X)
	#   --recursive, -r: recurse into directories
	#   --links, -l: copy symlinks as symlinks
	#   --perms, -p: preserve permissions
	#   --times, -t: preserve modification times
	#   --group, -g: preserve group
	#   --owner, 0o: preserve owner (super-user only)
	#   -D: same as --devices --specials
	#   --devices: preserve device files (super-user only)
	#   --specials: preserve special files
	# --human-readable, -h: output numbers in a human-readable format
	# --checksum, -c: skip based on checksum, not mod-time & size
	# --acls, -A: preserve ACLs (implies --perms)
	# --xattrs, -X: preserve extended attributes
	# --atimes, -U: preserve access (use) times
	# --crtimes, -N: preserve create times (newness)
	# --delete: delete extraneous files from dest dirs
	# --partial: keep partially transferred files
	# --progress: show progress during transfer
	# -P: same as --partial --progress
	if is-mac; then
		rsync -ahcP  "${_remote}" "${_destination}"
		if confirm-bool "Would you like to verify everything copied over?"; then
			rsync -inahcP "${_remote}" "${_destination}"
		fi
	else
		rsync -ahcAXUNP  "${_remote}" "${_destination}"
		if confirm-bool "Would you like to verify everything copied over?"; then
			rsync -inahcAXUNP "${_remote}" "${_destination}"
		fi
	fi
elif command-exists gcp; then
	# via gcp, overall progress
	# -a, --archive: same as -dR --preserve=all
	# -d: same as --no-dereference --preserve=links
	# -R, -r, --recursiveL copy directories recursively
	# -v, --verbose: display what is being done
	# -p: same as --preserve=mode,ownership,timestamps
	# --preserve PRESERVE: preserve specified attributes; accepted values: 'all', or one or more amongst {'ownership', 'timestamps', 'mode'}
	gcp -av "${_remote}" "${_destination}"
else
	# via scp
	# -p: Preserves modification times, access times, and modes from the original file.
	# -r: Recursively copy entire directories.  Note that scp follows symbolic links encountered in the tree traversal.
	scp -Apr "${_remote}" "${_destination}"
fi