#!/usr/bin/env bash
source "$BDIR/sources/strict.bash"
# https://apple.stackexchange.com/a/326863/15131
# https://stackoverflow.com/a/39208361/130638

function wset {
	if is-empty-string "$1"; then
		return 0
	fi
	p="/Users/balupton/Documents/Media/Media - Wallpapers/High Quality"
	if test "$1" = "select"; then
		pp="$p/$(choose-subfolder "$p")"
	else
		pp="$p/$1"
	fi
	osascript -e 'tell application "System Events" to tell current desktop to set pictures folder to "'"$pp"'"'
}
function vset {
	replace-inside "/Users/$(whoami)/Library/Application Support/Code/User/settings.json" "$1" "$2"
}
function mset {
	osascript -e "tell application \"System Events\" to tell appearance preferences to set dark mode to $1"
}

vlight="GitHub Plus"
vdark="An Old Hope"  # "Adapta Nokto", "An Old Hope", "Dracula", "Monokai++"

wlight="Day"
wdark="Night"

if is-affirmative "${1-}" "yes"; then
	w="" # w="${2:=$wdark}"
	mset "true"
	wset "$w"
	vset "$vlight" "$vdark"
else
	w="" # w="${2:=$wlight}"
	echo "light mode [wallpaper = $w] [vscode = $vlight]"
	mset "false"
	wset "$w"
	vset "$vdark" "$vlight"
fi
