#!/usr/bin/env bash

function date-adguard() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Outputs the date time in the format compatible with AdGuard rules, e.g.
			22 Feb 2022 09:02 UTC

			USAGE:
			date-adguard
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	# https://github.com/AdguardTeam/FiltersRegistry/issues/398
	date -u +"%d %b %Y %H:%M UTC"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	date-adguard "$@"
fi
