#!/usr/bin/env bash

function debug-network() (
	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Run a bash script with [-x] applied, which enables line by line tracelogs.

			USAGE:
			debug-bash -- <command...>
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item cmd=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--')
			cmd+=("$@")
			shift "$#"
			break
			;;
		*) cmd+=("$item") ;;
		esac
	done

	# check
	if test "${#cmd[@]}" -eq 0; then
		help "No command was provided"
	fi

	# =====================================
	# Act

	bash -xv "$(get-command "${cmd[0]}")" -- "${cmd[@]:1}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	debug-network "$@"
fi
