#!/usr/bin/env bash

domain='api.nordvpn.com'
server='9.9.9.9'
invalid='192.0.2.1'

printf "\nDATE:\n"
date

printf "\nRESOLVE:\n"
systemd-resolve --status

printf "\nDNS LISTENERS:\n"
sudo ss -lp 'sport = :domain'

printf "\nLISTENERS:\n"
sudo netstat -tulpn | grep LISTEN

printf "\nDNS:\n"
sudo resolvectl dns

printf "\nRESOLV.conf\n"
cat /etc/resolv.conf

printf "\nROUTE\n"
sudo route -n

printf "\nDIG:\n"
dig "$domain"

printf "\nTRACE:\n"
dig +trace"$domain"

printf "\nDIG @$invalid:\n"
dig @"$invalid" "$domain"

printf "\nDIG @$server:\n"
dig @"$server" hostname.bind chaos txt
dig @"$server" id.server chaos txt

printf "\nHOST:\n"
host -va "$domain"

printf "\nNSLOOKUP:\n"
nslookup -debug "$domain"

printf "\nCURL:\n"
curl "$domain"

printf "\nPING:\n"
ping -c 5 "$domain"

printf "\nWHOIS:\n"
whois "$domain"

# sudo apt install traceroute
# inetutils-traceroute is worse

# printf "\nTRACEROUTE:\n"
# traceroute -p 53 "$server"

# printf "\nTRACEROUTE -r:\n"
# traceroute -r -p 53 "$server"
