#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# help
if is-help "$@"; then
	cat <<-EOF >/dev/stderr
		ABOUT:
		??????
	EOF
	return 22 # Invalid argument
fi

down "$1" --destination="$(date-iso)$2"
