#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# download a file
# do not use the continue flags as they will prefer the local file over the remote file if the local exists
url="$(ask "Enter the URL of the file to download" "${1-}" --required)"
target="$(ask "If you wish to save it to a custom location, enter it now." "${2-}")"
if test -n "$target"; then
	dir="$(dirname "$target")"
	file="$(basename "$target")"
fi

# https://github.com/aria2/aria2/issues/1137
if command-exists aria2c; then
	if test -n "$target"; then
		aria2c --allow-overwrite=true --auto-file-renaming=false --dir="$dir" --out="$file" "$url"
	else
		aria2c --allow-overwrite=true --auto-file-renaming=false "$url"
	fi
elif command-exists wget; then
	if test -n "$target"; then
		wget -O "$target" -N "$url"
	else
		wget -N "$url"
	fi
elif command-exists curl; then
	if test -n "$target"; then
		curl -L "$url" -o "$target"
	else
		curl -OL "$url"
	fi
elif command-exists http; then
	if test -n "$target"; then
		http --output "$target" -d "$url"
	else
		http -d "$url"
	fi
fi
