#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# help
if is-help-empty "$@"; then
	stderr echo 'USAGE: down-zip <URL> [--destination=.] [--filter=.]'
	exit 1
fi

# options
url="$(ask --question="Enter the URL of the archive file to download" --default="${1-}" --required)"
destination="$(get-flag-value destination -- "$@")" # custom destination
filter="$(get-flag-value filter -- "$@")" # custom extraction
format="$(get-flag-value format -- "$@")" # format override
if test -z "$destination"; then
	destination="$(pwd)"
fi
if test -z "$format"; then
	format="$url"
fi

# download to temp
tempdir="$(mktemp -d)"
tempfile="$(mktemp)"
down "$url" --destination="$tempfile"
unziptar "$tempfile" --destination="$tempdir" --format="$format"

# download to destination
if test -n "$filter"; then
	mapfile -t results < <(expand-path "$tempdir/$filter")
	for result in "${results[@]}"; do
		cp -rf "$result" "$destination"
	done
	echo "unzipped $filter from $url to $destination"
else
	cp -rf "$tempdir/"* "$destination"
	echo "unzipped $url to $destination"
fi

# rm temps
rm -Rf "$tempdir"
rm -f "$tempfile"
