#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

found='no'

function act {
	if test "$1" = '--'; then
		found='yes'
	elif test "$found" = 'yes'; then
		echo "$1"
	fi
}

function finish {
	if test "$found" = 'no'; then
		return 1
	fi
}

source "$DOROTHY/sources/stdinargs.bash"
