#!/usr/bin/env bash

function echo_error() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Forward <input> to [echo-style], outputting to STDERR, and prepending an error notice.

			USAGE:
			echo-error [--] ...<input>
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_args=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		*)
			option_args+=("$item" "$@")
			shift $#
			break
			;;
		esac
	done

	# =====================================
	# Action

	echo-style $'\n' --error="ERROR:" $'\n' "${option_args[@]}" >/dev/stderr
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_error "$@"
fi
