#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

queue=0
while IFS= read -r line; do
	if test "$queue" -ne 0; then
		echo-clear-line
		queue=0
	fi
	echo "$line"
	queue=$((queue + 1))
done </dev/stdin

function finish {
	if test "$queue" -ne 0; then
		echo-clear-line
	fi
}
trap finish EXIT
