#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function help {
	cat <<-EOF >/dev/stderr
		ABOUT:
		Output each input, that is a value, onto its own line.
		Uses [is-value] for the internal check.

		USAGE:
		echo-values <...input>
		echo-lines <...input> | echo-values

		EXAMPLE:

		echo-values '' 0 a NULL VOID UNDEFINED false z

		    0
		    a
		    false
		    z

		echo-lines '' 0 a NULL VOID UNDEFINED false z | echo-verbose

		    0
		    a
		    false
		    z
	EOF
	return 22 # Invalid argument
}

function on_input {
	if is-value "$1"; then
		echo "$1"
	fi
}

source "$DOROTHY/sources/stdinargs.bash"
