#!/usr/bin/env bash

function echo_escape_regexp_replacement() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			For each <input>, escape the \`\$\` character that would otherwise interfere with regular expression replacement syntax.

			USAGE:
			echo-escape-regexp-replacement [...options] [--] ...<input>
			echo-lines ...<input> | echo-escape-regexp-replacement [...options]

			OPTIONS:
			$(__stdinargs__help_options --)

			QUIRKS:
			If you need backslashes escaped, pipe it to \`echo-escape-backslashes\`.

			EXAMPLES:
			\`echo-escape-regexp-replacement -- 'Hello \$world.'\`
			Outputs: \`Hello \$\$world.\`
			Returns: [0]

			\`echo-lines -- 'Hello \$world.' | echo-escape-regexp-replacement --stdin\`
			Outputs: \`Hello \$\$world.\`
			Returns: [0]
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	function __on_whole {
		local value="$1"
		value="${value//$/\$$}" # https://github.com/chmln/sd/issues/129
		__print_piece "$value" || return $?
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_escape_regexp_replacement "$@"
fi
