#!/usr/bin/env bash

function echo_filter_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- echo-filter --help

	## FILTER

	eval-tester --name='no args' --status=22 --ignore-stderr -- \
		echo-filter

	eval-tester --name='no args' --status=22 --ignore-stderr -- \
		echo-filter --

	local \
		inputs=(a B 'c C' 'd D' 'e E' 'f F') \
		filters=(--any --each --value='a' --value='b' --prefix='c' --prefix='D' --suffix='e' --suffix='F')

	# respect case
	eval-tester --stdout=$'a\nc C\nf F\n' --trailing-newlines -- \
		echo-filter "${filters[@]}" -- "${inputs[@]}"

	__print_lines "${inputs[@]}" | eval-tester --stdout=$'a\nc C\nf F\n' --trailing-newlines -- \
		echo-filter --stdin "${filters[@]}"

	# ignore case
	eval-tester --stdout=$'a\nB\nc C\nd D\ne E\nf F\n' --trailing-newlines -- \
		echo-filter --ignore-case "${filters[@]}" -- "${inputs[@]}"

	__print_lines "${inputs[@]}" | eval-tester --stdout=$'a\nB\nc C\nd D\ne E\nf F\n' --trailing-newlines -- \
		echo-filter --stdin --ignore-case "${filters[@]}"

	# lowercase
	eval-tester --stdout=$'a\nb\nc c\nd d\ne e\nf f\n' --trailing-newlines -- \
		echo-filter --lowercase "${filters[@]}" -- "${inputs[@]}"

	__print_lines "${inputs[@]}" | eval-tester --stdout=$'a\nb\nc c\nd d\ne e\nf f\n' --trailing-newlines -- \
		echo-filter --stdin --lowercase "${filters[@]}"

	# uppercase
	eval-tester --stdout=$'A\nB\nC C\nD D\nE E\nF F\n' --trailing-newlines -- \
		echo-filter --uppercase "${filters[@]}" -- "${inputs[@]}"

	__print_lines "${inputs[@]}" | eval-tester --stdout=$'A\nB\nC C\nD D\nE E\nF F\n' --trailing-newlines -- \
		echo-filter --stdin --uppercase "${filters[@]}"

	## HAS

	return 0 # @todo finish these tests

	eval-tester --status=22 --ignore-stderr -- \
		echo-filter --has

	eval-tester --status=22 --ignore-stderr -- \
		echo-filter --has --

	eval-tester --status=22 --ignore-stderr -- \
		echo-filter --has -- a b c

	eval-tester --status=22 --ignore-stderr -- \
		echo-filter --has a b -- a b c

	eval-tester --status=22 --ignore-stderr -- \
		echo-filter --has a b --

	eval-tester --status=22 --ignore-stderr -- \
		echo-filter --has a b

	eval-tester --status=1 -- \
		echo-filter --has a --

	eval-tester --status=1 -- \
		echo-filter --has --any a b --

	eval-tester --status=1 -- \
		echo-filter --has --all a b --

	# capture what [[ " ${items[*]} " =~ " $item " ]] cannot
	eval-tester --status=1 -- \
		echo-filter --has b -- a 'b b b'

	eval-tester --status=1 -- \
		echo-filter --has c -- a 'b b b'

	eval-tester --status=1 -- \
		echo-filter --has --any b c -- a 'b b b'

	eval-tester --status=1 -- \
		echo-filter --has --all b c -- a 'b b b'

	eval-tester -- \
		echo-filter --has --any a 'b b b' -- a 'b b b'

	eval-tester -- \
		echo-filter --has --all a 'b b b' -- a 'b b b'

	eval-tester -- \
		echo-filter --has --any --needle=a --needle='b b b' -- a 'b b b'

	eval-tester -- \
		echo-filter --has --all --needle=a --needle='b b b' -- a 'b b b'

	eval-tester -- \
		echo-filter --has --any a a -- a 'b b b'

	eval-tester -- \
		echo-filter --has --all a a -- a 'b b b'

	eval-tester -- \
		echo-filter --has --any a c -- a 'b b b'

	eval-tester --status=1 -- \
		echo-filter --has --all a c -- a 'b b b'

	eval-tester -- \
		echo-filter --has --any a c -- a 'b b b'

	eval-tester -- \
		echo-filter --has --all --ignore-case a C -- A 'b b b' c

	return 0
)
function echo_filter() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function __help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Filter each <input> by the options.

			USAGE:
			\`echo-filter [...options] [--] ...<input>\`
			\`echo-lines ...<input> | echo-filter [...options]\`

			OPTIONS:
			--case=lower | --lowercase
			    Compare elements of <input> irrespective of case, and return a lowercase result.
			--case=upper | --uppercase
			    Compare elements of <input> irrespective of case, and return an uppercase result.
			--case=ignore | --ignore-case
			    Compare elements of <input> irrespective of case.
			--case=sensitive
			    Compare elements of <input> normally, respecting case. The default behaviour.

			$(__stdinargs__help_options --)
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local options_filter=() option_stdinargs=()
	while [[ $# -ne 0 ]]; do
		if __is_stdinargs_option_or_argument "$1"; then
			option_stdinargs+=("$1")
		else
			options_filter+=("$1")
		fi
		shift
	done

	# =====================================
	# Action

	local pieces=()
	function __on_piece {
		pieces+=("$1")
	}
	function __on_finish {
		local results=()
		__filter --source={pieces} --target={results} "${options_filter[@]}" || return $?
		__print_lines "${results[@]}" || return $?
	}

	stdinargs "${option_stdinargs[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_filter_test
	else
		echo_filter "$@"
	fi
fi
