#!/usr/bin/env bash

function echo_lowercase() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output each input as lowercase.

			USAGE:
			echo-lowercase [...options] [--] ...<input>
			echo-lines ...<input> | echo-lowercase [...options]

			OPTIONS:
			$(stdinargs_options_help --)

			EXAMPLES:

			echo-lowercase -- HELLO WORLD

			    hello
			    world
			    # exit status: 0

			echo-lines -- HELLO WORLD | echo-lowercase

			    hello
				world
			    # exit status: 0

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		lowercase_string "$1"
	}

	stdinargs "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_lowercase "$@"
fi
