#!/usr/bin/env bash

function echo_values() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >&2
			ABOUT:
			Output each input, that is a value, onto its own line.
			Use to trim empty values from a list.
			Companion to [is-value], [is-empty-value]. Equivalent to a [echo-if-value], [echo-nonempty-values], [echo-non-nullish], [echo-not-nullish].

			USAGE:
			echo-values [...options] [--] ...<input>
			echo-lines ...<input> | echo-values [...options]

			OPTIONS:
			$(__stdinargs__help_options --)

			EXAMPLE:

			# input
			echo-lines -- '' 0 a NULL VOID UNDEFINED false z | echo-verbose --stdin

			    [0] = []
			    [1] = [0]
			    [2] = [a]
			    [3] = [NULL]
			    [4] = [VOID]
			    [5] = [UNDEFINED]
			    [6] = [false]
			    [7] = [z]

			# trimming using echo-values
			echo-values -- '' 0 a NULL VOID UNDEFINED false z | echo-verbose --stdin

			    [0] = [0]
			    [1] = [a]
			    [2] = [false]
			    [3] = [z]
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	function __on_piece {
		if is-value -- "$1"; then
			__print_lines "$1" || return $?
		fi
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_values "$@"
fi
