#!/usr/bin/env bash

function echo_escape_backslashes_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- echo-escape-backslashes --help
)

function echo_escape_bash() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Escape the <...input> for usage inside bash.

			USAGE:
			\`echo-escape-bash [...options] [--] ...<input>\`
			\`echo-lines ...<input> | echo-escape-bash [...options]\`

			OPTIONS:
			$(__stdinargs__help_options --)
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	# we could use @Q for this, but it is strange, so just use %q\n
	# bash-5.2$ printf '%q\n' " a'"
	# \ a\'
	# bash-5.2$ b=\ a\'
	# bash-5.2$ printf '%s\n' "[$b]"
	# [ a']
	# bash-5.2$ printf '%s\n' "${b@Q}"
	# ' a'\'''

	function __on_piece {
		printf '%q\n' "$@" || return $?
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_escape_backslashes_test
	else
		echo_escape_bash "$@"
	fi
fi
