#!/usr/bin/env bash

function print_lines_after() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Get everything after the first recurrence of <line>.

			USAGE:
			echo-lines-after --line=<line> [--] <...input>
			echo-lines <...input> | echo-lines-after --line=<line>

			EXAMPLE:

			echo-lines-after --line='' -- a b '' '' c d

			    c
			    d
			    # exit status: 0

			echo-lines a b '' '' c d | echo-lines-after --line=''

			    c
			    d
			    # exit status: 0

			echo-lines-after --line='' <<< "\$(echo-lines a b '' c d)"

			    c
			    d
			    # exit status: 0
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_line='' ARGS=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--line='*) option_line="${item#*--line=}" ;;
		'--')
			ARGS+=("$@")
			shift "$#"
			break
			;;
		*)
			ARGS+=("$item" "$@")
			shift "$#"
			break
			;;
		esac
	done

	# action
	local FOUND='no'
	function on_input {
		if test "$1" = "$option_line"; then
			FOUND='yes'
		elif test "$FOUND" = 'yes'; then
			print_line "$1"
		fi
	}
	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	print_lines_after "$@"
fi
