#!/usr/bin/env bash

# @todo once __get_substring supports indices for positive integers, rename or duplicate this as `echo-substring`

function echo_substr_test() (
	# trunk-ignore-all(cspell/error)
	source "$DOROTHY/sources/bash.bash"
	echo-style --h1="TEST: $0"

	function __test {
		local item expected args=()
		while [[ $# -ne 0 ]]; do
			local item="$1"
			shift
			if [[ $item == '--' ]]; then
				expected="${1-}"
				break
			fi
			args+=("$item")
		done
		eval-tester --stdout="$expected" -- \
			echo-substr "${args[@]}"
	}

	__test abcd -- abcd
	##
	__test abcd 0 -- abcd
	__test abcd 0 0 --
	__test abcd 0 1 -- a
	__test abcd 0 2 -- ab
	__test abcd 0 3 -- abc
	__test abcd 0 4 -- abcd
	__test abcd 0 5 -- abcd
	__test abcd 0 6 -- abcd
	__test abcd 0 -0 -- abcd
	__test abcd 0 -1 -- abc
	__test abcd 0 -2 -- ab
	__test abcd 0 -3 -- a
	__test abcd 0 -4 --
	__test abcd 0 -5 --
	__test abcd 0 -6 --
	#
	__test abcd 1 -- bcd
	__test abcd 1 0 --
	__test abcd 1 1 -- b
	__test abcd 1 2 -- bc
	__test abcd 1 3 -- bcd
	__test abcd 1 4 -- bcd
	__test abcd 1 5 -- bcd
	__test abcd 1 6 -- bcd
	__test abcd 1 -0 -- bcd
	__test abcd 1 -1 -- bc
	__test abcd 1 -2 -- b
	__test abcd 1 -3 --
	__test abcd 1 -4 --
	__test abcd 1 -5 --
	__test abcd 1 -6 --
	#
	__test abcd 2 -- cd
	__test abcd 2 0 --
	__test abcd 2 1 -- c
	__test abcd 2 2 -- cd
	__test abcd 2 3 -- cd
	__test abcd 2 4 -- cd
	__test abcd 2 5 -- cd
	__test abcd 2 6 -- cd
	__test abcd 2 -0 -- cd
	__test abcd 2 -1 -- c
	__test abcd 2 -2 --
	__test abcd 2 -3 --
	__test abcd 2 -4 --
	__test abcd 2 -5 --
	__test abcd 2 -6 --
	#
	__test abcd 3 -- d
	__test abcd 3 0 --
	__test abcd 3 1 -- d
	__test abcd 3 2 -- d
	__test abcd 3 3 -- d
	__test abcd 3 4 -- d
	__test abcd 3 5 -- d
	__test abcd 3 6 -- d
	__test abcd 3 -0 -- d
	__test abcd 3 -1 --
	__test abcd 3 -2 --
	__test abcd 3 -3 --
	__test abcd 3 -4 --
	__test abcd 3 -5 --
	__test abcd 3 -6 --
	#
	__test abcd 4 --
	__test abcd 4 0 --
	__test abcd 4 1 --
	__test abcd 4 2 --
	__test abcd 4 3 --
	__test abcd 4 4 --
	__test abcd 4 5 --
	__test abcd 4 6 --
	__test abcd 4 -0 --
	__test abcd 4 -1 --
	__test abcd 4 -2 --
	__test abcd 4 -3 --
	__test abcd 4 -4 --
	__test abcd 4 -5 --
	__test abcd 4 -6 --
	#
	__test abcd 5 --
	__test abcd 5 0 --
	__test abcd 5 1 --
	__test abcd 5 2 --
	__test abcd 5 3 --
	__test abcd 5 4 --
	__test abcd 5 5 --
	__test abcd 5 6 --
	__test abcd 5 -0 --
	__test abcd 5 -1 --
	__test abcd 5 -2 --
	__test abcd 5 -3 --
	__test abcd 5 -4 --
	__test abcd 5 -5 --
	__test abcd 5 -6 --
	#
	__test abcd 6 --
	__test abcd 6 0 --
	__test abcd 6 1 --
	__test abcd 6 2 --
	__test abcd 6 3 --
	__test abcd 6 4 --
	__test abcd 6 5 --
	__test abcd 6 6 --
	__test abcd 6 -0 --
	__test abcd 6 -1 --
	__test abcd 6 -2 --
	__test abcd 6 -3 --
	__test abcd 6 -4 --
	__test abcd 6 -5 --
	__test abcd 6 -6 --
	##
	__test abcd -0 --
	__test abcd -0 0 --
	__test abcd -0 1 --
	__test abcd -0 2 --
	__test abcd -0 3 --
	__test abcd -0 4 --
	__test abcd -0 5 --
	__test abcd -0 6 --
	__test abcd -0 -0 --
	__test abcd -0 -1 --
	__test abcd -0 -2 --
	__test abcd -0 -3 --
	__test abcd -0 -4 --
	__test abcd -0 -5 --
	__test abcd -0 -6 --
	#
	__test abcd -1 -- d
	__test abcd -1 0 --
	__test abcd -1 1 -- d
	__test abcd -1 2 -- d
	__test abcd -1 3 -- d
	__test abcd -1 4 -- d
	__test abcd -1 5 -- d
	__test abcd -1 6 -- d
	__test abcd -1 -0 -- d
	__test abcd -1 -1 --
	__test abcd -1 -2 --
	__test abcd -1 -3 --
	__test abcd -1 -4 --
	__test abcd -1 -5 --
	__test abcd -1 -6 --
	#
	__test abcd -2 -- cd
	__test abcd -2 0 --
	__test abcd -2 1 -- c
	__test abcd -2 2 -- cd
	__test abcd -2 3 -- cd
	__test abcd -2 4 -- cd
	__test abcd -2 5 -- cd
	__test abcd -2 6 -- cd
	__test abcd -2 -0 -- cd
	__test abcd -2 -1 -- c
	__test abcd -2 -2 --
	__test abcd -2 -3 --
	__test abcd -2 -4 --
	__test abcd -2 -5 --
	__test abcd -2 -6 --
	#
	__test abcd -3 -- bcd
	__test abcd -3 0 --
	__test abcd -3 1 -- b
	__test abcd -3 2 -- bc
	__test abcd -3 3 -- bcd
	__test abcd -3 4 -- bcd
	__test abcd -3 5 -- bcd
	__test abcd -3 6 -- bcd
	__test abcd -3 -0 -- bcd
	__test abcd -3 -1 -- bc
	__test abcd -3 -2 -- b
	__test abcd -3 -3 --
	__test abcd -3 -4 --
	__test abcd -3 -5 --
	__test abcd -3 -6 --
	#
	__test abcd -4 -- abcd
	__test abcd -4 0 --
	__test abcd -4 1 -- a
	__test abcd -4 2 -- ab
	__test abcd -4 3 -- abc
	__test abcd -4 4 -- abcd
	__test abcd -4 5 -- abcd
	__test abcd -4 6 -- abcd
	__test abcd -4 -0 -- abcd
	__test abcd -4 -1 -- abc
	__test abcd -4 -2 -- ab
	__test abcd -4 -3 -- a
	__test abcd -4 -4 --
	__test abcd -4 -5 --
	__test abcd -4 -6 --
	#
	__test abcd -5 -- abcd
	__test abcd -5 0 --
	__test abcd -5 1 --
	__test abcd -5 2 -- a
	__test abcd -5 3 -- ab
	__test abcd -5 4 -- abc
	__test abcd -5 5 -- abcd
	__test abcd -5 6 -- abcd
	__test abcd -5 -0 -- abcd
	__test abcd -5 -1 -- abc
	__test abcd -5 -2 -- ab
	__test abcd -5 -3 -- a
	__test abcd -5 -4 --
	__test abcd -5 -5 --
	__test abcd -5 -6 --
	#
	__test abcd -6 -- abcd
	__test abcd -6 0 --
	__test abcd -6 1 --
	__test abcd -6 2 --
	__test abcd -6 3 -- a
	__test abcd -6 4 -- ab
	__test abcd -6 5 -- abc
	__test abcd -6 6 -- abcd
	__test abcd -6 -0 -- abcd
	__test abcd -6 -1 -- abc
	__test abcd -6 -2 -- ab
	__test abcd -6 -3 -- a
	__test abcd -6 -4 --
	__test abcd -6 -5 --
	__test abcd -6 -6 --

	eval-tester --stdout=abcde -- \
		echo-substr -- abcde

	eval-tester --stdout=abcde -- \
		echo-substr 0 -- abcde

	eval-tester --stdout=bcde -- \
		echo-substr 1 -- abcde

	eval-tester -- \
		echo-substr 5 -- abcde

	eval-tester -- \
		echo-substr 6 -- abcde

	eval-tester -- \
		echo-substr 0 0 -- abcde

	eval-tester --stdout=a -- \
		echo-substr 0 1 -- abcde

	eval-tester --stdout=abcd -- \
		echo-substr 0 4 -- abcde

	eval-tester --stdout=abcde -- \
		echo-substr 0 5 -- abcde

	eval-tester --stdout=abcde -- \
		echo-substr 0 6 -- abcde

	eval-tester --stdout=abcde -- \
		echo-substr 0 -0 -- abcde

	eval-tester -- \
		echo-substr 1 0 -- abcde

	eval-tester --stdout=b -- \
		echo-substr 1 1 -- abcde

	eval-tester --stdout=bcd -- \
		echo-substr 1 3 -- abcde

	eval-tester --stdout=bcde -- \
		echo-substr 1 4 -- abcde

	eval-tester --stdout=bcde -- \
		echo-substr 1 5 -- abcde

	eval-tester --stdout=bcde -- \
		echo-substr 1 6 -- abcde

	eval-tester --stdout=bcde -- \
		echo-substr 1 -0 -- abcde

	eval-tester -- \
		echo-substr -3 0 -- abcde

	eval-tester --stdout=c -- \
		echo-substr -3 1 -- abcde

	eval-tester --stdout=cde -- \
		echo-substr -3 3 -- abcde

	eval-tester --stdout=cde -- \
		echo-substr -3 4 -- abcde

	eval-tester --stdout=cd -- \
		echo-substr -3 -1 -- abcde

	eval-tester -- \
		echo-substr -3 -3 -- abcde

	eval-tester --stdout=cde -- \
		echo-substr -3 -0 -- abcde

	eval-tester -- \
		echo-substr -5 0 -- abcde

	eval-tester --stdout=a -- \
		echo-substr -5 1 -- abcde

	eval-tester --stdout=abc -- \
		echo-substr -5 3 -- abcde

	eval-tester --stdout=abcd -- \
		echo-substr -5 4 -- abcde

	eval-tester --stdout=abcd -- \
		echo-substr -5 -1 -- abcde

	eval-tester --stdout=ab -- \
		echo-substr -5 -3 -- abcde

	eval-tester --stdout= -- \
		echo-substr -5 -5 -- abcde

	eval-tester --stdout= -- \
		echo-substr -5 -6 -- abcde

	eval-tester --stdout=abcde -- \
		echo-substr -5 -0 -- abcde

	eval-tester -- \
		echo-substr -6 0 -- abcde

	eval-tester -- \
		echo-substr -6 1 -- abcde

	eval-tester --stdout=ab -- \
		echo-substr -6 3 -- abcde

	eval-tester --stdout=abc -- \
		echo-substr -6 4 -- abcde

	eval-tester --stdout=abcd -- \
		echo-substr -6 -1 -- abcde

	eval-tester --stdout=ab -- \
		echo-substr -6 -3 -- abcde

	eval-tester --stdout= -- \
		echo-substr -6 -5 -- abcde

	eval-tester --stdout= -- \
		echo-substr -6 -6 -- abcde

	eval-tester --stdout=abcde -- \
		echo-substr -6 -0 -- abcde

	eval-tester --stdout=012345 -- \
		echo-substr --start=0 -- 012345

	eval-tester --stdout=01234 -- \
		echo-substr --length=-1 -- 012345

	eval-tester --stdout=45 -- \
		echo-substr --start=-2 -- 012345

	eval-tester --stdout=4 -- \
		echo-substr --start=-2 --length=-1 -- 012345

	eval-tester --stdout=012345 -- \
		echo-substr --start=-10 -- 012345

	eval-tester --stdout= -- \
		echo-substr --length=-10 -- 012345

	eval-tester --stdout=012345 -- \
		echo-substr --length=10 -- 012345

	eval-tester --stdout=012345 -- \
		echo-substr --start=-10 --length=10 -- 012345

	eval-tester --stdout= -- \
		echo-substr --start=10 --length=-10 -- 012345

	echo-style --g1="TEST: $0"
	return 0
)
function echo_substr() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Output a substring of the <input> by the <start> and <length> arguments.

			USAGE:
			echo-substr [...options] [--] ...<input>
			echo-lines ...<input> | echo-substr [...options]

			OPTIONS:
			--start=<start> | <start>
			    The start index of the substring, can be negative to start from the end, defaults to 0.

			--length=<length> | <length>
			    The length of the substring, defaults to the remaining length of the <input>.

			$(stdinargs_options_help --)
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process our own arguments, delegate everything else to stdinargs
	local item option_start='' option_length='' option_args=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--start='*) option_start="${item#*=}" ;;
		'--length='*) option_length="${item#*=}" ;;
		# forward to stdinargs, however support mixing and matching of our options, with stdinargs options
		'--')
			option_args+=("$item" "$@")
			shift $#
			break
			;;
		*)
			if __is_integer "$item"; then
				if [[ -z $option_start ]]; then
					option_start="$item"
					continue
				elif [[ -z $option_length ]]; then
					option_length="$item"
					continue
				fi
			fi
			option_args+=("$item")
			;;
		esac
	done

	# =====================================
	# Action

	function on_input {
		__get_substring "$1" "$option_start" "$option_length"
	}

	stdinargs "${option_args[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_substr_test
	else
		echo_substr "$@"
	fi
fi
