#!/usr/bin/env bash

function echo_trim_empty_lines() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			If an input is empty, do not output it.
			Uses [is-empty-value] for the check.

			USAGE:
			echo-trim-empty-lines <...input>
			echo-lines <...input> | echo-trim-empty-lines

			EXAMPLE:

			echo-trim-empty-lines '' 'a' ' ' 'b' 'null' 'c' 'false'

			    a
			    b
			    c
			    false

			echo-lines '' 'a' ' ' 'b' 'null' 'c' 'false' | echo-trim-empty-lines

			    a
			    b
			    c
			    false

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		if ! is-empty-value "$1"; then
			echo "$1"
		fi
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_trim_empty_lines "$@"
fi
