#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function help {
	cat <<-EOF >/dev/stderr
		ABOUT:
		Output inputs that are executable paths.

		USAGE:
		echo-if-file <...input>
		echo-lines <...input> | echo-if-file

		EXAMPLE:

		touch executable
		chmodx +x executable
		touch file

		echo-if-file executable file missing

		    executable
		    # exit status: 0

		echo-lines executable file missing | echo-if-file

		    executable
		    # exit status: 0

	EOF
	return 22 # Invalid argument
}

function on_input {
	if test -n "$1" -a -x "$1"; then
		echo "$1"
	fi
}

source "$DOROTHY/sources/stdinargs.bash"
