#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$(which echo-style)"

function echo-error() (
	echo-style $'\n' --error="ERROR:" $'\n' "$@" >/dev/stderr
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-error "$@"
fi
