#!/usr/bin/env bash

function echo-count-lines() (
	source "$DOROTHY/sources/bash.bash"

	local count_inline='yes'
	if test "${1-}" = '--inline'; then
		count_inline='yes'
		shift
	elif test "${1-}" = '--no-inline'; then
		count_inline='no'
		shift
	fi

	local index=0
	function on_arg {
		echo-count-lines <<<"$*"
		exit "$?"
	}
	function on_line {
		index="$((index + 1))"
	}
	function on_inline {
		if test "$count_inline" = 'yes'; then
			index="$((index + 1))"
		fi
	}
	function on_finish {
		echo "$index"
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-count-lines "$@"
fi
