#!/usr/bin/env bash

function echo_trim_special_test() (
	source "$DOROTHY/sources/bash.bash"

	local styles=(
		# ascii keys...
		all
		bell
		#newline <-- kept
		#tab <-- kept
		#space <-- kept
		backspace
		carriage-return
		escape
		home
		# everything else...
		clear-line
		delete-line
		# clear-screen <-- on CI this adds a newline, so isn't a good test
		enable-cursor-blinking
		disable-cursor-blinking
		show-cursor
		hide-cursor
		reset-cursor
		cursor-blinking-block
		cursor-steady-block
		cursor-blinking-underline
		cursor-steady-underline
		cursor-blinking-bar
		cursor-steady-bar
		alternative-screen-buffer
		# default-screen-buffer <-- on CI this adds a newline, so isn't a good test
		terminal-title
		terminal-resize
		terminal-clipboard
		reset
		bold
		dim
		italic
		underline
		double-underline
		blink
		invert
		conceal
		strike
		framed
		circled
		overlined
		foreground-black
		foreground-red
		foreground-green
		foreground-yellow
		foreground-blue
		foreground-magenta
		foreground-cyan
		foreground-white
		foreground-purple
		foreground-gray
		foreground-grey
		foreground-intense-black
		foreground-intense-red
		foreground-intense-green
		foreground-intense-yellow
		foreground-intense-blue
		foreground-intense-magenta
		foreground-intense-cyan
		foreground-intense-white
		foreground-intense-purple
		foreground-intense-gray
		foreground-intense-grey
		background-black
		background-red
		background-green
		background-yellow
		background-blue
		background-magenta
		background-cyan
		background-white
		background-purple
		background-gray
		background-grey
		background-intense-black
		background-intense-red
		background-intense-green
		background-intense-yellow
		background-intense-blue
		background-intense-magenta
		background-intense-cyan
		background-intense-white
		background-intense-purple
		background-intense-gray
		background-intense-grey
	)
	local args=() style expected=''
	for style in "${styles[@]}"; do
		args+=("--$style=" --="$style")
		expected+="$style"
	done

	{
		__print_style "${args[@]}" | echo-trim-special --stdin
	} | eval-tester --stdout="$expected" -- \
		cat

	return 0
)
function echo_trim_special() (
	source "$DOROTHY/sources/stdinargs.bash"
	source "$DOROTHY/sources/ansi.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Trims special characters from <input>.

			USAGE:
			echo-trim-special [...options] [--] ...<input>
			echo-lines ...<input> | echo-trim-special [...options]

			OPTIONS:
			$(__stdinargs__help_options --)

			EXAMPLE:

			echo-trim-special -- "\$(echo-style --green='a/b?c!e f\$g')"

			    abce fg
			    # exit status: 0

			echo-style --green='a/b?c!e f' | echo-trim-special --stdin

			    abce fg
			    # exit status: 0

			QUIRKS:
			This will trim slashes and question marks, etc.
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	function on_inline {
		__ansi_trim "$1" 'not-text'
	}
	function on_line {
		__ansi_trim "$1"$'\n' 'not-text'
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_trim_special_test
	else
		echo_trim_special "$@"
	fi
fi
