#!/usr/bin/env bash
source "$DOROTHY/sources/arrays.bash"
source "$DOROTHY/sources/strict.bash"
if test "$ARRAYS" = 'no'; then
	exit 95 # Operation not supported
fi

# invalid arguments
if test "${2-}" != '--'; then
	stderr echo "Usage: $0 <deliminator> -- ..."
	exit 1
fi

# no delim and newline delim are equivalent
# no need for anything complicated
# just echo each argument, which will put each part on a newline
if test -z "${1-}" -o "${1-}" = $'\n'; then
	echo-lines "${@:3}"
	exit "$?"  # exit with the above on success and failure
fi

# we have a delim, so split each argument by it
for arg in "${@:3}"; do
	# without a trailing delim added, then the last item will have a trailing newline attached
	# so we add a trailing delim to ensure the last item will be an empty newline which can be ignored
	mapfile -td "$1" parts <<< "${arg}${1}"
	echo-lines "${parts[@]::${#parts[@]}-1}"
done
