#!/usr/bin/env bash
# no strict as we need exit codes

function act {
	is-affirmative "$1"
	c="$?"
	if test "$c" -eq 0; then
		echo 'yes'
	elif test "$c" -eq 1; then
		echo 'no'
	else
		exit 1
	fi
}

function noact {
	exit 1
}

source "$DOROTHY/sources/stdinargs.bash"
