#!/usr/bin/env bash

function echo-trim-each-line() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Trims surrounding whitespace from each line.

			USAGE:
			echo-trim-each-line <...input>
			echo-lines <...input> | echo-trim-each-line

			EXAMPLE:

			echo-trim-each-line ' a '

			    a

			echo-trim-each-line $'\t a \t\n b '

			    a
			    b

			echo-lines $'\t a \t' ' b ' | echo-trim-each-line

			    a
			    b

		EOF
		return 22 # Invalid argument
	}

	function on_input {
		echo "$1" # on_input already trims each line!

		# local str="$1"
		# str="${str#"${str%%[![:space:]]*}"}"
		# str="${str%"${str##*[![:space:]]}"}"
		# echo "$str"

		# echo "$1" | grep -o '^[[:space:]]*[^[:space:]]\+[[:space:]]*$'
		# echo "$1" | awk '{$1=$1};1'
		# echo "$1" | sd '^[[:blank:]]+|[[:blank:]]+$' ''
		# echo "$1" | sed -e 's/^[[:blank:]]+|[[:blank:]]+$//'
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-trim-each-line "$@"
fi
