#!/usr/bin/env bash

function echo_quote() (
	source "$DOROTHY/sources/bash.bash"

	# this is not the same as ${var@Q}, which handles single quotes differently
	function on_input {
		local item="$1"
		if [[ $item != *"'"* ]]; then
			# does not contain single quotes
			echo_line "'$item'"
		elif [[ $item != *'"'* ]]; then
			# does not contain double quotes
			echo_line "\"$item\""
		elif [[ $item != *"\\'"* ]]; then
			# does not contain escaped single quotes
			echo_line "'${item//\'/\\\'}'"
		elif [[ $item != *"\\\""* ]]; then
			# does not contain escaped double quotes
			echo_line "\"${item//\"/\\\"}\""
		else
			# contains both escaped single and escaped double quotes
			# echo-quote "a\\'s\\\"a\\\"a\\'d"
			echo-style --error="echo-quote is unable to handle single and double quotes in the same string" >/dev/stderr
			echo_line "$item"
			return 5 # EIO 5 Input/output error
		fi
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_quote "$@"
fi
