#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function echo-on-empty-stdin() (
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output the arguments if STDIN is empty.

			USAGE:
			echo-on-empty-stdin <...input>
			echo-lines <...input> | echo-on-empty-stdin

			EXAMPLE:

			echo-on-empty-stdin fallback

			    fallback
			    # exit status: 0

			echo | echo-on-empty-stdin fallback

			    fallback
			    # exit status: 0

			echo frontback | echo-on-empty-stdin fallback

			    frontback
			    # exit status: 0
		EOF
		return 22 # Invalid argument
	}

	local args=() stdin=''
	function on_arg {
		args+=("$1")
	}
	function on_line {
		stdin+="$1"
	}
	function on_finish {
		if test -z "$stdin"; then
			echo-lines "${args[@]}"
		fi
	}

	local REQUIRE_STDIN=yes
	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-on-empty-stdin "$@"
fi
