#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# wait a second for stdin lines, and forward each one along
stdin="no"
while IFS= read -rt 1 item; do
	stdin="yes"
	echo "$item"
done <&0

# stdin was empty, so output our arguments
if test "$stdin" = "no"; then
	if test "$#" -ne 0; then
		echo-lines "$@"
	fi
fi
