#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function echo-no-colors() (
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Attempt to strip colours from the input.

			USAGE:
			echo-no-colors <...input>
			echo-lines <...input> | echo-no-colors

			EXAMPLE:

			echo-style --green='plant' | echo-no-colors

			    plant
			    # exit status: 0

		EOF
		return 22 # Invalid argument
	}

	function on_input {
		# https://superuser.com/a/380778
		# trunk-ignore(shellcheck/SC2001)
		sed 's/\x1b\[[0-9;]*m//g' <<<"$1"
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-no-colors "$@"
fi
