#!/usr/bin/env bash

function echo_trim_empty_lines_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- echo-trim-empty-lines --help
)

function echo_trim_empty_lines() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Trims empty lines from <input>.
			Companion to: $(__join --style=code --between=', ' -- 'is-not-whitespace' 'is-whitespace').
			Equivalent to: $(__join --style=code --between=', ' -- 'echo-strings' 'echo-nonempty-strings').

			USAGE:
			\`echo-trim-empty-lines [...options] [--] ...<input>\`
			\`echo-lines ...<input> | echo-trim-empty-lines [...options]\`

			OPTIONS:
			$(__stdinargs__help_options --)

			EXAMPLES:
			\`\`\`
			echo-trim-empty-lines -- a '' ' ' $'\t' $'\t\n ' c
			\`\`\`
			Outputs:
			\`\`\`
			a
			c
			\`\`\`
			Returns: [0]

			\`\`\`
			echo-lines -- a '' c | echo-trim-empty-lines --stdin
			\`\`\`
			Outputs:
			\`\`\`
			a
			c
			\`\`\`
			Returns: [0]
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	function on_line {
		if is-not-whitespace -- "$1"; then
			__print_lines "$1"
		fi
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_trim_empty_lines_test
	else
		echo_trim_empty_lines "$@"
	fi
fi
