#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function help {
	cat <<-EOF >/dev/stderr
		ABOUT:
		If input is provided, output it.
		If no input was provided, fail.

		USAGE:
		echo-or-fail <...input>
		echo-lines <...input> | echo-or-fail

		EXAMPLE:

		# success cases
		echo-or-fail 'sup'         # argument
		echo 'sup' | echo-or-fail  # stdin

		    sup
		    # exit status: 0

		# failure cases, no stdin, no arguments
		echo-or-fail
		true | echo-or-fail

		    # exit status: 96
	EOF
	return 22 # Invalid argument
}

function on_input {
	echo "$1"
}

function on_no_input {
	return 96 # No message available on STREAM
}

source "$DOROTHY/sources/stdinargs.bash"
