#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function echo-if-directory() (
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output inputs that are directories.

			USAGE:
			echo-if-directory <...input>
			echo-lines <...input> | echo-if-directory

			EXAMPLE:

			mkdir dir
			touch file

			echo-if-file dir file directory

			    dir
			    # exit status: 0

			echo-lines dir file missing | echo-if-directory

			    dir
			    # exit status: 0

		EOF
		return 22 # Invalid argument
	}

	function on_input {
		if test -n "$1" -a -d "$1"; then
			echo "$1"
		fi
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-if-directory "$@"
fi
