#!/usr/bin/env bash

function echo_verbose() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Quickly output inputs and their position.

			USAGE:
			echo-verbose <...input>
			echo-lines <...input> | echo-verbose

			EXAMPLE:

			echo-verbose a b c

			    [0] = [a]
			    [1] = [b]
			    [2] = [c]

			echo-lines a b c | echo-verbose

			    [0] = [a]
			    [1] = [b]
			    [2] = [c]

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# on each input, update the position, and output
	local INDEX=0
	function on_input {
		echo_line "[$INDEX] = [$1]"
		INDEX="$((INDEX + 1))"
	}
	function on_no_input {
		echo-style --dim='[ nothing provided ]'
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_verbose "$@"
fi
