#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function echo-escape-spaces() (
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			For each input, escape its spaces by prepending backslashes.

			USAGE:
			echo-escape-spaces <...input>
			echo-lines <...input> | echo-escape-spaces

			EXAMPLE:

			echo-escape-spaces 'hello world'

			    hello\ world
			    # exit status: 0

			echo-lines 'hello world' | echo-escape-spaces

			    hello\ world
			    # exit status: 0

		EOF
		return 22 # Invalid argument
	}

	function on_input {
		echo "${1// /\\ }"
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-escape-spaces "$@"
fi
