#!/usr/bin/env bash

function echo_trim_colors() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Attempt to strip colours from the input.

			USAGE:
			echo-trim-colors [...options] [--] ...<input>
			echo-lines ...<input> | echo-trim-colors [...options]

			OPTIONS:
			$(stdinargs_options_help --)

			EXAMPLE:

			echo-style --green='plant' | echo-trim-colors --stdin

			    plant
			    # exit status: 0

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		# https://superuser.com/a/380778
		# trunk-ignore(shellcheck/SC2001)
		sed 's/\x1b\[[0-9;]*m//g' <<<"$1"
	}

	stdinargs "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_trim_colors "$@"
fi
