#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=yes setup-util-sd

# help
function help {
	cat <<-EOF >/dev/stderr
		ABOUT:
		Trims surrounding whitespace from each line.

		USAGE:
		echo-trim-each-line <...input>
		echo-lines <...input> | echo-trim-each-line

		EXAMPLE:

		echo-trim-each-line ' a '

		    a

		echo-trim-each-line $'\t a \t\n b '

		    a
		    b

		echo-lines $'\t a \t' ' b ' | echo-trim-each-line

		    a
		    b

	EOF
	return 22 # Invalid argument
}

function on_input {
	echo "$1" | sd '^[[:blank:]]+|[[:blank:]]+$' ''
}

source "$DOROTHY/sources/stdinargs.bash"
