#!/usr/bin/env bash

function echo_if_file() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output inputs that are files.

			USAGE:
			echo-if-file <...input>
			echo-lines <...input> | echo-if-file

			EXAMPLES:

			touch file

			echo-if-file file missing

			    file
			    # exit status: 0

			echo-lines file missing | echo-if-file

			    file
			    # exit status: 0

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		if test -n "$1" -a -f "$1"; then
			print_line "$1"
		fi
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_if_file "$@"
fi
