#!/usr/bin/env bash

function echo-fstab-encode() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			fstab encode all input received.

			USAGE:
			echo-fstab-encode [...arguments]
			echo-lines [...arguments] | echo-fstab-encode

			EXAMPLES:
			echo-fstab-encode '| |=|,|\|#|'

			    |\040|\075|\054|\134|\043|

			echo-lines '| |=|,|\|#|' | echo-fstab-encode

			    |\040|\075|\054|\134|\043|

		EOF
		return 22 # Invalid argument
	}

	# this was provided by chatgpt, with printf modifications
	function on_input {
		local string="$1" char
		for ((i = 0; i < ${#string}; i++)); do
			char="${string:i:1}"
			case "$char" in
			' ' | '=' | ',' | '\' | '#')
				printf '\\%03o' "'$char"
				;;
			*)
				printf '%s' "$char"
				;;
			esac
		done
		printf '\n'
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-fstab-encode "$@"
fi
