#!/usr/bin/env bash

function echo_trim_special() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Trims special characters from the input.

			USAGE:
			echo-trim-special [...options] [--] ...<input>
			echo-lines ...<input> | echo-trim-special [...options]

			OPTIONS:
			$(stdinargs_options_help --)

			EXAMPLE:

			echo-trim-special -- "\$(echo-style --green='a/b?c!e f\$g')"

			    abce fg
			    # exit status: 0

			echo-style --green='a/b?c!e f' | echo-trim-special --stdin

			    abce fg
			    # exit status: 0

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		# don't use [sd] here, as this is used by [down], and thus [setup-util-sd]
		# https://www.gnu.org/software/sed/manual/html_node/Character-Classes-and-Bracket-Expressions.html
		print_line "$1" | sed -E 's/[^[:print:]]//g; s/\[[0-9]+m//g; s/[^[:alnum:][:space:].-]//g'
	}

	stdinargs "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_trim_special "$@"
fi
