#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# get separator
separator="$1"
shift

# trim --
while test "${1-}" = '--'; do
	shift
done

# act
items=()
function act {
	items+=("$1")
}
function finish {
	for i in "${!items[@]}"; do
		if test "$i" -eq 0; then
			printf '%s' "${items[i]}"
		else
			printf '%s%s' "$separator" "${items[i]}"
		fi
	done
}

source "$DOROTHY/sources/stdinargs.bash"
