#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# turns affirmative arguments into no
# turns non-affirmative arguments into yes

function act {
	local ec
	ec=0 && is-affirmative "$1" || ec="$?"
	if test "$ec" -eq 0; then
		echo 'no'
	elif test "$ec" -eq 1; then
		echo 'yes'
	else
		return 22 # Invalid argument
	fi
}

function no_args_nor_stdin {
	return 96 # No message available on STREAM
}

source "$DOROTHY/sources/stdinargs.bash"
