#!/usr/bin/env bash

function echo_fstab_decode() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			fstab decode all input received.

			USAGE:
			echo-fstab-decode [...arguments]
			echo-lines [...arguments] | echo-fstab-decode

			EXAMPLES:
			echo-fstab-encode '|\040|\075|\054|\134|\043|'

			    | |=|,|\|#|

			echo-lines '|\040|\075|\054|\134|\043|' | echo-fstab-encode

			    | |=|,|\|#|

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# this was provided by chatgpt
	function on_input {
		local string="$1"
		local decoded_string=""

		# Replace special octal representations with their respective characters
		decoded_string=${string//\\040/ }
		decoded_string=${decoded_string//\\075/=}
		decoded_string=${decoded_string//\\054/,}
		decoded_string=${decoded_string//\\134/\\}
		decoded_string=${decoded_string//\\043/#}

		echo "$decoded_string"
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_sort "$@"
fi
