#!/usr/bin/env bash

function echo_lines_after_test() (
	source "$DOROTHY/sources/bash.bash"
	source "$(type -P eval-tester)"

	# prepare
	local expected=$'c\n\nb' needles=('' '--needle=b')
	function pl {
		__print_lines a b '' b '' c '' b
	}

	# standard tests
	eval_tester --name='using arguments' --stdout="$expected" -- \
		echo-lines-after "${needles[@]}" -- "$(pl)"

	pl | eval_tester --name='using stdin' --stdout="$expected" -- \
		echo-lines-after "${needles[@]}"

	pl | eval_tester --name='using --stdin' --stdout="$expected" -- \
		echo-lines-after "${needles[@]}" --stdin

	pl | eval_tester --name='using -' --stdout="$expected" -- \
		echo-lines-after "${needles[@]}" -

	eval_tester --name='using <<<' --stdout="$expected" -- \
		echo-lines-after "${needles[@]}" - <<<"$(pl)"

	# https://github.com/bevry/dorothy/issues/283
	local in out
	in="$(mktemp)"
	out="$(mktemp)"
	pl >"$in"
	function test_a {
		echo-lines-after "${needles[@]}" --stdin <"$in"
	}
	function test_b {
		echo-lines-after "${needles[@]}" --stdin <"$in" >"$out"
		cat "$out"
	}
	function test_c {
		echo-lines-after "${needles[@]}" --stdin >"$out" <"$in"
		cat "$out"
	}
	function test_aa {
		__print_lines '0' >"$out"
		echo-lines-after "${needles[@]}" --stdin >>"$out" <"$in"
		cat "$out"
	}
	function test_bb {
		__print_lines '0' >"$out"
		echo-lines-after "${needles[@]}" --stdin <"$in" >>"$out"
		cat "$out"
	}
	eval_tester --stdout="$expected" -- test_a
	eval_tester --stdout="$expected" -- test_b
	eval_tester --stdout="$expected" -- test_c
	eval_tester --stdout=$'0\n'"$expected" -- test_aa
	eval_tester --stdout=$'0\n'"$expected" -- test_bb

	# done
	return 0
)
function echo_lines_after() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Get everything after the first recurrence of <line>.

			USAGE:
			echo-lines-after <needle> [...options] [--] ...<input>
			echo-lines ...<input> | echo-lines-after <needle> [...options]

			OPTIONS:
			<needle> | --needle=<needle>
			    Only output the <input> that occurs after one of these <needle> lines.
			    Use [--needle=<needle>] to provide multiple needles.

			$(stdinargs_options_help --)

			EXAMPLE:

			echo-lines-after --needle='b' -- a b b c b

			    c
			    b
			    # exit status: 0

			echo-lines -- a b b c b | echo-lines-after --needle='b' --stdin

			    c
			    b
			    # exit status: 0

			echo-lines-after --needle='b' --stdin <<< "\$(echo-lines -- a b b c b)"

			    c
			    b
			    # exit status: 0
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process our own arguments, delegate everything else to stdinargs
	local item option_needles=() option_args=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--needle='*) option_needles+=("${item#*=}") ;;
		# forward to stdinargs, however support mixing and matching of our options, with stdinargs options
		'--')
			option_args+=("$item" "$@")
			shift $#
			break
			;;
		'--'*) option_args+=("$item") ;;
		*)
			if [[ ${#option_needles[@]} -eq 0 ]]; then
				option_needles+=("$item")
			else
				option_args+=("$item")
			fi
			;;
		esac
	done

	# check
	if [[ ${#option_needles[@]} -eq 0 ]]; then
		help 'No <needle>s provided.'
	fi

	# =====================================
	# Action

	local output='no' found='no' # buffer=''
	function __on_line {
		local line="$1" match='no' needle
		if [[ $output == 'no' ]]; then
			for needle in "${option_needles[@]}"; do
				if [[ $line == "$needle" ]]; then
					match='yes'
					break
				fi
			done
			if [[ $match == 'yes' ]]; then
				# found, but not yet stopped finding, continue to next line
				found='yes'
				return 0
			elif [[ $found == 'yes' ]]; then
				# found, and stopped matching, start outputting
				output='yes'
			else
				# not yet found, continue to try and find a match
				return 0
			fi
		fi
		# buffer+="$line"$'\n'
		__print_lines "$line" || return
	}
	# function __on_finish {
	# 	__print_value_strings_or_nothing "$buffer" || return
	# }
	# ^ buffering does not solve the tests on linux (non-bsd/macos), as on linux `>>` will still overwrite if something called still did `>/dev/stdout` instead of `>>/dev/stdout`

	stdinargs "${option_args[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_lines_after_test
	else
		echo_lines_after "$@"
	fi
fi
