#!/usr/bin/env bash

function echo_subpaths() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			For each file, output its absolute path.
			For each directory, output the absolute paths for each of its direct children.

			USAGE:
			echo-subpaths [...options] [--] ...<input>
			echo-lines ...<input> | echo-subpaths [...options]

			OPTIONS:
			<input>
			    A path to a file or directory.

			$(stdinargs_options_help --)

			EXAMPLE:
			echo-subpaths -- ..
			echo-subpaths -- .
			echo-subpaths -- ./*
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	function on_line {
		if [[ -d $1 ]]; then
			fs-absolute -- "$1/"*
		else
			fs-absolute -- "$1"
		fi
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_subpaths "$@"
fi
