#!/usr/bin/env bash

# https://stackoverflow.com/a/1603436/130638
# sed -e '/^$/,$d' "$@" <-- before blank lines

function print_lines_before() (
	source "$DOROTHY/sources/bash.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Get everything before the first occurence of <line>.

			USAGE:
			echo-lines-before --line=<line> [--] <...input>
			echo-lines <...input> | echo-lines-before --line=<line>

			EXAMPLE:

			echo-lines-before --line='' -- a b '' c d

			    a
			    b
			    # exit status: 0

			echo-lines a b '' c d | echo-lines-before --line=''

			    a
			    b
			    # exit status: 0

			echo-lines-before --line='' <<< "\$(echo-lines a b '' c d)"

			    a
			    b
			    # exit status: 0
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_line='' ARGS=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--line='*) option_line="${item#*--line=}" ;;
		'--')
			ARGS+=("$@")
			shift "$#"
			break
			;;
		*)
			ARGS+=("$item" "$@")
			shift "$#"
			break
			;;
		esac
	done

	# action
	function on_input {
		if test "$1" = "$option_line"; then
			BREAK='yes'
		else
			print_line "$1"
		fi
	}
	local BREAK='no'
	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	print_lines_before "$@"
fi
