#!/usr/bin/env bash

function echo_escape_spaces() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			For each <input>, escape its spaces by prepending backslashes.

			USAGE:
			echo-escape-spaces [...options] [--] ...<input>
			echo-lines ...<input> | echo-escape-spaces [...options]

			OPTIONS:
			$(stdinargs_options_help --)

			EXAMPLE:

			echo-escape-spaces -- 'hello world'

			    hello\ world
			    # exit status: 0

			echo-lines -- 'hello world' | echo-escape-spaces --stdin

			    hello\ world
			    # exit status: 0

		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	function on_input {
		local value="$1"
		value="${value// /\\ }"
		print_line "$value"
	}

	stdinargs "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_escape_spaces "$@"
fi
