#!/usr/bin/env bash

function echo_error() (
	source "$DOROTHY/sources/bash.bash"

	function __help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Forward <input> to Dorothy's \`bash.bash:__print_error\`, outputting to STDERR, and prepending an error notice.

			USAGE:
			\`echo-error [--] ...<input>\`
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	if [[ $* == '--help' ]]; then
		__help || return $?
	else
		__print_error "$@" || return $?
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_error "$@"
fi
