#!/usr/bin/env bash

function echo_if_file_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-style --h1="TEST: $0"

	eval-tester --name='no args' \
		-- echo-if-file --

	eval-tester --name='empty args' \
		-- echo-if-file -- '' ''

	eval-tester --name='missing' \
		-- echo-if-file -- "$DOROTHY/this-does-not-exist"

	eval-tester --name='directory' \
		-- echo-if-file -- "$DOROTHY"

	eval-tester --name='file' --stdout="$DOROTHY/README.md" \
		-- echo-if-file -- "$DOROTHY/README.md"

	eval-tester --name='file then missing then dir' --stdout="$DOROTHY/README.md" \
		-- echo-if-file -- "$DOROTHY/README.md" "$DOROTHY/this-does-not-exist" "$DOROTHY"

	eval-tester --name='dir then missing then file' --stdout="$DOROTHY/README.md" \
		-- echo-if-file -- "$DOROTHY" "$DOROTHY/this-does-not-exist" "$DOROTHY/README.md"

	# test working symlinks
	local dir_target dir_symlink file_target file_symlink
	dir_target="$(fs-temp --directory='echo-if-file' --directory='dir_target' --touch)"
	file_target="$(fs-temp --directory='echo-if-file' --file='file_target' --touch)"
	dir_symlink="$(fs-temp --directory='echo-if-file' --directory='dir_symlink' --no-touch)"
	file_symlink="$(fs-temp --directory='echo-if-file' --file='file_symlink' --no-touch)"
	symlink-helper --existing="$dir_target" --symlink="$dir_symlink" --quiet
	symlink-helper --existing="$file_target" --symlink="$file_symlink" --quiet

	eval-tester --name='symlink dir' \
		-- echo-if-file -- "$dir_symlink"

	eval-tester --name='symlink file' --stdout="$file_symlink" \
		-- echo-if-file -- "$file_symlink"

	# test broken symlinks
	fs-rm --quiet --no-confirm -- "$dir_target" "$file_target"

	eval-tester --name='broken symlink dir' \
		-- echo-if-file -- "$dir_symlink"

	eval-tester --name='broken symlink file' \
		-- echo-if-file -- "$file_symlink"

	echo-style --g1="TEST: $0"
	return 0
)
function echo_if_file() (
	source "$DOROTHY/sources/stdinargs.bash"

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output <input>s that are a file, or an unbroken symlink to a file.
			Companion to [is-file].

			USAGE:
			echo-if-file [...options] [--] ...<input>
			echo-lines ...<input> | echo-if-file [...options]

			OPTIONS:
			--sudo=<sudo>
			--user=<user>
			--group=<group>
			    Forwarded to [is-file].

			$(stdinargs_options_help --)

			EXAMPLES:

			echo-if-file -- "$DOROTHY/README.md"

			    $DOROTHY/README.md
			    # exit status: 0

			echo-lines -- "$DOROTHY/README.md" | echo-if-file --stdin

			    $DOROTHY/README.md
			    # exit status: 0

		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_args=() option_sudo='' option_user='' option_group=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-sudo'* | '--sudo'*)
			option_sudo="$(get-flag-value --affirmative --fallback="$option_sudo" -- "$item")"
			;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		# forward to stdinargs, however support mixing and matching of our options, with stdinargs options
		'--')
			option_args+=("$item" "$@")
			shift $#
			break
			;;
		*) option_args+=("$item") ;;
		esac
	done

	# =====================================
	# Action

	local paths=()
	function on_input {
		local path="$1"
		if is-file --sudo="$option_sudo" --user="$option_user" --group="$option_group" -- "$path"; then
			paths+=("$path")
		fi
	}
	function on_finish {
		if [[ ${#paths[@]} -ne 0 ]]; then
			__print_lines "${paths[@]}"
		fi
	}
	stdinargs "${option_args[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		echo_if_file_test
	else
		echo_if_file "$@"
	fi
fi
