#!/usr/bin/env bash

function edit() (
	source "$DOROTHY/sources/bash.bash"
	require_array 'mapfile'

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Open your preferred editor.

			USAGE:
			edit [...options] [--] [...everything here is forwarded to the editor]

			OPTIONS:
			--dry
			    If enabled, output the editor instead of invoking it.

			--[no-]prompt
			    If enabled (the default), support editors that require additional arguments to edit the file.

			--only-editor
			    If enabled, only output the editor command, and not any arguments.
			    Enforces --dry.

			--sudo
			    If enabled, the editor will be opened in sudo mode.

			--terminal
			    If enabled, enforce a terminal editor.

			--gui
			    If enabled, enforce a gui editor.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item dry='no' prompt='yes' only_editor='no' sudo='no' terminal='' gui='' args=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-dry'* | '--dry'*)
			dry="$(get-flag-value dry --missing="$dry" -- "$item" | echo-affirmative)"
			;;
		'--no-prompt'* | '--prompt'*)
			prompt="$(get-flag-value prompt --missing="$prompt" -- "$item" | echo-affirmative)"
			;;
		'--no-only-editor'* | '--only-editor'*)
			only_editor="$(get-flag-value only-editor --missing="$only_editor" -- "$item" | echo-affirmative)"
			;;
		'--no-sudo'* | '--sudo'*)
			sudo="$(get-flag-value sudo --missing="$sudo" -- "$item" | echo-affirmative)"
			;;
		'--no-terminal'* | '--terminal'*)
			terminal="$(get-flag-value terminal --missing="$terminal" -- "$item" | echo-affirmative)"
			;;
		'--no-gui'* | '--gui'*)
			gui="$(get-flag-value gui --missing="$gui" -- "$item" | echo-affirmative)"
			;;
		'--')
			args+=("$@")
			shift "$#"
			break
			;;
		*)
			args+=("$item" "$@")
			shift "$#"
			break
			;;
		esac
	done

	# check conflicts
	if test -n "$terminal" -a "$terminal" = "$gui"; then
		help "[--terminal] and [--gui] must be opposite values."
	fi

	# default terminal
	if test -z "$terminal"; then
		if is-ssh || is-headless; then
			terminal='yes'
		fi
	fi

	# =====================================
	# Configuration

	source "$DOROTHY/sources/config.bash"

	# editors.bash provides:
	local TERMINAL_EDITORS=() GUI_EDITORS=()
	load_dorothy_config 'editors.bash'

	# check config
	if test "${#TERMINAL_EDITORS[@]}" -eq 0; then
		echo-style --warning="TERMINAL_EDITORS was undefined" >/dev/stderr
	fi
	if test "${#GUI_EDITORS[@]}" -eq 0; then
		echo-style --warning="GUI_EDITORS was undefined" >/dev/stderr
	fi

	# =====================================
	# Action

	# grab options
	local editors=()
	if test "$terminal" = 'yes' -o "$sudo" = 'yes'; then
		editors=("${TERMINAL_EDITORS[@]}")
	else
		editors=("${GUI_EDITORS[@]}")
	fi

	# filter options by available
	local editor __editor __command
	for __editor in "${editors[@]}"; do
		editor=()
		__command="${__editor%% *}"
		if test -n "$__command"; then
			if command-exists "$__command"; then
				mapfile -t editor < <(echo-split ' ' -- "$__editor")

				# absolute path so sudo has availability: may not actually be necessary
				# editor[0]="$(fs-absolute -- "${editor[0]}")"

				# editors that require prompts
				if [[ $__command =~ code|atom|subl ]]; then
					if test "$prompt" = 'yes'; then
						editor+=('-w') # wait
						if [[ $__command =~ code ]]; then
							editor+=('-n') # new window
						fi
					else
						continue
					fi
				elif [[ $__command =~ emacs ]]; then
					if test "$prompt" = 'yes'; then
						editor+=('--no-window-system')
					else
						continue
					fi
				fi

				# it exists, use it
				break
			elif get-app "$__command" >/dev/null; then
				# apps require prompts
				if test "$prompt" = 'yes'; then
					mapfile -t editor < <(echo-split ' ' -- "$__editor")
					editor=('open' '-a' "${editor[@]}")
				else
					continue
				fi
			fi

			# we have a suitable editor, leave the search
			break
		fi
	done

	# check editor
	if test "${#editor[@]}" -eq 0; then
		echo-style --error="$0: None of the configured editors were available:" $'\n' "$(echo-verbose "${editors[@]}")" >/dev/stderr
		return 42 # ENOPROTOOPT 42 Protocol not available
	fi

	# only output the editor command
	if test "$only_editor" != 'no'; then
		print_line "${editor[0]}"
		return
	fi

	# generate the entire command
	local cmd=()
	if test "$sudo" = 'yes'; then
		cmd+=(
			'sudo-helper'
			'--inherit'
			'--'
		)
	fi
	cmd+=("${editor[@]}")
	if test "${#args[@]}" -ne 0; then
		cmd+=("${args[@]}")
	fi

	# invoke
	if test "$dry" = 'yes'; then
		print_line "${cmd[@]}"
	else
		"${cmd[@]}"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	edit "$@"
fi
