#!/usr/bin/env bash
source "$BDIR/sources/essentials.sh"
source "$BDIR/sources/strict.bash"

add-scripts

if is-string "${1:-}"; then
	edit "$BDIR/commands/$1"
else
	edit "$BDIR" "$HOME/README.md"
fi
