#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/edit.sh"
source "$DOROTHY/sources/strict.bash"

# perms
setup-dorothy-permissions

edit "$DOROTHY"

if confirm-negative 'Open Git Reviewer?'; then
	ok git-review "$DOROTHY/user"
	ok git-review "$DOROTHY"
fi