#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/edit.sh"
source "$DOROTHY/sources/strict.bash"

add-scripts

mkdir -p "$DOROTHY/users/$(whoami)"
edit "$DOROTHY/users/$(whoami)"