#!/usr/bin/env bash

# escape-spaces converts the intuitive
# expand-path '/Applications/Visual *'
# into the correct
# expand-path '/Applications/Visual\\ *'

function expand-path-bash() (
	source "$DOROTHY/sources/bash.bash"
	require_nullglob

	if is-globstar "$*"; then # only if needed
		require_globstar
	fi
	for arg in "$@"; do
		eval echo-lines -- "$(echo-escape-spaces "$arg")"
	done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	expand-path-bash "$@"
fi
