#!/usr/bin/env bash
# check version....

# use globstar ** only if we need it
if is-globstar "$*"; then
	source "$DOROTHY/sources/globstar.bash"
	if test "$GLOBSTAR" = 'no'; then
		exit 1
	fi
fi

# nullglob prevents `missing*` from returning `"missing*"`
# which is essential if there are no matches
source "$DOROTHY/sources/nullglob.bash"
if test "$NULLGLOB" = 'no'; then
	exit 1
fi

# escape-spaces converts the intuitive
# expand-path '/Applications/Visual *'
# into the correct
# expand-path '/Applications/Visual\\ *'

for arg in "$@"; do
	eval echo-lines "$(escape-spaces "$arg")"
done
