#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/nullglob.bash"
if is-globstar "$*"; then # only if needed
	source "$DOROTHY/sources/globstar.bash"
fi

# escape-spaces converts the intuitive
# expand-path '/Applications/Visual *'
# into the correct
# expand-path '/Applications/Visual\\ *'

for arg in "$@"; do
	eval echo-lines "$(escape-spaces "$arg")"
done
