#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$(which echo-trim-empty-lines)"

function expand-path() (
	# using zsh then bash, works around macos which has old bash, but new zsh
	# so this is needed so setup-paths-commands can do its thing

	if type -P zsh &>/dev/null; then
		expand-path-zsh "$@" 2>/dev/null | echo-trim-empty-lines
	else
		source "$(which expand-path-bash)"
		expand-path-bash "$@" 2>/dev/null | echo-trim-empty-lines
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	expand-path "$@"
fi
