#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if command-exists curl; then
	curl -fsSL "$@"
elif command-exists wget; then
	wget "$@" -O -
else
	stderr 'curl and wget are not installed, at least one needs to exist'
	exist 1
fi
