#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

for arg in "$@"; do
	filename="${arg%.mov*}"

	ffmpeg -i "$arg" -map 0:0 -map 0:2 -c copy "$filename [00+02].mov"
	ffmpeg -i "$arg" -map 0:1 -map 0:3 -c copy "$filename [01+03].mov"

done