#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/globstar.bash"

ext="$(ask "What is the extension of the files you wish to find?" "${1-}" --required)"
cmd="$(ask "If you wish to run a command for each file, enter it now." "${2-}")"

if test -n "$cmd"; then
	find . -path "**/*.$ext" -exec "$cmd" {} \;
else
	find . -path "**/*.$ext"
fi
