#!/usr/bin/env bash
source "$BDIR/sources/strict.bash"

if command-exists dnscrypt-proxy; then
	echo 'restarting dnscrypt-proxy'
	brew services restart dnscrypt-proxy
fi

# https://support.apple.com/en-us/HT202516
if is-mac; then
	if command-exists mDNSResponder; then
		echo 'restarting mDNSResponder'
		sudo killall -HUP mDNSResponder
	fi
	if command-exists dscacheutil; then
		echo 'flushing dscacheutil'
		sudo dscacheutil -flushcache
	fi
	if command-exists discoveryutil; then
		echo 'flushing discoveryutil'
		sudo discoveryutil mdnsflushcache
	fi
else
	echo "DNS flushing only for MacOS currently"
fi