#!/usr/bin/env bash

function fs_diff_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-style --h1="TEST: $0"

	local actual_file data=$'a\n\0b' diff='a'
	actual_file="$(fs-temp --directory='fs-diff' --directory='tests' --file)"
	expected_file="$actual_file.expected"
	actual_file="$actual_file.actual"
	__print_string "$data" >"$expected_file"

	# same
	__print_string "$data" >"$actual_file"
	eval-tester --status=0 -- fs-diff -- "$actual_file" "$expected_file"

	# diff
	__print_string "$diff" >"$actual_file"
	eval-tester --status=0 -- fs-diff -- "$actual_file" "$expected_file"

	echo-style --g1="TEST: $0"
	return 0
)
function fs_diff() (
	source "$DOROTHY/sources/bash.bash"

	local all_tools=(delta difft diff-so-fancy git)

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Output a pretty difference comparison between two files.

			USAGE:
			fs-diff [...options] [-- <before-file> <after-file>]

			OPTIONS:
			--tool=<tool>
			    The diff tool to use.
			    Available tools in order of preference: ${all_tools[*]}

			--before=<before-file> | <before-file>
			    The old file for the comparison.

			--after=<after-file> | <after-file>
			    The new file for the comparison.

			--elevated=<elevated>
			--elevate=<elevate>
			    Unless specified, will auto-elevate if <before-file> or <after-file> are not readable otherwise.
			--user=<user>
			--group=<group>
			--reason=<reason>
			    Forwarded to [eval-helper].
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_before='' option_after='' option_tool='' option_elevated='' option_elevate='' option_user='' option_group='' option_reason=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--tool='*) option_tool="${item#*=}" ;;
		'--before='*) option_before="${item#*=}" ;;
		'--after='*) option_after="${item#*=}" ;;
		# <elevate>
		'--elevated='*) option_elevated="${item#*=}" ;;
		'--no-elevate'* | '--elevate'*)
			option_elevate+="$(get-flag-value --affirmative --fallback="$option_elevate" -- "$item")"
			;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--reason='*) option_reason="${item#*=}" ;;
		# </elevate>
		'--')
			if [[ -z $option_before ]]; then
				option_before="$1"
				shift
			fi
			if [[ -z $option_after ]]; then
				option_after="$1"
				shift
			fi
			if [[ $# -ne 0 ]]; then
				help "An unrecognised flag was provided: $*"
			fi
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if [[ -z $option_before ]]; then
				option_before="$item"
			elif [[ -z $option_after ]]; then
				option_after="$item"
			else
				help "An unrecognised flag was provided: $item"
			fi
			;;
		esac
	done

	# ensure sudo is a valid value
	if [[ -n $option_user || -n $option_group ]]; then
		option_elevate='yes'
	fi
	if [[ -z $option_reason ]]; then
		option_reason='Your password is required to momentarily grant privileges to compare the files:'
	fi

	# ensure before and after are valid
	if [[ -z $option_before || -z $option_after ]]; then
		help 'You must provide both <before> and <after> files.'
	fi

	# ensure tool
	if [[ $option_tool == '?' ]]; then
		option_tool="$(choose --required 'Which diff tool to use?' -- "${all_tools[@]}")"
		if __command_missing -- "$option_tool"; then
			get-installer --first-success --invoke --quiet -- "$option_tool"
		fi
	elif [[ -z $option_tool ]]; then
		local item
		for item in "${all_tools[@]}"; do
			if __command_exists -- "$item"; then
				option_tool="$item"
				break
			fi
		done
	fi

	# auto-elevation
	if [[ -z $option_elevated ]]; then
		option_elevated="$(mktemp)"
	fi
	is-readable --elevated="$option_elevated" --elevate="13 93 $option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
		"$option_before" "$option_after"
	if [[ -s $option_elevated ]]; then
		option_elevate='yes'
	fi

	# =====================================
	# Action

	# @todo support just plain diff
	if [[ $option_tool == 'delta' ]]; then
		# delta fails to detect terminal width correctly so do it ourselves
		local terminal_columns
		__split terminal_size --no-zero-length < <(get-terminal-lines-and-columns || :)
		if [[ ${#terminal_size[@]} -eq 2 ]]; then
			terminal_columns="${terminal_size[1]}"
		else
			terminal_columns='variable'
		fi
		# https://github.com/dandavison/delta/issues/221
		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			delta --width="$terminal_columns" --paging never -s "$option_before" "$option_after" | echo-trim-zero-length --stdin
	elif [[ $option_tool == 'difft' ]]; then
		# difftastic
		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			difft "$option_before" "$option_after"
	elif [[ $option_tool == 'diff-so-fancy' ]]; then
		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			diff -u -- "$option_before" "$option_after" | diff-so-fancy
	elif [[ $option_tool == 'git' ]]; then
		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			git diff -- "$option_before" "$option_after"
	else
		help "The tool [$option_tool] is not yet supported."
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		fs_diff_test
	else
		fs_diff "$@"
	fi
fi
