#!/usr/bin/env bash

function fs_diff_test() (
	source "$DOROTHY/sources/bash.bash"

	local actual_file
	actual_file="$(fs-temp --directory='fs-diff' --directory='tests' --file)"
	expected_file="$actual_file.expected"
	actual_file="$actual_file.actual"
	printf 'a\n\0b' >"$expected_file" # don't use variable, don't use __print_* as bash trims null characters

	# same
	printf 'a\n\0b' >"$actual_file"
	eval-tester --status=0 -- fs-diff -- "$actual_file" "$expected_file"

	# diff
	printf 'a\n' >"$actual_file"
	eval-tester --status=1 --ignore-stdout -- fs-diff -- "$actual_file" "$expected_file"

	return 0
)
function fs_diff() (
	source "$DOROTHY/sources/bash.bash"

	local all_tools=(delta difft diff-so-fancy git)

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Output a pretty difference comparison between two files.

			USAGE:
			fs-diff [...options] [-- <before-file> <after-file>]

			OPTIONS:
			--tool=<tool>
			    The diff tool to use.
			    Available tools in order of preference: ${all_tools[*]}

			--before=<before-file> --after=<after-file> | -- <before-file> <after-file>
			    <before-file> is the old file for the comparison.
			    <after-file> is the new file for the comparison.

			--unchanged
			    Show all lines instead of just changed lines.

			--elevated=<elevated>
			--elevate=<elevate>
			    Unless specified, will auto-elevate if <before-file> or <after-file> are not readable otherwise.
			--user=<user>
			--group=<group>
			--reason=<reason>
			    Forwarded to [eval-helper].

			RETURNS:
			[0] if no diff was necessary, the files are the same.
			[1] if a diff was necessary, the files are different.
			[*] if another error occurred.
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_before='' option_after='' option_tool='' option_unchanged='' option_elevated='' option_elevate='' option_user='' option_group='' option_reason=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--tool='*) option_tool="${item#*=}" ;;
		'--before='*) option_before="${item#*=}" ;;
		'--after='*) option_after="${item#*=}" ;;
		'--no-unchanged'* | '--unchanged'*) __flag --source={item} --target={option_unchanged} --affirmative ;;
		# <elevate>
		'--elevated='*) option_elevated="${item#*=}" ;;
		'--no-elevate'* | '--elevate'*) __flag --source={item} --target={option_elevate} --affirmative ;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--reason='*) option_reason="${item#*=}" ;;
		# </elevate>
		'--')
			if [[ $1 == --*=* ]]; then
				help "An unrecognised argument was provided: $1"
			fi
			if [[ -z $option_before ]]; then
				option_before="$1"
				shift
			fi
			if [[ -z $option_after ]]; then
				option_after="$1"
				shift
			fi
			if [[ $# -ne 0 ]]; then
				help "An unrecognised flag was provided: $*"
			fi
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if [[ -z $option_before ]]; then
				option_before="$item"
			elif [[ -z $option_after ]]; then
				option_after="$item"
			else
				help "An unrecognised flag was provided: $item"
			fi
			;;
		esac
	done

	# ensure sudo is a valid value
	if [[ -n $option_user || -n $option_group ]]; then
		option_elevate='yes'
	fi
	if [[ -z $option_reason ]]; then
		option_reason='Your password is required to momentarily grant privileges to compare the files:'
	fi

	# ensure before and after are valid
	if [[ -z $option_before || -z $option_after ]]; then
		help 'You must provide both <before> and <after> files.'
	fi

	# ensure tool
	if [[ $option_tool == '?' ]]; then
		option_tool="$(choose --required 'Which diff tool to use?' -- "${all_tools[@]}")"
		if __command_missing -- "$option_tool"; then
			get-installer --first-success --invoke --quiet -- "$option_tool"
		fi
	elif [[ -z $option_tool ]]; then
		local item
		for item in "${all_tools[@]}"; do
			if __command_exists -- "$item"; then
				option_tool="$item"
				break
			fi
		done
	fi

	# auto-elevation
	if [[ -z $option_elevated ]]; then
		option_elevated="$(mktemp)"
	fi
	is-readable --elevated="$option_elevated" --elevate="13 93 $option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
		"$option_before" "$option_after"
	if [[ -s $option_elevated ]]; then
		option_elevate='yes'
	fi

	# =====================================
	# Action

	# @todo support just plain diff
	if [[ $option_tool == 'delta' ]]; then
		# delta fails to detect terminal width correctly so do it ourselves
		local terminal_size=() delta_args=(--paging never -s "$option_before" "$option_after")
		__split --target={terminal_size} --no-zero-length --invoke=try -- \
			get-terminal-lines-and-columns
		if [[ ${#terminal_size[@]} -eq 2 ]]; then
			delta_args+=(--width="${terminal_size[1]}")
		else
			delta_args+=(--width='variable')
		fi
		if [[ $option_unchanged == 'yes' ]]; then
			delta_args+=('-@=-U9999')
		fi
		# https://github.com/dandavison/delta/issues/221
		eval-helper --inherit --redirect-stdout='(echo-trim-zero-length --stdin)' --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			delta "${delta_args[@]}"
	elif [[ $option_tool == 'difft' ]]; then
		# difftastic
		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			difft "$option_before" "$option_after"
	elif [[ $option_tool == 'diff-so-fancy' ]]; then
		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			diff -u -- "$option_before" "$option_after" | diff-so-fancy
	elif [[ $option_tool == 'git' ]]; then
		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
			git diff -- "$option_before" "$option_after"
	else
		help "The tool [$option_tool] is not yet supported."
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		fs_diff_test
	else
		fs_diff "$@"
	fi
fi
