#!/usr/bin/env bash

function fs_extension() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Get the extension of a basename.

			USAGE:
			fs-extension [--] ...<path>

			EXAMPLE:
			fs-extension .dorothy/a.b.c
			    c

		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item paths=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--')
			paths+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) paths+=("$item") ;;
		esac
	done

	# check
	if test "${#paths[@]}" -eq 0; then
		help 'No <path>s were provided.'
	fi

	# =====================================
	# Action

	local path
	for path in "${paths[@]}"; do
		print_line "${path##*.}" # fs-extension .dorothy/a.b.c => c
	done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	fs_extension "$@"
fi
