#!/usr/bin/env bash

function fs_join() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Join <path>s together.

			USAGE:
			fs-join [--] ...<path>
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_paths=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--path='*) option_paths+=("${item#*=}") ;;
		'--')
			option_paths+=("$@")
			shift "$#"
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			option_paths+=("$item" "$@")
			shift "$#"
			break
			;;
		esac
	done

	# =====================================
	# Action

	# allow leading slashes on first item
	# so /Volumes/... still works
	local result="${option_paths[0]}" i next
	for ((i = 1; i < ${#option_paths[@]}; i++)); do
		next="${option_paths[i]}"
		# trim trailing slashes
		while [[ $result == *'/' ]]; do
			result="$(__get_substring "$result" 0 -1)"
		done
		while [[ $next == *'/' ]]; do
			next="$(__get_substring "$next" 0 -1)"
		done
		# trim leading slashes
		while [[ $next == '/'* ]]; do
			next="$(__get_substring "$next" 1)"
		done
		# join
		if [[ -n $result && -n $next ]]; then
			result="$result/$next"
		else
			result="$result$next"
		fi
	done
	__print_lines "$result"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	fs_join "$@"
fi
