#!/usr/bin/env bash

function fs_owner_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- fs-owner --help

	# @todo add way more tests
	eval-tester --name='ok using arguments' --ignore-stdout -- \
		fs-owner -- "$DOROTHY/README.md"

	return 0
)
function fs_owner() (
	source "$DOROTHY/sources/is-fs.bash"

	# =====================================
	# Arguments

	function __help {
		local fodder
		fodder="$(__is_fs__options '13')" || return $?
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Output the user id, user name, group id, and group name of the path.

			USAGE:
			fs-owner [...options] [--] ...<path>

			OPTIONS:
			$fodder

			RETURNS:
			[0] if we could retrieve ownership for all <path>s
			[2] if a <path> was missing
			[13] if a <path> was not accessible
			[22] if empty arguments were provided
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	__is_fs__args "$@" || return $?

	# invoke
	__is_fs__invoke 'fs-owner.bash' '13' || return $?

	# errors
	__is_fs__error || return $?

	# done
	return "$fs_status"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		fs_owner_test
	else
		fs_owner "$@"
	fi
fi
