#!/usr/bin/env bash

function fs-rm() (
	source "$DOROTHY/sources/strict.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Remove the paths from the file system, with some safety checks in place.

			USAGE:
			fs-rm [...options] [--] ...<path>

			OPTIONS:
			--no-confirm
			    If specified, skip confirms.

			--sudo
			    If specified, use sudo when removing the files.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item paths=() quiet='no' confirm='yes' sudo='no'
	quiet="$(echo-quiet "$quiet" -- "$@")"
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
		'--no-confirm'* | '--confirm'*)
			confirm="$(get-flag-value confirm --missing="$confirm" -- "$item" | echo-affirmative)"
			;;
		'--no-sudo'* | '--sudo'*)
			sudo="$(get-flag-value sudo --missing="$sudo" -- "$item" | echo-affirmative)"
			;;
		'--')
			paths+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) paths+=("$item") ;;
		esac
	done

	# check
	if test "${#paths[@]}" -eq 0; then
		help "No <paths> were provided."
	fi

	# =====================================
	# Dependencies

	setup-util-dust --quiet

	# =====================================
	# Action

	function maybe_sudo {
		if test "$sudo" = 'yes'; then
			sudo-helper --inherit -- "$@"
		else
			"$@"
		fi
	}

	function do_confirm {
		local path="$1"

		# note its structure and size
		echo
		maybe_sudo eval-helper --no-quiet --wrap -- ls -la "$path"
		echo
		maybe_sudo eval-helper --no-quiet --wrap -- dust --no-percent-bars "$path"
		echo
		maybe_sudo eval-helper --no-quiet --wrap -- dust --no-percent-bars --filecount "$path"
		echo

		# confirm their removal
		confirm --positive --ppid=$$ -- "$(
			echo-style --notice="Confirm removal of non-empty" --bold=" $path " --notice="?"
		)"
	}

	local conclusion
	function act {
		local path="$1"
		path="$(fs-absolute -- "$path")"

		# is the path missing
		if test ! -e "$path"; then
			conclusion="$(
				echo-style --green="was previously removed."
			)"
			return 0
		fi
		# path exists

		# delete empty directories
		maybe_sudo find "$path" -empty -type d -delete || :
		if test ! -e "$path"; then
			conclusion="$(
				echo-style --green="was only empty directories, it has been removed."
			)"
			return 0
		fi
		# there are leftovers

		# confirm and remove, or no confirm and remove
		if test "$confirm" = 'no' || do_confirm "$path"; then
			maybe_sudo rm -rfv "$path" || :
			# || : as we detect successful removal below
		fi

		# fail if not removed
		if test -e "$path"; then
			conclusion="$(
				echo-style --red="has non-empty files, it has been kept."
			)"
			return 66 # Directory not empty
		fi

		# success if removed
		conclusion="$(
			echo-style --green="had non-empty files, it was manually removed."
		)"
	}

	# act with wrapping of success
	local path title result=0
	for path in "${paths[@]}"; do
		if test "$quiet" = 'yes'; then
			act "$path"
		else
			title="fs-rm $(echo-quote "$path")"
			echo-segment --h2="$title"
			if act "$path"; then
				echo-segment --g2="$title" " $conclusion"
			else
				result="$?"
				echo-segment --e2="$title" " $conclusion"
			fi
		fi
	done

	return "$result"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	fs-rm "$@"
fi
