#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function fs-realpath() (
	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output the absolute (relative paths are expanded) and real (symlinks are resolved) respresentation of a path.

			USAGE:
			fs-realpath <path>

			QUIRKS:
			Use [fs-absolute] if you do not want symlinks resolved.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# options
	local item option_path=''
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--path='*) option_path="${item:7}" ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if test -z "$option_path"; then
				option_path="$item"
			else
				help "An unrecognised argument was provided: $item"
			fi
			;;
		esac
	done

	# adjust path
	if test -z "$option_path"; then
		help "No <path> was provided."
	fi

	# =====================================
	# Action

	if command-exists realpath; then
		realpath "$option_path"
	elif command-exists readlink; then
		readlink -e "$option_path"
	elif command-exists fish && test "$(version-compare "$(fish -c 'echo $FISH_VERSION')" 3.3.0)" -ge 0; then
		# https://gitter.im/fish-shell/fish-shell?at=60e4d29c9cf317173013b830
		# not supported in fish v3.1.2
		# supported in fish version v3.3.0
		# exact compatibility unknown
		# if you are using an old version, remove fish and reinstall using [setup-util-fish]
		# shellcheck disable=SC2016
		fish -c 'realpath "$argv[1]"' -- "$option_path"
	else
		env QUIET=yes setup-util-realpath
		realpath "$option_path"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	fs-realpath "$@"
fi
