#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=yes setup-util-dust

# prepare
path="$1"
conclusion=''

function fs_size() {
	# is the path missing
	if test ! -e "$path"; then
		conclusion="is missing."
		return 2 # No such file or directory
	fi
	# path exists

	# note its contents
	echo
	echo-eval ls -la "$path"
	echo
	echo-eval dust --no-percent-bars "$path"
	echo
	echo-eval dust --no-percent-bars --filecount "$path"
	echo
	if is-empty-ls "$path"; then
		conclusion="is an empty directory."
		return
	fi

	# note its size
	if is-empty-size "$path"; then
		conclusion="is only empty directories."
		return
	fi

	# leftovers
	conclusion="has non-empty files."
	return
}

# act
echo-segment --h1="fs-size $path"
if fs_size; then
	echo-segment --g1="fs-size $path" " $conclusion"
else
	echo-segment --e1="fs-size $path" " $conclusion"
fi
