#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

path="$(ask --question="Enter the path to output the structure of." --default="${1-}" --required)"

# ls
#   -A, --almost-all           do not list implied . and ..
#   -l                         use a long listing format
#     --time-style=TIME_STYLE  time/date format with -l; see TIME_STYLE below

if test -d "$path"; then
	cd "$path" || exit 1
	ls -lA --time-style=+''
else
	cd "$(dirname "$path")" || exit 1
	ls -lA --time-style=+'' "$(basename "$path")"
fi
