#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# =====================================
# Arguments

# help
function help() {
	cat <<-EOF >/dev/stderr
		ABOUT:
		Make a temporary file inside a directory.

		USAGE:
		fs-temp [--prefix=...] [--suffix=...] [directory]
	EOF
	if test "$#" -ne 0; then
		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines "$@")" >/dev/stderr
	fi
	return 22 # Invalid argument
}

# process
option_directory=''
option_prefix=''
option_suffix=''
while test "$#" -ne 0; do
	item="$1"
	shift
	case "$item" in
	'--help' | '-h') help ;;
	'--directory='*) option_directory="${item:12}" ;;
	'--prefix='*) option_prefix="${item:9}" ;;
	'--suffix='*) option_suffix="${item:9}" ;;
	'--') ;;
	'--'*) help "An unrecognised flag was provided: $item" ;;
	*)
		if test -z "$option_directory"; then
			option_directory="$item"
		else
			help "An unrecognised argument was provided: $item"
		fi
		;;
	esac
done

# if no directory was provided, then use a random one
if test -z "$option_directory"; then
	option_directory="$(mktemp -d)"
else
	mkdir -p "$option_directory"
fi

# =====================================
# Act

# generate a non-existent path
result=''
while true; do
	result="${option_directory}/${option_prefix}$RANDOM${option_suffix}"
	if test ! -e "$result"; then
		break
	fi
done

# done
echo "$result"
