#!/usr/bin/env bash

function fs_temp() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Make a temporary path.

			USAGE:
			fs-temp [...options] --directory[=<dirname>]   # generate a directory path
			fs-temp [...options] --file[=<filename>]       # generate a file path

			OPTIONS:
			--xdg
			    If truthy, enforce XDG usage.
			    If falsey, disable XDG usage.
			    If omitted, use system XDG preference.

			--root=<root> | --inside=<root>
			    Use this as the root directory path.
			    If omitted, will detect it based on XDG usage.

			--directory=<dirname>
			    Append the <root> path with this <dirname>.
			    Use an empty <dirname> to generate a non-existent directory name.

			--file=<filename>
			    Append the <root> path with this <filename>.
			    Use an empty <filename> to generate a non-existent filename.
			    You can specify multiple if you want multiple filenames generated.

			--prefix=<prefix>
			    When generating a <dirname> or <filename>, use this <prefix>.

			--suffix=<suffix>
			    When generating a <dirname> or <filename>, use this <suffix>.

			--extension=<extension>
			    When generating a <filename>, use this <extension>.

			--touch
			    Unless falsey, then directories will be made.
			    If truthy, the file, if applicable, will be created.

			--content=<content>
			    If provided, and if making a file, then the content of the file will be <content>.
			    Implies [--touch].

			QUIRKS:
			Unless [--touch] is truthy, then file paths won't be created on the file system.
			Unless [--touch] is falsey, directory paths will be created.
			This combination is to avoid your tooling complaining about existing files,
			while avoiding complaints about unable to write a new file to a non-existent path.
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	local option_xdg="${PREFER_XDG:-"no"}"
	local option_root=''
	local option_directories=()
	local option_files=()
	local option_prefix=''
	local option_suffix=''
	local option_extension=''
	local option_touch=''
	local option_content=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-xdg'* | '--xdg'*) __flag --source={item} --target={option_xdg} --affirmative --coerce ;;
		'--no-touch'* | '--touch'*) __flag --source={item} --target={option_touch} --affirmative --coerce ;;
		'--root='* | '--inside='*) option_root="${item#*=}" ;;
		'--directory') option_directories+=('') ;;
		'--directory='*) option_directories+=("${item#*=}") ;;
		'--file') option_files+=('') ;;
		'--file='*) option_files+=("${item#*=}") ;;
		'--prefix='*) option_prefix="${item#*=}" ;;
		'--suffix='*) option_suffix="${item#*=}" ;;
		'--extension='*) option_extension="${item#*=}" ;;
		'--content='*)
			option_touch=yes
			option_content="${item#*=}"
			;;
		'--') ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# if extension exists, ensure it starts with a .
	if [[ -n $option_extension && ${option_extension:0:1} != '.' ]]; then
		option_extension=".${option_extension}"
	fi

	# ensure --file[=...] or --directory[=....] where provided
	if [[ ${#option_files[@]} -eq 0 && ${#option_directories[@]} -eq 0 ]]; then
		help "You must provide at least one --file[=<filename>] or --directory[=<dirname>] option, so we know what we are generating."
	fi

	# =====================================
	# Act

	local root directory file

	# generate the root path, that directories and the file will go inside
	if [[ -n $option_root ]]; then
		root="$option_root"
	else
		if [[ $option_xdg == 'yes' ]]; then
			root="$XDG_CACHE_HOME/dorothy"
		else
			root="$(mktemp -d)"
		fi
	fi

	# add the directories to the root
	for directory in "${option_directories[@]}"; do
		if [[ -z $directory ]]; then
			# generate a non-existent directory name
			while :; do
				directory="$option_prefix$(get-random-number)$option_suffix"
				if is-missing -- "$root/$directory"; then
					break
				fi
			done
		fi
		root="$root/$directory"
	done

	# ensure the root (with added directories) now exists
	if [[ $option_touch != 'no' ]]; then
		__mkdirp "$root"
	fi

	# if no files, output directory path
	if [[ ${#option_files[@]} -eq 0 ]]; then
		__print_lines "$root"
	else
		# output as many filenames as requested
		for file in "${option_files[@]}"; do
			if [[ -z $file ]]; then
				# generate a non-existent filename
				while :; do
					file="$option_prefix$(get-random-number)$option_suffix$option_extension"
					if is-missing -- "$root/$file"; then
						break
					fi
				done
			fi
			if [[ $option_touch == 'yes' ]]; then
				if [[ -n $option_content ]]; then
					printf '%s' "$option_content" >"$root/$file"
				else
					touch -- "$root/$file"
				fi
			fi
			__print_lines "$root/$file"
		done
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	fs_temp "$@"
fi
