#!/usr/bin/env bash

# =====================================
# Arguments

# help
function help() {
	cat <<-EOF >/dev/stderr
		ABOUT:
		Geocodes a location to coordinates using the Mapbox API:
		https://docs.mapbox.com/help/getting-started/geocoding/

		USAGE:
		geocode [--token=...] [--location=...]
	EOF
	if test "$#" -ne 0; then
		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
	fi
	return 22 # Invalid argument
}

# process
option_token=''
option_location=''
while test "$#" -ne 0; do
	item="$1"
	shift
	case "$item" in
	'help' | '--help' | '-h') help ;;
	'--token='*) option_token="${item:8}" ;;
	'--location='*) option_location="${item:11}" ;;
	'--'*) help "An unrecognised flag was provided: $item" ;;
	*) help "An unrecognised argument was provided: $item" ;;
	esac
done

# ensure
option_token="$(
	ask --required \
		--question='What is your Mapbox Access Token?' \
		--default="$option_token"
)"
option_location="$(
	ask --required \
		--question='What is the location to geocode?' \
		--default="$option_location"
)"

# =====================================
# Action

fetch "https://api.mapbox.com/geocoding/v5/mapbox.places/$option_location.json?access_token=$option_token"
