#!/usr/bin/env bash

# help
if is-help "$@"; then
	stderr echo-lines \
		'ABOUT:' \
		'Geocodes a location to coordinates using the Mapbox API:' \
		'https://docs.mapbox.com/help/getting-started/geocoding/' \
		'' \
		'USAGE:' \
		'geocode <--location=...> <--token=...>'
	exit 22 # Invalid argument
fi

# options
token="$(ask --question='What is your Mapbox Access Token?' --required --flag=token -- "$@")"
location="$(ask --question='What is the location to geocode?' --required --flag=location -- "$@")"

# act
fetch "https://api.mapbox.com/geocoding/v5/mapbox.places/$location.json?access_token=$token"
