#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# Ensure the name has .app appended
name="${*%.app}.app"

# Iterate through a few options
dirs=(
	"$HOME/Applications"
	"/Applications"
	"/Applications/Setapp"
)
for dir in "${dirs[@]}"; do
	path="$dir/$name"
	if is-dir "$path"; then
		echo "$path"
		exit 0
	fi
done

# No path was successful, so exit
exit 1