#!/usr/bin/env bash

# @todo this command needs a major rework

function get-first-commit() (
	source "$DOROTHY/sources/strict.bash"

	# dependencies
	source "$DOROTHY/sources/ripgrep.bash"

	function act {
		local fc repo
		if test -z "${OPEN-}"; then
			git log --reverse --oneline | echo-first
		else
			fc="$(git log --reverse --oneline | echo-first | rg '(.+?) .+' --replace '$1')"
			repo="$(git remote -v | echo-first | rg '.+?github[.]com:(.+?)[.]git.+' --replace '$1')"
			open "https://github.com/$repo/commit/$fc"
		fi
	}

	local tempdir
	if test -n "${1-}"; then
		tempdir="$(mktemp -d)"
		gh repo clone "$1" "$tempdir" -- --quiet
		cd "$tempdir"
		act
		rm -Rf "$tempdir"
	else
		act
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	get-first-commit "$@"
fi
