#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# help
if is-help "$@"; then
	cat <<-EOF >/dev/stderr
		ABOUT:
		Output a random number.

		USAGE:
		get-random-number
	EOF
	exit 22 # Invalid argument
fi

# act
if test -n "$RANDOM"; then
	echo "$RANDOM"
else
	env QUIET=yes setup-util-fish
	fish -c random
fi
