#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# depends on:
# https://github.com/BurntSushi/ripgrep/

target="${1:?"USAGE: get-local-to-remote <locally-mounted-path>"}"

remotes="$(get-volumes --remote)"
mapfile -t remotes <<<"$remotes"

result=''
for parts in "${remotes[@]}"; do
	mapfile -d $'\t' -t parts <<< "$parts"$'\t'  # the $'\t' is necessary to remove the trailing newline that is injected on the last element
	volume="${parts[0]}"
	path="$(echo "$target" | rg '^'"$volume"'(.+)' --replace '$1' || echo '')"
	if test -n "$path"; then
		server="${parts[1]}"
		directory="${parts[2]}"
		result="$server:$directory$path"
		break
	fi
done

if test -n "$result"; then
	echo "The local to remote conversion for [$target] will probably be something like these, but not these, as the username will be a local login username, and the mount point will be the local mount point rather than the remote mount point, as such, these are only suggestions to guide what the correct combination could be:"
	echo
	echo "$result"
	echo
	echo "$result" | rg --color never '(.+)@(.+?)([.].+)?:(.+)' --replace 'a-login-user@$2:/mnt$4'
else
	exit 1
fi
