#!/usr/bin/env bash

function get_terminal_lines_and_columns_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- get-terminal-lines-and-columns --help
)

function get_terminal_lines_and_columns() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Get terminal size in lines and columns.

			USAGE:
			get-terminal-lines-and-columns [...options]

			RETURNS:
			[0] can detect terminal lines and columns
			[19] cannot detect terminal lines and columns
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Action

	[[ $CAN_QUERY_TERMINAL_SIZE == 'yes' ]] || return 19
	get-terminal-lines-and-columns.bash || return $?
	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		get_terminal_lines_and_columns_test
	else
		get_terminal_lines_and_columns "$@"
	fi
fi
