#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function get-min() (
	echo-lines -- "$@" | sort -n | echo-first
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	get-min "$@"
fi
