#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# prepare
needle="${1-}"
haystack="${2-}"
if test -z "$needle" -o "$#" -le 1; then
	stderr echo 'USAGE: get-first-suffix <needle> <haystack>'
	stderr echo
	stderr echo 'EXAMPLES:'
	stderr echo 'get-first-suffix = a=b=c  # b=c'
	stderr echo 'get-first-suffix = sup    # sup'
fi

# check if empty
if test -z "$haystack"; then
	exit 0
fi

# do the magic
echo "${haystack#*"$needle"}"
