#!/usr/bin/env bash

function get_opensuse_release() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Get the release identifier of the openSUSE system.

			USAGE:
			get-opensuse-release

			QUIRKS:
			Returns [1] if not openSUSE, or if the check failed.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Dependencies

	setup-util-gsed --quiet

	# =====================================
	# Action

	if is-opensuse && test -f /etc/os-release; then
		config-helper /etc/os-release -- \
			--field=NAME --field=VERSION | gsed -e 's/"//g' -e 's/ /_/g' | echo-join '_' --stdin
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	get_opensuse_release "$@"
fi
