#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

flag="${1-}"
multi="${MULTI-}"
# shellcheck disable=2016
if test -z "$flag" -o "${2-}" != '--'; then
	stderr echo 'USAGE:'
	stderr echo 'get-flag-value <flag> -- <--flag=value> <--flag> <--no-flag> ...'
	stderr echo
	stderr echo '--flag becomes yes'
	stderr echo '--no-flag becomes no'
	stderr echo
	stderr echo 'by default only returns first instance, if wanting duplicates:'
	stderr echo 'mapfile -t a < <(env MULTI=yes get-flag-value a -- --a --a)'
	stderr echo
	stderr echo 'DOES NOT SUPPORT: --flag value'
	stderr echo 'IT ONLY SUPPORTS: --flag=value'
	stderr echo
	exit 1
fi

for arg in "${@:3}"; do
	result=''
	# check arg
	if test "${arg:0:(2 + ${#flag})}" = "--$flag"; then
		e="${arg:(2 + ${#flag}):1}"
		if test -z "$e"; then
			result='yes'
		elif test "$e" = '='; then
			result="${arg:(3 + ${#flag})}"
		fi
	elif test "${arg:0:(5 + ${#flag})}" = "--no-$flag"; then
		e="${arg:(5 + ${#flag}):1}"
		if test -z "$e"; then
			result='no'
		fi
	fi
	# have result?
	if test -n "$result"; then
		echo "$result"
		# if single, one result is all we want
		if test "$multi" != 'yes'; then
			break
		fi
	fi
done
