#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function get-python-version() (
	# python outputs the version to stderr, so we have to redirect stderr to stdout for it to be captured
	version="$("${1:-"python"}" --version 2>&1)"

	if test -n "${2-}"; then
		if [[ $version == "Python $2"* ]]; then
			return
		else
			return 1
		fi
	else
		echo "$version"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	get-python-version "$@"
fi
