#!/usr/bin/env bash

function get_volumes_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- get-volumes --help
)

function get_volumes() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Get the volumes attached to the current system.

			USAGE:
			\`get-volumes [...options]\`

			OPTIONS:
			--remote
			    Only output remote volumes, as a TSV of volume, server, directory.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_remote=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-remote'* | '--remote'*) __flag --source={item} --target={option_remote} --affirmative ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Action

	local mount volumes=()
	mount="$(mount)"
	__split --target={volumes} --no-zero-length --invoke=try -- \
		echo-regexp -ong --regexp='.+ on (.+) \(.+' --replace='$1' -- "$mount"
	if [[ ${#volumes[@]} -eq 0 ]]; then
		__print_style --stderr --error='No volumes found.'
		return 1
	fi

	local volume source server directory
	if [[ $option_remote == 'yes' ]]; then
		for volume in "${volumes[@]}"; do
			source="$(echo-regexp -o --regexp='//(.+) on '"$volume"' .+' --replace='$1' -- "$mount")"
			if [[ -n $source ]]; then
				server="$(echo-regexp -o --regexp='(.+)/.+' --replace='$1' -- "$source")"
				directory="$(echo-regexp -o --regexp='.+(/.+)' --replace='$1' -- "$source")"
				printf '%s\t%s\t%s\n' "$volume" "$server" "$directory"
			fi
		done
	else
		__print_lines "${volumes[@]}"
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		get_volumes_test
	else
		get_volumes "$@"
	fi
fi
