#!/usr/bin/env bash

function get_random_number() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Output a random number.

			USAGE:
			get-random-number
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Action

	# if our shell provides the RANDOM special variable use that, otherwise install fish and use its technique
	if [[ -n $RANDOM ]]; then
		__print_lines "$RANDOM"
	else
		__command_required -- 'fish' || return
		fish -c random
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	get_random_number "$@"
fi
