#!/usr/bin/env bash

function get_app_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- get-app --help
)

# @todo it's possible to add support for fetching version as well
# @todo merge into `setup-util`

function get_app() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Check, invoke, or query an <app>.

			USAGE:
			\`get-app [...options] [--] <app>\`
			\`get-app --open [..options] [-- ...<argument>]\`

			OPTIONS:
			<app> | --app=<app>
			    The application name or path to get the full path of.

			--invoke|open [-- ...<argument>]
			    Invoke the <app> if found, passing any provided <argument>s to it.
			    Not yet supported for WinGet and Scoop applications.

			--source=...<source:bins|apps|flatpak|scoop|winget> | ---sources=...<source>
			    Limit searching to the specified <source>s.
			    If not provided, all available sources will be searched.
			    If <source:bins> is enabled, searches for the application's binaries via \`PATH\`, which includes WSL paths.
			    If <source:apps> is enabled, searches for the application via usual paths and formats. Which on this system are:
			$(__join --source={app_search_paths} --left='        * ' --style=code --between=$'\n')
			    If <source:flatpak> is enabled, searches Flatpak applications. Only available on Linux.
			    If <source:scoop> is enabled, searches Scoop applications. Only available on Windows.
			    If <source:winget> is enabled, searches WinGet applications. Only available on Windows.

			--first | --first-success
			--each
			--every
			--which=<which:first|each|every>
			    If <first>, the default, stop after the first found <app> occurrence. Implies <any>.
			    If <each>, stop at the <first> found of each <app>. Requires <need> to be specified.
			    If <every>, find all occurrences of each <app>. Requires <need> to be specified.
			--optional
			--any
			--all | --first-failure
			--need=<need:optional|any|all>
			    If <optional>, do not require any <app>s to be found, but output their information if not <quiet>.
			    If <any>, the default if <first>, require at least one <app> to be found. Unless <first> is specified, continue to output details for all if not <quiet>.
			    If <all>, the default if not <first>, require all <app>s to be found.

			--details
			--input
			--name
			--id
			--path
			--output=<output:details|input|name|id|path>
			    If <output:details>, and if the <app> is found, output the all details of the <app>.
			    If <output:input>, and if the <app> is found, output the <app> value.
			    If <output:name>, and if the <app> is found, output the name of the <app>.
			    If <output:id>, and if the <app> is found, output the identifier of the <app>, if an identifier is not available, output the name.
			    If <output:path>, and if the <app> is found, output the location of the <app>. Not yet supported for WinGet and Scoop applications.
			--[no-]quiet | --[no-]verbose
			    If <quiet>, do not output any result.
			If neither <output> nor <quiet> are provided, then <output:details> will be set.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_apps=() option_sources=() option_args=() option_quiet='no' option_which='first' option_need='' option_invoke='no' option_output=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--app='* | '--name='* | '--id='*) option_apps+=("${item#*=}") ;;
		'--source='* | '--sources='*) __split --target={option_sources} --append --delimiters=$'\n\t ,|' --no-zero-length -- "${item#*=}" ;;
		'--no-verbose'* | '--verbose'*) __flag --source={item} --target={option_quiet} --non-affirmative --coerce ;;
		'--no-quiet'* | '--quiet'*) __flag --source={item} --target={option_quiet} --affirmative --coerce ;;
		'--no-invoke'* | '--invoke'* | '--no-open'* | '--open'*) __flag --source={item} --target={option_invoke} --affirmative --coerce ;;
		'--first' | '--which=first') option_which='first' ;;
		'--each' | '--which=each') option_which='each' ;;
		'--every' | '--which=every') option_which='every' ;;
		'--which=') : ;;
		'--optional' | '--need=optional') option_need='optional' ;;
		'--any' | '--need=any') option_need='any' ;;
		'--all' | '--need=all') option_need='all' ;;
		'--need=') : ;;
		'--details' | '--output=details') option_output='details' ;;
		'--input' | '--output=input') option_output='input' ;;
		'--name' | '--output=name') option_output='name' ;;
		'--id' | '--output=id') option_output='id' ;;
		'--path' | '--output=path' | '--location' | '--output=location') option_output='path' ;;
		'--')
			if [[ $option_invoke == 'yes' ]]; then
				option_args+=("$@")
			else
				option_apps+=("$@")
			fi
			shift $#
			break
			;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		'-'*) help 'An unrecognised argument was provided: ' --variable-value={item} ;; # capture typos like -source=<source>
		*) option_apps+=("$item") ;;
		esac
	done

	# check
	if [[ ${#option_apps[@]} -eq 0 ]]; then
		help --help='No <app>s provided.'
	fi
	if [[ $findable == 'no' ]]; then
		if [[ $option_quiet == 'no' ]]; then
			__print_error --help='`get-app`: Unable to detect applications on this platform. Send a PR to expand support.' || :
		fi
		return 19 # ENODEV 19 Operation not supported by device
	fi

	# if no sources, add them all
	local sources=''
	if [[ ${#option_sources[@]} -eq 0 ]]; then
		option_sources+=('bins' 'apps' 'flatpak' 'scoop' 'winget')
	fi
	__unique --source+target={option_sources}
	__join --source={option_sources} --target={sources} --left='[' --right=']'

	# imply
	# @todo should check and ensure this match's `bash.bash:__iterate`
	if [[ -z $option_which ]]; then
		option_which='first'
	fi
	if [[ -z $option_need ]]; then
		if [[ $option_which == 'first' ]]; then
			option_need='any'
		else
			option_need='all'
		fi
	fi

	# headless, no apps
	if is-system --headless; then
		if [[ $option_need == 'optional' ]]; then
			return 0
		fi
		return 19 # ENODEV 19 Operation not supported by device
	fi

	# details
	if [[ $option_quiet == 'no' && -z $option_output ]]; then
		option_output='details'
	fi

	# =====================================
	# Action

	# helpers
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		get_app_test
	else
		get_app "$@"
	fi
fi
