#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# @todo what is the different between this and command-exists ?

function get-command() (
	command -v "$*"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	get-command "$@"
fi
