#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function get-command() (
	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Output the path of the command.

			USAGE:
			get-command <command>
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item command=''
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if test -z "$command"; then
				command="$item"
			else
				help "An unrecognised argument was provided: $item"
			fi
			;;
		esac
	done

	# check
	if test -z "$command"; then
		help "<command> is required"
	fi

	# =====================================
	# Action

	# these two options seem equivalent
	command -v "$command"
	# type -P "$command"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	get-command "$@"
fi
