#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

remote="$(ask --question='What remote to configure?' --default="${1:-"origin"}" --required)"
url="$(ask --question='What is the URL to configure the remote to?' --default="${2-}" --required)"
ourl="$(git-remote-url "$remote")"

git remote remove "$remote"
git remote add "$remote" "$url"

nurl="$(git-remote-url "$remote")"
if test "$nurl" != "$url"; then
	stderr echo "Failed to change remote $remote"
	stderr echo "from  $ourl"
	stderr echo "to    $url"
	stderr echo "is    $nurl"

	glines="$(git config --global --list | grep '.insteadof=')"
	if test -n "$glines"; then
		stderr echo
		stderr echo 'you have replacement rules in your global git config, remove them if you want this to work:'
		stderr echo "$glines"
	fi

	llines="$(git config --list | grep '.insteadof=')"
	if test -n "$llines"; then
		stderr echo
		stderr echo 'you have replacement rules in your local git config, remove them if you want this to work:'
		stderr echo "$llines"
	fi

	if test -n "$glines" -o -n "$llines"; then
		stderr echo
		stderr echo 'try run the following and try again'
		echo "$glines" | sed -E 's#^#git config --global --unset #; s#=.+##'
		echo "$llines" | sed -E 's#^#git config --unset #; s#=.+##'
	fi

	exit 1
fi
