#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# options
remote="$(
	ask --required \
		--question='What remote to configure?' \
		--default="${1:-"origin"}"
)"
purl="$(
	ask --required \
		--question='What is the URL to configure the remote to?' \
		--default="${2-}"
)"
ourl="$(git-remote-url "$remote")"

# check if there is a difference
if test "$purl" = "$ourl"; then
	echo "Original URL: $ourl"
	echo "Proposed URL: $purl"
	echo "They are the same, skipping application, but will still test."
else
	# apply the change
	git remote remove "$remote"
	git remote add "$remote" "$purl"

	# check if it changed
	nurl="$(git-remote-url "$remote")"
	if test "$nurl" != "$purl"; then
		echo "Failed to change remote $remote"
		echo "from  $ourl"
		echo "to    $purl"
		echo "is    $nurl"

		glines="$(git config --global --list | grep '.insteadof=')"
		if test -n "$glines"; then
			echo
			echo 'you have replacement rules in your global git config, remove them if you want this to work:'
			echo "$glines"
		fi

		llines="$(git config --list | grep '.insteadof=')"
		if test -n "$llines"; then
			echo
			echo 'you have replacement rules in your local git config, remove them if you want this to work:'
			echo "$llines"
		fi

		if test -n "$glines" -o -n "$llines"; then
			echo
			echo 'try run the following and try again'
			echo "$glines" | sed -E 's#^#git config --global --unset #; s#=.+##'
			echo "$llines" | sed -E 's#^#git config --unset #; s#=.+##'
		fi

		exit 1
	fi
fi

# test the the change
if git-remote-ok "$remote"; then
	echo 'Test success.'
	exit 0
else
	echo 'Test failed.'
	exit 1
fi
