#!/usr/bin/env bash
source "$BDIR/sources/strict.bash"
source "$BDIR/sources/paths.sh"

if get-app "Gitfox.app"; then
	open-app "Gitfox.app" "$@"
elif get-app "Tower.app"; then
	open-app "Tower.app" "$@"
elif command-exists gf; then
	gf "$@"
elif command-exists tower; then
	tower "$@"
else
	fail "gf and tower are missing"
fi