#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

git shortlog --summary --email

oldemail="$(
	ask --required \
		--question="What is the old email?" \
		--default="${1-}"
)"
newemail="$(
	ask --required \
		--question="What is the new email?" \
		--default="${2-}"
)"
newname="$(
	ask --required \
		--question="What is the old name?" \
		--default="${3-}"
)"

rm -Rf .git/refs/original

git filter-branch --env-filter "
OLD_EMAIL=\"$oldemail\"
CORRECT_EMAIL=\"$newemail\"
CORRECT_NAME=\"$newname\"
if [ \"\$GIT_COMMITTER_EMAIL\" = \"\$OLD_EMAIL\" ]; then
	export GIT_COMMITTER_NAME=\"\$CORRECT_NAME\"
	export GIT_COMMITTER_EMAIL=\"\$CORRECT_EMAIL\"
fi
if [ \"\$GIT_AUTHOR_EMAIL\" = \"\$OLD_EMAIL\" ]; then
	export GIT_AUTHOR_NAME=\"\$CORRECT_NAME\"
	export GIT_AUTHOR_EMAIL=\"\$CORRECT_EMAIL\"
fi
" --tag-name-filter cat -- --branches --tags
