#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if test -z "${GIT_PROTOCOL-}"; then
	source "$DOROTHY/sources/user.sh"
fi

pref="${1:-"${GIT_PROTOCOL-}"}"
if test "$pref" = 'https'; then
	# skip checks if https
	echo 'https'
	exit 0
fi

choices=()
if ssh-ok; then
	choices+=('ssh')
fi
choices+=('https')

choose-option --question='Which git protocol do you wish to use?' --filter="$pref" -- "${choices[@]}"
