#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

remote="$("$DOROTHY/commands/ask-mandatory" 'What remote to configure?' "${1:-"origin"}")"
url="$("$DOROTHY/commands/ask-mandatory" 'What is the URL to configure the remote to?' "${2-}")"
ourl="$("$DOROTHY/commands/git-remote-url" "$remote")"

git remote remove "$remote"
git remote add "$remote" "$url"

nurl="$("$DOROTHY/commands/git-remote-url" "$remote")"
if test "$nurl" != "$url"; then
	stderr echo "Failed to change remote $remote"
	stderr echo "from  $ourl"
	stderr echo "to    $url"
	stderr echo "is    $nurl"

	glines="$(git config --global --list | grep '.insteadof=')"
	if test -n "$glines"; then
		stderr echo
		stderr echo 'you have replacement rules in your global git config, remove them if you want this to work:'
		stderr echo "$glines"
	fi

	llines="$(git config --list | grep '.insteadof=')"
	if test -n "$llines"; then
		stderr echo
		stderr echo 'you have replacement rules in your local git config, remove them if you want this to work:'
		stderr echo "$llines"
	fi

	if test -n "$glines" -o -n "$llines"; then
		stderr echo
		stderr echo 'try run the following and try again'
		echo "$glines" | sed 's#^#git config --global --unset #' | sed -E 's#=.+##'
		echo "$llines" | sed 's#^#git config --unset #' | sed -E 's#=.+##'
	fi

	exit 1
fi
