#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

remote="$(ask --question='What remote to configure?' --default="${1:-"origin"}" --required)"
protocol="$(git-protocol-ask "${2-}")"

ourl="$(git-remote-url "$remote")"
url="$(git-protocol-format "$ourl" "$protocol")"
git-remote-apply "$remote" "$url"

git remote -v
