#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=y setup-util-ripgrep

# act
url="$(github-release-file "$1" "$2")"
if test -z "$url"; then
	stderr echo "failed to determine the release file for [$1] [$2]"
	exit 1
fi

if echo "$url" | rg '.(tar|gz|zip)'; then
	# may include arguments for subfile and destination
	echo "extracting [$url] to [${*:3}]"
	down-zip-file "$url" "${@:3}"
else
	# may include argument for destination
	echo "downloading [$url] to [${3-}]"
	down "$url" "${3-}"
fi
