#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if test -z "${1-}"; then
	stderr echo 'USAGE: http-status <URL> [...flags]'
	exit 1
fi

#      --connect-timeout <seconds>   Maximum time allowed for connection
#  -I, --head                        Show document info only
#  -o, --output <file>               Write to file instead of stdout
#  -s, --silent                      Silent mode
#  -A, --user-agent <name>           Send User-Agent <name> to server
#  -w, --write-out <format>          Use output FORMAT after completion
curl \
	--connect-timeout 5 \
	--head \
	--output /dev/null \
	--silent \
	--write-out "%{http_code}" \
	"$@"
