#!/usr/bin/env bash

function is_accessible_test() (
	source "$DOROTHY/sources/is-fs-tests.bash"

	local root command='is-accessible'
	root="$(is_fs_tests__prep "$command")"

	eval-tester --name='no args' --status=22 --ignore-stderr -- \
		"$command" --

	# test no escalation
	local tuples=(
		22 ''

		0 "$root/missing-dir/missing-file"
		0 "$root/missing-file"

		0 "$root/targets/empty-dir"
		0 "$root/targets/empty-file"
		0 "$root/targets/filled-dir/empty-subfile"
		0 "$root/targets/filled-dir/filled-subdir"
		0 "$root/targets/filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/filled-dir/filled-subfile"
		0 "$root/targets/filled-file"
		0 "$root/targets/unaccessible-empty-dir"
		0 "$root/targets/unaccessible-empty-file"
		0 "$root/targets/unaccessible-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subfile"
		0 "$root/targets/unaccessible-filled-file"
		0 "$root/targets/unexecutable-empty-dir"
		0 "$root/targets/unexecutable-empty-file"
		0 "$root/targets/unexecutable-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subfile"
		0 "$root/targets/unexecutable-filled-file"
		0 "$root/targets/unreadable-empty-dir"
		0 "$root/targets/unreadable-empty-file"
		0 "$root/targets/unreadable-filled-dir"
		0 "$root/targets/unreadable-filled-dir/empty-subfile"
		0 "$root/targets/unreadable-filled-dir/filled-subdir"
		0 "$root/targets/unreadable-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unreadable-filled-dir/filled-subfile"
		0 "$root/targets/unreadable-filled-file"
		0 "$root/targets/unwritable-empty-dir"
		0 "$root/targets/unwritable-empty-file"
		0 "$root/targets/unwritable-filled-dir"
		0 "$root/targets/unwritable-filled-dir/empty-subfile"
		0 "$root/targets/unwritable-filled-dir/filled-subdir"
		0 "$root/targets/unwritable-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unwritable-filled-dir/filled-subfile"
		0 "$root/targets/unwritable-filled-file"

		0 "$root/symlinks/empty-dir"
		0 "$root/symlinks/empty-file"
		0 "$root/symlinks/filled-dir--empty-subfile"
		0 "$root/symlinks/filled-dir--filled-subdir"
		0 "$root/symlinks/filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/filled-dir--filled-subfile"
		0 "$root/symlinks/filled-file"
		0 "$root/symlinks/unaccessible-empty-dir"
		0 "$root/symlinks/unaccessible-empty-file"
		0 "$root/symlinks/unaccessible-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		0 "$root/symlinks/unaccessible-filled-file"
		0 "$root/symlinks/unexecutable-empty-dir"
		0 "$root/symlinks/unexecutable-empty-file"
		0 "$root/symlinks/unexecutable-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subfile"
		0 "$root/symlinks/unexecutable-filled-file"
		0 "$root/symlinks/unreadable-empty-dir"
		0 "$root/symlinks/unreadable-empty-file"
		0 "$root/symlinks/unreadable-filled-dir"
		0 "$root/symlinks/unreadable-filled-dir--empty-subfile"
		0 "$root/symlinks/unreadable-filled-dir--filled-subdir"
		0 "$root/symlinks/unreadable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unreadable-filled-dir--filled-subfile"
		0 "$root/symlinks/unreadable-filled-file"
		0 "$root/symlinks/unwritable-empty-dir"
		0 "$root/symlinks/unwritable-empty-file"
		0 "$root/symlinks/unwritable-filled-dir"
		0 "$root/symlinks/unwritable-filled-dir--empty-subfile"
		0 "$root/symlinks/unwritable-filled-dir--filled-subdir"
		0 "$root/symlinks/unwritable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unwritable-filled-dir--filled-subfile"
		0 "$root/symlinks/unwritable-filled-file"
	)
	is_fs_tests__tuples --group='test no escalation' "$command" --no-sudo -- "${tuples[@]}"

	# test default escalation
	tuples=(
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subfile"
	)
	is_fs_tests__tuples --group='test default escalation' "$command" -- "${tuples[@]}"

	# test with escalation
	tuples=(
		0 "$root/targets/unaccessible-filled-dir/empty-subfile"
		0 "$root/targets/unaccessible-filled-dir/filled-subdir"
		0 "$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unaccessible-filled-dir/filled-subfile"
		0 "$root/targets/unexecutable-filled-dir/empty-subfile"
		0 "$root/targets/unexecutable-filled-dir/filled-subdir"
		0 "$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unexecutable-filled-dir/filled-subfile"
		0 "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		0 "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subfile"
	)
	is_fs_tests__tuples --group='test with escalation' "$command" --elevate -- "${tuples[@]}"

	# break the symlinks
	eval-helper --elevate -- rm -rf -- "$root/targets"
	tuples=(
		0 "$root/symlinks/empty-dir"
		0 "$root/symlinks/empty-file"
		0 "$root/symlinks/filled-dir--empty-subfile"
		0 "$root/symlinks/filled-dir--filled-subdir"
		0 "$root/symlinks/filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/filled-dir--filled-subfile"
		0 "$root/symlinks/filled-file"
		0 "$root/symlinks/unaccessible-empty-dir"
		0 "$root/symlinks/unaccessible-empty-file"
		0 "$root/symlinks/unaccessible-filled-dir"
		0 "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		0 "$root/symlinks/unaccessible-filled-file"
		0 "$root/symlinks/unexecutable-empty-dir"
		0 "$root/symlinks/unexecutable-empty-file"
		0 "$root/symlinks/unexecutable-filled-dir"
		0 "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subfile"
		0 "$root/symlinks/unexecutable-filled-file"
		0 "$root/symlinks/unreadable-empty-dir"
		0 "$root/symlinks/unreadable-empty-file"
		0 "$root/symlinks/unreadable-filled-dir"
		0 "$root/symlinks/unreadable-filled-dir--empty-subfile"
		0 "$root/symlinks/unreadable-filled-dir--filled-subdir"
		0 "$root/symlinks/unreadable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unreadable-filled-dir--filled-subfile"
		0 "$root/symlinks/unreadable-filled-file"
		0 "$root/symlinks/unwritable-empty-dir"
		0 "$root/symlinks/unwritable-empty-file"
		0 "$root/symlinks/unwritable-filled-dir"
		0 "$root/symlinks/unwritable-filled-dir--empty-subfile"
		0 "$root/symlinks/unwritable-filled-dir--filled-subdir"
		0 "$root/symlinks/unwritable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unwritable-filled-dir--filled-subfile"
		0 "$root/symlinks/unwritable-filled-file"
	)
	is_fs_tests__tuples --group='test broken symlinks' "$command" -- "${tuples[@]}"

	return 0
)
function is_accessible() (
	source "$DOROTHY/sources/is-fs.bash"

	# help
	function __help {
		local fodder
		fodder="$(__is_fs__options '')" || return $?
		cat <<-EOF >&2 || return $?
			ABOUT:
			Check if all <path>s are accessible, regardless of whether they exist or not.

			USAGE:
			is-accessible [...options] [--] ...<path>

			OPTIONS:
			$fodder

			RETURNS:
			[0] if all <path>s were accessible
			[13] if a <path> was not accessible
			[22] if empty arguments were provided
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@" || return $?
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	__is_fs__args "$@" || return $?

	# invoke
	__is_fs__invoke 'is-accessible.bash' '' || return $?

	# if verbose and failure, output contextual failure
	if [[ $option_quiet == 'no' && $fs_status -ne 0 ]]; then
		__is_fs__error "$fs_status" || return $?
	fi

	# done
	return "$fs_status"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_accessible_test
	else
		is_accessible "$@"
	fi
fi
