#!/usr/bin/env bash

# `arch -x86_64 sh; is-apple-silicon; echo $?` should output 0 if on apple silicon, so it should be apple silicon regardless of emulation

function is_apple_silicon() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Checks if the system is Apple Silicon, regardless of emulation (e.g. \`arch -x86_64 ...\` trickery).

			USAGE:
			\`is-apple-silicon\`

			RETURNS:
			[0] if the system is Apple Silicon
			[1] if the system is not Apple Silicon
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Action

	if __is_macos; then
		local arch
		arch="$(__get_arch)" || return $?
		if [[ $arch == 'a64' ]]; then
			return 0
		else
			return 1
		fi
	else
		return 1
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_apple_silicon "$@"
fi
