#!/usr/bin/env bash

# is the array partially full?

# failure if all values are empty
# pass if any value is truthy

function is_array_full_or_partial() (
	source "$DOROTHY/sources/bash.bash"

	local arg

	for arg in "$@"; do
		if test -n "$arg"; then
			return 0
		fi
	done

	return 1
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_array_full_or_partial "$@"
fi
