#!/usr/bin/env bash

function is-apple-silicon() (
	source "$DOROTHY/sources/bash.bash"

	is-mac && test "$(uname -p)" = 'arm' -o "$(uname -m)" = 'arm64'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-apple-silicon "$@"
fi
