#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# is the array partially full?

# failure if all values are empty
# pass if any value is truthy

function is-array-full-or-partial() (
	local arg

	for arg in "$@"; do
		if test -n "$arg"; then
			return
		fi
	done

	return 1
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-array-full-or-partial "$@"
fi
