#!/usr/bin/env bash

# is the array absolutely empty?

# failure if any value is truthy
# pass if all values are empty

# if you are using this in conjuction with a is-array-partial,
# or your own test -n or test -z calls,
# then there is no need for this

function is-array-empty() (
	source "$DOROTHY/sources/strict.bash"

	local arg
	for arg in "$@"; do
		if test -n "$arg"; then
			return 1
		fi
	done
	return 0
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-array-empty "$@"
fi
