#!/usr/bin/env bash

# is-array-count 4 a b c d

function is_array_count() (
	source "$DOROTHY/sources/bash.bash"

	if test "$(get-array-count "${@:2}")" -eq "$1"; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_array_count "$@"
fi
