#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function is-alpine() (
	if test -f /etc/os-release; then
		grep -qi 'ID=alpine' /etc/os-release 2>/dev/null
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-alpine "$@"
fi
