#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

stance="${1-}"

if is-either "$stance" "Y" "y" "YES" "yes" "TRUE" "true"; then
	exit 0
elif is-either "$stance" "N" "n" "NO" "no" "FALSE" "false"; then
	exit 1
else
	exit 2
fi
