#!/usr/bin/env bash

function __is_affirmative() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function __help {
		cat <<-EOF >&2
			ABOUT:
			Check if <input> is an affirmative value.

			USAGE:
			is-affirmative [...options] [--] ...<input>

			OPTIONS:
			<input>
			    Input to check is an affirmative value.

			--ignore-empty:
			    Ignore/skip empty values.

			RETURNS:
			[0] if all <input>s are affirmative
			[1] if any <input>s are non-affirmative
			[91] if invalid values are provided, or no <input>s are provided
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@" || return
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_inputs=() option_ignore_empty='no'
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') __help ;;
		'--no-ignore-empty'* | '--ignore-empty'*) __flag {option_ignore_empty} --affirmative -- "$item" ;;
		'--')
			option_inputs+=("$@")
			shift "$#"
			break
			;;
		'--'*) __help "An unrecognised flag was provided: $item" ;;
		'') ;; # ignore empty values
		*) option_inputs+=("$item") ;;
		esac
	done

	# =====================================
	# Action

	local input had_affirmative='no'
	for input in "${option_inputs[@]}"; do
		case "$input" in
		'Y' | 'y' | 'YES' | 'yes' | 'TRUE' | 'true') had_affirmative='yes' ;;
		'N' | 'n' | 'NO' | 'no' | 'FALSE' | 'false') return 1 ;;
		'')
			if [[ $option_ignore_empty == 'yes' ]]; then
				continue
			else
				return 91 # ENOMSG 91 No message of desired type
			fi
			;;
		*)
			return 91 # ENOMSG 91 No message of desired type
			;;
		esac
	done

	if [[ $had_affirmative == 'no' ]]; then
		return 91 # ENOMSG 91 No message of desired type
	else
		return 0
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	__is_affirmative "$@"
fi
