#!/usr/bin/env bash

function is_btrfs() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Checks if a path is a btrfs filesystem.

			USAGE:
			is-btrfs [--] ...<path>

			RETURNS:
			[0] if all <path>s are btrfs filesystems.
			[1] if any <path>s are not btrfs filesystems.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_paths=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--')
			option_paths+=("$@")
			shift "$#"
			break
			;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) option_paths+=("$item") ;;
		esac
	done

	# check
	if [[ ${#option_paths[@]} -eq 0 ]]; then
		help 'No <path>s provided.'
	fi

	# =====================================
	# Action

	local path filesystem
	for path in "${option_paths[@]}"; do
		filesystem="$(get-filesystem "$path")"
		[[ $filesystem == 'btrfs' ]] || return $?
	done
	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_btrfs "$@"
fi
