#!/usr/bin/env bash

function is_ci() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Checks if the environment is a CI environment.

			USAGE:
			is-ci
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	is-affirmative --ignore-empty -- "${CI-}" "${CONTINUOUS_INTEGRATION-}" "${BUILD_NUMBER-}" "${RUN_ID-}" || return 1
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_ci "$@"
fi
