#!/usr/bin/env bash

function is_deb() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF
			ABOUT:
			Checks if the system can process \`.deb\` files, by checking if the system has \`apt-get\` (i.e. \`apt\`) or \`dpkg\` available.

			USAGE:
			is-deb

			RETURNS:
			[0] if the system can process \`.deb\` files
			[1] if the system cannot process \`.deb\` files
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Action

	# for some reason, `apt` exists on macos at /usr/bin/apt, so use `apt-get` instead
	if __command_exists -- apt-get || __command_exists -- dpkg; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_deb "$@"
fi
