#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# ubuntu desktop on raspi
# XDG_CURRENT_DESKTOP='ubuntu:GNOME'
# DESKTOP_SESSION='ubuntu'

# ubuntu server on raspi
# both empty

is-mac || test -n "${XDG_CURRENT_DESKTOP-}" -o -n "${DESKTOP_SESSION-}"
