#!/usr/bin/env bash

function is_digit() (
	source "$DOROTHY/sources/bash.bash"

	is-number "$1" && test "$1" -ge 0 -a "$1" -le 9
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_digit "$@"
fi
