#!/usr/bin/env bash

function is_empty_string_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-segment --h1="TEST: $0"

	eval-tester --name='zero-length is empty' \
		-- is-empty-string ''

	eval-tester --name='space is empty' \
		-- is-empty-string $' '

	eval-tester --name='newline is empty' \
		-- is-empty-string $'\n'

	eval-tester --name='tab is empty' \
		-- is-empty-string $'\n'

	eval-tester --name='whitespace combo is empty' \
		-- is-empty-string $'\n\t '

	eval-tester --name='letters not empty' --status=1 \
		-- is-empty-string 'a'

	echo-segment --g1="TEST: $0"
	return 0
)
function is_empty_string() (
	source "$DOROTHY/sources/bash.bash"

	# help
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Check if the input has non-whitespace characters.

			USAGE:
			is-empty-string <input>
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	if test "$#" -eq 0; then
		help 'No <input> provided.'
	elif test "$*" = '--help'; then
		help
	elif [[ $* =~ ^[[:space:]]*$ ]]; then
		# value is only whitespace characters
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	if test "$*" = '--test'; then
		is_empty_string_test
	else
		is_empty_string "$@"
	fi
fi
