#!/usr/bin/env bash

function is_executable_test() (
	source "$DOROTHY/sources/is-fs-tests.bash"
	eval-tester --ignore-stderr --status=22 -- is-executable --help

	local root command='is-executable'
	root="$(is_fs_tests__prep "$command")"

	eval-tester --name='no args' --status=22 --ignore-stderr -- \
		"$command" --

	# NOTE:
	# unaccessible paths aren't actually accessible to only root
	# it's more that root doesn't care, and bypasses the permissions anyway
	# so [chmod a-rwx] removes access to everything, but root doesn't care
	# however, unless [chown 0:0] is also done, then a standard user could undo the [chmod a-rwx]

	# NOTE:
	# chmod a-x -- <dir> <file>
	# sudo test -x <dir> # 0
	# sudo test -x <file> # 1
	# chown '0:0' -- <dir> <file>
	# sudo test -x <dir> # 0
	# sudo test -x <dir> # 1
	# the reason for this:
	# root disregards dir/file read/write/exec permissions, except file exec permissions
	# this is because everything, except bin execution, must be available to root
	# this means that encryption is the only protection against root
	# so make sure your volumes/secrets are encrypted to avoid a root user from accessing them
	# such as via attaching the volume to a new sudo machine

	# test no escalation
	local tuples=(
		22 ''

		2 "$root/missing-dir/missing-file"
		2 "$root/missing-file"

		0 "$root/targets/empty-dir"
		0 "$root/targets/empty-file"
		0 "$root/targets/filled-dir/empty-subfile"
		0 "$root/targets/filled-dir/filled-subdir"
		0 "$root/targets/filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/filled-dir/filled-subfile"
		0 "$root/targets/filled-file"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-empty-dir"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unaccessible-filled-dir/filled-subfile"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-filled-file"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unexecutable-empty-dir"
		93 "$root/targets/unexecutable-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unexecutable-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/targets/unexecutable-filled-dir/filled-subfile"
		93 "$root/targets/unexecutable-filled-file"
		0 "$root/targets/unreadable-empty-dir"
		0 "$root/targets/unreadable-empty-file"
		0 "$root/targets/unreadable-filled-dir"
		0 "$root/targets/unreadable-filled-dir/empty-subfile"
		0 "$root/targets/unreadable-filled-dir/filled-subdir"
		0 "$root/targets/unreadable-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unreadable-filled-dir/filled-subfile"
		0 "$root/targets/unreadable-filled-file"
		0 "$root/targets/unwritable-empty-dir"
		0 "$root/targets/unwritable-empty-file"
		0 "$root/targets/unwritable-filled-dir"
		0 "$root/targets/unwritable-filled-dir/empty-subfile"
		0 "$root/targets/unwritable-filled-dir/filled-subdir"
		0 "$root/targets/unwritable-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unwritable-filled-dir/filled-subfile"
		0 "$root/targets/unwritable-filled-file"

		0 "$root/symlinks/empty-dir"
		0 "$root/symlinks/empty-file"
		0 "$root/symlinks/filled-dir--empty-subfile"
		0 "$root/symlinks/filled-dir--filled-subdir"
		0 "$root/symlinks/filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/filled-dir--filled-subfile"
		0 "$root/symlinks/filled-file"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-empty-dir"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-filled-file"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unexecutable-empty-dir"
		93 "$root/symlinks/unexecutable-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unexecutable-filled-dir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		"$(__status__root_or_nonroot 0 13)" "$root/symlinks/unexecutable-filled-dir--filled-subfile"
		93 "$root/symlinks/unexecutable-filled-file"
		0 "$root/symlinks/unreadable-empty-dir"
		0 "$root/symlinks/unreadable-empty-file"
		0 "$root/symlinks/unreadable-filled-dir"
		0 "$root/symlinks/unreadable-filled-dir--empty-subfile"
		0 "$root/symlinks/unreadable-filled-dir--filled-subdir"
		0 "$root/symlinks/unreadable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unreadable-filled-dir--filled-subfile"
		0 "$root/symlinks/unreadable-filled-file"
		0 "$root/symlinks/unwritable-empty-dir"
		0 "$root/symlinks/unwritable-empty-file"
		0 "$root/symlinks/unwritable-filled-dir"
		0 "$root/symlinks/unwritable-filled-dir--empty-subfile"
		0 "$root/symlinks/unwritable-filled-dir--filled-subdir"
		0 "$root/symlinks/unwritable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unwritable-filled-dir--filled-subfile"
		0 "$root/symlinks/unwritable-filled-file"
	)
	is_fs_tests__tuples --group='test no escalation' "$command" --no-sudo -- "${tuples[@]}"

	# test with escalation
	tuples=(
		0 "$root/targets/unaccessible-empty-dir"
		0 "$root/targets/unaccessible-empty-file"
		0 "$root/targets/unaccessible-filled-dir"
		0 "$root/targets/unaccessible-filled-dir/empty-subfile"
		0 "$root/targets/unaccessible-filled-dir/filled-subdir"
		0 "$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unaccessible-filled-dir/filled-subfile"
		0 "$root/targets/unaccessible-filled-file"
		0 "$root/targets/unexecutable-empty-dir"
		93 "$root/targets/unexecutable-empty-file"
		0 "$root/targets/unexecutable-filled-dir"
		0 "$root/targets/unexecutable-filled-dir/empty-subfile"
		0 "$root/targets/unexecutable-filled-dir/filled-subdir"
		0 "$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unexecutable-filled-dir/filled-subfile"
		93 "$root/targets/unexecutable-filled-file"

		0 "$root/symlinks/unaccessible-empty-dir"
		0 "$root/symlinks/unaccessible-empty-file"
		0 "$root/symlinks/unaccessible-filled-dir"
		0 "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		0 "$root/symlinks/unaccessible-filled-file"
		0 "$root/symlinks/unexecutable-empty-dir"
		93 "$root/symlinks/unexecutable-empty-file"
		0 "$root/symlinks/unexecutable-filled-dir"
		0 "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subfile"
		93 "$root/symlinks/unexecutable-filled-file"
	)
	is_fs_tests__tuples --group='test with escalation' "$command" --elevate -- "${tuples[@]}"

	# test default escalation
	tuples=(
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-empty-dir"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-filled-dir"
		0 "$root/targets/unaccessible-filled-dir/empty-subfile"
		0 "$root/targets/unaccessible-filled-dir/filled-subdir"
		0 "$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unaccessible-filled-dir/filled-subfile"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unaccessible-filled-file"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unexecutable-empty-dir"
		93 "$root/targets/unexecutable-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/targets/unexecutable-filled-dir"
		0 "$root/targets/unexecutable-filled-dir/empty-subfile"
		0 "$root/targets/unexecutable-filled-dir/filled-subdir"
		0 "$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir"
		0 "$root/targets/unexecutable-filled-dir/filled-subfile"
		93 "$root/targets/unexecutable-filled-file"

		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-empty-dir"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-filled-dir"
		0 "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unaccessible-filled-file"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unexecutable-empty-dir"
		93 "$root/symlinks/unexecutable-empty-file"
		"$(__status__root_or_nonroot 0 93)" "$root/symlinks/unexecutable-filled-dir"
		0 "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		0 "$root/symlinks/unexecutable-filled-dir--filled-subfile"
		93 "$root/symlinks/unexecutable-filled-file"
	)
	is_fs_tests__tuples --group='test default escalation' "$command" -- "${tuples[@]}"

	# break the symlinks
	eval-helper --elevate -- rm -rf -- "$root/targets"
	tuples=(
		9 "$root/symlinks/empty-dir"
		9 "$root/symlinks/empty-file"
		9 "$root/symlinks/filled-dir--empty-subfile"
		9 "$root/symlinks/filled-dir--filled-subdir"
		9 "$root/symlinks/filled-dir--filled-subdir--empty-subdir"
		9 "$root/symlinks/filled-dir--filled-subfile"
		9 "$root/symlinks/filled-file"
		9 "$root/symlinks/unaccessible-empty-dir"
		9 "$root/symlinks/unaccessible-empty-file"
		9 "$root/symlinks/unaccessible-filled-dir"
		9 "$root/symlinks/unaccessible-filled-dir--empty-subfile"
		9 "$root/symlinks/unaccessible-filled-dir--filled-subdir"
		9 "$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir"
		9 "$root/symlinks/unaccessible-filled-dir--filled-subfile"
		9 "$root/symlinks/unaccessible-filled-file"
		9 "$root/symlinks/unexecutable-empty-dir"
		9 "$root/symlinks/unexecutable-empty-file"
		9 "$root/symlinks/unexecutable-filled-dir"
		9 "$root/symlinks/unexecutable-filled-dir--empty-subfile"
		9 "$root/symlinks/unexecutable-filled-dir--filled-subdir"
		9 "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
		9 "$root/symlinks/unexecutable-filled-dir--filled-subfile"
		9 "$root/symlinks/unexecutable-filled-file"
		9 "$root/symlinks/unreadable-empty-dir"
		9 "$root/symlinks/unreadable-empty-file"
		9 "$root/symlinks/unreadable-filled-dir"
		9 "$root/symlinks/unreadable-filled-dir--empty-subfile"
		9 "$root/symlinks/unreadable-filled-dir--filled-subdir"
		9 "$root/symlinks/unreadable-filled-dir--filled-subdir--empty-subdir"
		9 "$root/symlinks/unreadable-filled-dir--filled-subfile"
		9 "$root/symlinks/unreadable-filled-file"
		9 "$root/symlinks/unwritable-empty-dir"
		9 "$root/symlinks/unwritable-empty-file"
		9 "$root/symlinks/unwritable-filled-dir"
		9 "$root/symlinks/unwritable-filled-dir--empty-subfile"
		9 "$root/symlinks/unwritable-filled-dir--filled-subdir"
		9 "$root/symlinks/unwritable-filled-dir--filled-subdir--empty-subdir"
		9 "$root/symlinks/unwritable-filled-dir--filled-subfile"
		9 "$root/symlinks/unwritable-filled-file"
	)
	is_fs_tests__tuples --group='test broken symlinks' "$command" -- "${tuples[@]}"

	return 0
)
function is_executable() (
	source "$DOROTHY/sources/is-fs.bash"

	# =====================================
	# Arguments

	function __help {
		local fodder
		fodder="$(__is_fs__options '13')" || return $?
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Check if all <path>s are executable.
			Companion to: $(__join --style=code --between=', ' -- 'echo-if-executable').

			USAGE:
			\`is-executable [...options] [--] ...<path>\`

			OPTIONS:
			$fodder

			RETURNS:
			[0] if all <path>s were executable
			[2] if a <path> was missing
			[9] if a <path> was a broken symlink
			[13] if a <path> was not accessible
			[22] if empty arguments were provided
			[93] if a <path> was present, but was not executable
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	__is_fs__args "$@" || return $?

	# invoke
	__is_fs__invoke 'is-executable.bash' '13' || return $?

	# errors
	case "$fs_status" in
	93) __is_fs__error 'The <path> was present, but was not executable:' || return $? ;;
	*) __is_fs__error || return $? ;;
	esac

	# done
	return "$fs_status"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_executable_test
	else
		is_executable "$@"
	fi
fi
