#!/usr/bin/env bash

# prepare
v="${1-}"

# check for an empty string
# otherwise check for empty values
is-empty-string "$v" || test \
	"$v" = "null" -o "$v" = "NULL" -o \
	"$v" = "void" -o "$v" = "VOID" -o \
	"$v" = 'undefined' -o "$v" = 'UNDEFINED'

# don't consider 0 empty as version-compare believes 0 is a valid value
