#!/usr/bin/env bash

function is_empty_file_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-style --h1="TEST: $0"

	# prep
	local root dir file dir_target dir_symlink file_target file_symlink
	root="$(fs-temp --directory='is-empty-file-test')"
	fs-rm --quiet --no-confirm -- "$root"
	dir="$(fs-temp --root="$root" --directory --touch)"
	file="$(fs-temp --root="$root" --file --touch)"
	dir_target="$(fs-temp --root="$root" --directory='dir_target' --touch)"
	file_target="$(fs-temp --root="$root" --file='file_target' --touch)"
	dir_symlink="$(fs-temp --root="$root" --directory='dir_symlink' --no-touch)"
	file_symlink="$(fs-temp --root="$root" --file='file_symlink' --no-touch)"
	symlink-helper --existing="$dir_target" --symlink="$dir_symlink" --quiet
	symlink-helper --existing="$file_target" --symlink="$file_symlink" --quiet

	# test standard paths
	eval-tester --name='no args' --status=22 --ignore-stderr \
		-- is-empty-file --

	eval-tester --name='empty args' --status=22 \
		-- is-empty-file -- '' ''

	eval-tester --name='missing' --status=2 \
		-- is-empty-file -- "$DOROTHY/this-does-not-exist"

	eval-tester --name='empty dirs' --status=79 \
		-- is-empty-file -- "$dir" "$dir"

	eval-tester --name='empty files' \
		-- is-empty-file -- "$file" "$file"

	eval-tester --name='non-empty dir' --status=79 \
		-- is-empty-file -- "$DOROTHY"

	eval-tester --name='non-empty file' --status=27 \
		-- is-empty-file -- "$DOROTHY/README.md"

	# test working symlinks
	eval-tester --name='symlink empty dir' --status=79 \
		-- is-empty-file -- "$dir_symlink"

	eval-tester --name='symlink empty file' \
		-- is-empty-file -- "$file_symlink"

	eval-tester --name='symlink empty file then non-empty dir' --status=79 \
		-- is-empty-file -- "$file_symlink" "$DOROTHY"

	eval-tester --name='symlink empty file then non-empty file' --status=27 \
		-- is-empty-file -- "$file_symlink" "$DOROTHY/README.md"

	eval-tester --name='symlink empty file then missing' --status=2 \
		-- is-empty-file -- "$file_symlink" "$DOROTHY/this-does-not-exist"

	# test non-empty symlinks
	__print_line >"$file_target"

	eval-tester --name='symlink non-empty file' --status=27 \
		-- is-empty-file -- "$file_symlink"

	eval-tester --name='empty file then symlink non-empty file' --status=27 \
		-- is-empty-file -- "$file" "$file_symlink"

	# test broken symlinks
	fs-rm --quiet --no-confirm -- "$dir_target" "$file_target"

	eval-tester --name='broken symlink dir' --status=9 \
		-- is-empty-file -- "$dir_symlink"

	eval-tester --name='broken symlink file' --status=9 \
		-- is-empty-file -- "$file_symlink"

	eval-tester --name='broken symlink file then non-empty dir' --status=9 \
		-- is-empty-file -- "$file_symlink" "$DOROTHY"

	eval-tester --name='broken symlink file then file' --status=9 \
		-- is-empty-file -- "$file_symlink" "$DOROTHY/README.md"

	eval-tester --name='broken symlink file then missing' --status=9 \
		-- is-empty-file -- "$file_symlink" "$DOROTHY/this-does-not-exist"

	echo-style --g1="TEST: $0"
	return 0
)
function is_empty_file() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Checks if a <path> is an empty file, aka a file without content, aka a file with zero-length content.
			Companion to [is-nonempty-file].

			USAGE:
			is-empty-file [...options] [--] ...<path>

			OPTIONS:
			--sudo=<sudo>
			    Defaults to [13], escalating to root if permission would otherwise be denied.
			--user=<user>
			--group=<group>
			    Forwarded to [sudo-helper].

			RETURNS:
			[0] if all <path>s were a readable zero-length file
			[2] if a <path> was not found
			[9] if a <path> was a broken symlink
			[13] if a <path> was a non-readable file, as such the length could not be determined, or if a <path> was not accessible: unless [--no-sudo] was provided a sudo request will be made to prevent this failure.
			[22] if empty arguments are provided
			[27] if a <path> was a file, or an unbroken symlink to a file, but was not empty
			[79] if a <path> was found, but was not a file nor an unbroken symlink to a file
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_inputs=() option_sudo='13' option_user='' option_group=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-sudo'* | '--sudo'*)
			option_sudo="$(get-flag-value --affirmative --fallback-on-empty --fallback="$option_sudo" -- "$item")"
			;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--')
			option_inputs+=("$@")
			shift "$#"
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) option_inputs+=("$item") ;;
		esac
	done

	# check
	if [[ ${#option_inputs[@]} -eq 0 ]]; then
		help "No <path>s provided."
	fi

	# =====================================
	# Action

	sudo-helper --inherit --sudo="$option_sudo" --user="$option_user" --group="$option_group" -- is-empty-file.bash -- "${option_inputs[@]}"
	return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_empty_file_test
	else
		is_empty_file "$@"
	fi
fi
