#!/usr/bin/env bash

function is_empty_ls() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Checks if <path> has no contents.

			USAGE:
			is-empty-ls [--] ...<path>

			RETURNS:
			[0] if all <path>s were empty.
			[1] if any <path>s were not empty.
			[2] if any <path> were not a directory.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_paths=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--')
			option_paths+=("$@")
			shift "$#"
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) option_paths+=("$item") ;;
		esac
	done

	# check
	if test "${#option_paths[@]}" -eq 0; then
		help "No <path>s provided."
	fi

	# =====================================
	# Action

	local path
	for path in "${option_paths[@]}"; do
		if test ! -d "$path"; then
			echo-error 'A path was was not a directory: ' --code="$path"
			return 2
		fi
		test -z "$(ls -A "$path")"
	done
	return 0
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_empty_ls "$@"
fi
