#!/usr/bin/env bash

function is_empty_directory() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Checks if the path is an empty directory.

			USAGE:
			is-empty-directory [--] ...<path>
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item paths=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--')
			paths+=("$@")
			shift "$#"
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) paths+=("$item") ;;
		esac
	done

	# check
	if test "${#paths[@]}" -eq 0; then
		help "No <path>s were provided."
	fi

	# =====================================
	# Action

	# action
	local path result
	for path in "${paths[@]}"; do
		if test ! -d "$path"; then
			return 1
		fi
		result="$(ls -A "$path")"
		if test -z "$result"; then
			continue
		else
			return 1
		fi
	done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_empty_directory "$@"
fi
