#!/usr/bin/env bash

# unfortunately, empty directories may still be 4096 bytes long
# which can be filtered by doing `du -t 4097` however `du -c` still reports such in total
# --apparent-size has no affect

function is_empty_size() (
	source "$DOROTHY/sources/bash.bash"

	if test "$(du -s "$1")" = $'0\t'"$1"; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_empty_size "$@"
fi
