#!/usr/bin/env bash

function is_either() (
	source "$DOROTHY/sources/bash.bash"

	local arg
	for arg in "${@:2}"; do
		if test "$1" = "$arg"; then
			return 0
		fi
	done
	return 1
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_either "$@"
fi
