#!/usr/bin/env bash

function is_globstar_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-segment --h1="TEST: $0"

	eval-tester --name='empty' --status=1 \
		-- is-globstar

	eval-tester --name='empty string' --status=1 \
		-- is-globstar ''

	eval-tester --name='non-globstar string' --status=1 \
		-- is-globstar ' /Users/runner/.cache/dorothy/unziptar/5241/rg'

	eval-tester --name='star string' --status=1 \
		-- is-globstar ' /Users/runner/.cache/dorothy/*/unziptar/5241/rg'

	eval-tester --name='globstar string' --status=0 \
		-- is-globstar ' /Users/runner/.cache/dorothy/**/unziptar/5241/rg'

	echo-segment --g1="TEST: $0"
	return 0
)
function is_globstar() (
	source "$DOROTHY/sources/bash.bash"

	[[ $* == *'**'* ]]
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	if test "$*" = '--test'; then
		is_globstar_test
	else
		is_globstar "$@"
	fi
fi
