#!/usr/bin/env bash

function is-globstar() (
	source "$DOROTHY/sources/strict.bash"

	# https://stackoverflow.com/a/240181
	grep --quiet --fixed-strings --regexp='**' <<<"$*"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-globstar "$@"
fi
