#!/usr/bin/env bash

function is_globstar() (
	source "$DOROTHY/sources/bash.bash"

	# https://stackoverflow.com/a/240181
	grep --quiet --fixed-strings --regexp='**' <<<"$*"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_globstar "$@"
fi
