#!/usr/bin/env bash

function is_gnome() (
	source "$DOROTHY/sources/bash.bash"

	if test "${DESKTOP_SESSION-}" = 'gnome'; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_gnome "$@"
fi
