#!/usr/bin/env bash

# ubuntu desktop on raspi
# XDG_CURRENT_DESKTOP='ubuntu:GNOME'
# DESKTOP_SESSION='ubuntu'

# ubuntu server on raspi
# both empty

function is_headful() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Checks if there is Desktop/GUI available to our current session.
			macOS and WSL will always return [0] success.
			This is usually used in conjuction with [is-ssh].

			USAGE:
			is-headful

			RETURNS:
			[0] if the session exposes a Desktop/GUI.
			[1] if the session does not expose a Desktop/GUI.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	if is-mac || is-wsl || test -n "${XDG_CURRENT_DESKTOP-}" -o -n "${DESKTOP_SESSION-}"; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_headful "$@"
fi
