#!/usr/bin/env bash

function is_interactive() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Checks if the environment is actually interactive.

			USAGE:
			is-interactive [...options]

			OPTIONS:
			--verbose
			    If provided, output more information.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_quiet=''
	option_quiet="$(echo-quiet --no-env "$option_quiet" -- "$@")"
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	is-tty --quiet="$option_quiet"
	! is-ci --quiet="$option_quiet"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_interactive "$@"
fi
