#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

url="${1:-"cloudflare.com"}"

if command-exists ping; then  # fresh macos without brew has no ping
	if silent ping -c 1 "$url"; then
		echo 'yes'
		exit
	fi
elif command-exists whois; then
	if silent whois "$url"; then
		echo 'yes'
		exit
	fi
fi

echo 'no'
exit 1
