#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://stackoverflow.com/a/29234612/130638

# trunk-ignore(shellcheck/SC2235)
function is-integer() (
	[[ $1 == ?(-)+([0-9]) ]]
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-integer "$@"
fi
