#!/usr/bin/env bash

function is_linux_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-segment --h1="TEST: $0"

	local os
	os="$(uname -s)"
	if test "$os" = 'Linux'; then
		eval-tester --name='is linux' --status='0' \
			-- is-linux --question='is linux'
	else
		eval-tester --name='is not linux' --status='1' \
			-- is-linux --question='is not linux'
	fi

	echo-segment --g1="TEST: $0"
	return 0
)
function is_linux() (
	source "$DOROTHY/sources/bash.bash"

	# this will/should pass on WSL on Windows
	if test "$(uname -s)" = 'Linux'; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	if test "$*" = '--test'; then
		is_linux_test
	else
		is_linux "$@"
	fi
fi
