#!/usr/bin/env bash

function is_missing_test() (
	source "$DOROTHY/sources/is-fs-tests.bash"
	local root command='is-missing' tuples=()
	root="$(is_fs_tests__prep "$command")"

	eval-tester --ignore-stderr --status=22 -- "$command" --help
	eval-tester --name='no args' --status=22 --ignore-stderr -- "$command" --

	# test no privilege elevation
	tuples=(
		--path='' --status=22

		--path="$root/missing-dir/missing-file"
		--path="$root/missing-file"

		--path="$root/targets/empty-dir" --status=17
		--path="$root/targets/empty-file" --status=17
		--path="$root/targets/filled-dir/empty-subfile" --status=17
		--path="$root/targets/filled-dir/filled-subdir" --status=17
		--path="$root/targets/filled-dir/filled-subdir/empty-subdir" --status=17
		--path="$root/targets/filled-dir/filled-subfile" --status=17
		--path="$root/targets/filled-file" --status=17
		--path="$root/targets/unaccessible-empty-dir" --status=17
		--path="$root/targets/unaccessible-empty-file" --status=17
		--path="$root/targets/unaccessible-filled-dir" --status=17
		--path="$root/targets/unaccessible-filled-dir/empty-subfile" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unaccessible-filled-dir/filled-subdir" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unaccessible-filled-dir/filled-subfile" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unaccessible-filled-file" --status=17
		--path="$root/targets/unexecutable-empty-dir" --status=17
		--path="$root/targets/unexecutable-empty-file" --status=17
		--path="$root/targets/unexecutable-filled-dir" --status=17
		--path="$root/targets/unexecutable-filled-dir/empty-subfile" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unexecutable-filled-dir/filled-subdir" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unexecutable-filled-dir/filled-subfile" --status="$(__is_fs_tests__print_root_or_nonroot 17 13)"
		--path="$root/targets/unexecutable-filled-file" --status=17
		--path="$root/targets/unreadable-empty-dir" --status=17
		--path="$root/targets/unreadable-empty-file" --status=17
		--path="$root/targets/unreadable-filled-dir" --status=17
		--path="$root/targets/unreadable-filled-dir/empty-subfile" --status=17
		--path="$root/targets/unreadable-filled-dir/filled-subdir" --status=17
		--path="$root/targets/unreadable-filled-dir/filled-subdir/empty-subdir" --status=17
		--path="$root/targets/unreadable-filled-dir/filled-subfile" --status=17
		--path="$root/targets/unreadable-filled-file" --status=17
		--path="$root/targets/unwritable-empty-dir" --status=17
		--path="$root/targets/unwritable-empty-file" --status=17
		--path="$root/targets/unwritable-filled-dir" --status=17
		--path="$root/targets/unwritable-filled-dir/empty-subfile" --status=17
		--path="$root/targets/unwritable-filled-dir/filled-subdir" --status=17
		--path="$root/targets/unwritable-filled-dir/filled-subdir/empty-subdir" --status=17
		--path="$root/targets/unwritable-filled-dir/filled-subfile" --status=17
		--path="$root/targets/unwritable-filled-file" --status=17

		--path="$root/symlinks/empty-dir" --status=17
		--path="$root/symlinks/empty-file" --status=17
		--path="$root/symlinks/filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/filled-file" --status=17
		--path="$root/symlinks/unaccessible-empty-dir" --status=17
		--path="$root/symlinks/unaccessible-empty-file" --status=17
		--path="$root/symlinks/unaccessible-filled-dir" --status=17
		# these pass as the symlink itself as a file accessible even if the target's parent is unaccessible
		--path="$root/symlinks/unaccessible-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-file" --status=17
		--path="$root/symlinks/unexecutable-empty-dir" --status=17
		--path="$root/symlinks/unexecutable-empty-file" --status=17
		--path="$root/symlinks/unexecutable-filled-dir" --status=17
		# these pass as the symlink itself as a file accessible even if the target's parent is unexecutable
		--path="$root/symlinks/unexecutable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-file" --status=17
		--path="$root/symlinks/unreadable-empty-dir" --status=17
		--path="$root/symlinks/unreadable-empty-file" --status=17
		--path="$root/symlinks/unreadable-filled-dir" --status=17
		--path="$root/symlinks/unreadable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unreadable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unreadable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unreadable-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unreadable-filled-file" --status=17
		--path="$root/symlinks/unwritable-empty-dir" --status=17
		--path="$root/symlinks/unwritable-empty-file" --status=17
		--path="$root/symlinks/unwritable-filled-dir" --status=17
		--path="$root/symlinks/unwritable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unwritable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unwritable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unwritable-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unwritable-filled-file" --status=17
	)
	is_fs_tests__tuples --group='test no privilege elevation' "$command" --no-elevate -- "${tuples[@]}"

	# test default privilege elevation
	tuples=(
		--path="$root/targets/unaccessible-filled-dir/empty-subfile" --status=17
		--path="$root/targets/unaccessible-filled-dir/filled-subdir" --status=17
		--path="$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir" --status=17
		--path="$root/targets/unaccessible-filled-dir/filled-subfile" --status=17
		--path="$root/targets/unexecutable-filled-dir/empty-subfile" --status=17
		--path="$root/targets/unexecutable-filled-dir/filled-subdir" --status=17
		--path="$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir" --status=17
		--path="$root/targets/unexecutable-filled-dir/filled-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subfile" --status=17
	)
	is_fs_tests__tuples --group='test default privilege elevation' "$command" -- "${tuples[@]}"

	# test with privilege elevation
	tuples=(
		--path="$root/targets/unaccessible-filled-dir/empty-subfile" --status=17
		--path="$root/targets/unaccessible-filled-dir/filled-subdir" --status=17
		--path="$root/targets/unaccessible-filled-dir/filled-subdir/empty-subdir" --status=17
		--path="$root/targets/unaccessible-filled-dir/filled-subfile" --status=17
		--path="$root/targets/unexecutable-filled-dir/empty-subfile" --status=17
		--path="$root/targets/unexecutable-filled-dir/filled-subdir" --status=17
		--path="$root/targets/unexecutable-filled-dir/filled-subdir/empty-subdir" --status=17
		--path="$root/targets/unexecutable-filled-dir/filled-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subfile" --status=17
	)
	is_fs_tests__tuples --group='test with privilege elevation' "$command" --elevate -- "${tuples[@]}"

	# break the symlinks
	is_fs_tests__break_symlinks
	tuples=(
		--path="$root/symlinks/empty-dir" --status=17
		--path="$root/symlinks/empty-file" --status=17
		--path="$root/symlinks/filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/filled-file" --status=17
		--path="$root/symlinks/unaccessible-empty-dir" --status=17
		--path="$root/symlinks/unaccessible-empty-file" --status=17
		--path="$root/symlinks/unaccessible-filled-dir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unaccessible-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unaccessible-filled-file" --status=17
		--path="$root/symlinks/unexecutable-empty-dir" --status=17
		--path="$root/symlinks/unexecutable-empty-file" --status=17
		--path="$root/symlinks/unexecutable-filled-dir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unexecutable-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unexecutable-filled-file" --status=17
		--path="$root/symlinks/unreadable-empty-dir" --status=17
		--path="$root/symlinks/unreadable-empty-file" --status=17
		--path="$root/symlinks/unreadable-filled-dir" --status=17
		--path="$root/symlinks/unreadable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unreadable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unreadable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unreadable-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unreadable-filled-file" --status=17
		--path="$root/symlinks/unwritable-empty-dir" --status=17
		--path="$root/symlinks/unwritable-empty-file" --status=17
		--path="$root/symlinks/unwritable-filled-dir" --status=17
		--path="$root/symlinks/unwritable-filled-dir--empty-subfile" --status=17
		--path="$root/symlinks/unwritable-filled-dir--filled-subdir" --status=17
		--path="$root/symlinks/unwritable-filled-dir--filled-subdir--empty-subdir" --status=17
		--path="$root/symlinks/unwritable-filled-dir--filled-subfile" --status=17
		--path="$root/symlinks/unwritable-filled-file" --status=17
	)
	is_fs_tests__tuples --group='test broken symlinks' "$command" -- "${tuples[@]}"

	return 0
)
function is_missing() (
	source "$DOROTHY/sources/is-fs.bash"

	# =====================================
	# Arguments

	function __help {
		local fodder
		fodder="$(__is_fs__options '13')" || return $?
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Check if all <path>s are missing (not a file/directory/symlink/broken-symlink).
			Companion to: $(__join --style=code --between=', ' -- 'is-present' 'is-exist').
			Equivalent to: $(__join --style=code --between=', ' -- 'is-missing-path' 'is-path-missing').

			USAGE:
			\`is-missing [...options] [--] ...<path>\`

			OPTIONS:
			$fodder

			RETURNS:
			[0] if all <path>s were missing (not even a broken symlink).
			[13] if a <path> was not accessible
			[17] if a <path> was present
			[22] if empty arguments were provided
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	__is_fs__args "$@" || return $?

	# invoke
	__is_fs__invoke 'is-missing.bash' '13' || return $?

	# errors
	case "$fs_status" in
	17) __is_fs__error 'The <path> was present:' || return $? ;;
	*) __is_fs__error || return $? ;;
	esac

	# done
	return "$fs_status"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_missing_test
	else
		is_missing "$@"
	fi
fi
