#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# trunk-ignore(shellcheck/SC2235)
function is-missing() (
	test ! -e "$1"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-missing "$@"
fi
