#!/usr/bin/env bash

function is-mac() (
	source "$DOROTHY/sources/strict.bash"

	test "$(uname -s)" = "Darwin"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-mac "$@"
fi
