#!/usr/bin/env bash

function is_not_symlink_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-style --h1="TEST: $0"

	# test standard paths
	eval-tester --name='no args' --status=22 --ignore-stderr \
		-- is-not-symlink --

	eval-tester --name='empty args' --status=22 \
		-- is-not-symlink -- '' ''

	eval-tester --name='missing' --status=2 \
		-- is-not-symlink -- "$DOROTHY/this-does-not-exist"

	eval-tester --name='directory' \
		-- is-not-symlink -- "$DOROTHY"

	eval-tester --name='file' \
		-- is-not-symlink -- "$DOROTHY/README.md"

	# prep
	local root dir_target dir_symlink file_target file_symlink
	root="$(fs-temp --directory='is-not-symlink-test')"
	fs-rm --quiet --no-confirm -- "$root"
	dir_target="$(fs-temp --root="$root" --directory='dir_target' --touch)"
	file_target="$(fs-temp --root="$root" --file='file_target' --touch)"
	dir_symlink="$(fs-temp --root="$root" --directory='dir_symlink' --no-touch)"
	file_symlink="$(fs-temp --root="$root" --file='file_symlink' --no-touch)"
	symlink-helper --existing="$dir_target" --symlink="$dir_symlink" --quiet
	symlink-helper --existing="$file_target" --symlink="$file_symlink" --quiet

	# test working symlinks
	eval-tester --name='symlink dir' --status=79 \
		-- is-not-symlink -- "$dir_symlink"

	eval-tester --name='symlink file' --status=79 \
		-- is-not-symlink -- "$file_symlink"

	eval-tester --name='symlink dir then dir' --status=79 \
		-- is-not-symlink -- "$dir_symlink" "$DOROTHY"

	eval-tester --name='symlink file then file' --status=79 \
		-- is-not-symlink -- "$file_symlink" "$DOROTHY/README.md"

	eval-tester --name='symlink file then missing' --status=79 \
		-- is-not-symlink -- "$file_symlink" "$DOROTHY/this-does-not-exist"

	# test broken symlinks
	fs-rm --quiet --no-confirm -- "$dir_target" "$file_target"

	eval-tester --name='broken symlink dir' --status=79 \
		-- is-not-symlink -- "$dir_symlink"

	eval-tester --name='broken symlink file' --status=79 \
		-- is-not-symlink -- "$file_symlink"

	eval-tester --name='broken symlink dir then dir' --status=79 \
		-- is-not-symlink -- "$dir_symlink" "$DOROTHY"

	eval-tester --name='broken symlink file then file' --status=79 \
		-- is-not-symlink -- "$file_symlink" "$DOROTHY/README.md"

	eval-tester --name='broken symlink file then missing' --status=79 \
		-- is-not-symlink -- "$file_symlink" "$DOROTHY/this-does-not-exist"

	echo-style --g1="TEST: $0"
	return 0
)
function is_not_symlink() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Check if all <path>s are not a symlink, broken or otherwise.
			Companion to [is-broken-symlink], [is-symlink].

			USAGE:
			is-not-symlink [...options] [--] ...<path>

			OPTIONS:
			--sudo=<sudo>
			    Defaults to [13], escalating to root if permission would otherwise be denied.
			--user=<user>
			--group=<group>
			    Forwarded to [sudo-helper].

			RETURNS:
			[0] if all <path>s existed and were not a symlink (broken or otherwise)
			[2] if a <path> was not found
			[13] if a <path> was not accessible: unless [--no-sudo] was provided a sudo request will be made to prevent this failure.
			[22] if empty arguments are provided
			[79] if a <path> was a symlink (broken or otherwise)
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_inputs=() option_sudo='13' option_user='' option_group=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-sudo'* | '--sudo'*)
			option_sudo="$(get-flag-value --affirmative --fallback-on-empty --fallback="$option_sudo" -- "$item")"
			;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--')
			option_inputs+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) option_inputs+=("$item") ;;
		esac
	done

	# verify
	if [[ ${#option_inputs[@]} -eq 0 ]]; then
		help 'No <input>s provided.'
	fi

	# =====================================
	# Action

	sudo-helper --inherit --sudo="$option_sudo" --user="$option_user" --group="$option_group" -- is-not-symlink.bash -- "${option_inputs[@]}"
	return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_not_symlink_test
	else
		is_not_symlink "$@"
	fi
fi
