#!/usr/bin/env bash

function is-nonempty-string() (
	source "$DOROTHY/sources/bash.bash"

	! is-empty-string "$1"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-nonempty-string "$@"
fi
