#!/usr/bin/env bash

function is_non_affirmative_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- is-non-affirmative --help
)

function is_non_affirmative() (
	source "$DOROTHY/sources/bash.bash"

	function __help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Check if <input> is a non-affirmative value.
			Companion to [is-affirmative].

			USAGE:
			is-non-affirmative [...options] [--] ...<input>

			OPTIONS:
			<input>
			    Input to check is a non-affirmative value.

			--ignore-empty:
			    Ignore/skip empty values.

			RETURNS:
			[0] if all <input>s are non-affirmative
			[1] if any <input>s are affirmative
			[91] if invalid values are provided, or no <input>s are provided
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	if [[ $* == '--help' ]]; then
		__help || return $?
	else
		__is_non_affirmative "$@" || return $?
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_non_affirmative_test
	else
		is_non_affirmative "$@"
	fi
fi
