#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function is-neither() (
	local arg

	for arg in "${@:2}"; do
		if test "$1" = "$arg"; then
			return 1
		fi
	done

	return
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-neither "$@"
fi
