#!/usr/bin/env bash

function is_nonempty_file() (
	source "$DOROTHY/sources/bash.bash"

	test -s "$1"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_nonempty_file "$@"
fi
