#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# checks if the first argument exists in the subsequent arguments

for item in "${@:2}"; do
	if test "$item" = "$1"; then
		exit
	fi
done

exit 1