#!/usr/bin/env bash

# checks if the first argument exists in the subsequent arguments

function is_needle() (
	source "$DOROTHY/sources/bash.bash"

	local item
	for item in "${@:2}"; do
		if test "$item" = "$1"; then
			return 0
		fi
	done

	return 1
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_needle "$@"
fi
