#!/usr/bin/env bash

function is-opensuse() (
	source "$DOROTHY/sources/strict.bash"

	if test -f /etc/os-release; then
		grep -qi 'openSUSE' /etc/os-release 2>/dev/null
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-opensuse "$@"
fi
