#!/usr/bin/env bash

function is_present() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Check if all <path>s are present (file/directory/symlink).
			Opposite of [is-missing].

			USAGE:
			is-presen [...options] [--] ...<path>

			OPTIONS:
			--sudo
			    If specified, use sudo on filesystem interactions.
			--user=<user>
			--group=<group>
			    If specified use this user and/or group for filesystem interactions.

			RETURNS:
			[0] if all <path>s were present
			[1] if any <path>s were not present
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_inputs=() option_sudo='no' option_user='' option_group=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-sudo'* | '--sudo'*)
			option_sudo="$(get-flag-value --affirmative --fallback="$option_sudo" -- "$item")"
			;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--')
			option_inputs+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) option_inputs+=("$item") ;;
		esac
	done

	# verify
	if [[ ${#option_inputs[@]} -eq 0 ]]; then
		help 'No <input>s provided.'
	fi

	# =====================================
	# Action

	function __sudo_wrapper {
		while [[ $1 == '--' ]]; do
			shift
		done
		if [[ $option_sudo == 'yes' || -n $option_user || -n $option_group ]]; then
			sudo-helper --inherit --user="$option_user" --group="$option_group" -- "$@"
			return
		else
			"$@"
			return
		fi
	}

	local input
	for input in "${option_inputs[@]}"; do
		# just -e is faulty, as -e fails on broken symlinks
		if __sudo_wrapper -- test ! -e "$input" -a ! -L "$input"; then
			return 1
		fi
	done
	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_present "$@"
fi
