#!/usr/bin/env bash

function is_raspi() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return
			ABOUT:
			Checks if the system is a Raspberry Pi

			USAGE:
			\`is-raspi\`

			RETURNS:
			[0] if the system is a Raspberry Pi
			[1] if the system is not a Raspberry Pi
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Action

	# HOSTTYPE, OSTYPE, MACHTYPE do not help here
	# `uname -a` is `uname -mnrsv`
	local via_uname
	via_uname="$(uname -a)" || return 46 # EPFNOSUPPORT 46 Protocol family not supported
	if [[ $via_uname == *raspi* ]]; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_raspi "$@"
fi
