#!/usr/bin/env bash

function is_readable_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-style --h1="TEST: $0"
	eval-tester --name='no args' --status=22 --ignore-stderr \
		-- is-readable --

	eval-tester --name='empty args' --status=22 \
		-- is-readable -- '' ''

	eval-tester --name='missing' --status=2 \
		-- is-readable -- "$DOROTHY/this-does-not-exist"

	eval-tester --name='directory' \
		-- is-readable -- "$DOROTHY"

	eval-tester --name='file' \
		-- is-readable -- "$DOROTHY/README.md"

	eval-tester --name='file then dir' \
		-- is-readable -- "$DOROTHY/README.md" "$DOROTHY"

	eval-tester --name='dir then file' \
		-- is-readable -- "$DOROTHY" "$DOROTHY/README.md"

	eval-tester --name='dir then file then missing then invalid' --status=2 \
		-- is-readable -- "$DOROTHY" "$DOROTHY/README.md" "$DOROTHY/this-does-not-exist" ''

	eval-tester --name='dir then invalid then missing then file' --status=22 \
		-- is-readable -- "$DOROTHY" '' "$DOROTHY/this-does-not-exist" "$DOROTHY/README.md"

	# test working symlinks
	local dir_target dir_symlink file_target file_symlink
	dir_target="$(fs-temp --directory='is-readable' --directory='dir_target' --touch)"
	file_target="$(fs-temp --directory='is-readable' --file='file_target' --touch)"
	dir_symlink="$(fs-temp --directory='is-readable' --directory='dir_symlink' --no-touch)"
	file_symlink="$(fs-temp --directory='is-readable' --file='file_symlink' --no-touch)"
	symlink-helper --existing="$dir_target" --symlink="$dir_symlink" --quiet
	symlink-helper --existing="$file_target" --symlink="$file_symlink" --quiet

	eval-tester --name='symlink dir' \
		-- is-readable -- "$dir_symlink"

	eval-tester --name='symlink file' \
		-- is-readable -- "$file_symlink"

	# test no longer readable
	fs-own --quiet --permissions='-r' -- "$file_target"
	eval-tester --name='no longer readable' --status=1 \
		-- is-readable -- "$file_target"

	# test broken symlinks
	fs-rm --quiet --no-confirm -- "$dir_target" "$file_target"

	eval-tester --name='broken symlink dir' --status=1 \
		-- is-readable -- "$dir_symlink"

	eval-tester --name='broken symlink file' --status=1 \
		-- is-readable -- "$file_symlink"

	echo-style --g1="TEST: $0"
	return 0
)
function is_readable() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Check if all <path>s are readable.

			USAGE:
			is-readable [...options] [--] ...<path>

			OPTIONS:
			--sudo
			    If specified, use sudo on filesystem interactions.
			--user=<user>
			--group=<group>
			    If specified use this user and/or group for filesystem interactions.

			RETURNS:
			[0] if all <path>s are readable
			[1] if any <path>s are not readable
			[2] if any <path>s do not exist (even as a broken symlink)
			[22] if empty arguments are provided
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_inputs=() option_sudo='no' option_user='' option_group=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-sudo'* | '--sudo'*)
			option_sudo="$(get-flag-value --affirmative --fallback="$option_sudo" -- "$item")"
			;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--')
			option_inputs+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) option_inputs+=("$item") ;;
		esac
	done

	# verify
	if [[ ${#option_inputs[@]} -eq 0 ]]; then
		help 'No <input>s provided.'
	fi

	# =====================================
	# Action

	sudo-helper --inherit --sudo="$option_sudo" --user="$option_user" --group="$option_group" -- is-readable.bash -- "${option_inputs[@]}"
	return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_readable_test
	else
		is_readable "$@"
	fi
fi
