#!/usr/bin/env bash

function is_raspi() (
	source "$DOROTHY/sources/bash.bash"

	if [[ "$(uname -a)" == *raspi* ]]; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is_raspi "$@"
fi
