#!/usr/bin/env bash

# @todo rename to is-root-user or is-user-root

function is_root_test() (
	source "$DOROTHY/sources/is-fs-tests.bash"
	echo-style --h1="TEST: $0"

	eval-helper --invalidate-elevation

	eval-helper --verbose --wrap -- bash -c 'echo $USER' || :
	eval-helper --verbose --wrap -- whoami || :
	eval-helper --verbose --wrap -- logname || :
	eval-helper --verbose --wrap -- id || :
	eval-helper --verbose --wrap -- id -u || :
	eval-helper --verbose --wrap -- id -un || :
	eval-helper --verbose --wrap -- is-root --verbose || :
	eval-helper --verbose --wrap -- is-root --login --verbose || :

	eval-helper --elevate --verbose --wrap -- bash -c 'echo $USER' || :
	eval-helper --elevate --verbose --wrap -- whoami || :
	eval-helper --elevate --verbose --wrap -- logname || :
	eval-helper --elevate --verbose --wrap -- id || :
	eval-helper --elevate --verbose --wrap -- id -u || :
	eval-helper --elevate --verbose --wrap -- id -un || :
	eval-helper --elevate --inherit --verbose --wrap -- is-root --verbose || :
	eval-helper --elevate --inherit --verbose --wrap -- is-root --login --verbose || :

	echo-style --g1="TEST: $0"
	return 0
)
function is_root() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Check if the currently logged in user, or the specified <user>s are root.

			USAGE:
			is-root [...options] [--] ...<user>

			OPTIONS:
			--user=<user> | ...<user>
			    Specify a <user> to check if it is root.

			--login
			    If enabled, the login user will be used as the <user> if none were provided.
			    Otherwise, the active user will be used as the <user> if none were provided.
			    If the elevation timestamp is active and not yet reset, then the active user will be root.

			RETURNS:
			[0] if all <user>s were root
			[1] if a <user> was not accessible
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_quiet='' option_login='' option_inputs=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-verbose'* | '--verbose'*)
			option_quiet="$(get-flag-value --non-affirmative --fallback="$option_quiet" -- "$item")"
			;;
		'--no-quiet'* | '--quiet'*)
			option_quiet="$(get-flag-value --affirmative --fallback="$option_quiet" -- "$item")"
			;;
		'--no-login'* | '--login'*)
			option_login="$(get-flag-value --affirmative --fallback="$option_login" -- "$item")"
			;;
		'--user='*) option_inputs+=("${item#*=}") ;;
		'--')
			option_inputs+=("$@")
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) option_inputs+=("$item") ;;
		esac
	done

	# verify
	if [[ ${#option_inputs[@]} -eq 0 ]]; then
		if [[ $option_login == 'yes' ]]; then
			option_inputs+=("$USER") # login user, will still be the login user even if the elevation timestamp is active and not yet reset
		else
			option_inputs+=("$(whoami)") # current user, will be [root] if the elevation timestamp is active and not yet reset
		fi
	fi

	# =====================================
	# Action

	local user
	for user in "${option_inputs[@]}"; do
		# if [[ "$(id -u "$user")" -ne 0 ]]; then
		if [[ $user != 'root' ]]; then
			if [[ -z $option_quiet || $option_quiet == 'no' ]]; then
				echo-style --stderr --error1='User ' --code-error1="$user" --error1=' is not root.'
			fi
			return 1
		elif [[ $option_quiet == 'no' ]]; then
			echo-style --stderr --info1='User ' --code-info1="$user" --info1=' is root.'
		fi
	done
	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_root_test
	else
		is_root "$@"
	fi
fi
