#!/usr/bin/env bash

function is-snap() (
	source "$DOROTHY/sources/bash.bash"

	if is-wsl; then
		return 1
	fi
	command-exists snap
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-snap "$@"
fi
