#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# act
needle="${1:?"USAGE: is-suffix <NEEDLE> <HAYSTACK>"}"
haystack="${2:?"USAGE: is-suffix <needle> <HAYSTACK>"}"

# oldschool way:
# env QUIET=y setup-util-ripgrep
# echo "$haystack" | rg --quiet "$needle"'$'

# better way:
test "$needle" = "${haystack:${#needle} * -1}"
