#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if command-missing rg; then
	stderr echo 'missing dependency [ripgrep], installing it automatically...'
	stderr setup-util-ripgrep
fi

needle="${1:?"USAGE: is-suffix <NEEDLE> <HAYSTACK>"}"
haystack="${2:?"USAGE: is-suffix <needle> <HAYSTACK>"}"

echo "$haystack" | rg --quiet "$needle"'$'
