#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

r="$(sha256sum "$1")"
h="${r%  *}"

for arg in "${@:2}"; do
	rr="$(sha256sum "$arg")"
	hh="${rr%  *}"
	if test "$hh" != "$h"; then
		exit 1
	fi
done

exit 0