#!/usr/bin/env bash

function is-ubuntu() (
	source "$DOROTHY/sources/strict.bash"

	uname -a | grep --quiet --ignore-case --fixed-strings --regexp='ubuntu'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-ubuntu "$@"
fi
