#!/usr/bin/env bash

function is-user-in-group() (
	source "$DOROTHY/sources/strict.bash"

	# confirm the groups is available
	# vscode flatpak doesn't have it, so vscode flatpak terminal will fail
	# roups: command not found
	if command-missing groups; then
		return 2
	fi

	# prepare
	local group="$1" user="${2-}"

	# check
	if test -n "$user"; then
		groups "$user" | grep --quiet --fixed-strings --regexp="$group"
	else
		groups | grep --quiet --fixed-strings --regexp="$group"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	is-user-in-group "$@"
fi
