#!/usr/bin/env bash

function is_value() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Check if the <input> is a non-empty value.
			Companion to [is-empty-value].

			USAGE:
			is-value  [...options] [--] <input>

			OPTIONS:
			<input> | --value=<input>
			    Verify this <input> is an empty value

			RETURNS:
			[0] if all <input>s are not empty values.
			[1] if any <input>s are an empty value.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process our arguments
	local item option_inputs=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--value='*) option_inputs+=("${item#*=}") ;;
		--)
			option_inputs+=("$@")
			shift $#
			;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*)
			option_inputs+=("$item" "$@")
			shift "$#"
			break
			;;
		esac
	done

	# check
	if [[ ${#option_inputs[@]} -eq 0 ]]; then
		help 'No <input>s was provided.'
	fi

	# =====================================
	# Action

	local value
	for value in "${option_inputs[@]}"; do
		if is-empty-value -- "$value"; then
			return 1
		else
			# all good, continue
			:
		fi
	done
	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_value "$@"
fi
