#!/usr/bin/env bash

function is_vscode_like() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Checks if the environment is running within a VSCode-like editor.
			Currently supports VSCode, Cursor, and VSCode Insiders.

			USAGE:
			is-vscode-like

			RETURNS:
			[0] if the environment is within a VSCode-like editor
			[1] if the environment is not within a VSCode-like editor
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	if [[ ${TERM_PROGRAM-} == 'vscode']]; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_vscode_like "$@"
fi
