#!/usr/bin/env bash

function is_windows() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Checks if the environment is Windows

			USAGE:
			is-windows

			RETURNS:
			[0] if the environment is Windows
			[1] if the environment is not Windows
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	# x64: MINGW64_NT-10.0-26100 fv-az1791-892 3.6.3-086201ea.x86_64 2025-06-05 13:51 UTC x86_64 Msys
	local u
	u="$(uname -a)"
	if [[ $u == MINGW64_NT* || $u == *-WSL* ]]; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_windows "$@"
fi
