#!/usr/bin/env bash

function is_wsl() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Checks if the environment is WSL (Windows Subsystem for Linux)

			USAGE:
			is-wsl

			RETURNS:
			[0] if the environment is WSL
			[1] if the environment is not WSL
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Action

	if uname -a | grep --quiet --ignore-case --fixed-strings --regexp='-WSL'; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_wsl "$@"
fi
