#!/usr/bin/env bash

function macos_drive_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- macos-drive --help
)

function macos_drive() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function __help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Guides you through creating a macOS installation media.

			USAGE:
			\`macos-drive\`
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') __help || return $? ;;
		'--'*) __help 'An unrecognised flag was provided: ' --variable-value={item} || return $? ;;
		*) __help 'An unrecognised argument was provided: ' --variable-value={item} || return $? ;;
		esac
	done

	# =====================================
	# Action

	# helpers
	local installer name volume
	function __choose_volume {
		choose --linger --confirm --required --question="Install $name to which volume?" -- /Volumes/* || return $?
	}
	function __confirm_installation {
		confirm --linger --bool --ppid=$$ -- "Confirm installation of $name to $volume?" || return $?
	}
	function __perform_installation {
		eval-helper --elevate -- "$installer/Contents/Resources/createinstallmedia" --volume "$volume" || return $?
	}

	# select the installer
	installer="$(macos-installer)"
	name="$(fs-path --no-parents -- "$installer")"
	volume="$(__choose_volume)"
	if __confirm_installation; then
		__perform_installation
	else
		return 125 # ECANCELED 125 Operation cancelled
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		macos_drive_test
	else
		macos_drive "$@"
	fi
fi
