#!/usr/bin/env bash

function macos-drive() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Guides you through creating a macOS installation media.

			USAGE:
			macos-drive
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	# helpers
	local installer name volume
	function choose_volume {
		choose-option --required \
			--question="Install $name to which volume?" \
			-- /Volumes/*
	}
	function confirm_installation {
		confirm --bool --ppid=$$ -- "Confirm installation of $name to $volume?"
	}
	function do_installation {
		sudo-helper -- "$installer/Contents/Resources/createinstallmedia" --volume "$volume"
	}

	# select the installer
	installer="$(macos-installer)"
	name="$(basename "$installer")"
	volume="$(choose_volume)"
	if confirm_installation; then
		do_installation
		return "$?"
	else
		return 125 # Operation canceled
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	macos-drive "$@"
fi
