#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/nullglob.bash"
# https://apple.stackexchange.com/a/326863/15131
# https://stackoverflow.com/a/39208361/130638

# configuration
wallpapers_superset_directory_path="/Users/$(whoami)/Documents/Wallpapers"
vscode_settings_file="/Users/$(whoami)/Library/Application Support/Code/User/settings.json"
vscode_theme_light="Light+"       # "GitHub Light"
vscode_theme_dark="Monokai Night" # "Save My Eyes", "An Old Hope", "Adapta Nokto", "An Old Hope", "Dracula", "Monokai++"
wallpaper_directory_light="Light"
wallpaper_directory_dark="Dark"

# verify
errors=()
if test ! -f "$vscode_settings_file"; then
	errors+=("Missing: $vscode_settings_file")
fi
if test ! -d "$wallpapers_superset_directory_path"; then
	errors+=("Missing: $wallpapers_superset_directory_path/")
fi
if test -n "$wallpaper_directory_light" -a ! -d "$wallpapers_superset_directory_path/$wallpaper_directory_light"; then
	errors+=("Missing: $wallpapers_superset_directory_path/$wallpaper_directory_light/")
fi
if test -n "$wallpaper_directory_dark" -a ! -d "$wallpapers_superset_directory_path/$wallpaper_directory_dark"; then
	errors+=("Missing: $wallpapers_superset_directory_path/$wallpaper_directory_dark/")
fi
if test "${#errors[@]}" -ne 0; then
	for error in "${errors[@]}"; do
		stderr echo-color --error "$error"
	done
	exit 1
fi

# options
theme="$(choose-option --required --question='Which macOS theme to apply?' --filter="${1-}" -- dark light)"

# helpers
function macos_wallpaper_directory_setter {
	local wallpapers_subset_directory="${1-}" wallpapers_subset_directory_path
	if is-empty-string "$1"; then
		return 0
	fi
	if test -z "$wallpapers_subset_directory"; then
		wallpapers_subset_directory_path="$(choose-path --question='Which wallpaper directory?' -- "$wallpapers_superset_directory_path/"*)"
	else
		wallpapers_subset_directory_path="$wallpapers_superset_directory_path/$wallpapers_subset_directory"
	fi
	macos_wallpaper_directory_set "$wallpapers_subset_directory_path"
}
function macos_wallpaper_directory_set() {
	local wallpaper_directory="$1"
	osascript -e "tell application \"System Events\" to tell current desktop to set pictures folder to \"$wallpaper_directory\""
}
function vscode_set_theme {
	local new_theme="$1"
	jq ".[\"workbench.colorTheme\"] = \"${new_theme}\"" "$vscode_settings_file" | sponge "$vscode_settings_file"
}
function macos_dark_mode_enable {
	local dark_mode_boolean='true'
	if ! is-affirmative "${1-}"; then
		dark_mode_boolean='false'
	fi
	osascript -e "tell application \"System Events\" to tell appearance preferences to set dark mode to $dark_mode_boolean"
}

if test "$theme" = 'dark'; then
	# enable dark mode
	macos_dark_mode_enable 'true'
	macos_wallpaper_directory_setter "$wallpaper_directory_dark"
	vscode_set_theme "$vscode_theme_dark"
else
	# disable dark mode
	macos_dark_mode_enable 'false'
	macos_wallpaper_directory_setter "$wallpaper_directory_light"
	vscode_set_theme "$vscode_theme_light"
fi
