#!/usr/bin/env bash

function network_interface() (
	source "$DOROTHY/sources/bash.bash"
	# trunk-ignore(shellcheck/SC2034)
	local all_tools=(ip netstat)

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Helpers for dealing with network interfaces.

			USAGE:
			network-interface <up|down|restart> <interface>
			network-interface list

			OPTIONS:
			--tool=<tool:$(__join --source={all_tools} --between='|' -- '?')>
			    The tool to use. Use \`?\` to prompt. Default is the first available tool.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item action='' option_interface='' option_tool=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--tool='*) option_tool="${item#*=}" ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*)
			if [[ -z $action ]]; then
				action="$item"
			elif [[ -z $option_interface ]]; then
				option_interface="$item"
			else
				help 'An unrecognised argument was provided: ' --variable-value={item}
			fi
			;;
		esac
	done

	# ensure
	if [[ -z $action ]]; then
		help "You must provide an <action>"
	fi
	if [[ -z $option_interface && $action != 'list' ]]; then
		help "You must provide an <interface>"
	fi

	# ensure tool
	__tool --tool={option_tool} --tools={all_tools} --help={help} || return $?

	# =====================================
	# Action

	# https://archlinux.org/news/deprecation-of-net-tools/
	# https://wiki.archlinux.org/title/Network_configuration#net-tools

	function up {
		if [[ $option_tool == 'ip' ]]; then
			eval-helper --elevate -- ip link set "$option_interface" up
		elif [[ $option_tool == 'netstat' ]]; then
			eval-helper --elevate -- ifup "$option_interface"
		fi
		sleep 3
	}
	function down {
		if [[ $option_tool == 'ip' ]]; then
			eval-helper --elevate -- ip link set "$option_interface" down
		elif [[ $option_tool == 'netstat' ]]; then
			eval-helper --elevate -- ifdown "$option_interface"
		fi
		sleep 3
	}
	function restart {
		if [[ $option_tool == 'ip' ]]; then
			# restart action isn't a thing
			# so make it two step
			# and don't care if down fails,
			# as we just care about up
			eval-helper --elevate -- ip link set "$option_interface" down || :
			eval-helper --elevate -- ip link set "$option_interface" up
		elif [[ $option_tool == 'netstat' ]]; then
			eval-helper --elevate -- ifdown "$option_interface"
			eval-helper --elevate -- ifup "$option_interface"
		fi
	}
	function list {
		if __is_macos; then
			# An asterisk (*) denotes that a network service is disabled.
			networksetup -listallnetworkservices | grep --invert-match --fixed-strings --regexp='*'
		else
			resolvectl status --no-pager | echo-regexp -ong --regexp='Link \d \((.+?)\)' --replace='$1'
		fi
	}

	# =====================================
	# Act

	case "$action" in
	'up' | 'down' | 'restart' | 'list')
		"$action"
		;;
	*)
		help "Unknown action: $action"
		;;
	esac
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	network_interface "$@"
fi
