#!/usr/bin/env bash

# workaround nvm trying to compile from source old builds on apple silicon
# https://github.com/nvm-sh/nvm/issues/2596

if is-apple-silicon; then
	arch -x86_64 /bin/bash -c "source $DOROTHY/sources/nvm.sh; nvm $*"
else
	source "$DOROTHY/sources/nvm.sh"
	nvm "$@"
fi
