#!/usr/bin/env bash

# execute a command inside a nvm context without strict mode

if test "${1-}" = '--2596'; then
	# workaround nvm trying to compile from source old builds on apple silicon
	# https://github.com/nvm-sh/nvm/issues/2596
	if is-apple-silicon; then
		arch -x86_64 /bin/bash -c "source $DOROTHY/sources/nvm.sh; $*"
	fi
else
	source "$DOROTHY/sources/nvm.sh"
	"$@"
fi
