#!/usr/bin/env bash

# this is only used by `git-helper review`, and is now replaced by `setup-util invoke ...`

function open_app_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- open-app --help
)

# @todo merge into `setup-util`

function open_app() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='open-app' --bold=' has been deprecated in favor of ' --code='setup-util invoke'
	setup-util --invoke "$option_name" -- "${option_args[@]}" || return $?
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		open_app_test
	else
		open_app "$@"
	fi
fi
