#!/usr/bin/env bash

function open-app() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Open the specified GUI application.

			QUIRKS:
			Uses [get-app] to determine the application path to open.

			USAGE:
			open-app <app> [-- <...args>]

			OPTIONS:
			<app>
			    App name or path.

			<...args>
			    Arguments to pass to the application.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item name='' args=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--name='*) name="${item:7}" ;;
		'--')
			args+=("$@")
			shift "$#"
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if test -z "$name"; then
				name="$item"
			else
				help "An unrecognised argument was provided: $item"
			fi
			;;
		esac
	done

	# =====================================
	# Act

	local app
	app="$(get-app "$name")"
	if test -n "$app"; then
		open -a "$app" "${args[@]}"
	else
		echo-style --error="Unable to find the application: $name" >/dev/stderr
		return 2 # ENOENT 2 No such file or directory
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	open-app "$@"
fi
