#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

p="$(pwd)"
password="$1"
outdir="${2:-out}"
outdir="$(fs-absolute "$outdir")"
mkdir -p "$outdir"

function decrypt {
	local input inputdir output
	input="$(fs-absolute "$1")"
	inputdir="$(dirname "$input")"
	output="$outdir/$(basename "$1")"
	cd "$inputdir" || exit 1
	echo "$1 to $output"
	while is-file "$output"; do
		output="$(fs-filename "$output")!.pdf"
	done
	(qpdf -password="$password" -decrypt "$input" "$output" && echo "SUCCESS") || echo "FAILURE"
	cd "$p" || exit 1
}

if test -n "$password"; then
	find-files pdf | while read -r file; do
		decrypt "$file" "$2" "$1"
	done
else
	echo "decrypt <password>"
fi
