#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# todo this failed on a new setup
# perhaps old bash
# or perhaps only doing 1 item causes it to fail
# error occured on each of the read statements below
# read: error setting terminal attributes: Input/output error
# read: read error: 0: Input/output error

# for term in vt100 linux screen xterm; do
# 	echo "$term:"
# 	infocmp -L1 $term | grep -E 'key_(left|right|up|down|home|end)'
# done

# timeout
option_timeout="$(get-flag-value timeout -- "$@")"
if ! is-number "$option_timeout"; then
	option_timeout=600 # ten minutes
fi

# 1 char (not delimiter), silent
ec=0; read -sN1 -t "$option_timeout" k0 || ec="$?"
if test "$ec" -gt 128; then
	exit 62  # Timer expired
elif test "$ec" -ne 0; then
	exit "$ec"  # some other issue, let the caller figure it out
fi

# catch multi-char special key sequences if they exist
read -sN1 -t 0.0001 k1 || :
read -sN1 -t 0.0001 k2 || :
read -sN1 -t 0.0001 k3 || :

# combine
key="${k0}${k1-}${k2-}${k3-}"

case "$key" in
	# vt100
	$'\eOB') echo down ;;
	$'\eOD') echo left ;;
	$'\eOC') echo right ;;
	$'\eOA') echo up ;;
	# linux
	$'\e[B') echo down ;;
	$'\e[4~') echo end ;;
	$'\e[1~') echo home ;;
	$'\e[D') echo left ;;
	$'\e[C') echo right ;;
	$'\e[A') echo up ;;
	# screen
	$'\eOB') echo down ;;
	$'\e[4~') echo end ;;
	$'\e[1~') echo home ;;
	$'\eOD') echo left ;;
	$'\eOC') echo right ;;
	$'\eOA') echo up ;;
	# xterm
	$'\eOB') echo down ;;
	$'\eOF') echo end ;;
	$'\eOH') echo home ;;
	$'\eOD') echo left ;;
	$'\eOC') echo right ;;
	$'\eOA') echo up ;;
	# special
	$'\x7f') echo backspace ;;
	$'\x01') echo all ;; # what type of key is this?
	$'\x1b') echo escape ;;
	$'\x0a') echo enter ;;
	$'\t') echo tab ;;
	' ') echo space ;;
	# other
	$'\eOH') echo home ;;
	$'\e[H') echo home ;;
	$'\eOF') echo end ;;
	$'\eOF') echo end ;;
	*) echo "$key" ;;
esac
