#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

usage="USAGE: replace-inside <file> <search> [replace]"
file="${1:?"$usage"}"
search="${2:?"$usage"}"
replace="${3-}"  # optional in case we actually want to remove the line

contents="$(cat "$file")"
echo -n "${contents//"$search"/"$replace"}" > "$file"

# ensure it ends with a newline
"$DOROTHY/commands/ensure-trailing-newline" "$file"
