#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=y setup-util-jq
env QUIET=y setup-util-gh

# act
action="${1:-open}"

PASS="\e[1;4;32m"
FAILURE="\e[1;4;31m"
NORMAL="\e[0m"

if test "$action" = "browse"; then
	gh browse
elif test "$action" = "status"; then
	echo -n 'ci: '
	repo ci
	echo -n 'version: '
	repo version
	echo 'move onto the next package'
elif test "$action" = "ci"; then
	travis status # "hhub ci-status" is unreliable
elif test "$action" = "slug"; then
	git remote get-url origin | sed 's/.*github.com.//; s/.git//'
elif test "$action" = "travis"; then
	travisTLD="$(jq -r '.badges.config.travisTLD' < package.json)"
	if is-empty-value "$travisTLD"; then
		travisTLD="com";
	fi
	open "https://travis-ci.${travisTLD}/$(repo slug)"
elif test "$action" = "version"; then
	name="$(jq -r .name package.json)"
	version="$(jq -r .version package.json)"
	published="$(npm view "$name@$version" version)"
	if test "$version" = "$published"; then
		echo -e "version $version ${PASS}released${NORMAL}"
	else
		stderr echo -e "version $version ${FAILURE}unreleased${NORMAL}"
		exit 1
	fi
else
	stderr echo "USAGE: repo <browse|status|travis|ssh|version>"
	exit 1
fi
