#!/usr/bin/env bash

function rm-modules() (
	source "$DOROTHY/sources/strict.bash"
	source "$DOROTHY/sources/nullglob.bash"
	source "$DOROTHY/sources/globstar.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Removes all Node.js temporary module and package manager files in the provided path.

			USAGE:
			rm-modules [.]
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item path=''
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if test -z "$path"; then
				path="$item"
			else
				help "An unrecognised argument was provided: $item"
			fi
			;;
		esac
	done

	# ensure
	if test -z "$path"; then
		path="$(pwd)"
	fi

	# =====================================
	# Act

	rm -Rfv "$path"/**/{node_modules,pnp,package-lock.json,yarn.lock,.pnp.js,.log}
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	rm-modules "$@"
fi
