#!/usr/bin/env bash

function setup_util_xcode() (
	source "$DOROTHY/sources/bash.bash"
	source "$(type -P eval-helper)"

	# checks
	if ! is-mac || [[ -n $CI ]]; then
		echo-style --stderr --notice="[$0] is only intended to be run on interactive macOS systems, skipping."
		return 0
	fi

	# =====================================
	# Dependencies

	local bin_gsed_or_sed
	bin_gsed_or_sed="$(echo-gnu-command --install -- gsed)"

	# =====================================
	# Action

	# arguments
	local option_quiet='no'
	option_quiet="$(echo-option_quiet-enabled --fallback="$option_quiet" -- "$@")"

	# log
	if [[ $option_quiet == 'no' ]]; then
		echo-style --h1="Install Xcode"
	fi

	# check if xcode exists
	local xcode xcodebuild xcodesdk
	while :; do
		# prerequisites
		setup-util-apple-rosetta --quiet="$option_quiet"
		setup-util-apple-cli-tools --quiet="$option_quiet"

		# determine xcode location
		xcode="$(get-app -- 'Xcode' || get-app -- 'Xcode-beta' || :)"
		xcodebuild="$xcode/Contents/Developer/usr/bin/xcodebuild"
		xcodesdk="$xcode/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"

		# confirm xcode exists
		if [[ -z $xcode ]]; then
			if __command_missing -- mas || ! setup-util --name='Xcode' MAS='497799835'; then
				echo-style --notice='Xcode requires manual installation...'
				open 'https://apps.apple.com/us/app/xcode/id497799835'
				confirm --ppid=$$ -- 'Press <enter> once Xcode has been installed...'
			fi
			continue # try again
		fi

		# confirm xcode sdk exists
		if [[ ! -x $xcodebuild ]] || ! "$xcodebuild" -sdk "$xcodesdk" -find clang &>/dev/null; then
			echo-style --notice="Xcode SDKs require manual installation, opening Xcode..."
			open "$xcode"
			confirm --ppid=$$ -- 'Press <enter> once the Xcode Components have been installed...'
			continue # try again
		fi

		# xcode sdk license
		function __xcode_license_accepted {
			# https://stackoverflow.com/a/60906147/130638
			local xcode_version accepted_license_version
			# @todo replace with `echo-regexp` and `echo-write`
			xcode_version="$("$xcodebuild" -version | grep --regexp='^Xcode\s' | "$bin_gsed_or_sed" -E 's/^Xcode[[:space:]]+([0-9\.]+)/\1/' | cut -d '.' -f 1 || :)"
			accepted_license_version="$(defaults read /Library/Preferences/com.apple.dt.Xcode 2>/dev/null | grep IDEXcodeVersionForAgreedToGMLicense | cut -d '"' -f 2 | cut -d '.' -f 1 || :)"
			[[ $xcode_version -eq $accepted_license_version ]] || eval-helper --elevate -- "$xcodebuild" -license accept || return
			return
		}
		if [[ $option_quiet == 'yes' ]]; then
			__xcode_license_accepted || continue # try again
		else
			eval_helper --quiet="$option_quiet" --no-wrap --shapeshifter \
				--pending="$(echo-style --bold="Accepting Xcode license...")" \
				--success="$(echo-style --success="Accepted Xcode license.")" \
				--failure="$(echo-style --error="Failed to accept Xcode license.")" -- \
				__xcode_license_accepted || continue # try again
		fi

		# success
		break
	done

	# log
	if [[ $option_quiet == 'no' ]]; then
		echo-style --g1="Install Xcode"
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_xcode "$@"
fi
