#!/usr/bin/env bash

function setup_util_xcode() (
	source "$DOROTHY/sources/bash.bash"
	source "$(type -P eval-helper)"

	# checks
	if ! is-mac || [[ -n $CI ]]; then
		__print_style --stderr --notice="[$0] is only intended to be run on interactive macOS systems, skipping." || return $?
		return 0
	fi

	# =====================================
	# Dependencies

	local bin_gsed_or_sed
	bin_gsed_or_sed="$(echo-gnu-command --install -- gsed)" || return $?

	# =====================================
	# Action

	# arguments
	local option_quiet='no'
	option_quiet="$(get-terminal-quiet-support --fallback="$option_quiet" -- "$@")" || return $?

	# log
	if [[ $option_quiet == 'no' ]]; then
		__print_style --h1="Install Xcode" || return $?
	fi

	# check if xcode exists
	local xcode xcodebuild xcodesdk
	function __xcode_license_accepted {
		# https://stackoverflow.com/a/60906147/130638
		local xcode_version accepted_license_version
		# @todo replace with `echo-regexp` and `echo-write`
		xcode_version="$("$xcodebuild" -version | grep --extended-regexp --regexp='^Xcode\s' | "$bin_gsed_or_sed" -E 's/^Xcode[[:space:]]+([0-9\.]+)/\1/' | cut -d '.' -f 1 || :)"
		accepted_license_version="$(defaults read /Library/Preferences/com.apple.dt.Xcode 2>/dev/null | grep IDEXcodeVersionForAgreedToGMLicense | cut -d '"' -f 2 | cut -d '.' -f 1 || :)"
		[[ $xcode_version -eq $accepted_license_version ]] || eval-helper --elevate -- "$xcodebuild" -license accept || return $?
		return $?
	}
	while :; do
		# prerequisites
		setup-util-apple-rosetta --quiet="$option_quiet" || return $?
		setup-util-apple-cli-tools --quiet="$option_quiet" || return $?

		# determine xcode location
		xcode="$(get-app -- 'Xcode' || get-app -- 'Xcode-beta' || :)"
		xcodebuild="$xcode/Contents/Developer/usr/bin/xcodebuild"
		xcodesdk="$xcode/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"

		# confirm xcode exists
		if [[ -z $xcode ]]; then
			if __command_missing -- mas || ! setup-util --name='Xcode' MAS='497799835'; then
				__print_style --notice='Xcode requires manual installation...' || return $?
				open 'https://apps.apple.com/us/app/xcode/id497799835' || return $?
				confirm --ppid=$$ -- 'Press <enter> once Xcode has been installed...' || return $?
			fi
			continue # try again
		fi

		# confirm xcode sdk exists
		if [[ ! -x $xcodebuild ]] || ! "$xcodebuild" -sdk "$xcodesdk" -find clang &>/dev/null; then
			__print_style --notice="Xcode SDKs require manual installation, opening Xcode..." || return $?
			open "$xcode" || return $?
			confirm --ppid=$$ -- 'Press <enter> once the Xcode Components have been installed...' || return $?
			continue # try again
		fi

		# xcode sdk license
		if [[ $option_quiet == 'yes' ]]; then
			__xcode_license_accepted || continue # try again
		else
			eval_helper --quiet="$option_quiet" --no-wrap --shapeshifter \
				--pending="$(__print_style --bold="Accepting Xcode license...")" \
				--success="$(__print_style --success="Accepted Xcode license.")" \
				--failure="$(__print_style --error="Failed to accept Xcode license.")" -- \
				__xcode_license_accepted || continue # try again
		fi

		# success
		break
	done

	# log
	if [[ $option_quiet == 'no' ]]; then
		__print_style --g1="Install Xcode" || return $?
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_xcode "$@"
fi
