#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://stedolan.github.io/jq/download/
# https://github.com/stedolan/jq/releases

# https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux32
# https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
# https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64

function setup-util-jq() (
	# determine github args if github is an option on this platform
	local arch github_asset_filter='' github=()
	arch="$(get-arch)"
	if is-mac; then
		github_asset_filter='-osx-amd64'
	else
		if test "$arch" = 'x64'; then
			github_asset_filter='-linux64'
		elif test "$arch" = 'x32'; then
			github_asset_filter='-linux32'
		fi
	fi
	if test -n "$github_asset_filter"; then
		github+=(
			GITHUB_SLUG='stedolan/jq'
			GITHUB_RELEASE='latest'
			GITHUB_ASSET_FILTER="$github_asset_filter"
			GITHUB_FILENAME='jq'
		)
	fi

	# install, preferring github
	setup-util "$@" CLI='jq' \
		"${github[@]}" \
		APT='jq' \
		BREW='jq' \
		CHOCO='jq' \
		DNF='jq' \
		PACMAN='jq' \
		PKG='jq' \
		PKGUTIL='jq' \
		PORT='jq' \
		ZYPPER='jq' \
		-- github ...
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-jq "$@"
fi
