#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/dnsutils/filelist (no bins...)

function setup_util_dig() (
	source "$DOROTHY/sources/bash.bash"

	# no apk
	local options=(
		--cli=dig
		"$@"
		APT='dnsutils'
		AUR='dnsutils'
		RPM='bind-utils'
		ZYPPER='bind-utils'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_dig "$@"
fi
