#!/usr/bin/env bash
source "$HOME/.scripts/sources/essentials.sh"
source "$HOME/.scripts/sources/strict.bash"

# Check
if ! command-exists code; then
	stderr echo -e '\nVisual Studio Code (code) does not seem to be installed...'
	exit
fi

# Helper
function vscodeinstall() {
	for ARG in "$@"; do
		echo -n 0 | code --install-extension "$ARG"
	done
}

# Correct settings
echo -e '\nSymlinking Visual Studio Code settings...'
if is-mac; then
	TARGET="$HOME/Library/Application Support/Code/User"
elif is-linux; then
	TARGET="$HOME/.config/Code/User"
else
	stderr echo 'unknown environment'
	exit 1
fi
SOURCE="$HOME/.scripts/users/$(whoami)/vscode"
ln-make "$SOURCE/settings.json" "$TARGET/settings.json"
ln-make "$SOURCE/keybindings.json" "$TARGET/keybindings.json"
echo '...success'

# Install extensions
if is-present "${VSCODE_INSTALL:-}"; then
	echo -e '\nInstalling Visual Studio Code extensions...'
	vscodeinstall "${VSCODE_INSTALL[@]}"
	echo '...success'
fi

# Customise stylesheets
app=$(get-app Visual Studio Code.app)

# https://github.com/Microsoft/vscode/issues/1896#issuecomment-283858289
if false; then # doesn't seem necessary with recent vscode updates
	stylesheet="$app/Contents/Resources/app/out/vs/workbench/workbench.main.css"
	if is-file "$stylesheet"; then
		if silent grep 'fix font rendering' <"$stylesheet"; then
			echo "setup already completed"
		else
			echo "
			/* fix font rendering */
			.monaco-editor {
				-webkit-font-smoothing: antialiased !important;
				text-rendering: optimizeLegibility !important;
			}" >>"$stylesheet"
			echo "setup completed"
		fi
	else
		echo "vscode not installed"
	fi
fi

# https://github.com/akamud/vscode-theme-onelight/pull/2
stylesheet=$(expand-path "$HOME/.vscode/extensions/akamud.vscode-theme-onelight-*")
stylesheet="$stylesheet/themes/OneLight.json"
if is-file "$stylesheet"; then
	echo -e '\nChanging Visual Studio Code OneLight theme background to white...'
	sed -e 's/#FAFAFA/#FFFFFF/' -e 's/#F2F2F2/#F5F5F5/' <"$stylesheet" >"$stylesheet.tmp"
	mv -f "$stylesheet.tmp" "$stylesheet"
	echo '...success'
fi
