#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/arrays.bash"
requires_array_support 'mapfile' 'empty'

# =====================================
# Configuration

source "$DOROTHY/sources/config.sh"

# setup.bash provides:
MAS_INSTALL=() # tupe array of id, label
load_dorothy_config 'setup.bash'

# =====================================
# Action

function mas_prepare() {
	local email
	email="$(ask --question="The macOS application installer requires your Apple App Store email, enter it now." --require)"
	if is-value "$email"; then
		mas signout
		mas signin --dialog "$email"
	else
		return 1
	fi
}
function mas_install() {
	env NAME='Mac App Store command-line interface' CLI='mas' BREW='mas' setup-util brew
	echo-segment --h2="Install $# macOS apps"
	if test "$#" -ne 0; then
		mas_prepare
		mas install "$@"
	fi
	echo-segment --g2="Install $# macOS apps"
}
function mas_ask() {
	local choices fodder
	if test "$#" -ne 0; then
		fodder="$(choose-option --multi --question="Which Mac App Store apps would you like to install?" --label -- "${MAS_INSTALL[@]}")"
		mapfile -t choices <<<"$fodder" # <( destroys stdin
		mas_install "${choices[@]}"
	fi
}
mas_ask "${MAS_INSTALL[@]}"
