#!/usr/bin/env bash

function setup_util_mas() (
	source "$DOROTHY/sources/bash.bash"

	# checks
	if ! is-mac; then
		echo-style --notice="[$0] is only intended to be run on macOS systems, skipping." >/dev/stderr
		return 0
	fi

	# improve performance
	if is-needle --quiet "$@" && ! is-needle --upgrade "$@" && ! is-needle --uninstall "$@" && command-exists mas; then
		return 0
	fi

	# setup
	local options=(
		--name='Mac App Store CLI'
		--cli='mas'
		"$@"
		BREW='mas'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_mas "$@"
fi
