#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/sharkdp/fd
# find alternative

function setup-util-fd() (
	setup-util "$@" CLI='fd' \
		APT='fd-find' \
		APK='fd' \
		BREW='fd' \
		CARGO='fd-find' \
		CHOCO='fd' \
		DNF='fd-find' \
		EMERGE='fd' \
		NIX='fd' \
		NPM='fd-find' \
		PACMAN='fd' \
		PKG='fd-find' \
		PORT='fd' \
		SCOOP='fd' \
		XBPS='fd' \
		ZYPPER='fd'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-fd "$@"
fi
