#!/usr/bin/env bash

# https://gnu.org/software/coreutils
# https://www.gnu.org/software/coreutils/manual/html_node/index.html
# provides these essential utilities: ls, sort, head, realpath, etc.
# provides these less common utilities: b2sum base32 basenc chcon dir dircolors factor hostid md5sum nproc numfmt pinky ptx realpath runcon sha1sum sha224sum sha256sum sha384sum sha512sum shred shuf stdbuf tac timeout truncate vdir

# https://packages.debian.org/sid/amd64/coreutils/filelist
# /bin/cat
# /bin/chgrp
# /bin/chmod
# /bin/chown
# /bin/cp
# /bin/date
# /bin/dd
# /bin/df
# /bin/dir
# /bin/echo
# /bin/false
# /bin/ln
# /bin/ls
# /bin/mkdir
# /bin/mknod
# /bin/mktemp
# /bin/mv
# /bin/pwd
# /bin/readlink
# /bin/rm
# /bin/rmdir
# /bin/sleep
# /bin/stty
# /bin/sync
# /bin/touch
# /bin/true
# /bin/uname
# /bin/vdir
# /usr/bin/[
# /usr/bin/arch
# /usr/bin/b2sum
# /usr/bin/base32
# /usr/bin/base64
# /usr/bin/basename
# /usr/bin/basenc
# /usr/bin/chcon
# /usr/bin/cksum
# /usr/bin/comm
# /usr/bin/csplit
# /usr/bin/cut
# /usr/bin/dircolors
# /usr/bin/dirname
# /usr/bin/du
# /usr/bin/env
# /usr/bin/expand
# /usr/bin/expr
# /usr/bin/factor
# /usr/bin/fmt
# /usr/bin/fold
# /usr/bin/groups
# /usr/bin/head
# /usr/bin/hostid
# /usr/bin/id
# /usr/bin/install
# /usr/bin/join
# /usr/bin/link
# /usr/bin/logname
# /usr/bin/md5sum
# /usr/bin/md5sum.textutils
# /usr/bin/mkfifo
# /usr/bin/nice
# /usr/bin/nl
# /usr/bin/nohup
# /usr/bin/nproc
# /usr/bin/numfmt
# /usr/bin/od
# /usr/bin/paste
# /usr/bin/pathchk
# /usr/bin/pinky
# /usr/bin/pr
# /usr/bin/printenv
# /usr/bin/printf
# /usr/bin/ptx
# /usr/bin/realpath
# /usr/bin/runcon
# /usr/bin/seq
# /usr/bin/sha1sum
# /usr/bin/sha224sum
# /usr/bin/sha256sum
# /usr/bin/sha384sum
# /usr/bin/sha512sum
# /usr/bin/shred
# /usr/bin/shuf
# /usr/bin/sort
# /usr/bin/split
# /usr/bin/stat
# /usr/bin/stdbuf
# /usr/bin/sum
# /usr/bin/tac
# /usr/bin/tail
# /usr/bin/tee
# /usr/bin/test
# /usr/bin/timeout
# /usr/bin/tr
# /usr/bin/truncate
# /usr/bin/tsort
# /usr/bin/tty
# /usr/bin/unexpand
# /usr/bin/uniq
# /usr/bin/unlink
# /usr/bin/users
# /usr/bin/wc
# /usr/bin/who
# /usr/bin/whoami
# /usr/bin/yes
# /usr/sbin/chroot

# https://repology.org/project/coreutils/versions

function setup_util_coreutils() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--name='Core Utilities'
		--cli='tac' # must be a less common utility, as many but not all are provided by the os
		"$@"
		APK='coreutils'
		APT='coreutils'
		AUR='coreutils'
		BREW='coreutils'
		EMERGE='sys-apps/coreutils'
		NIX='nixpkgs.coreutils'
		RPM='coreutils'
		XBPS='coreutils'
		ZYPPER='coreutils'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_coreutils "$@"
fi
