#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://www.flatpak.org/setup/Ubuntu/

env name='Flatpak' CLI=flatpak \
	APT=flatpak \
	setup-util

# env name='Flatpak plugin for the Software app' \
# 	APT=gnome-software-plugin-flatpak \
# 	setup-util
# Installing the Flatpak plugin will also install a deb version of Software and result in two Software apps being installed at the same time.

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
