#!/usr/bin/env bash

# Diff/Merge Tool: diff
# https://www.gnu.org/s/diffutils/
# https://packages.debian.org/sid/amd64/diffutils/filelist
# /usr/bin/cmp
# /usr/bin/diff
# /usr/bin/diff3
# /usr/bin/sdiff

# https://repology.org/project/diffutils/versions

function setup_util_diff() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--cli='diff'
		"$@"
		APK='diffutils'
		APT='diffutils'
		AUR='diffutils'
		BREW='diffutils'
		EMERGE='sys-apps/diffutils'
		EOPKG='diffutils'
		NIX='diffutils'
		SCOOP='diffutils'
		ZYPPER='diffutils'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_diff "$@"
fi
