#!/usr/bin/env bash

# https://github.com/aria2/aria2
# wget alternative

# https://github.com/aria2/aria2/releases
# aria2-1.36.0-aarch64-linux-android-build1.zip
# aria2-1.36.0-win-32bit-build1.zip
# aria2-1.36.0-win-64bit-build1.zip
# aria2-1.36.0.tar.bz2
# aria2-1.36.0.tar.gz
# aria2-1.36.0.tar.xz

# https://packages.debian.org/sid/amd64/aria2/filelist
# /usr/bin/aria2c

# https://repology.org/project/aria2/versions

function setup_util_aria2() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists aria2c; then
		return 0
	fi

	# despite docs, no apk
	local options=(
		--cli='aria2c'
		"$@"
		APT='aria2' # UBUNTU
		AUR='aria2' # ARCH
		BREW='aria2'
		RPM='aria2'   # FEDORA
		URPMI='aria2' # MAGEIA
		NIX='aria2'
		XBPS='aria2' # VOID
		WINGET='aria2'
		ZYPPER='aria2' # SUSE
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_aria2 "$@"
fi
