#!/usr/bin/env bash

function setup_util_git() (
	source "$DOROTHY/sources/bash.bash"

	# Git
	# https://git-scm.com/download/linux
	# https://packages.debian.org/sid/amd64/git/filelist
	# /usr/bin/git
	# /usr/bin/git-receive-pack
	# /usr/bin/git-shell
	# /usr/bin/git-upload-archive
	# /usr/bin/git-upload-pack
	# /usr/bin/scalar
	local options=(
		--name='git'
		--cli='git'
		"$@"
		APK='git' # ALPINE
		APT='git' # UBUNTU
		AUR='git' # ARCH
		BREW='git'
		BSD='git'
		EMERGE='dev-vcs/git' # GENTOO
		NIX='nixpkgs.git'
		RPM='git'         # FEDORA
		URPMI='git'       # MAGEIA
		XBPS='git'        # VOID
		ZYPPER='git-core' # SUSE
	)
	setup-util "${options[@]}"

	# GPG
	setup-util-gpg --optional "$@"

	# https://en.wikipedia.org/wiki/OpenSSH
	setup-util-sshd --optional "$@"

	# Diff/Merge Tool: meld
	# http://meldmerge.org
	# https://yousseb.github.io/meld/
	# https://coderefinery.github.io/installation/difftools/
	# setup-util  --confirm --optional --name='Meld' --cli='meld' "$@" \
	# 	APT='meld' \
	# 	RPM='meld' \
	# 	CASK='meld'
	# ^ does anyone ever use this???

	# Diff/Merge Tool: delta
	setup-util-delta --confirm --optional "$@"

	# Diff/Merge Tool: diff
	# https://www.gnu.org/s/diffutils/
	# https://packages.debian.org/sid/amd64/diffutils/filelist
	# /usr/bin/cmp
	# /usr/bin/diff
	# /usr/bin/diff3
	# /usr/bin/sdiff
	options=(
		--optional
		--cli='diff'
		"$@"
		APT='diffutils' # UBUNTU
		BREW='diffutils'
	)
	setup-util "${options[@]}"

	# Git LFS
	# https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md
	# https://packages.debian.org/sid/amd64/git-lfs/filelist
	# /usr/bin/git-lfs
	options=(
		--optional
		--name='Git Large File Storage'
		--cli='git-lfs'
		"$@"
		APT='git-lfs' # UBUNTU
		AUR='git-lfs' # ARCH
		BREW='git-lfs'
		RPM='git-lfs' # FEDORA
	)
	setup-util "${options[@]}"

	# Pinentry
	# https://www.gnupg.org/related_software/pinentry/
	# https://github.com/GPGTools/pinentry
	# https://gpgtools.org/
	# on brew, `pinentry` replaces `pinentry-mac` and `gpg-suite-pinentry`
	options=(
		--optional
		--name='Pinentry'
		--cli='pinentry'
		"$@"
		BREW='pinentry'
	)
	setup-util "${options[@]}"
	# @todo figure out linux options

	# ssh-askpass
	# ensure it is installed on ubuntu 22.04
	# https://packages.debian.org/sid/amd64/ssh-askpass/filelist (no bins)
	options=(
		--optional
		--cli='ssh-askpass'
		"$@"
		APT='ssh-askpass'     # UBUNTU
		AUR='x11-ssh-askpass' # ARCH
	)
	setup-util "${options[@]}"
	# if it is missing, then check alternative locations
	local target='/usr/lib/ssh/ssh-askpass' files=() file
	if is-missing "$target"; then
		files=(
			# manjaro/gnome
			'/usr/lib/seahorse/ssh-askpass'
			# arch/gnome
			'/usr/lib/ssh/gnome-ssh-askpass3'
			# arch/minimal/ubuntu 22.04
			'/usr/lib/ssh/x11-ssh-askpass'
		)
		for file in "${files[@]}"; do
			if test -x "$file"; then
				sudo-helper --inherit \
					-- symlink-helper --existing="$file" --symlink="$target"
				break
			fi
		done
	fi

	# Gitell
	options=(
		--optional
		--cli='gitell'
		"$@"
		DOWNLOAD="$(
			github-download \
				--dry \
				--slug='deadc0de6/gitell' \
				--head \
				--pathname='gitell'
		)"
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_git "$@"
fi
