#!/usr/bin/env bash

# https://github.com/XAMPPRocky/tokei
# code stats, wc alternative

function setup-util-trunk() (
	source "$DOROTHY/sources/bash.bash"

	setup-util "$@" --name='Trunk.io' --cli='trunk' \
		DOWNLOAD='https://trunk.io/releases/trunk' \
		DOWNLOAD_FILENAME='trunk'

	# always upgrade, as it is still buggy
	trunk upgrade
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-trunk "$@"
fi
