#!/usr/bin/env bash

# https://github.com/pemistahl/grex
# regexp builder

# https://github.com/pemistahl/grex/releases
# grex-v1.4.2-aarch64-apple-darwin.tar.gz
# grex-v1.4.2-x86_64-apple-darwin.tar.gz
# grex-v1.4.2-x86_64-pc-windows-msvc.zip
# grex-v1.4.2-x86_64-unknown-linux-musl.tar.gz

function setup_util_grex() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if is-needle --quiet "$@" && ! is-needle --upgrade "$@" && ! is-needle --uninstall "$@" && command-exists grex; then
		return 0
	fi

	# setup
	local arch options=(
		--cli='grex'
		"$@"
		BREW='grex'
		CARGO='grex'
		CHOCO='grex'
		SCOOP='grex'
	)
	function get_github_asset_url {
		github-download \
			--dry \
			--slug='pemistahl/grex' \
			--latest \
			--asset-filter="$(echo-escape-regex -- "$1")$" | echo-first-line || :
	}
	function add_download_option {
		options+=(
			DOWNLOAD="$(get_github_asset_url "$1")"
			DOWNLOAD_UNZIP_FILTER="$2"
		)
	}
	arch="$(get-arch)"
	if is-mac; then
		if test "$arch" = 'a64'; then
			add_download_option '-aarch64-apple-darwin.tar.gz' 'grex'
		elif test "$arch" = 'x64'; then
			add_download_option '-x86_64-apple-darwin.tar.gz' 'grex'
		fi
	elif is-linux; then
		if test "$arch" = 'x64'; then
			add_download_option '-x86_64-unknown-linux-musl.tar.gz' 'grex'
		fi
	elif is-wsl; then
		if test "$arch" = 'x64'; then
			add_download_option '-x86_64-pc-windows-msvc.zip' 'grex.exe'
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_grex "$@"
fi
