#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# [tealdeer](https://github.com/dbrgn/tealdeer)
# tldr alternative

# https://dbrgn.github.io/tealdeer/installing.html
# there are other options, but good luck trying to figure out what they are

env NAME='tealdeer' CLI='tldr' \
	AUR='tealdeer-bin' \
	BREW='tealdeer' \
	CARGO='tealdeer' \
	PKG='tealdeer' \
	setup-util
