#!/usr/bin/env bash

	# https://wiki.archlinux.org/title/transmission
	# https://help.ubuntu.com/community/TransmissionHowTo

function setup_util_transmission() (
	source "$DOROTHY/sources/util.bash"
	source "$(type -P setup-util)" # enable *_EVAL
	util_options=(
		--name='Transmission'
		--cli='transmission-daemon'
		# despite docs, the apt repo is outdated and is already inside official repos, so is not needed
		APT='transmission-cli' APT='transmission-common' APT='transmission-daemon'
		RECONFIGURE_EVAL='__reconfigure'
	)
	local service_title='Transmission'
	local service_ids=(
		'transmission-daemon'
	)
	local service_uninstall_paths=(
		# user config and data
		/var/lib/*'transmission-daemon'*
		# '/var/lib/transmission-daemon/info/settings.json'
		# '/var/lib/transmission-daemon/.config/transmission-daemon/settings.json'
	)
	function __reconfigure {
		# if missing, complete uninstall and exit
		if setup-util "${util_options[@]}" is-installed; then
			# remove service
			service-helper --remove -- \
				"${service_ids[@]}"

			# remove paths
			fs-remove --confirm --elevate -- "${service_uninstall_paths[@]}"

			# remove user
			if is-user -- debian-transmission; then
				eval-helper --elevate -- userdel debian-transmission
			fi

			# remove group
			if is-group -- debian-transmission; then
				eval-helper --elevate -- groupdel --force debian-transmission
			fi

			# all done for uninstall
			return 0
		fi

		# if installed, configure service if supported
		if service-helper --supported; then
			# verify the service was initialised
			if ! service-helper --exists -- "${service_ids[@]}"; then
				__print_error "$service_title was installed, however the service was not."
				return 1
			fi
		fi
	}

	# setup
	setup_util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_transmission "$@"
fi
