#!/usr/bin/env bash

# https://github.com/eza-community/eza
# ls alternative

# https://github.com/eza-community/eza/releases

# https://repology.org/project/eza/versions

function setup_util_eza() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=eza "$@"; then
		return 0
	fi

	# despite docs, no apk
	local arch options=(
		--cli='eza'
		"$@"
		APT_KEY='https://raw.githubusercontent.com/eza-community/eza/main/deb.asc'
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://deb.gierens.de stable main'
		APT='eza'
		AUR='eza'
		BREW='eza'
		CARGO='eza'
		NIX='eza' NIX_PROFILE='nixpkgs#eza'
		PORT='eza'
	)
	function __get_github_asset_url {
		local suffix="$1" regexp
		regexp="$(echo-escape-regexp -- "$suffix")$" || return $?
		github-download --dry --slug='eza-community/eza' --latest --asset-regexp="$regexp" | echo-first-line || return $? # don't use $ as version number is after the arch
	}
	function __add_download_option {
		local suffix="$1" file="$2" url
		url="$(__get_github_asset_url "$suffix")" || return $?
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB="$file"
		)
	}
	arch="$(__get_arch)"
	if __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option 'aarch64-unknown-linux-gnu.tar.gz' 'eza' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option 'x86_64-unknown-linux-musl.tar.gz' 'eza' || :
		fi
	elif __is_windows; then
		if [[ $arch == 'x64' ]]; then
			__add_download_option 'x86_64-pc-windows-gnu.zip' 'eza.exe' || :
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_eza "$@"
fi
