#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://deno.land/#installation
# https://github.com/denoland/deno_install

function setup-util-deno() (
	setup-util "$@" CLI='deno' \
		BREW='deno' \
		CARGO='deno' \
		CHOCO='deno' \
		INSTALLER='https://deno.land/x/install/install.sh' \
		PACMAN='deno' \
		PORT='deno' \
		SCOOP='deno' \
		SNAP='deno'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-deno "$@"
fi
