#!/usr/bin/env bash

function setup_util_krypton() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists krgpg; then
		return 0
	fi

	# setup
	local options=(
		--name='Krypton'
		--cli='krgpg'
		"$@"
		INSTALLER='https://krypt.co/kr'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_krypton "$@"
fi
