#!/usr/bin/env bash
# shellcheck disable=SC1091
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/splitlines.bash"
source "$DOROTHY/sources/config.sh"
load_dorothy_config 'editors.bash'

# NOTES
# Always use terminal editor for prompts as GUI editors are too slow

# prepare
export EDITOR

# load the env difference echo handling
# shellcheck disable=SC2034
shell="${1-}"
source "$DOROTHY/sources/env.bash"

# Set the editor configuration
export LC_CTYPE="${LC_CTYPE:-"en_US.UTF-8"}"

# Terminal Editor
if is-array-empty "${TERMINAL_EDITORS-[@]}"; then
	stderr echo "# cannot set terminal editor, as \$TERMINAL_EDITORS was undefined"
else
	for prompt in "${TERMINAL_EDITORS[@]}"; do
		name="${prompt%% *}"
		if command-exists "$name"; then
			export TERMINAL_EDITOR="$name"
			export TERMINAL_EDITOR_PROMPT="$prompt"
			EDITOR="$prompt"
			break
		fi
	done
fi

# GUI Editor
if is-array-empty "${GUI_EDITORS-[@]}"; then
	stderr echo "# cannot set gui editor, as \$GUI_EDITORS was undefined"
else
	for prompt in "${GUI_EDITORS[@]}"; do
		name="${prompt%% *}"
		if command-exists "$name"; then
			export GUI_EDITOR="$name"
			export GUI_EDITOR_PROMPT="$prompt"
			break
		fi
	done
fi

# check EDITOR was set
if test -z "$EDITOR"; then
	stderr echo "# EDITOR was not set, as TERMINAL_EDITORS had no values"
fi
