#!/usr/bin/env bash

# https://github.com/dalance/procs
# ps alternative

# https://github.com/dalance/procs/releases
# procs-0.14.0-1.x86_64.rpm
# procs-v0.14.0-x86_64-linux.zip
# procs-v0.14.0-x86_64-mac.zip
# procs-v0.14.0-x86_64-windows.zip

# https://repology.org/project/procs/versions

function setup_util_procs() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='procs'
		# no apt
		APK='procs'
		AUR='procs'
		BREW='procs'
		CARGO='procs'
		NIX='procs'
		RPM='procs'
		SCOOP='procs'
		SNAP='procs'
		ZYPPER='procs'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='dalance/procs' glob='procs' arch
	arch="$(__get_arch)"
	if __is_macos; then
		__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-mac.zip' "$glob" || :
	elif __is_linux; then
		if [[ $arch == 'x64' ]]; then
			__fetch_and_add_rpm_option_via_slug_suffix "$slug" '.x86_64.rpm' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-linux.zip' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_procs "$@"
fi
