#!/usr/bin/env bash

# https://askubuntu.com/a/38782/22776

function setup_linux_safegraphics() (
	source "$DOROTHY/sources/bash.bash"

	# assert compatibility
	if ! is-linux; then
		echo-style --stderr --notice="[$0] is only intended to be run on Linux systems, skipping."
		return 0
	fi

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Configure Linux with Safe Graphics.
			Useful for getting Ubuntu installed on a 2010 iMac.

			USAGE:
			setup-linux-safegraphics
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	echo-style --h1='Update GRUB with Safe Graphics'

	config-helper --elevate --file='/etc/default/grub' -- \
		--field='GRUB_CMDLINE_LINUX_DEFAULT' --no-quote --value='"quiet splash nomodeset"'

	grub-helper

	echo-style --g1='Update GRUB with Safe Graphics'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_linux_safegraphics "$@"
fi
