#!/usr/bin/env bash

# https://github.com/ytdl-org/youtube-dl

function setup_util_youtube_dl() (
	source "$DOROTHY/sources/bash.bash"

	# don't improve performance, as we want to ensure correct cli

	# only support uv, as others are buggy, so uninstall the rest
	local options=(
		--uninstall
		--quiet
		--name='youtube-dl'
		BREW='youtube-dl'
	)
	setup-util "${options[@]}"

	# only use uv
	options=(
		--cli='youtube-dl'
		--name='youtube-dl'
		"$@"
		UV='youtube-dl'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_youtube_dl "$@"
fi
