#!/usr/bin/env bash

# https://github.com/YS-L/csvlens?tab=readme-ov-file

# https://github.com/YS-L/csvlens/releases
# csvlens-aarch64-apple-darwin.tar.xz
# csvlens-aarch64-pc-windows-msvc.zip
# csvlens-aarch64-unknown-linux-gnu.tar.xz
# csvlens-x86_64-apple-darwin.tar.xz
# csvlens-x86_64-pc-windows-msvc.zip
# csvlens-x86_64-unknown-linux-gnu.tar.xz
# csvlens-x86_64-unknown-linux-musl.tar.xz

# https://repology.org/project/csvlens/versions

function setup_util_csvlens() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='csvlens'
		# despite docs, no apk
		AUR='csvlens'
		BREW='csvlens'
		BSD='csvlens'
		CARGO='csvlens'
		PKG='csvlens'
		PKGADD='csvlens'
		PKGIN='csvlens'
		SCOOP='csvlens'
		WINGET='csvlens'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='YS-L/csvlens' glob='*/csvlens' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-apple-darwin.tar.xz' "$glob" || :
		else
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-apple-darwin.tar.xz' "$glob" || :
		fi
	elif __is_linux; then
		if [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-unknown-linux-musl.tar.xz' "$glob" || :
		elif [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-unknown-linux-gnu.tar.xz' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_csvlens "$@"
fi
