#!/usr/bin/env bash
# shellcheck disable=SC2164
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/globstar.bash"
source "$DOROTHY/sources/nullglob.bash"
source "$DOROTHY/sources/arrays.bash"
requires_array_support 'mapfile'

# perform the act
cd "$DOROTHY"

# user/secrets may need sudo
echo-style --header 'correcting permissions...'
mapfile -t directories < <(find-directories)
commands=(
	"$DOROTHY/commands/"*
	"$DOROTHY/user/commands/"*
	"$DOROTHY/user/commands.local/"*
)
chmod-helper --changes --permissions='+rwx' -- "${directories[@]}" "${commands[@]}"

echo-style --header 'staging new files...'
# The following paths are ignored by one of your .gitignore files: ...
# hint: Use -f if you really want to add them.
# hint: Turn this message off by running
# hint: "git config advice.addIgnoredFile false"
ok silent git add --ignore-errors "$DOROTHY"/**

echo-style --header 'staging changed files...'
ok git add -u

echo-style --header 'removing junk...'
rm-junk
