#!/usr/bin/env bash

# https://github.com/XAMPPRocky/tokei
# code stats, wc alternative

# https://github.com/XAMPPRocky/tokei/releases
# tokei-aarch64-unknown-linux-gnu.tar.gz
# tokei-arm-linux-androideabi.tar.gz
# tokei-arm-unknown-linux-gnueabi.tar.gz
# tokei-armv7-linux-androideabi.tar.gz
# tokei-armv7-unknown-linux-gnueabihf.tar.gz
# tokei-i686-pc-windows-msvc.exe
# tokei-i686-unknown-linux-gnu.tar.gz
# tokei-i686-unknown-linux-musl.tar.gz
# tokei-mips-unknown-linux-gnu.tar.gz
# tokei-mips64-unknown-linux-gnuabi64.tar.gz
# tokei-mips64el-unknown-linux-gnuabi64.tar.gz
# tokei-mipsel-unknown-linux-gnu.tar.gz
# tokei-powerpc64-unknown-linux-gnu.tar.gz
# tokei-powerpc64le-unknown-linux-gnu.tar.gz
# tokei-s390x-unknown-linux-gnu.tar.gz
# tokei-sparcv9-sun-solaris.tar.gz
# tokei-x86_64-apple-darwin.tar.gz
# tokei-x86_64-pc-windows-msvc.exe
# tokei-x86_64-unknown-linux-gnu.tar.gz
# tokei-x86_64-unknown-linux-musl.tar.gz
# tokei-x86_64-unknown-netbsd.tar.gz

function setup_util_tokei() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='tokei'
		--cli='tokei'
		# no apt
		APK='tokei'
		AUR='tokei'
		BREW='tokei'
		BSD='tokei'
		CARGO='tokei'
		CONDA_CHANNEL='conda-forge'
		CONDA='tokei'
		NIX='tokei'
		PORT='tokei'
		RPM='tokei'
		SCOOP='tokei'
		ZYPPER='tokei'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='XAMPPRocky/tokei' glob='tokei' arch
	arch="$(__get_arch)"
	if __is_macos; then
		__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-apple-darwin.tar.gz' "$glob" || :
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-unknown-linux-gnu.tar.gz' "$glob" || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-arm-unknown-linux-gnueabi.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-unknown-linux-musl.tar.gz' "$glob" || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-i686-unknown-linux-musl.tar.gz' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_tokei "$@"
fi
