#!/usr/bin/env bash

# https://github.com/vinceliuice/WhiteSur-gtk-theme

function setup_util_whitesur() (
	source "$DOROTHY/sources/util.bash"
	source "$(type -P setup-util)" # CUSTOM_INSTALL_EVAL CUSTOM_UNINSTALL_EVAL
	util_options=(
		--name='WhiteSur GTK Theme'
		CUSTOM_INSTALL_EVAL='__whitesur_install'
		CUSTOM_UNINSTALL_EVAL='__whitesur_uninstall'
	)
	function __whitesur_sync {
		local root
		root="$(fs-make --root="$DOROTHY/state" --directory='setup-util-whitesur')" || return $?
		cd "$root" || return $?
		git-helper sync --url='https://github.com/vinceliuice/WhiteSur-gtk-theme.git' --depth=1 || return $?
	}
	function __whitesur_install() (
		__whitesur_sync || return $?
		./install.sh || return $?
	)
	function __whitesur_uninstall() (
		__whitesur_sync || return $?
		./install.sh --uninstall || return $?
	)
	setup_util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_whitesur "$@"
fi
