#!/usr/bin/env bash

# https://github.com/charmbracelet/gum#installation
# Make sure to tap [Show all 35 assets]

# https://github.com/charmbracelet/gum/releases
# gum-0.11.0.aarch64.rpm
# gum-0.11.0.armv7hl.rpm
# gum-0.11.0.i386.rpm
# gum-0.11.0.tar.gz
# gum-0.11.0.x86_64.rpm
# gum_0.11.0_aarch64.apk
# gum_0.11.0_amd64.deb
# gum_0.11.0_arm64.deb
# gum_0.11.0_armhf.deb
# gum_0.11.0_armv7.apk
# gum_0.11.0_Darwin_arm64.tar.gz
# gum_0.11.0_Darwin_x86_64.tar.gz
# gum_0.11.0_Freebsd_arm.tar.gz
# gum_0.11.0_Freebsd_arm64.tar.gz
# gum_0.11.0_Freebsd_i386.tar.gz
# gum_0.11.0_Freebsd_x86_64.tar.gz
# gum_0.11.0_i386.deb
# gum_0.11.0_Linux_arm.tar.gz
# gum_0.11.0_Linux_arm64.tar.gz
# gum_0.11.0_Linux_i386.tar.gz
# gum_0.11.0_Linux_x86_64.tar.gz
# gum_0.11.0_Netbsd_arm.tar.gz
# gum_0.11.0_Netbsd_i386.tar.gz
# gum_0.11.0_Netbsd_x86_64.tar.gz
# gum_0.11.0_Openbsd_arm.tar.gz
# gum_0.11.0_Openbsd_arm64.tar.gz
# gum_0.11.0_Openbsd_i386.tar.gz
# gum_0.11.0_Openbsd_x86_64.tar.gz
# gum_0.11.0_Windows_i386.zip
# gum_0.11.0_Windows_x86_64.zip
# gum_0.11.0_x86.apk
# gum_0.11.0_x86_64.apk

# rpm repo support requires the following, which isn't important as they provide .rpm files anyway
# printf '%s\n' '[charm]
# name=Charm
# baseurl=https://repo.charm.sh/yum/
# enabled=1
# gpgcheck=1
# gpgkey=https://repo.charm.sh/yum/gpg.key' | echo-write -- /etc/yum.repos.d/charm.repo
# sudo yum install gum

function setup_util_gum() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='gum'
		APK='gum'
		APT_KEY='https://repo.charm.sh/apt/gpg.key'
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://repo.charm.sh/apt/ * *'
		AUR='gum'
		BREW='gum'
		GO='github.com/charmbracelet/gum'
		NIX='nixpkgs.gum'
		PKG='gum'
		PORT='gum'
		SCOOP='charm-gum'
		WINGET='charmbracelet.gum'
		XBPS='gum'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='charmbracelet/gum' glob='gum' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '_Darwin_arm64.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '_Darwin_x86_64.tar.gz' "$glob" || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_apk_option_via_slug_suffix "$slug" '_aarch64.apk' || :
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_arm64.deb' || :
			__fetch_and_add_rpm_option_via_slug_suffix "$slug" '.aarch64.rpm' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '_Linux_arm64.tar.gz' "$glob" || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_apk_option_via_slug_suffix "$slug" '_armv7.apk' || :
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_armhf.deb' || :
			__fetch_and_add_rpm_option_via_slug_suffix "$slug" '.armv7hl.rpm' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '_Linux_arm.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_apk_option_via_slug_suffix "$slug" '_x86_64.apk' || :
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_amd64.deb' || :
			__fetch_and_add_rpm_option_via_slug_suffix "$slug" '.x86_64.rpm' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '_Linux_x86_64.tar.gz' "$glob" || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_apk_option_via_slug_suffix "$slug" '_x86.apk' || :
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_i386.deb' || :
			__fetch_and_add_rpm_option_via_slug_suffix "$slug" '.i386.rpm' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '_Linux_i386.tar.gz' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_gum "$@"
fi
