#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/gnome-software/filelist
# /usr/bin/gnome-software

function setup_util_gnome_software() (
	source "$DOROTHY/sources/bash.bash"

	# checks
	if ! is-gnome; then
		__print_style --stderr --notice="[$0] is for Linux systems with [gnome] installed, skipping." || return
		return 0
	fi

	# setup
	local options=(
		--name='Gnome Software'
		--cli='gnome-software'
		"$@"
		APT='gnome-software' # UBUNTU
		AUR='gnome-software' # ARCH
	)
	setup-util "${options[@]}" || return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_gnome_software "$@"
fi
