#!/usr/bin/env bash

function setup_bin_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- setup-bin --help
)

function setup_bin() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			For Applications you already have installed, expose their binaries to \`PATH\` by symlinks inside \`XDG_BIN_HOME\`.

			USAGE:
			setup-bin
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =====================================
	# Helpers

	# prepare
	__print_style --h1='Setup Binaries'

	# symlink_app <app> ...[<existing> <symlink>]
	function symlink_app {
		local app path existing symlink
		# get the app
		app="$1"
		shift
		# get the path
		path="$(get-app --quiet -- "$app" || :)"
		if [[ -n $path && -d $path ]]; then
			# create a symlink for each bin
			while [[ $# -ne 0 ]]; do
				existing="$path/$1"
				shift
				symlink="$XDG_BIN_HOME/$1"
				shift
				if [[ -x $existing ]]; then
					fs-link --existing="$existing" --symlink="$symlink"
				fi
			done
		fi
	}

	# =====================================
	# Binaries

	# Atom
	symlink_app 'Atom.app' \
		'Contents/Resources/app/atom.sh' 'atom' \
		'Contents/Resources/app/apm/bin/apm' 'apm'

	# Visual Studio Code - Insiders
	symlink_app 'Visual Studio Code - Insiders.app' \
		'Contents/Resources/app/bin/code' 'code'

	# Visual Studio Code - Flatpak
	if __command_exists -- flatpak && flatpak info com.visualstudio.code &>/dev/null; then
		cat <<-EOF >"$XDG_BIN_HOME/code"
			#!/usr/bin/env bash
			flatpak run com.visualstudio.code "\$@"
		EOF
		fs-own --x -- "$XDG_BIN_HOME/code"
	fi

	# Visual Studio Code
	symlink_app 'Visual Studio Code.app' \
		'Contents/Resources/app/bin/code' 'code'

	# GitHub
	symlink_app 'GitHub.app' \
		'Contents/MacOS/github_cli' 'github'

	# Tower
	symlink_app 'Tower.app' \
		'Contents/MacOS/gittower' 'tower'

	# GitFox
	symlink_app 'Gitfox.app' \
		'Contents/SharedSupport/bin/gitfox-cli' 'gitfox'

	# Kaleidoscope
	symlink_app 'Kaleidoscope.app' \
		'Contents/Resources/bin/ksdiff' 'ksdiff'

	# =====================================
	# Remove broken symlinks

	local bins=() bin missing=() remove=()
	__split --target={bins} --no-zero-length --invoke -- \
		echo-subpaths -- "$XDG_BIN_HOME"
	for bin in "${bins[@]}"; do
		if [[ ! -e $bin ]]; then
			missing+=("$bin")
		fi
	done
	for bin in "${missing[@]}"; do
		if is-broken-symlink -- "$bin"; then
			remove+=("$bin")
		fi
	done
	if [[ ${#remove[@]} -ne 0 ]]; then
		eval-helper \
			--pending="$(__print_style --notice='Removing broken symlinks:')" \
			--success="$(__print_style --success='Removed broken symlinks.')" \
			--failure="$(__print_style --error='Failed to remove broken symlinks.')" \
			-- rm -v -- "${remove[@]}" # fs-remove is too verbose
	fi

	# =====================================
	# Permissions

	# gsed symlink requires sudo
	# [stat  -c %U "$(fs-path --resolve "$XDG_BIN_HOME/gsed")"] returns [root] however that is so involved for this check
	fs-own --x -- "$XDG_BIN_HOME/"* || :

	# =====================================
	# Done

	__print_style --g1='Setup Binaries'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		setup_bin_test
	else
		setup_bin "$@"
	fi
fi
