#!/usr/bin/env bash

# https://github.com/nushell/nushell
# https://github.com/nushell/nushell/issues/9999

# https://github.com/nushell/nushell/releases
# nu-0.108.0-aarch64-apple-darwin.tar.gz
# nu-0.108.0-aarch64-pc-windows-msvc.msi
# nu-0.108.0-aarch64-pc-windows-msvc.zip
# nu-0.108.0-aarch64-unknown-linux-gnu.tar.gz
# nu-0.108.0-aarch64-unknown-linux-musl.tar.gz
# nu-0.108.0-armv7-unknown-linux-gnueabihf.tar.gz
# nu-0.108.0-armv7-unknown-linux-musleabihf.tar.gz
# nu-0.108.0-loongarch64-unknown-linux-gnu.tar.gz
# nu-0.108.0-loongarch64-unknown-linux-musl.tar.gz
# nu-0.108.0-riscv64gc-unknown-linux-gnu.tar.gz
# nu-0.108.0-x86_64-apple-darwin.tar.gz
# nu-0.108.0-x86_64-pc-windows-msvc.msi
# nu-0.108.0-x86_64-pc-windows-msvc.zip
# nu-0.108.0-x86_64-unknown-linux-gnu.tar.gz
# nu-0.108.0-x86_64-unknown-linux-musl.tar.gz

# https://repology.org/project/nushell/versions

function setup_util_nu() (
	source "$DOROTHY/sources/bash.bash"

	# options
	local option_reconfigure='yes'
	__flag --target={option_reconfigure} --name='reconfigure' --affirmative --coerce -- "$@"

	# nushell requires all sources files to exist ahead of time
	function __write_state_config {
		local file="$1" method="$2" target="$3"
		# if the target exist and is a non-em,pty file, then source it
		if [[ -n $target && -s $target ]]; then
			# source it
			local escaped
			escaped="$(echo-quote -- "$target")" || return
			cat <<-EOF >"$file" || return
				#!/usr/bin/env nu
				$method $escaped
			EOF
		else
			# otherwise just be empty
			cat <<-EOF >"$file" || return
				#!/usr/bin/env nu
			EOF
		fi
	}
	function __reconfigure {
		# if reconfigure is not desired, or if not installed, then don't reconfigure
		if [[ $option_reconfigure == 'no' ]] || __command_missing -- nu; then
			return 0
		fi

		# ensure nushell configuration directory exists
		local config_dir
		config_dir="$(nu -c 'echo $nu.default-config-dir')" || return
		fs-mkdir -- "$config_dir" || return

		# ensure [themes/starship.nu] works
		fs-mkdir -- "$XDG_STATE_HOME/starship" || return
		if __command_exists -- starship; then
			starship init nu >"$XDG_STATE_HOME/starship/init.nu" || return
		else
			fs-remove --quiet --no-confirm -- "$XDG_STATE_HOME/starship/init.nu" || return
		fi
		__write_state_config "$DOROTHY/state/sources/starship.nu" 'use' "$XDG_STATE_HOME/starship/init.nu" || return

		# ensure [sources/autocomplete.nu] works
		fs-mkdir -- "$XDG_STATE_HOME/carapace" || return
		if __command_exists -- carapace; then
			carapace _carapace nushell >"$XDG_STATE_HOME/carapace/init.nu" || return
		else
			fs-remove --quiet --no-confirm -- "$XDG_STATE_HOME/carapace/init.nu" || return
		fi
		__write_state_config "$DOROTHY/state/sources/carapace.nu" 'source' "$XDG_STATE_HOME/carapace/init.nu" || return

		# ensure [(config|config.local)/interactive.nu] works
		local file files=(
			'interactive.nu'
		)
		local dir dirs=(
			'config.local'
			'config'
		)
		for file in "${files[@]}"; do
			# scaffold configuration files if the user is setup and has configuration directories
			if [[ -d "$DOROTHY/user/config" ]]; then
				# user configuration exists, scaffold the config.local file
				if [[ -d "$DOROTHY/user/config.local" && ! -f "$DOROTHY/user/config.local/$file" ]]; then
					cat <<-EOF >"$DOROTHY/user/config.local/$file" || return
						#!/usr/bin/env nu

						# load my public configuration
						source ../config/$file
					EOF
				fi
				# user configuration exists, scaffold the config file
				if [[ ! -f "$DOROTHY/user/config/$file" ]]; then
					cat <<-EOF >"$DOROTHY/user/config/$file" || return
						#!/usr/bin/env nu

						# load the dorothy defaults
						source ~/.local/share/dorothy/config/$file
					EOF
					# ^ this should load in a way that is cross-os compatible, hence [source ~/...] instead of interpolating [source $DOROTHY/...]
				fi
			fi

			# enable or disable the configuration files, based on their existence
			for dir in "${dirs[@]}"; do
				__write_state_config "$DOROTHY/state/$dir/$file" 'source' "$DOROTHY/user/$dir/$file" || return
				# ^ as this is local to the machine, it doesn't need to be cross-os compatible
			done
		done
	}

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=nu "$@"; then
		__reconfigure
		return 0
	fi

	# setup
	# rpm/fedora is outdated
	local arch options=(
		--name='Nushell'
		--cli='nu'
		"$@"
		APK='nushell' # ALPINE
		AUR='nushell' # ARCH
		BREW='nushell'
		CARGO='nu'
		CHOCO='nushell'
		DNF_REPO='https://yum.fury.io/nushell/' # Fedora, AlmaLinux, RedHat, Rocky
		DNF='nushell'
		EMERGE='app-shells/nushell' # GENTOO
		NIX='nushell'
		EOPKG='nushell' # SOLUS
		NODE='nushell'
		SCOOP='nu'
		WINGET='nushell'
		ZYPPER='nushell' # SUSE
	)
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return
		github-download --dry --slug='nushell/nushell' --latest --asset-regexp="$regexp" | echo-first-line || return
	}
	function __add_download_option {
		local url
		url="$(__get_github_asset_url "$1")" || return
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB="*/$2"
		)
	}
	arch="$(get-arch)"
	if is-mac; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-apple-darwin.tar.gz' 'nu' || :
		else
			__add_download_option '-x86_64-apple-darwin.tar.gz' 'nu' || :
		fi
	elif is-linux; then # includes wsl
		if [[ $arch == 'r64' ]]; then
			__add_download_option '-riscv64gc-unknown-linux-gnu.tar.gz' 'nu' || :
		elif [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-unknown-linux-musl.tar.gz' 'nu' || :
		elif [[ $arch == 'a32' ]]; then
			__add_download_option '-armv7-unknown-linux-musleabihf.tar.gz' 'nu' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-unknown-linux-musl.tar.gz' 'nu' || :
		fi
	elif is-windows; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-pc-windows-msvc.zip' 'nu.exe' || : # uses windows config, rather than wsl config
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-pc-windows-msvc.zip' 'nu.exe' || : # uses windows config, rather than wsl config
		fi
	fi
	setup-util "${options[@]}"
	# .msi failed with: This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package.
	#
	# function add_installer_option {
	# 	options+=(
	# 		INSTALLER="$(__get_github_asset_url "$1")"
	# 		INSTALLER_OPEN=yes
	# 	)
	# }
	# add_installer_option '-aarch64-pc-windows-msvc.msi'
	# add_installer_option '-x86_64-pc-windows-msvc.msi'

	# finish
	__reconfigure
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_nu "$@"
fi
