#!/usr/bin/env bash

# https://mediaarea.net
# https://mediaarea.net/en/MediaInfo
# https://mediaarea.net/en/MediaInfo/Download
# https://mediaarea.net/en/MediaInfo/Download/Mac_OS <-- is a .dmg that is then a .pkg that then install the cli
# https://repology.org/project/mediainfo/versions
# https://mediaarea.net/en/Repos

function setup_util_mediainfo() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='MediaInfo'
		--cli='mediainfo'
		--app='MediaInfo'
		APK='mediainfo'
		APT='mediainfo'
		AUR='mediainfo'
		BREW='media-info'
		EMERGE='media-video/mediainfo'
		FLATPAK_REPO='https://flathub.org/repo/flathub.flatpakrepo'
		FLATPAK='net.mediaarea.MediaInfo'
		NIX='mediainfo'
		RPM='mediainfo'
		URPMI='mediainfo'
		XBPS='mediainfo-cli'
		ZYPPER='mediainfo'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# handle the repository
	# https://mediaarea.net/en/Repos
	if is-system --deb; then
		setup-util --optional --quiet --name='MediaInfo APT Repository' DEB='https://mediaarea.net/repo/deb/repo-mediaarea_1.0-26_all.deb' "${setup_options[@]}"
	fi
	if is-system --rpm; then
		setup-util --optional --quiet --name='MediaInfo RPM Repository' RPM='https://mediaarea.net/repo/rpm/releases/repo-MediaArea-1.0-26.noarch.rpm' "${setup_options[@]}"
	fi

	# fetch and use configuration
	local arch
	arch="$(__get_arch)"
	if __is_linux; then
		if [[ $arch == 'x64' ]]; then
			util_options+=(
				SNAP='https://mediaarea.net/download/binary/mediainfo/25.09/mediainfo_25.09_amd64.snap'
				APPIMAGE='https://mediaarea.net/download/binary/mediainfo/20.09/mediainfo-20.09.glibc2.3-x86_64.AppImage'
			)
		elif [[ $arch == 'x32' ]]; then
			util_options+=(
				SNAP='https://mediaarea.net/download/binary/mediainfo/25.03/mediainfo_25.03_i386.snap'
				APPIMAGE='https://mediaarea.net/download/binary/mediainfo/20.09/mediainfo-20.09.glibc2.3-i686.AppImage'
			)
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_mediainfo "$@"
fi
