#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-python() (
	# python2
	setup-util "$@" --cli='python' \
		APK='python' \
		APT='python' \
		BREW='python' \
		PACMAN='python' \
		YUM='python'

	# python3
	setup-util "$@" --cli='python3' \
		APK='python3' \
		APT='python3' \
		BREW='python3' \
		PACMAN='python3' \
		YUM='python3'

	# pipx dependencies for linux, not macos
	if is-linux; then
		setup-util "$@" --optional --name='python3-venv' \
			APT='python3-venv' \
			PACMAN='python-virtualenv'
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-python "$@"
fi
