#!/usr/bin/env bash

# dnscrypt-proxy
# https://github.com/DNSCrypt/dnscrypt-proxy/releases
# dnscrypt-proxy-android_arm-2.1.5.zip
# dnscrypt-proxy-android_arm64-2.1.5.zip
# dnscrypt-proxy-android_i386-2.1.5.zip
# dnscrypt-proxy-android_x86_64-2.1.5.zip
# dnscrypt-proxy-dragonflybsd_amd64-2.1.5.tar.gz
# dnscrypt-proxy-freebsd_amd64-2.1.5.tar.gz
# dnscrypt-proxy-freebsd_arm-2.1.5.tar.gz
# dnscrypt-proxy-freebsd_i386-2.1.5.tar.gz
# dnscrypt-proxy-linux_arm-2.1.5.tar.gz
# dnscrypt-proxy-linux_arm64-2.1.5.tar.gz
# dnscrypt-proxy-linux_i386-2.1.5.tar.gz
# dnscrypt-proxy-linux_mips-2.1.5.tar.gz
# dnscrypt-proxy-linux_mips64-2.1.5.tar.gz
# dnscrypt-proxy-linux_mips64le-2.1.5.tar.gz
# dnscrypt-proxy-linux_mipsle-2.1.5.tar.gz
# dnscrypt-proxy-linux_riscv64-2.1.5.tar.gz
# dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz
# dnscrypt-proxy-macos_arm64-2.1.5.zip
# dnscrypt-proxy-macos_x86_64-2.1.5.zip
# dnscrypt-proxy-netbsd_amd64-2.1.5.tar.gz
# dnscrypt-proxy-netbsd_i386-2.1.5.tar.gz
# dnscrypt-proxy-openbsd_amd64-2.1.5.tar.gz
# dnscrypt-proxy-openbsd_i386-2.1.5.tar.gz
# dnscrypt-proxy-solaris_amd64-2.1.5.tar.gz
# dnscrypt-proxy-win32-2.1.5.zip
# dnscrypt-proxy-win64-2.1.5.zip

function setup_util_dnscrypt_proxy() (
	source "$DOROTHY/sources/bash.bash"
	setup-dns --service='dnscrypt-proxy' "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_dnscrypt_proxy "$@"
fi
