#!/usr/bin/env bash

# https://www.nerdfonts.com/font-downloads
# https://github.com/ryanoasis/nerd-fonts/releases

function setup_util_nerd_fonts() (
	source "$DOROTHY/sources/bash.bash"

	# don't improve performance, as we prompt the user for which fonts to install
	# so currently don't have the ability to check that the prompted font is installed or not
	# that would require say a CASK_SEARCH arg, or accepting multiple --font args

	# if brew, prompt for casks
	if __is_brew; then
		local available_ids=() selected_ids=() id
		function __get_font_identifiers {
			brew search --cask --quiet '/-nerd-font$/' | echo-regexp -ong --regexp='font-(.+?)-nerd-font' --replace='$1' || return
		}
		__split --target={available_ids} --no-zero-length --invoke -- \
			__get_font_identifiers
		__split --target={selected_ids} --no-zero-length --invoke -- \
			choose --linger --confirm --multi --question='Which Nerd Fonts?' -- "${available_ids[@]}"
		for id in "${selected_ids[@]}"; do
			setup-util --font="$id" "$@" \
				CASK="font-$id-nerd-font"
		done
	else
		# otherwise prompt for tars
		# need to avoid FontPatcher.zip asset
		local available_assets=() available_ids=() selected_indices=() asset id index
		__split --target={available_assets} --no-zero-length --invoke -- \
			github-download --dry --slug='ryanoasis/nerd-fonts' --latest --asset-regexp='\.tar\.xz$' --archive-glob='*.{otf,ttf}'
		for asset in "${available_assets[@]}"; do
			id="$(echo-regexp -o --regexp='([^/]+?)[.]tar[.]xz$' --replace='$1'-- "$asset")"
			available_ids+=("$id")
		done
		__split --target={selected_indices} --no-zero-length --invoke -- \
			choose --linger --confirm --multi --question='Which Nerd Fonts?' --index -- "${available_ids[@]}"

		# only install these if installing, we also do uninstall remember
		for index in "${selected_indices[@]}"; do
			asset="${available_assets[index]}"
			id="${available_ids[index]}"
			setup-util --font="$id" "$@" \
				DOWNLOAD="$asset" \
				DOWNLOAD_ARCHIVE_GLOB='**/*.{otf,ttf}'
		done
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_nerd_fonts "$@"
fi
