#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# [bottom](https://github.com/ClementTsang/bottom)
# top alternative

env CLI=btm \
	BREW='clementtsang/bottom/bottom' \
	CARGO=bottom \
	DNF_COPR='atim/bottom' \
	DNF=bottom \
	EOPKG=bottom \
	NIX=bottom \
	PORT=bottom \
	SCOOP=bottom \
	WINGET=bottom \
	YAY='bottom-bin' \
	EMERGE_EVAL='
		sudo eselect repository enable guru
		sudo emerge --sync guru
		echo "sys-process/bottom" | sudo tee /etc/portage/package.accept_keywords/10-guru
		sudo emerge sys-process/bottom::guru
	' \
	setup-util
