#!/usr/bin/env bash

# https://www.flatpak.org/setup/Ubuntu/
# https://wiki.manjaro.org/index.php/Flatpak

function setup-util-flatpak() (
	source "$DOROTHY/sources/strict.bash"

	# check for linux
	if ! is-linux; then
		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
		return 0
	fi
	if is-headless; then
		echo-style --notice="[$0] is only intended to be run on desktop Linux systems, skipping." >/dev/stderr
		return 0
	fi

	# install flatpak
	# despite docs, no apk
	setup-util "$@" --name='Flatpak' --cli='flatpak' \
		APT='flatpak' \
		AUR='flatpak' \
		RPM='flatpak' \
		ZYPPER='flatpak'

	# capture exit from --optional and --confirm
	if ! command-exists flatpak; then
		return 0
	fi

	# log start
	echo-segment --h2='Configure flatpak'

	# install sources
	sudo-helper -- flatpak remote-add --if-not-exists flathub \
		'https://flathub.org/repo/flathub.flatpakrepo'
	# ^ sudo with flatpak avoids gui sudo prompt

	# install flatpak support for gnome-software (if it exists)
	if is-apt && command-exists gnome-software; then
		setup-util "$@" --optional --name='Flatpak via Gnome Software' \
			APT='gnome-software-plugin-flatpak'
	fi

	# log success
	echo-segment --g2='Configure flatpak'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-flatpak "$@"
fi
