#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://micro-editor.github.io
# https://github.com/zyedidia/micro

env CLI='micro' \
	APT='micro' \
	BREW='micro' \
	CHOCO='micro' \
	CURL='https://getmic.ro' \
	DNF='micro' \
	EGET='zyedidia/micro' \
	EOPKG='micro' \
	PACMAN='micro' \
	PKGADD='micro' \
	PORT='micro' \
	SCOOP='micro' \
	SNAP='micro --classic' \
	setup-util
