#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/XAMPPRocky/tokei
# code stats, wc alternative

env NAME='tokei' CLI=tokei \
	APK=tokei \
	BREW=tokei \
	CARGO=tokei \
	CONDA_CHANNEL='conda-forge' \
	CONDA=tokei \
	DNF=tokei \
	NIX=tokei \
	PACMAN=tokei \
	PKG=tokei \
	PKGIN=tokei \
	PORT=tokei \
	SCOOP=tokei \
	ZYPPER=tokei \
	setup-util
