#!/usr/bin/env bash

function setup_util_brew() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check=is-brew; then
		return 0
	fi

	# environment provides:
	# HOMEBREW_ARCH (macos), HOMEBREW_PREFIX (macosl, linux)
	if [[ -z "${HOMEBREW_PREFIX-}" ]]; then
		echo-error --bold='setup-util-brew: cannot setup brew because HOMEBREW_PREFIX is missing, this could be due to:' --newline \
			'- homebrew is only supported on macOS and Windows' --newline \
			'- this command was executed before Dorothy could configure the shell environment, this most likely occured because a Dorothy maintainer invoked a dorothy command within the dorothy install process'
		env
		return 6 # ENXIO 6 Device not configured
	fi

	# enable EVAL_INSTALL, etc
	source "$(type -P setup-util)"

	# uninstall brew, and adapt the system accordingly
	function brew_uninstall {
		local remove removals=(
			"$HOMEBREW_PREFIX"/*
			/usr/local/*
			/opt/homebrew/*
		)

		# reconfigure shells for the lack of brew, by trimming the brew shells
		grep --invert-match --fixed-strings --regexp="$HOMEBREW_PREFIX" /etc/shells | echo-wait --sudo /etc/shells

		# set the default shell to a non-brew shell
		setup-shell --no-brew

		# reset anything that depends on brew
		setup-dns system || :
		setup-git || :

		# uninstall brew
		if __is_brew; then
			if [[ -n "${HOMEBREW_ARCH-}" ]]; then
				arch -"$HOMEBREW_ARCH" \
					/bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force
			else
				/bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force
			fi
		fi

		# remove any leftover directories
		for remove in "${removals[@]}"; do
			if [[ -n "$remove" && -e "$remove" ]]; then
				fs-rm --quiet --no-confirm --sudo -- "$remove" || :
			fi
		done
	}

	# recomended installation method, it is pretty much the only one that works properly
	# https://github.com/bevry/dorothy/commit/fff6fbc079aaa6ab9bb8438e02c307ebad46fd75
	# https://github.com/bevry/dorothy/commit/69dbbe81bf30f9e0d9a1dd1d00eca3f3c88b943b
	function brew_install {
		if [[ -n "${HOMEBREW_ARCH-}" ]]; then
			arch "-${HOMEBREW_ARCH}" \
				/bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		else
			/bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		fi
		source "$DOROTHY/sources/environment.sh" # child processes will also inherit these changes
	}

	# ugprade brew
	function brew_upgrade {
		if __is_brew; then
			brew update
		else
			brew_install
		fi
	}

	# setup
	local options=(
		--cli='brew'
		"$@"
		EVAL_INSTALL='brew_install'
		EVAL_UPGRADE='brew_upgrade'
		EVAL_UNINSTALL='brew_uninstall'
	)
	setup_util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_brew "$@"
fi
