#!/usr/bin/env bash

# https://wiki.manjaro.org/index.php/Snap
# https://packages.ubuntu.com/bionic/gnome/gnome-software-plugin-snap
# https://snapcraft.io/docs/installing-snap-on-opensuse
# https://software.opensuse.org/download/package?package=snapd&project=system:snappy
# https://en.opensuse.org/Snap <-- this is the correct info
# https://software.opensuse.org/download/package?package=snapd&project=system:snappy <-- this is not correct

# https://packages.debian.org/sid/amd64/snapd/filelist
# /usr/bin/snap
# /usr/bin/snapctl
# /usr/bin/ubuntu-core-launcher

function setup_util_snap() (
	source "$DOROTHY/sources/bash.bash"

	# checks
	if ! is-linux; then
		__print_style --stderr --notice="[$0] is only intended to be run on Linux systems, skipping." || return
		return 0
	fi

	# setup
	local options=(
		--name='snap'
		--cli='snap'
		"$@"
		APT='snapd' # UBUNTU
		AUR='snapd' # ARCH
		RPM='snapd' # FEDORA
		ZYPPER_REPO_ALIAS='snappy'
		ZYPPER_REPO="https://download.opensuse.org/repositories/system:snappy/$(get-opensuse-release 2>/dev/null || :)/"
		ZYPPER='snapd' # SUSE
	)
	setup-util "${options[@]}" || return

	# if installed, configure
	if is-snap; then
		# log start
		__print_style --h2='Configure snap' || return

		# ensure snap is discoverable to the system
		if is-not-directory -- /snap; then
			fs-link --elevate \
				--symlink='/snap' --existing='/var/lib/snapd/snap' || return
		fi

		# ensure snap service is running
		if service-helper --supported; then
			service-helper --enable --start -- snapd.socket snapd.apparmor || return
		fi

		# install snap support for gnome-software (if it exists)
		if __command_exists -- gnome-software; then
			# PAMAC='gnome-software-snap' \
			# Error: target not found: gnome-software-snap
			setup-util --optional --name='Snap via Gnome Software' "$@" \
				APT='gnome-software-plugin-snap' || return
		fi

		# log success
		__print_style --g2='Configure snap' || return
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_snap "$@"
fi
