#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/strict.bash"

# check
if ! is-apk; then
	exit 0
fi

# user
if is-present "${APK_INSTALL-}"; then
	apk add "${APK_INSTALL[@]}"
fi
