#!/usr/bin/env bash

# https://www.flatpak.org/setup/Ubuntu/
# https://wiki.manjaro.org/index.php/Flatpak

# https://packages.debian.org/sid/amd64/flatpak/filelist
# /usr/bin/flatpak

function setup_util_flatpak() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='Flatpak'
		--cli='flatpak'
		# despite docs, no apk
		APT='flatpak'
		AUR='flatpak'
		RPM='flatpak'
		ZYPPER='flatpak'
		RECONFIGURE_INSTALL_EVAL='__reconfigure'
	)
	function __reconfigure {
		# setup flatpak support for gnome-software (if it exists)
		if is-system --apt && __command_exists -- gnome-software; then
			local util_options=(
				--optional
				--name='Flatpak via Gnome Software'
				APT='gnome-software-plugin-flatpak'
			)
			setup-util dependency "${util_options[@]}"
		fi

		# if installed, then configure
			# log start
		__print_style --h2='Configure flatpak'

		# install sources
		eval-helper --elevate -- flatpak remote-add --if-not-exists flathub \
			'https://flathub.org/repo/flathub.flatpakrepo'
		# ^ sudo with flatpak avoids gui sudo prompt

		# log success
		__print_style --g2='Configure flatpak'
	}

	# checks
	if ! __is_linux; then
		__print_style --stderr --notice="[$0] is only intended to be run on Linux systems, skipping."
		return 0
	fi
	if is-system --headless; then
		__print_style --stderr --notice="[$0] is only intended to be run on desktop Linux systems, skipping."
		return 0
	fi

	# setup
	setup_util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_flatpak "$@"
fi
