#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/globstar.bash"
source "$DOROTHY/sources/nullglob.bash"
if test "$NULLGLOB" = 'no' -o "$GLOBSTAR" = 'no'; then
	exit 1
fi

# perform the act
cd "$DOROTHY" || exit 1

echo 'correcting permissions...'
chmod -f +rwx ./**
chmod -f -x ./**/*.md ./sources/*.* ./user/**/*.*
chmod -f +x ./**/commands/*

echo 'stage new files...'
ok silent git add --ignore-errors ./**

echo 'stage changed files...'
ok git add -u

echo 'unstage sensitive files...'
# prevent [git add ./*.sh] from adding [env.*] if it exists
mkdir -p ./user/env
silent git rm --ignore-unmatch --cached -r ./**/env/
silent git rm --ignore-unmatch --cached ./**/env.*

echo 'removing junk...'
rm-junk
