#!/usr/bin/env bash

# https://zsh.sourceforge.io

# https://packages.debian.org/sid/amd64/zsh/filelist
# /bin/rzsh
# /bin/zsh
# /bin/zsh5

function setup_util_zsh() (
	source "$DOROTHY/sources/bash.bash"

	function do_configure {
		# https://zsh.sourceforge.io/Intro/intro_3.html
		# [.zshenv] needs to be in [$HOME] but all others inside [$ZDOTDIR]
		# [$ZDOTDIR] guaranteed by [setup-environment-commands]
		__mkdirp "$ZDOTDIR" # required for opensuse
		fs-move -- "$ZDOTDIR/.zshenv" "$HOME/.zshenv"
		fs-move -- "$HOME/.zprofile" "$ZDOTDIR/.zprofile"
		fs-move -- "$HOME/.zshrc" "$ZDOTDIR/.zshrc"
		fs-move -- "$HOME/.zlogin" "$ZDOTDIR/.zlogin"
		fs-move -- "$HOME/.zlogout" "$ZDOTDIR/.zlogout"
		config-helper --file="$HOME/.zshenv" -- \
			--find='ZDOTDIR=.+' --replace="ZDOTDIR='$ZDOTDIR'"
	}

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check --cli=zsh; then
		do_configure
		return 0
	fi

	# https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH
	local options=(
		--name='zsh'
		--cli='zsh'
		"$@"
		APK='zsh' # ALPINE
		APT='zsh' # UBUNTU
		AUR='zsh' # ARCH
		BREW='zsh'
		BSD='zsh'
		EMERGE='zsh' # GENTOO
		EOPKG='zsh'  # SOLUS
		PORT='zsh'
		RPM='zsh'    # FEDORA
		XBPS='zsh'   # VOID
		ZYPPER='zsh' # SUSE
	)
	setup-util "${options[@]}"

	# if installed, then configure
	if __command_exists -- zsh; then
		do_configure
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_zsh "$@"
fi
