#!/usr/bin/env bash

# https://prettier.io/docs/en/install.html

function setup-util-prettier() (
	source "$DOROTHY/sources/strict.bash"

	setup-util "$@" --name='Prettier' --cli='prettier' \
		NODE='prettier'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-prettier "$@"
fi
