#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://www.gnu.org/software/emacs/
# https://github.com/emacs-mirror/emacs

env NAME='GNU Emacs' CLI='emacs' \
	APT='emacs' \
	CASK='emacs' \
	setup-util
