#!/usr/bin/env bash

# https://tea.xyz => https://github.com/teaxyz/setup/blob/main/install.sh => magical installer, ignore it
# https://github.com/teaxyz/docs/pull/13
# https://docs.tea.xyz/getting-started/install-tea/without-installer

# https://github.com/teaxyz/cli/releases
# tea-0.39.5+darwin+aarch64.tar.xz
# tea-0.39.5+darwin+x86-64.tar.xz
# tea-0.39.5+linux+aarch64.tar.xz
# tea-0.39.5+linux+x86-64.tar.xz
# tea-0.39.5.tar.xz

# https://docs.tea.xyz/appendix/uninstall-tea
# $HOME/.tea

function setup_util_tea() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=tea "$@"; then
		return 0
	fi

	# don't interfere with github download:
	# DOWNLOAD="https://tea.xyz/$(uname)/$(uname -m)"
	# DOWNLOAD_FILENAME='tea'
	local arch options=(
		--cli='tea'
		"$@"
		BREW='teaxyz/pkgs/tea-cli'
	)
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return
		github-download --dry --slug='teaxyz/cli' --latest --asset-regexp="$regexp" | echo-first-line || return
	}
	function __add_download_option {
		local url
		url="$(__get_github_asset_url "$1")" || return
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB='tea'
		)
	}
	arch="$(get-arch)"
	if is-mac; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '+darwin+aarch64' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '+darwin+x86-64' || :
		fi
	elif is-linux; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '+linux+aarch64' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '+linux+x86-64' || :
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_tea "$@"
fi
