#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-gsed() (
	if is-mac; then
		setup-util "$@" NAME='GNU sed' CLI='gsed' \
			BREW='gnu-sed'
	elif command-missing gsed; then
		# make the symlink, using our reliable helper
		symlink-helper --existing="$(which sed)" --symlink="$XDG_BIN_HOME/gsed"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-gsed "$@"
fi
