#!/usr/bin/env bash

# https://github.com/jqlang/jq

# https://github.com/jqlang/jq/releases
# jq-1.7rc1.tar.gz
# jq-1.7rc1.zip
# jq-linux-amd64
# jq-linux-arm64
# jq-linux-armel
# jq-linux-armhf
# jq-linux-i386
# jq-linux-mips
# jq-linux-mips64
# jq-linux-mips64el
# jq-linux-mips64r6
# jq-linux-mips64r6el
# jq-linux-mipsel
# jq-linux-mipsr6
# jq-linux-mipsr6el
# jq-linux-powerpc
# jq-linux-ppc64el
# jq-linux-riscv64
# jq-linux-s390x
# jq-macos-amd64
# jq-macos-arm64
# jq-windows-amd64.exe
# jq-windows-i386.exe

# https://packages.debian.org/sid/amd64/jq/filelist
# /usr/bin/jq

# https://repology.org/project/jq/versions

function setup_util_jq() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='jq'
		APK='jq'
		APT='jq'
		AUR='jq'
		BREW='jq'
		BSD='jq'
		EMERGE='app-misc/jq'
		NIX='jq'
		PORT='jq'
		RPM='jq'
		SCOOP='jq'
		URPMI='jq'
		WINGET='jq'
		XBPS='jq'
		ZYPPER='jq'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='jqlang/jq' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix "$slug" '-macos-arm64' || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix "$slug" '-macos-amd64' || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix "$slug" '-linux-arm64' || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix "$slug" '-linux-armhf' || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix "$slug" '-linux-amd64' || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix "$slug" '-linux-i386' || :
		elif [[ $arch == 'r64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix "$slug" '-linux-riscv64' || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_jq "$@"
fi
