#!/usr/bin/env bash

# https://en.wikipedia.org/wiki/Vim_(text_editor)

# https://www.digitalocean.com/community/tutorials/installing-and-using-the-vim-text-editor-on-a-cloud-server

# https://packages.debian.org/sid/amd64/vim/filelist
# /usr/bin/vim.basic

function setup_util_vim() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists vim; then
		return 0
	fi

	# setup
	local options=(
		--name='Vim (Vi IMproved)'
		--cli='vim'
		"$@"
		APK='vim' # ALPINE
		APT='vim' # UBUNTU
		AUR='vim' # ARCH
		BREW='vim'
		RPM='vim'    # FEDORA
		ZYPPER='vim' # SUSE
	)
	setup-util "${options[@]}"

	# if installed, configure
	if command-exists vim; then
		# ensure vim configuration
		if test ! -f "$HOME/.vimrc"; then
			cat <<-EOF
				Vim configuration missing, applying the fancy defaults from:
				$(echo-style --dim='https://github.com/amix/vimrc')
			EOF
			github-download \
				--slug='amix/vimrc' \
				--ref='master' \
				--pathname='vimrcs/basic.vim' \
				--filepath="$HOME/.vimrc"
		fi
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_vim "$@"
fi
