#!/usr/bin/env bash

# https://github.com/BurntSushi/ripgrep
# https://github.com/BurntSushi/ripgrep/issues/1094
# grep alternative

# https://github.com/BurntSushi/ripgrep/releases
# https://github.com/microsoft/ripgrep-prebuilt/releases
# ripgrep-v13.0.0-10-aarch64-apple-darwin.tar.gz
# ripgrep-v13.0.0-10-aarch64-pc-windows-msvc.zip
# ripgrep-v13.0.0-10-aarch64-unknown-linux-gnu.tar.gz
# ripgrep-v13.0.0-10-aarch64-unknown-linux-musl.tar.gz
# ripgrep-v13.0.0-10-arm-unknown-linux-gnueabihf.tar.gz
# ripgrep-v13.0.0-10-i686-pc-windows-msvc.zip
# ripgrep-v13.0.0-10-i686-unknown-linux-musl.tar.gz
# ripgrep-v13.0.0-10-powerpc64le-unknown-linux-gnu.tar.gz
# ripgrep-v13.0.0-10-s390x-unknown-linux-gnu.tar.gz
# ripgrep-v13.0.0-10-x86_64-apple-darwin.tar.gz
# ripgrep-v13.0.0-10-x86_64-pc-windows-msvc.zip
# ripgrep-v13.0.0-10-x86_64-unknown-linux-musl.tar.gz

# https://packages.debian.org/sid/amd64/ripgrep/filelist
# /usr/bin/rg

# https://repology.org/project/ripgrep/versions

function setup_util_ripgrep() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='ripgrep'
		--cli='rg'
		APK='ripgrep'
		APT='ripgrep'
		AUR='ripgrep'
		BREW='ripgrep'
		BSD='ripgrep'
		CARGO='ripgrep'
		EMERGE='sys-apps/ripgrep'
		URPMI='ripgrep'
		NIX='ripgrep'
		PORT='ripgrep'
		SCOOP='ripgrep'
		ZYPPER='ripgrep'
	)
	if ! is-system --almalinux; then
		# almalinux is not aware of the DNF package
		util_options+=(DNF='ripgrep')
	fi

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='microsoft/ripgrep-prebuilt' glob='rg' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-apple-darwin.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-apple-darwin.tar.gz' "$glob" || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-unknown-linux-musl.tar.gz' "$glob" || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-arm-unknown-linux-gnueabihf.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-unknown-linux-musl.tar.gz' "$glob" || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-i686-unknown-linux-musl.tar.gz' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_ripgrep "$@"
fi
