#!/usr/bin/env bash

# https://github.com/showcases/fonts
# https://github.com/todylu/monaco.ttf

function setup_util_monaco() (
	source "$DOROTHY/sources/util.bash"
util_options=(
		--font='Monaco.ttf'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	__fetch_and_add_download_option_via_slug_pathname_filename 'todylu/monaco.ttf' 'monaco.ttf' 'Monaco.ttf' || :

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_monaco "$@"
fi
