#!/usr/bin/env bash

# Note, if you are after a terminal for Raspberry OS, then go with `ptyxis` instead
# As, Alacritty needs manual config file changes to do Login Shell

# https://github.com/alacritty/alacritty

# https://github.com/alacritty/alacritty/releases/tag/v0.16.1
# alacritty-bindings.5.gz
# alacritty-msg.1.gz
# Alacritty-v0.16.1-installer.msi
# Alacritty-v0.16.1-portable.exe
# Alacritty-v0.16.1.dmg
# alacritty.1.gz
# alacritty.5.gz
# alacritty.bash
# Alacritty.desktop
# alacritty.fish
# alacritty.info
# Alacritty.svg
# _alacritty

# https://repology.org/project/alacritty/versions

function setup_util_alacritty() (
	source "$DOROTHY/sources/bash.bash"

	# v0.13 is only one that supports .toml, which is the only documented configuration format
	local options=(
		--app='Alacritty'
		--cli=alacritty
		"$@"
		AUR='alacritty'
		CASK='alacritty'
		DEB='alacritty' # repology says `rust-alacritty`, but that is 404, `alacritty` is correct
		RPM='alacritty'
		SCOOP='alacritty'
		SNAP='alacritty --edge --classic'
		WINGET='alacritty'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_alacritty "$@"
fi
