#!/usr/bin/env bash

# https://repology.org/project/firefox/versions

function setup_util_firefox() (
	source "$DOROTHY/sources/bash.bash"

	local options=(
		--name='Firefox'
		--app='Firefox'
		"$@"
		APK='firefox'               # ALPINE
		APT='firefox'               # UBUNTU
		AUR='firefox'               # ARCH
		CASK='firefox'              # MACOS
		CHOCOLATEY='firefox'        # WINDOWS
		EMERGE='www-client/firefox' # GENTOO
		NIX='nixpkgs.firefox'       # NIX
		RPM='firefox'               # FEDORA
		URPMI='firefox'             # MAGEIA
		XBPS='firefox'              # VOID
		ZYPPER='firefox'            # SUSE
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_firefox "$@"
fi
