#!/usr/bin/env bash

# https://starship.rs
# https://starship.rs/guide/#🚀-installation
# cross-shell prompt

# https://github.com/starship/starship/releases
# starship-aarch64-apple-darwin.tar.gz
# starship-aarch64-pc-windows-msvc.zip
# starship-aarch64-unknown-linux-musl.tar.gz
# starship-arm-unknown-linux-musleabihf.tar.gz
# starship-i686-pc-windows-msvc.msi
# starship-i686-pc-windows-msvc.zip
# starship-i686-unknown-linux-musl.tar.gz
# starship-x86_64-apple-darwin.tar.gz
# starship-x86_64-pc-windows-msvc.msi
# starship-x86_64-pc-windows-msvc.zip
# starship-x86_64-unknown-freebsd.tar.gz
# starship-x86_64-unknown-linux-gnu.tar.gz
# starship-x86_64-unknown-linux-musl.tar.gz

function setup_util_starship() (
	source "$DOROTHY/sources/util.bash"
	source "$(type -P setup-util)" # enable *_EVAL
	 util_options=(
		--name='Starship'
		--cli='starship'
		# INSTALLER='https://starship.rs/install.sh'
		BREW='starship'
		SCOOP='starship'
		RECONFIGURE_EVAL='__reconfigure'
	)
	function __reconfigure {
		# if we are installed, note fonts
		if setup-util "${util_options[@]}" is-installed; then
			__print_style \
				'If you see unknown icons while using Starship, you probably require fonts:' --newline \
				--code='setup-util-noto-emoji # for emojis' --newline \
				--code='setup-util-nerd-fonts # for glyphs' --newline \
				'Then set your terminal to use one of the installed fonts.' || return $?
		fi

		# reconfigure nushell regardless of starship existence
		if setup-util-nu is-installd; then
			setup-util-nu reconfigure || return $?
		fi
	}

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='starship/starship' glob='starship' arch
	arch="$(__get_arch)" || return $?
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-apple-darwin.tar.gz' "$glob" || return $?
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-apple-darwin.tar.gz' "$glob" || return $?
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-unknown-linux-musl.tar.gz' "$glob" || return $?
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-arm-unknown-linux-musl.tar.gz' "$glob" || return $?
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-unknown-linux-musl.tar.gz' "$glob" || return $?
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-i686-unknown-linux-musl.tar.gz' "$glob" || return $?
		fi
	fi

	# setup
	setup_util "${util_options[@]}" "${user_options[@]}" || return $?
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_starship "$@"
fi
