#!/usr/bin/env bash

function setup-util-zsh() (
	source "$DOROTHY/sources/bash.bash"

	# https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH
	setup-util "$@" --name='zsh' --cli='zsh' \
		APK='zsh' \
		APT='zsh' \
		AUR='zsh' \
		BREW='zsh' \
		BSD='zsh' \
		EMERGE='zsh' \
		EOPKG='zsh' \
		PORT='zsh' \
		RPM='zsh' \
		VOID='zsh' \
		ZYPPER='zsh'

	# https://ohmyz.sh/#install
	setup-util "$@" --confirm --optional --name='Oh My ZSH' \
		INSTALLER='https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-zsh "$@"
fi
