#!/usr/bin/env bash

# https://xxhash.com
# https://github.com/Cyan4973/xxHash
# https://github.com/Cyan4973/xxHash/releases/tag/v0.8.3

# https://repology.org/project/xxhash/versions

function setup_util_xxhash() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=xxhsum "$@"; then
		return 0
	fi

	# despite docs, no apk
	local options=(
		--cli='xxhsum'
		"$@"
		BREW='xxhash'
		APK='xxhash'
		AUR='xxhash'
		APT='xxhash'
		RPM='xxhash'
		VOID='xxHash'
		ZYPPER='xxhash'
		GENTOO='dev-libs/xxhash'
		NIX='xxHash'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_xxhash "$@"
fi
