#!/usr/bin/env bash

# https://github.com/calcom/font

function setup_util_cal_sans() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check --font='CalSans*'; then
		return 0
	fi

	# setup
	function __get_github_asset_url {
		github-download --dry --slug='calcom/font' --pathname='fonts/otf/CalSans-Regular.otf' --latest || return $?
	}
	local options=(
		--name='Cal Sans'
		--font='CalSans*'
		"$@"
		CASK='font-cal-sans'
		DOWNLOAD="$(__get_github_asset_url)"
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_cal_sans "$@"
fi
