#!/usr/bin/env bash

# Desktop
# https://support.1password.com/install-linux/
# https://support.1password.com/betas/?linux
# https://releases.1password.com/linux/beta/#1password-for-linux-8.6.0-68
# https://1password.community/discussion/comment/631532#Comment_631532
# https://developer.1password.com/docs/ssh/agent
# https://aur.archlinux.org/packages/1password
# https://aur.archlinux.org/packages/1password-beta

# Browser
# https://app-updates.agilebits.com/product_history/B5X
# https://support.1password.com/betas/#install-a-beta-release-of-the-1password-extension

# This use to install the betas, as the betas were more stable. However that was a long time ago. If you desire the betas, send a PR for a `--beta` flag, or make a `setup-util-1password-beta`

function setup_util_1password() (
	source "$DOROTHY/sources/util.bash"
	source "$(type -P setup-util)" # enable *_EVAL
	util_options=(
		# `snap` and `flatpak` are last because `The 1Password SSH agent doesn't work with Flatpak  or Snap Store installations of 1Password. To use the SSH agent, choose a different method to install 1Password for Linux.`
		--source='... snap flatpak'
		--name='1Password Desktop'
		--app='1Password' # macos
		--app='1password' # .desktop
		--configure-eval='__configure'
		CASK='1password'
	)
	function __configure {
		# Browser Extension
		if [[ $SETUP_UTIL__INSTALLED == 'yes' ]]; then
			if [[ $SETUP_UTIL__EXTRA == 'yes' ]]; then
				__print_style 'Install the 1Password Browser extension by visiting the following URL:' --newline --url='https://1password.com/downloads/browser-extension' || return $?
			fi

			# Vivaldi
			setup-util-vivaldi configure || return $?
		fi
	}
	# use platform exclusive configuration
	if __is_linux; then
		local arch reason='Your password is required to momentarily grant privileges to install 1Password.'
		arch="$(__get_arch)"
		function __apt_keys {
			setup-util-gpg --dependency || return $? # always call, as it ensures gpg is also setup correctly
			fs-mkdir --reason="$reason" -- \
				/etc/debsig/policies/AC2D62742012EA22 \
				/usr/share/debsig/keyrings/AC2D62742012EA22 || return $?
			fetch 'https://downloads.1password.com/linux/debian/debsig/1password.pol' |
				echo-write --binary --reason="$reason" -- \
					/etc/debsig/policies/AC2D62742012EA22/1password.pol || return $?
			fetch 'https://downloads.1password.com/linux/keys/1password.asc' |
				eval-helper --elevate --reason="$reason" -- \
					gpg --dearmor --output \
					/usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg || return $?
		}
		function __rpm_keys {
			eval-helper --elevate --reason="$reason" -- \
				rpm --import 'https://downloads.1password.com/linux/keys/1password.asc' || return $?
			echo-write --reason="$reason" -- /etc/yum.repos.d/1password.repo <<-EOF || return $?
				[1password]
				name=1Password Channel
				baseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch
				enabled=1
				gpgcheck=1
				repo_gpgcheck=1
				gpgkey="https://downloads.1password.com/linux/keys/1password.asc"
			EOF
		}
		function __gpg_keys {
			setup-util-gpg --dependency || return $? # always call, as it ensures gpg is also setup correctly
			fetch 'https://downloads.1password.com/linux/keys/1password.asc' | gpg --import || return $?
		}
		function __install {
			# linux 1password expects it to be inside `/opt/1Password/`

			# ensure moving doesn't get nested
			fs-remove --quiet --no-confirm --elevate -- \
				/opt/1Password || return $?

			# make the directory again
			eval-helper --elevate --reason="$reason" -- \
				mkdir -pv -- \
				/opt/1Password || return $?

			# move everything that was extracted to go inside the directory
			eval-helper --elevate --reason="$reason" -- \
				mv -v -- \
				1password-*/* \
				/opt/1Password || return $?

			# run the official after-install script, and if it fails, just do the symlink part of it
			eval-helper --elevate --reason="$reason" -- \
				/opt/1Password/after-install.sh ||
				eval-helper --elevate --reason="$reason" -- \
					ln -sf -- \
					/opt/1Password/1password /usr/bin/1password || return $?
		}
		function __uninstall {
			# https://support.1password.com/uninstall-1password/
			if is-present -- /opt/1Password/after-remove.sh; then
				eval-helper --elevate --reason="$reason" -- \
					/opt/1Password/after-remove.sh || :
			fi
			fs-remove --quiet --no-confirm --elevate -- \
				/opt/1Password /usr/bin/1password || return $?
		}
		function __add_download_option {
			local url="$1"
			util_options+=(
				DOWNLOAD="$url"
				DOWNLOAD_ARCHIVE_EXTRACT='yes'
				DOWNLOAD_TARGET_PATH='/opt/1Password/1password'
				DOWNLOAD_BUILD_INSTALL_EVAL='__install'
			)
		}
		util_options+=(
			EVAL_UNINSTALL='__uninstall'
		)
		if [[ $arch == 'a64' ]]; then
			# only a64
			__add_download_option 'https://downloads.1password.com/linux/tar/stable/aarch64/1password-latest.tar.gz'
		else
			# only x64
			__add_download_option 'https://downloads.1password.com/linux/tar/stable/xx86_64/1password-latest.tar.gz'
			util_options+=(
				APT_INSTALL_EVAL='__apt_keys'
				APT_KEY='https://downloads.1password.com/linux/keys/1password.asc'
				APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://downloads.1password.com/linux/debian/amd64 stable main'
				APT='1password'
				AUR_INSTALL_EVAL='__aur_keys'
				AUR='1password'
				FLATPAK='https://downloads.1password.com/linux/flatpak/1Password.flatpakref'
				RPM_INSTALL_EVAL='__rpm_keys'
				RPM='1password'
				SNAP='1password'
			)
		fi
	fi

	# setup
	setup_util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_1password "$@"
fi
