#!/usr/bin/env bash

function setup_util_apt() (
	source "$DOROTHY/sources/bash.bash"

	# checks
	if ! is-apt; then
		__print_style --stderr --notice="[$0] is only intended to be run on aptitude systems, skipping." || return
		return 0
	fi

	# setup
	# lsb-release is missing on Debian on GitHub CI
	local options=(
		--name='APT Essentials'
		"$@"
		APT='apt-transport-https' APT='ca-certificates' APT='lsb-release' # UBUNTU, DEBIAN
	)
	setup-util "${options[@]}"  || return
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_apt "$@"
fi
