#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://signal.org/
# https://www.makeuseof.com/install-signal-desktop-linux/

function setup-util-signal() (
	setup-util "$@" --name='Signal.org' \
		APT_KEY='https://updates.signal.org/desktop/apt/keys.asc' \
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://updates.signal.org/desktop/apt xenial main' \
		APT='signal-desktop' \
		AUR='signal-desktop' \
		CASK='signal' \
		FLATPAK='org.signal.Signal'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-signal "$@"
fi
