#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/nano/filelist
# /bin/nano
# /bin/rnano

function setup_util_nano() (
	source "$DOROTHY/sources/util.bash"
	source "$(type -P setup-util)" # enable *_EVAL
	util_options=(
		--name='GNU nano'
		--cli='nano'
		APK='nano'
		APT='nano'
		BREW='nano'
		RECONFIGURE_INSTALLED_EVAL='__reconfigure'
	)
	function __reconfigure {
		# fix ubuntu server issue:
		# Unable to create directory /home/ubuntu/.local/share/nano/: No such file or directory
		# It is required for saving/loading search history or cursor positions.
		__mkdirp "$XDG_DATA_HOME/nano" || return $?
	}
	setup_util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_nano "$@"
fi
