#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-devel() (
	if is-apt; then
		setup-util "$@" --optional --name='APT Essentials' \
			APT='apt-transport-https ca-certificates'
	fi

	setup-util "$@" --optional --name='Build Essentials' \
		APT='build-essential' \
		AUR='base-devel' \
		BREW='coreutils' \
		RPM='coreutils' \
		ZYPPER='coreutils'

	# https://apple.stackexchange.com/a/362837
	setup-util "$@" --optional --cli='clang' \
		APT='clang' \
		AUR='clang' \
		BREW='llvm' \
		RPM='clang' \
		ZYPPER='clang'

	setup-util "$@" --optional --cli='make' \
		APT='make' \
		ZYPPER='make'

	setup-util "$@" --optional --cli='cmake' \
		APT='cmake' \
		AUR='cmake' \
		BREW='cmake' \
		RPM='cmake' \
		ZYPPER='cmake'

	# https://rentes.github.io/unix/utilities/2015/07/27/moreutils-package/
	# https://www.putorius.net/moreutils.html
	setup-util "$@" --optional --cli='errno' \
		APT='moreutils' \
		AUR='moreutils' \
		BREW='moreutils' \
		RPM='moreutils' \
		ZYPPER='moreutils'

	setup-util "$@" --optional --cli='llvm-gcc' \
		APT='llvm' \
		AUR='llvm' \
		BREW='llvm' \
		RPM='llvm' \
		ZYPPER='llvm'

	setup-util "$@" --optional --cli='pkg-config' \
		APT='pkg-config' \
		AUR='pkg-config' \
		BREW='pkg-config' \
		RPM='pkg-config' \
		ZYPPER='pkg-config'

	setup-util "$@" --optional --name='openssl/libssl' \
		APT='libssl-dev' \
		AUR='openssl' \
		BREW='openssl' \
		RPM='openssl-devel' \
		ZYPPER='openssl'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-devel "$@"
fi
