#!/usr/bin/env bash

# https://github.com/githubnext/monaspace
# https://github.com/githubnext/monaspace/releases

function setup_util_monaspace() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='Monaspace'
		--font='Monaspace*'
		CASK='font-monaspace-var'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	# downloading the tarball includes all fonts variations, which is like a GB
	# github-download --dry --slug='githubnext/monaspace' --latest
	# this just fetches variable, which is 2MB
	function __add_download_option {
		local url
		url="$(__get_github_asset_url_via_slug_regexp 'githubnext/monaspace' '^monaspace-variable-v[0-9.]+\.zip$')" || return $?
		util_options+=(
			DOWNLOAD="$url"
			# DOWNLOAD_ARCHIVE_GLOB='*/fonts/*/*.{otf,ttf}' # <-- for tarball
			DOWNLOAD_ARCHIVE_GLOB='Variable Fonts/*/*.ttf' # <-- for specific variation
		)
	}
	__add_download_option || :

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_monaspace "$@"
fi
