#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/imsnif/bandwhich
# bandwidth monitor

setup-util "$@" CLI='bandwhich' \
	BREW='bandwhich' \
	CARGO='bandwhich' \
	DNF_COPR='atim/bandwhich' \
	DNF='bandwhich' \
	NIX='nixpkgs.bandwhich' \
	PACMAN='bandwhich' \
	PKG='bandwhich' \
	XBPS='bandwhich'
