#!/usr/bin/env bash

# https://docs.docker.com/engine/install/fedora/
# https://docs.docker.com/engine/install/fedora/#install-using-the-convenience-script
# https://docs.docker.com/engine/install/ubuntu/
# https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
# https://docs.docker.com/engine/install/linux-postinstall/
# don't go rootless, is too complicated

# for some reason https://docs.docker.com/engine/install/linux-postinstall/ recommends
#	sudo-helper -- groupadd docker || :
#	sudo-helper -- usermod -aG docker "$USER"
# yet https://snapcraft.io/docker recommends
#	sudo-helper -- addgroup --system docker || :
#	sudo-helper -- adduser "$USER" docker || :
# we will prcoeed with the official instructions

# old ways
#	sudo-helper -- service docker restart
# new ways are what are implemented

# @todo experiemnt with using `newgrp docker` instead to workaround need for postinstall

function setup-util-docker() (
	source "$DOROTHY/sources/strict.bash"
	source "$(which eval-helper)"

	# =====================================
	# Arguments

	# help
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Sets up Docker according to the recommended setup for your platform.

			USAGE:
			setup-util-docker

			OPTIONS:
			--paths
			    If specified, output the paths used by syncthing; useful for restoring backups.

			--service
			    If specified, output the service name.

			...
			    All other options are forwarded to $(echo-style --code='setup-util').
		EOF
		return 22 # Invalid argument
	}

	# process
	local item action='install' util=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--paths') action='paths' ;;
		'--service') action='service' ;;
		'--install') action='install' ;;
		'--uninstall') action='uninstall' ;;
		'--check') action='check' ;;
		'--action='*) action="${item#*--action=}" ;;
		*) util+=("$item") ;;
		esac
	done

	# ensure action inside util
	util+=("--action=$action")

	# =====================================
	# Preparation

	local service_name='docker'
	local service_user="$USER"
	local service_group='docker'
	local service_attach_users=("$service_user")
	# local service_attach_groups=("$service_group")
	local service_config_paths=(
		"$HOME/.docker"
	)
	local service_uninstall_paths=(
		/etc/apparmor.d/docker
		/etc/docker
		/usr/bin/docker-compose
		/var/lib/containerd
		/var/lib/docker
		/var/run/docker.sock
	)

	# =====================================
	# Simple Actions

	if test "$action" = 'paths'; then
		echo-lines "${service_config_paths[@]}"
		return 0
	elif test "$action" = 'service'; then
		echo "$service_name"
		return 0
	fi

	# =====================================
	# Setup Utility

	function check_group {
		is-group "$service_group"
	}
	function check_user_in_group {
		is-user-in-group --user="$service_user" --group="$service_group"
	}
	function delete_service_group {
		# remove the group from all users and the system, better than delgroup which is more focused only on the current user
		sudo-helper -- groupdel "$service_group"
	}
	function add_service_group {
		# add a group to the system, better than addgroup which is more focused only on the current user
		sudo-helper -- groupadd "$service_group"
	}
	function add_service_users_to_service_group {
		local user
		for user in "${service_attach_users[@]}"; do
			# attach the user to the group
			sudo-helper -- usermod -aG "$service_group" "$user"
		done
	}
	function add_permissions_to_config {
		mkdir -p "${service_config_paths[@]}"
		fs-own --user="$service_user" --group="$service_group" --permissions='g+rwx' \
			-- "${service_config_paths[@]}"
	}

	function run_official_linux_installer() (
		# run inside a subshell
		set +Eeuo # disable strict mode
		eval "$(fetch https://get.docker.com)"
	)
	function run_official_linux_checks() (
		# run inside a subshell
		set +Eeuo # disable strict mode
		eval "$(fetch https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh)"
	)
	function run_checks() {
		echo
		echo 'Testing if containers work correctly by running hello-world in a container...'
		docker run --rm hello-world

		echo
		echo 'Testing if networking works correctly by pinging gateway...'
		docker run --rm -it alpine ping -c4 "$(what-is-my-gateway)"

		echo
		echo 'Testing if networking works correctly by pinging cloudflare...'
		docker run --rm -it alpine ping -c4 cloudflare.com
	}

	# macos
	# https://docs.docker.com/desktop/install/mac-install/
	if is-mac; then
		setup-util "${util[@]}" --app='Docker' CASK='docker'
		while command-missing docker; do
			echo
			echo-style --code='docker' --dim=' command not found'
			echo-style --notice='Continue installation via the Docker app...'
			open "$(get-app 'Docker')"

			echo
			confirm --ppid=$$ -- 'Press <enter> once Docker has finished installing...'
		done
		action='check'
		# /Applications/Docker.app/Contents/MacOS/Docker --uninstall
	elif is-linux; then
		# uninstall
		if test "$action" = 'uninstall'; then
			echo
			echo 'Cleaning tooling...'
			if is-dnf; then
				# https://docs.docker.com/engine/install/fedora/
				sudo dnf remove docker \
					docker-client \
					docker-client-latest \
					docker-common \
					docker-latest \
					docker-latest-logrotate \
					docker-logrotate \
					docker-selinux \
					docker-engine-selinux \
					docker-engine || :
			elif command-exists apt-get snap; then
				# https://docs.docker.com/engine/install/ubuntu/
				sudo-helper -- apt-get purge -y \
					containerd \
					docker \
					docker-ce \
					docker-ce-cli \
					docker-ce-rootless-extras \
					docker-engine \
					docker.io \
					runc ||
					:
				sudo-helper -- snap remove --purge docker || :
				sudo-helper -- apt-get autoremove -y --purge || :
				sudo-helper -- dpkg --configure -a || :
				sudo-helper -- apt-get update || :
				sudo-helper -- apt-get -f install || :
			fi

			echo
			echo 'Cleaning files...'
			sudo-helper -- umount /var/lib/docker/ || :
			fs-rm --sudo -- "${service_uninstall_paths[@]}"

			if is-group "$service_group"; then
				echo
				echo 'Cleaning group...'
				delete_service_group
			fi

			echo
			echo-style --success='Uninstall complete.'

		elif test "$action" = 'install'; then
			# check configuration
			if command-missing docker || ! check_group || ! check_user_in_group; then
				echo-error "$0: Docker is misconfigured."
				echo-style 'Try uninstall: ' --code='setup-util-docker --uninstall'
				echo-style 'Then install: ' --code='setup-util-docker'
				return 1
			fi

			# https://forums.docker.com/t/installing-docker-on-ubuntu-16-04-lts-throws-error-for-command-linux-image-extra/21546?u=balupton
			# https://askubuntu.com/a/1236711/22776
			echo
			echo 'Installing dependencies...'
			setup-util-devel
			setup-util-snap --optional
			setup-util --optional --name='Kernel Virtualisation Helpers' \
				APT='linux-image-extra-virtual'

			echo
			echo 'Install using the official convenience script...'
			if ! run_official_linux_installer || command-missing docker; then
				echo-error "$0: Docker installation failed."
				return 1
			fi

			echo
			echo 'Configuring group...'
			if ! check_group; then
				# official installer may add the group for us
				add_service_group
			fi
			if ! check_user_in_group; then
				add_service_users_to_service_group

				echo
				echo 'Continuing installer with desired group permissions.'
				echo "$0" | newgrp docker
			fi

			echo
			echo 'Configuring permissions...'
			add_permissions_to_config

			echo
			echo 'Configuring service...'
			service-helper --restart --reenable -- containerd docker # docker.socket
			sleep 2
			service-helper --status -- containerd docker

			echo
			echo 'Testing if docker is configured correctly by running check-config...'
			run_official_linux_checks

			echo
			echo-style --success='Docker has been setup.'
			action='check'
		fi # end install
	fi  # end os

	if test "$action" = 'check'; then
		eval-helper --quiet --no-wrap \
			--pending="$(echo-style --bold="Testing Docker...")" \
			--success="$(echo-style --success="Docker is working.")" \
			--failure="$(echo-style --error="Failed to verify docker works.")" \
			-- run_checks
	fi

)

# fire if invoked stqandalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-docker "$@"
fi
