#!/usr/bin/env bash

# https://github.com/dandavison/delta
# diff alternative

# https://github.com/dandavison/delta/releases
# delta-0.16.5-aarch64-apple-darwin.tar.gz
# delta-0.16.5-aarch64-unknown-linux-gnu.tar.gz
# delta-0.16.5-arm-unknown-linux-gnueabihf.tar.gz
# delta-0.16.5-i686-unknown-linux-gnu.tar.gz
# delta-0.16.5-x86_64-apple-darwin.tar.gz
# delta-0.16.5-x86_64-pc-windows-msvc.zip
# delta-0.16.5-x86_64-unknown-linux-gnu.tar.gz
# delta-0.16.5-x86_64-unknown-linux-musl.tar.gz
# git-delta-musl_0.16.5_amd64.deb
# git-delta_0.16.5_amd64.deb
# git-delta_0.16.5_arm64.deb
# git-delta_0.16.5_armhf.deb
# git-delta_0.16.5_i386.deb

function setup_util_delta() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='delta'
		AUR='git-delta-bin'
		BREW='git-delta'
		BSD='git-delta'
		CARGO='git-delta'
		EMERGE='dev-util/git-delta'
		NIX='nixpkgs.gitAndTools.delta'
		PORT='git-delta'
		RPM='git-delta'
		SCOOP='delta'
		XBPS='delta'
		ZYPPER='git-delta'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='dandavison/delta' glob='delta' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-apple-darwin.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-apple-darwin.tar.gz' "$glob" || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_arm64.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-unknown-linux-gnu.tar.gz' "$glob" || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_armhf.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-arm-unknown-linux-gnueabihf.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_amd64.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-unknown-linux-musl.tar.gz' "$glob" || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_i386.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-i686-unknown-linux-gnu.tar.gz' "$glob" || :
		fi
	fi
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_delta "$@"
fi
