#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-mas() (
	# check for support
	if ! is-mac; then
		echo-style --notice="[$0] is only intended to be run on macOS systems, skipping." >/dev/stderr
		return 0
	fi

	# =====================================
	# Action

	setup-util "$@" --name='Mac App Store command-line interface' --cli='mas' \
		BREW='mas'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-mas "$@"
fi
