#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://askubuntu.com/a/38782/22776

sudo-inherit config-helper \
	--file=/etc/default/grub \
	--find='GRUB_CMDLINE_LINUX_DEFAULT=.*' \
	--replace='GRUB_CMDLINE_LINUX_DEFAULT="quiet splash nomodeset"'

update-grub-universal
