#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://developers.cloudflare.com/warp-client/get-started/linux
# https://developers.cloudflare.com/warp-client/setting-up/linux
# https://developers.cloudflare.com/warp-client/setting-up/macOS
# currently only supports apt+yum on amd64:
# https://pkg.cloudflareclient.com/packages/cloudflare-warp
# doesn't support arm64:
# https://community.cloudflare.com/t/cloudflare-warp-linux-client-for-armv8-arm64-aarch64-devices/278777
# doesn't support arch-linux (manjaro):
# https://community.cloudflare.com/t/cloudflare-warp-linux-client-for-arch-linux-manjaro/298649

function setup-util-warp() (
	setup-util "$@" --app='Cloudflare WARP' --cli='warp-cli' \
		APT_KEY='https://pkg.cloudflareclient.com/pubkey.gpg' \
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://pkg.cloudflareclient.com/ {DISTRO} main' \
		APT='cloudflare-warp' \
		CASK='cloudflare-warp' \
		RPM='cloudflare-warp'

	# sudo-helper -- rpm -ivh http://pkg.cloudflareclient.com/cloudflare-release-el<VERSION>.rpm
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-warp "$@"
fi
