#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# Make the directory
rm -Rf "$HOME/.clojure"
mkdir "$HOME/.clojure"
cd "$HOME/.clojure" || exit 1

# Install Clojure
down-zip http://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.zip

# Install ClojureScript
cd "$HOME/bin" || exit 1
down https://github.com/clojure/clojurescript/releases/download/r1.9.229/cljs.jar

# Install Boot
cd "$HOME/bin" || exit 1
down https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
chmod +x boot.sh
