#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/dnsutils/filelist (no bins...)

function setup_util_dig() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli=dig
		# no apk
		APT='dnsutils'
		AUR='dnsutils'
		RPM='bind-utils'
		ZYPPER='bind-utils'
	)
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_dig "$@"
fi
