#!/usr/bin/env bash

function setup-util-python() (
	source "$DOROTHY/sources/bash.bash"

	# python2
	# homebrew no longer offers python2, their suggestion is to use pyenv instead
	# despite docs, apk does not offer python or python2
	setup-util "$@" --optional --cli='python2' \
		APT='python2' \
		AUR='python2' \
		RPM='python' \
		ZYPPER='python'

	# python3
	setup-util "$@" --cli='python3' \
		APK='python3' \
		APT='python3' \
		AUR='python3' \
		BREW='python3' \
		RPM='python3' \
		ZYPPER='python3'

	# pipx dependencies for linux, not macos
	if is-linux; then
		setup-util "$@" --optional --name='python3-venv' \
			APT='python3-venv' \
			AUR='python-virtualenv' \
			ZYPPER='python3-virtualenv'
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-python "$@"
fi
