#!/usr/bin/env bash
# shellcheck disable=SC1091
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/arrays.bash"
requires_array_support 'mapfile'

# =====================================
# Notes

# Don't use `is-admin` here, as sudo does not necessarily load this
# so sudo should inherit standard config.

# Right to left is the prefernece for paths.

# Always use terminal editor for prompts as GUI editors are too slow.

# =====================================
# Helpers

function rubygems {
	local gem="$1" gemdirs gemdir
	export GEM_HOME="$HOME/.gem"
	if test -x "$gem"; then
		mapfile -t gemdirs < <("$gem" environment gempath | tr ':' '\n')
		for gemdir in "${gemdirs[@]}"; do
			PATH="$gemdir/bin:$PATH"
		done
	fi
}

# =====================================
# Configuration

source "$DOROTHY/sources/config.bash"

# arguments provides:
export shell="${1-}"

# environment provides:
# DOROTHY

# editors.bash provies:
# TERMINAL_EDITORS, GUI_EDITORS
# these are loaded prior to env.bash, as we do not want to export them
load_dorothy_config 'editors.bash'

# environment.bash provides:
# NVM_DIR, HOMEBREW_ARCH, PYENV_VERSION, RUBY_VERSION
# and other overrides

# load env.bash now, so that
# any exported variables changed from now on are echo'd at finish
source "$DOROTHY/sources/env.bash"

# =====================================
# Prepare

# reset paths and flags
export PATH="$DOROTHY/commands:/usr/sbin:/usr/bin:/sbin:/bin"
export MANPATH='/usr/share/man' INFOPATH='/usr/share/info' CLASSPATH='' LDFLAGS='' CPPFLAGS='' PKG_CONFIG_PATH=''

# reset editor
export LANG LC_CTYPE TERMINAL_EDITOR TERMINAL_EDITOR_PROMPT GUI_EDITOR GUI_EDITOR_PROMPT EDITOR

# XDG
# https://wiki.archlinux.org/title/XDG_Base_Directory
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}"
export XDG_BIN_HOME="${XDG_BIN_HOME:-"$HOME/.local/bin"}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-"$HOME/.local/share"}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-"$HOME/.local/state"}"
# XDG_RUNTIME_DIR must be created by the system, as it is a special directory
# ^ these will probably result in duplicates, however, `env.bash` will trim them

# =====================================
# Configuration

# prepare hooks, and load user ovverrides
function before_dorothy_paths {
	return
}
function after_dorothy_paths {
	return
}
function after_everything {
	return
}
load_dorothy_config 'environment.bash'

# =====================================
# Environment

# XDG compiled properties
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-"$XDG_DATA_HOME:/usr/local/share:/usr/share"}"
export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS:-"$XDG_CONFIG_HOME:/etc/xdg"}"

# Flatpak
if test -d '/var/lib/flatpak/exports/share'; then
	XDG_DATA_DIRS="/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
fi
if test -d "$XDG_DATA_HOME/flatpak/exports/share"; then
	XDG_DATA_DIRS="$XDG_DATA_HOME/flatpak/exports/share:$XDG_DATA_DIRS"
fi

# Xcode
if test -d "/Applications/Xcode.app/Contents/Developer/usr/bin"; then
	PATH="/Applications/Xcode.app/Contents/Developer/usr/bin:$PATH"
fi

# Snap
if test -d "/snap/bin"; then
	PATH="/snap/bin:$PATH"
fi

# Homebrew, UNIX
if test -d "/usr/local/bin"; then
	PATH="/usr/local/bin:$PATH"
fi
if test -d "/usr/local/sbin"; then
	PATH="/usr/local/sbin:$PATH"
fi
if test -d "/usr/local/man"; then
	MANPATH="/usr/local/man:$MANPATH"
fi

# Homebrew
if is-mac; then
	export HOMEBREW_ARCH HOMEBREW_PREFIX HOMEBREW_CELLAR HOMEBREW_REPOSITORY HOMEBREW_SHELLENV_PREFIX
	if test -z "${HOMEBREW_ARCH-}"; then
		if test "$(uname -p)" = 'arm' -o "$(uname -m)" = 'arm64'; then
			HOMEBREW_ARCH='arm64e'
		else
			HOMEBREW_ARCH='x86_64'
		fi
	fi
	if test -z "${HOMEBREW_PREFIX-}"; then
		if test "$HOMEBREW_ARCH" = 'arm64e'; then
			HOMEBREW_PREFIX='/opt/homebrew'
		else
			HOMEBREW_PREFIX='/usr/local'
		fi
	fi
	if test -z "${HOMEBREW_CELLAR-}"; then
		if test -x "${HOMEBREW_PREFIX}/bin/brew"; then
			HOMEBREW_CELLAR="$("${HOMEBREW_PREFIX}/bin/brew" --cellar)"
		else
			HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
		fi
	fi
	if test -z "${HOMEBREW_REPOSITORY-}"; then
		if test -x "${HOMEBREW_PREFIX}/bin/brew"; then
			HOMEBREW_REPOSITORY="$("${HOMEBREW_PREFIX}/bin/brew" --repo)"
		else
			HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
		fi
	fi
	if test -z "${HOMEBREW_SHELLENV_PREFIX-}"; then
		HOMEBREW_SHELLENV_PREFIX="$HOMEBREW_PREFIX"
	fi
fi

# if homebrew is installed, then add its paths
if test -x "${HOMEBREW_PREFIX-}/bin/brew"; then
	# linux
	export HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-"/usr/local"}"

	# /usr/local already added to PATH, so only add these if different
	if test "$HOMEBREW_PREFIX" != '/usr/local'; then
		if test -d "$HOMEBREW_PREFIX/bin"; then
			PATH="$HOMEBREW_PREFIX/bin:$PATH"
		fi
		if test -d "$HOMEBREW_PREFIX/sbin"; then
			PATH="$HOMEBREW_PREFIX/sbin:$PATH"
		fi
	fi

	# add the rest
	if test -d "$HOMEBREW_PREFIX/share/man"; then
		MANPATH="$HOMEBREW_PREFIX/share/man:$MANPATH"
	fi
	if test -d "$HOMEBREW_PREFIX/share/info"; then
		INFOPATH="$HOMEBREW_PREFIX/share/info:$INFOPATH"
	fi

	# for compilers to find homebrew
	if test -d "$HOMEBREW_PREFIX/lib"; then
		LDFLAGS="-L$HOMEBREW_PREFIX/lib $LDFLAGS"
	fi
	if test -d "$HOMEBREW_PREFIX/include"; then
		CPPFLAGS="-I$HOMEBREW_PREFIX/include $CPPFLAGS"
	fi
	if test -d "$HOMEBREW_PREFIX/lib/pkgconfig"; then
		PKG_CONFIG_PATH="$HOMEBREW_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
	fi

	# llvm
	if test -d "$HOMEBREW_PREFIX/opt/llvm/bin"; then
		p="$HOMEBREW_PREFIX/opt/llvm"
		PATH="$p/bin:$PATH"
		# for compilers to find llvm
		if test -d "$p/lib"; then
			LDFLAGS="-L$p/lib $LDFLAGS"
		fi
		if test -d "$p/include"; then
			CPPFLAGS="-I$p/include $CPPFLAGS"
		fi
	fi

	# SQLite (dependency of python)
	if test -d "$HOMEBREW_PREFIX/opt/sqlite/bin"; then
		p="$HOMEBREW_PREFIX/opt/sqlite"
		PATH="$p/bin:$PATH"
		# for compilers to find sqlite
		if test -d "$p/lib"; then
			LDFLAGS="-L$p/lib $LDFLAGS"
		fi
		if test -d "$p/include"; then
			CPPFLAGS="-I$p/include $CPPFLAGS"
		fi
		# for pkg-config to find sqlite
		if test -d "$p/lib/pkgconfig"; then
			PKG_CONFIG_PATH="$p/lib/pkgconfig $PKG_CONFIG_PATH"
		fi
	fi

	# guile (dependency of something)
	if test -d "$HOMEBREW_PREFIX/share/guile"; then
		export GUILE_LOAD_PATH="$HOMEBREW_PREFIX/share/guile/site/3.0"
		export GUILE_LOAD_COMPILED_PATH="$HOMEBREW_PREFIX/lib/guile/3.0/site-ccache"
		export GUILE_SYSTEM_EXTENSIONS_PATH="$HOMEBREW_PREFIX/lib/guile/3.0/extensions"
	fi

	# icu4c (dependency of heroku)
	if test -d "$HOMEBREW_PREFIX/opt/icu4c/bin"; then
		PATH="$HOMEBREW_PREFIX/opt/icu4c/bin:$PATH"
	fi
	if test -d "$HOMEBREW_PREFIX/opt/icu4c/sbin"; then
		PATH="$HOMEBREW_PREFIX/opt/icu4c/sbin:$PATH"
	fi

	# Sphinx (dependency of ruby)
	if test -d "$HOMEBREW_PREFIX/opt/sphinx-doc/bin"; then
		PATH="$HOMEBREW_PREFIX/opt/sphinx-doc/bin:$PATH"
	fi

	# GetText (dependency of gpg)
	if test -d "$HOMEBREW_PREFIX/opt/gettext/bin"; then
		PATH="$HOMEBREW_PREFIX/opt/gettext/bin:$PATH"
	fi

	# Ruby
	if test -n "${HOMEBREW_RUBY_VERSION-}"; then
		p=''
		if test "$HOMEBREW_RUBY_VERSION" = 'default'; then
			p="$HOMEBREW_PREFIX/opt/ruby"
		else
			p="$HOMEBREW_PREFIX/opt/ruby@$HOMEBREW_RUBY_VERSION"
		fi
		if test ! -d "$p/bin"; then
			echo "# specified HOMEBREW_RUBY_VERSION was not found at $p" >/dev/stderr
		else
			PATH="$p/bin:$PATH"
			rubygems "$p/bin/gem"
			# for compilers to find ruby
			if test -d "$p/lib"; then
				LDFLAGS="-L$p/lib $LDFLAGS"
			fi
			if test -d "$p/include"; then
				CPPFLAGS="-I$p/include $CPPFLAGS"
			fi
			# for pkg-config to find ruby
			if test -d "$p/lib/pkgconfig"; then
				PKG_CONFIG_PATH="$p/lib/pkgconfig:$PKG_CONFIG_PATH"
			fi
		fi
	else
		# add them all, exlcuding special paths
		mapfile -t rubydirs < <(expand-path "$HOMEBREW_PREFIX/opt/ruby*/bin")
		for rubydir in "${rubydirs[@]}"; do
			PATH="$rubydir:$PATH"
			rubygems "$rubydir/gem"
		done
	fi

	# Node
	mapfile -t nodedirs < <(expand-path "$HOMEBREW_CELLAR/node/*/bin")
	for nodedir in "${nodedirs[@]}"; do
		PATH="$nodedir:$PATH"
	done

	# Python
	# https://docs.brew.sh/Homebrew-and-Python
	if test -d "$HOMEBREW_PREFIX/opt/python/libexec/bin"; then
		PATH="$HOMEBREW_PREFIX/opt/python/libexec/bin:$PATH"
	fi

	# Python: Pip
	mapfile -t pipdirs < <(expand-path "$HOME/Library/Python/*/bin")
	for pipdir in "${pipdirs[@]}"; do
		PATH="$pipdir:$PATH"
	done

	# OpenSSL (dependency of python, gpg, and node)
	# openssl is a symlink to whatever directory has the latest version
	if test -d "$HOMEBREW_PREFIX/opt/openssl/bin"; then
		p="$HOMEBREW_PREFIX/opt/openssl"
		PATH="$p/bin:$PATH"
		if test -d "$p/lib"; then
			LDFLAGS="-L$p/lib $LDFLAGS"
		fi
		if test -d "$p/include"; then
			CPPFLAGS="-I$p/include $CPPFLAGS"
		fi
		if test -d "$p/lib/pkgconfig"; then
			PKG_CONFIG_PATH="$p/lib/pkgconfig:$PKG_CONFIG_PATH"
		fi
		# ^^ setup-util-gocryptfs needs this on macos big sur
		# ```
		# Package libcrypto was not found in the pkg-config search path.
		# Perhaps you should add the directory containing `libcrypto.pc'
		# to the PKG_CONFIG_PATH environment variable
		# No package 'libcrypto' found
		# pkg-config: exit status 1
		# ```
		# and
		# ```
		# ld: library not found for -lcrypto
		# clang: error: linker command failed with exit code 1 (use -v to see invocation)
		# ````
	fi

	# NSS
	if test -d "$HOMEBREW_PREFIX/opt/nss/bin"; then
		PATH="$HOMEBREW_PREFIX/opt/nss/bin:$PATH"
	fi

	# Anaconda
	if test -d "$HOMEBREW_PREFIX/anaconda3/bin"; then
		PATH="$HOMEBREW_PREFIX/anaconda3/bin:$PATH"
	fi

	# Heroku
	if test -d "$HOMEBREW_PREFIX/heroku/bin"; then
		PATH="$HOMEBREW_PREFIX/heroku/bin:$PATH"
	fi

else
	rubygems "$(which gem)"
fi

# NVM
if test -z "${NVM_DIR-}" -a -d "$HOME/.nvm"; then
	export NVM_DIR="$HOME/.nvm"
fi

# Python: pyenv
if test -z "${PYENV_ROOT-}" -a -d "$HOME/.pyenv"; then
	export PYENV_ROOT="$HOME/.pyenv"
fi
if test -n "${PYENV_ROOT-}"; then
	PATH="$PYENV_ROOT/bin:$PATH"
	PATH="$PYENV_ROOT/shims:$PATH"
fi

# Rust: rustup
if test -z "${RUSTUP_HOME-}" -a -d "$HOME/.rustup"; then
	export RUSTUP_HOME="$HOME/.rustup"
fi

# Rust: cargo
if test -z "${CARGO_HOME-}" -a -d "$HOME/.cargo"; then
	export CARGO_HOME="$HOME/.cargo"
fi
if test -n "${CARGO_HOME-}"; then
	mkdir -p "$CARGO_HOME"
	PATH="$CARGO_HOME/bin:$PATH"

	# Rust: cargo target
	# workaround for ubuntu server, which /tmp may often be read-only
	# https://doc.rust-lang.org/stable/cargo/guide/build-cache.html
	export CARGO_TARGET_DIR
	mkdir -p "${CARGO_TARGET_DIR:="$CARGO_HOME/target"}"
fi

# Go
# https://pkg.go.dev/cmd/go#hdr-Environment_variables
# only define GOPATH, defining GOROOT and GOBIN cause too many errors on linux
# such as incorrect "is not in GOROOT" errors
if command-exists go; then
	export GOPATH
	# detect GOPATH if not defined
	if test -z "${GOPATH-}"; then
		# fetch the go bin paths
		if test -n "${HOMEBREW_CELLAR-}"; then
			# mac
			mapfile -t gopaths < <(expand-path "$HOMEBREW_CELLAR/go/*")
			for gopath in "${gopaths[@]}"; do
				GOPATH="$gopath"
				break # only do the first
			done
		elif test -d "$HOME/go"; then
			# linux
			GOPATH="$HOME/go"
		fi
	fi
	# if we were able to find one
	if test -n "${GOPATH-}"; then
		# then create its parts and add it to PATH
		mkdir -p "$GOPATH/bin"
		mkdir -p "$GOPATH/libexec"
		PATH="$GOPATH/bin:$PATH"
	fi
fi

# Clojurescript
if test -d "$HOME/.clojure/clojure-1.8"; then
	PATH="$HOME/.clojure/clojure-1.8.0:$PATH"
	CLASSPATH="$HOME/.clojure/clojure-1.8.0:$CLASSPATH"
fi

# Yarn
if command-exists yarn; then
	PATH="$(yarn global bin):$PATH"
fi

# Flossbank
if test -d "$HOME/.flossbank/bin"; then
	PATH="$HOME/.flossbank/bin:$PATH"
fi

# Geneics: Java
CLASSPATH=".:$CLASSPATH"

# Generics: pip, pipx
# python get-pip.py --user
# even though this is the same as non-custom XDG_BIN_HOME,
# add it anyway in the case it is different,
# `env.bash` will remove any duplicates anyway
if test -d "$HOME/.local/bin"; then
	PATH="$HOME/.local/bin:$PATH"
fi

# Generics: XDG, always add, even if not existent, in case it is created later
PATH="$XDG_BIN_HOME:$PATH"

# Scripts
before_dorothy_paths
PATH="$DOROTHY/commands:$PATH"
PATH="$DOROTHY/user/commands:$PATH"
PATH="$DOROTHY/user/commands.local:$PATH"
after_dorothy_paths

# Generics: manual local commands
if test -d "$HOME/.bin"; then
	PATH="$HOME/.bin:$PATH"
fi
if test -d "$HOME/bin"; then
	PATH="$HOME/bin:$PATH"
fi

# =====================================
# Finish

# Load the last user hook, to complete the environment configuration
after_everything

# =====================================
# Editor

# Now that the environment is configured, we can now configure the editor, as it is possible to be detected now that paths are setup.

# LANG, LC_CTYPE
if test -z "${LANG-}"; then
	LANG='en_US.UTF-8'
fi
if test -z "${LC_CTYPE-}"; then
	LC_CTYPE="$LANG"
fi

# TERMINAL_EDITOR, TERMINAL_EDITOR_PROMPT
if test -n "${TERMINAL_EDITOR-}"; then
	if test -z "${TERMINAL_EDITOR_PROMPT-}"; then
		TERMINAL_EDITOR_PROMPT="$TERMINAL_EDITOR"
	fi
else
	# we do `|| test`` here instead of `-o`, because if TERMINAL_EDITORS is unbound, then the array length check will fail
	# which is what the `-z ...` initial check is prevent
	if test -z "${TERMINAL_EDITORS-}" || test "${#TERMINAL_EDITORS[@]}" -eq 0; then
		stderr echo "# cannot set terminal editor, as TERMINAL_EDITORS was undefined"
	else
		for prompt in "${TERMINAL_EDITORS[@]}"; do
			name="${prompt%% *}"
			if command-exists "$name"; then
				TERMINAL_EDITOR="$name"
				TERMINAL_EDITOR_PROMPT="$prompt"
				break
			fi
		done
	fi
fi

# GUI_EDITOR, GUI_EDITOR_PROMPT
if test -n "${GUI_EDITOR-}"; then
	if test -z "${GUI_EDITOR_PROMPT-}"; then
		GUI_EDITOR_PROMPT="$GUI_EDITOR"
	fi
else
	# we do `|| test`` here instead of `-o`, because if GUI_EDITORS is unbound, then the array length check will fail
	# which is what the `-z ...` initial check is prevent
	if test -z "${GUI_EDITORS-}" || test "${#GUI_EDITORS[@]}" -eq 0; then
		stderr echo "# cannot set gui editor, as GUI_EDITORS was undefined"
	else
		for prompt in "${GUI_EDITORS[@]}"; do
			name="${prompt%% *}"
			if command-exists "$name"; then
				GUI_EDITOR="$name"
				GUI_EDITOR_PROMPT="$prompt"
				break
			fi
		done
	fi
fi

# Checks
if test -z "${EDITOR-}"; then
	if test -n "${TERMINAL_EDITOR_PROMPT-}"; then
		EDITOR="$TERMINAL_EDITOR_PROMPT"
	else
		stderr echo "# EDITOR was not set, as TERMINAL_EDITOR/TERMINAL_EDITORS had no valid values"
	fi
fi
