#!/usr/bin/env bash
source "$BDIR/sources/essentials.sh"
source "$BDIR/sources/strict.bash"

# Check
if ! command-exists apm; then
	stderr echo ''
	stderr echo 'Atom (apm) does not seem to be installed...'
	exit
fi

# Correct settings
echo ''
echo 'Symlinking Atom settings...'
SOURCE="$BDIR/users/$(whoami)/atom"
TARGET="$HOME/.atom"
ln-make "$SOURCE/config.cson" "$TARGET/config.cson"
ln-make "$SOURCE/styles.less" "$TARGET/styles.less"
echo '...success'

# Update
echo 'Updating existing Atom plugins...'
apm update --no-confirm
echo '...success'

# Install
echo ''
echo 'Installing Atom plugins...'
ok apm install "${ATOM_INSTALL[@]}"
echo '...success'
