#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/ogham/exa
# ls alternative

env CLI=exa \
	APT=exa \
	APK=exa \
	BREW=exa \
	CARGO=exa \
	DNF=exa \
	EMERGE='sys-apps/exa' \
	NIX=exa \
	PACMAC=exa \
	PKG=exa \
	PORT=exa \
	XBPS=exa \
	ZYPPER=exa \
	setup-util
