#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/strict.bash"

# Install python if necessary
echo -e "\nEnsuring python is installed..."
env CLI=python \
	APK=python \
	APT=python \
	BREW=python \
	PACMAN=python \
	YUM=python \
	setup-util

# Reload paths
echo -e '\nReload paths to ensure python is detected...'
source "$DOROTHY/sources/paths.sh"

# Helper
function act {
	echo -e "\nInstalling $# pip packages..."
	for arg in "$@"; do
		env NAME="pip:$arg" PIP="$arg" setup-util pip
	done
}

# Ensure pip exists
if ! pipp --version; then
	echo "Could not find pip, installing it manually..."
	d="$(mktemp -d)"
	cd "$d" || exit 1
	# python outputs the version to stderr, so we have to redirect stderr to stdout for it to be captured
	if [[ "$(python --version 2>&1)" = 'Python 2.7.'* ]]; then
		down 'https://bootstrap.pypa.io/pip/2.7/get-pip.py' --destination='get-pip.py'
	else
		down 'https://bootstrap.pypa.io/get-pip.py' --destination='get-pip.py'
	fi
	python get-pip.py --user
fi

# Reload Paths
echo -e '\nReload paths and install latest pip tooling...'
source "$DOROTHY/sources/paths.sh"
act pip setuptools

# Reload Paths
echo -e '\nReload paths for latest pip tooling...'
source "$DOROTHY/sources/paths.sh"

# Install
if test -v 'PYTHON_INSTALL'; then
	act "${PYTHON_INSTALL[@]}"
fi

# Done
echo -e '\nInstalled python and its pips successfully. ✅'
