#!/usr/bin/env bash

# https://zsh.sourceforge.io

# https://packages.debian.org/sid/amd64/zsh/filelist
# /bin/rzsh
# /bin/zsh
# /bin/zsh5

function setup_util_zsh() (
	source "$DOROTHY/sources/bash.bash"

	# options
	local option_reconfigure='yes'
	__flag --target={option_reconfigure} --name='reconfigure' --affirmative --coerce -- "$@"

	# helpers
	function __reconfigure {
		# if reconfigure is not desired, or if not installed, then don't reconfigure
		if [[ $option_reconfigure == 'no' ]] || __command_missing -- zsh; then
			return 0
		fi

		# https://zsh.sourceforge.io/Intro/intro_3.html
		# `.zshenv` needs to be in `$HOME` but all others inside `$ZDOTDIR`
		# `$ZDOTDIR` guaranteed by `setup-environment-commands`
		fs-mkdir -- "$ZDOTDIR" || return $? # required for opensuse
		fs-move -- "$ZDOTDIR/.zshenv" "$HOME/.zshenv" || return $?
		fs-move -- "$HOME/.zprofile" "$ZDOTDIR/.zprofile" || return $?
		fs-move -- "$HOME/.zshrc" "$ZDOTDIR/.zshrc" || return $?
		fs-move -- "$HOME/.zlogin" "$ZDOTDIR/.zlogin" || return $?
		fs-move -- "$HOME/.zlogout" "$ZDOTDIR/.zlogout" || return $?
		config-helper --file="$HOME/.zshenv" -- \
			--find='ZDOTDIR=.+' --replace="ZDOTDIR='$ZDOTDIR'" || return $?
	}

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check --cli=zsh; then
		__reconfigure
		return 0
	fi

	# https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH
	local options=(
		--name='zsh'
		--cli='zsh'
		"$@"
		APK='zsh'
		APT='zsh'
		AUR='zsh'
		BREW='zsh'
		BSD='zsh'
		EMERGE='zsh'
		EOPKG='zsh'
		PORT='zsh'
		RPM='zsh'
		XBPS='zsh'
		ZYPPER='zsh'
	)
	setup-util "${options[@]}"
	__reconfigure
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_zsh "$@"
fi
