#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://wiki.manjaro.org/index.php/Pamac

function setup-util-pamac() (
	# check for linux
	if ! is-linux; then
		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
		return 0
	fi

	# install pamac
	setup-util "$@" NAME='pamac' CLI='pamac' \
		PACMAN='pamac-cli'

	# capture exit from --optional and --confirm
	if ! command-exists pamac; then
		return 0
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-pamac "$@"
fi
