#!/usr/bin/env bash

# https://github.com/ali-rantakari/trash
# only provides [trash] binary

# https://packages.debian.org/sid/amd64/trash-cli/filelist
# /usr/bin/trash
# /usr/bin/trash-empty
# /usr/bin/trash-list
# /usr/bin/trash-put
# /usr/bin/trash-restore
# /usr/bin/trash-rm

# ubuntu also has [gio trash ...]

function setup_util_trash() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists trash; then
		return 0
	fi

	# setup
	local options=(
		--cli='trash'
		"$@"
		APT='trash-cli' # UBUNTU
		BREW='trash'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_trash "$@"
fi
