#!/usr/bin/env bash

# https://en.wikipedia.org/wiki/File_(command)
# https://pkgs.alpinelinux.org/package/edge/main/x86_64/file
# https://github.com/file/file
# https://pubs.opengroup.org/onlinepubs/9699919799/utilities/file.html

# https://repology.org/project/file/versions

function setup_util_file() (
	source "$DOROTHY/sources/bash.bash"

	# no apk
	local options=(
		--name='File type identification utility'
		--cli='file'
		"$@"
		APK='file'
		APT='file'
		AUR='file'
		BREW='file'
		EMERGE='sys-apps/file'
		NIX='nixpkgs.file'
		RPM='file'
		SCOOP='file'
		URPMI='file'
		XBPS='file'
		ZYPPER='file'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_file "$@"
fi
