#!/usr/bin/env bash

# https://github.com/vigna/ne
# https://github.com/vigna/ne/blob/master/INSTALL.md

function setup-util-ne() (
	source "$DOROTHY/sources/bash.bash"

	# no apk
	setup-util "$@" --name='ne, the nice editor' --cli='ne' \
		APT='ne' \
		BREW='ne'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-ne "$@"
fi
