#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-strongbox() (
	setup-util "$@" CLI=strongbox \
		GO='github.com/uw-labs/strongbox'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-strongbox "$@"
fi
