#!/usr/bin/env bash

# https://github.com/rrthomas/recode
# https://github.com/rrthomas/recode/issues/28
# https://pkgs.alpinelinux.org/packages?name=recode

# https://repology.org/project/recode/versions
# https://pkgs.org/search/?q=recode&on=name
# https://release-monitoring.org/project/4176/
function setup-util-recode() (
	source "$DOROTHY/sources/bash.bash"

	setup-util "$@" --cli='recode' \
		APT='recode' \
		APK='recode' \
		AUR='recode' \
		BREW='recode' \
		RPM='recode'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-recode "$@"
fi
