#!/usr/bin/env bash

# https://github.com/imsnif/bandwhich
# bandwidth monitor

# https://github.com/imsnif/bandwhich/releases
# bandwhich-v0.20.0-x86_64-unknown-linux-musl.tar.gz

# https://repology.org/project/bandwhich/versions

function setup_util_bandwhich() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists bandwhich; then
		return 0
	fi

	# setup
	local arch options=(
		--cli='bandwhich'
		"$@"
		AUR='bandwhich' # ARCH
		BREW='bandwhich'
		BSD='bandwhich'
		CARGO='bandwhich'
		DNF_COPR='atim/bandwhich'
		DNF='bandwhich' # FEDORA
		NIX='nixpkgs.bandwhich'
		XBPS='bandwhich' # VOID
	)
	function get_github_asset_url {
		github-download \
			--dry \
			--slug='imsnif/bandwhich' \
			--release='latest' \
			--asset-filter="$(echo-escape-regex "$1")$" | echo-first-line || :
	}
	function add_download_option {
		options+=(
			DOWNLOAD="$(get_github_asset_url "$1")"
			DOWNLOAD_UNZIP_FILTER='**/bandwhich'
		)
	}
	arch="$(get-arch)"
	if is-linux && test "$arch" = 'x64'; then
		add_download_option 'x86_64-unknown-linux-musl.tar.gz'
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_bandwhich "$@"
fi
