#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# install
if is-brew; then
	brew install rustup
elif command-exists rustup; then
	rustup update
else
	# https://rust-lang.github.io/rustup/installation/other.html
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path
fi
