#!/usr/bin/env bash

# brew/macos version
# https://github.com/ali-rantakari/trash
# only provides [trash] binary

# debian/ubuntu version
# https://github.com/andreafrancia/trash-cli
# https://packages.debian.org/sid/amd64/trash-cli/filelist
# /usr/bin/trash
# /usr/bin/trash-empty
# /usr/bin/trash-list
# /usr/bin/trash-put
# /usr/bin/trash-restore
# /usr/bin/trash-rm

# ubuntu also has [gio trash ...]

function setup_util_trash() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--cli='trash'
		"$@"
		APT='trash-cli' # UBUNTU
		BREW='trash'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_trash "$@"
fi
