#!/usr/bin/env bash

# https://deno.land/#installation
# https://github.com/denoland/deno_install

# https://github.com/denoland/deno/releases
# deno-aarch64-apple-darwin.zip
# deno-aarch64-unknown-linux-gnu.zip
# deno-x86_64-apple-darwin.zip
# deno-x86_64-pc-windows-msvc.zip
# deno-x86_64-unknown-linux-gnu.zip
# denort-aarch64-apple-darwin.zip
# denort-aarch64-unknown-linux-gnu.zip
# denort-x86_64-apple-darwin.zip
# denort-x86_64-pc-windows-msvc.zip
# denort-x86_64-unknown-linux-gnu.zip

# https://github.com/LukeChannings/deno-arm64/releases
# deno-linux-arm64.zip

# arm64
# https://github.com/denoland/deno/issues/4862
# https://github.com/LukeChannings/deno-arm64
# now mainlined

# https://repology.org/project/deno/versions

# Note that for Alpine, Alpine uses musl, whereas Deno only provides gnu builds, as such executing the gnu build on Alpine fails with 127
# https://github.com/denoland/deno_docker/issues/240 - request for apk package
# https://github.com/denoland/deno/issues/3711 - request for musl build
# https://pkgs.alpinelinux.org/packages?name=deno - community build for alpine

function setup_util_deno() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='deno'
		# Don't use the official yet stupid `INSTALLER='https://deno.land/install.sh'`, unlike `setup-util`, it ignores XDG and dumps the bin in `$HOME/.deno/bin/deno` with nothing else in `$HOME/.deno` except that bin, making it useless without slow clutter of env modifications
		# Don't use `SNAP='deno'` without `--classic` as it faces `Permission denied (os error 13)` when running on scripts outside the snap <https://github.com/denoland/deno/issues/5816>
		# However, don't use `SNAP='deno --classic'` either as `--classic` is ignored sometimes with `Warning: flag --classic ignored for strictly confined snap deno`
		APK_REPO='http://dl-cdn.alpinelinux.org/alpine/edge/community'
		APK='deno'
		AUR='deno'
		BREW='deno'
		PORT='deno'
		SCOOP='deno'
		WINGET='DenoLand.Deno'
	)
	# cargo fails on windows: https://github.com/bevry/dorothy/actions/runs/16106748853/job/45443438885
	if ! __is_windows; then
		util_options+=(CARGO='deno')
	fi

	# check if deno is installed via snap, if so, uninstall it
	# if `--classic` worked, we could do ` | grep --quiet --extended-regexp --regexp='classic$'` however --classic doesn't work either
	setup-util "${util_options[@]}" --dependency uninstall --source='snap' SNAP='deno'

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='denoland/deno' glob='deno' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" 'deno-aarch64-apple-darwin.zip' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" 'deno-x86_64-apple-darwin.zip' "$glob" || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" 'deno-aarch64-unknown-linux-gnu.zip' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" 'deno-x86_64-unknown-linux-gnu.zip' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_deno "$@"
fi
