#!/usr/bin/env bash

# Remove old linux kernels
# https://launchpad.net/linux-purge

function setup_util_linux_purge() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if is-needle --quiet "$@" && ! is-needle --upgrade "$@" && ! is-needle --uninstall "$@" && command-exists linux-purge; then
		return 0
	fi

	# setup
	local options=(
		--cli='linux-purge'
		"$@"
		DOWNLOAD='https://git.launchpad.net/linux-purge/plain/linux-purge'
	)
	setup-util "${options[@]}"

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_linux_purge "$@"
fi
