#!/usr/bin/env bash

# https://github.com/showcases/fonts
# https://github.com/todylu/monaco.ttf

function setup_util_source_code_pro() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='Source Code Pro'
		--font='SourceCodePro-*'
		CASK='font-source-code-pro'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	__fetch_and_add_download_option_via_slug_regexp_glob 'adobe-fonts/source-code-pro' '^[OT]TF-' '**/*.{otf,ttf}' || return $?

	# setup
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_source_code_pro "$@"
fi
