#!/usr/bin/env bash

# https://fishshell.com
# https://github.com/fish-shell/fish-shell

# https://github.com/fish-shell/fish-shell/releases
# fish-4.3.3-linux-aarch64.tar.xz
# fish-4.3.3-linux-x86_64.tar.xz
# fish-4.3.3.app.zip
# fish-4.3.3.pkg
# fish-4.3.3.tar.xz
# fish-4.3.3.tar.xz.asc

# https://repology.org/project/fish/versions

function setup_util_fish() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--name='Fish Shell'
		--cli='fish'
		"$@"
		APK='fish'
		APT_REPO='ppa:fish-shell/release-4'
		APT='fish'
		AUR='fish'
		BREW='fish'
		BSD='fish'
		DNF='fish'
		EMERGE='fish'
		EOPKG='fish'
		GUIX='fish'
		NIX='fish'
		PORT='fish'
		XBPS='fish-shell'
		ZYPPER_REPO='https://download.opensuse.org/repositories/shells:fish:release:4/openSUSE_Tumbleweed/shells:fish:release:4.repo'
		ZYPPER='fish'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_fish "$@"
fi
