#!/usr/bin/env bash

# https://github.com/ScoopInstaller/Scoop#installation
# https://github.com/ScoopInstaller/Scoop/wiki/Uninstalling-Scoop

function setup_util_scoop() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='Scoop'
		--cli='scoop'
		CUSTOM_INSTALL_EVAL='__scoop_install'
		CUSTOM_UPGRADE_EVAL='__scoop_upgrade'
		CUSTOM_UNINSTALL_EVAL='__scoop_uninstall'
	)
	function __scoop_install {
		powershell.exe -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser; Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression' || return $?
	}
	function __scoop_upgrade {
		scoop update || return $?
	}
	function __scoop_uninstall {
		scoop uninstall scoop || return $?
	}
	setup_util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_scoop "$@"
fi
