#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-coreutils() (
	# ls, sort, head, realpath, etc.
	# https://gnu.org/software/coreutils
	setup-util "$@" --optional --name='Core Utilities' \
		APK='coreutils' \
		APT='coreutils' \
		AUR='coreutils' \
		BREW='coreutils' \
		RPM='coreutils' \
		ZYPPER='coreutils'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-coreutils "$@"
fi
