#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# check
if ! is-apk; then
	echo-style --notice="[$0] is for systems with [apk] installed, skipping." >/dev/stderr
	exit 0
fi

# =====================================
# Start

echo-segment --h1='Setup APK'

# =====================================
# Configuration

source "$DOROTHY/sources/config.sh"

# setup.bash provides:
APK_INSTALL=()
load_dorothy_config 'setup.bash'

# =====================================
# Packages

# install
function install_apk_bulk() {
	echo-segment --h2="Install $# apk packages"
	if test "$#" -ne 0; then
		env NAME="apk:$*" APK="$*" setup-util apk
	fi
	echo-segment --g2="Install $# apk packages"
}
install_apk_bulk "${APK_INSTALL[@]}"

# =====================================
# Done

echo-segment --g1="Setup APK"
