#!/usr/bin/env bash

function setup_linux_raspi_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- setup-linux-raspi --help
)

function setup_linux_raspi() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	# @todo new install/update/reconfigure
	function __help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Configure Linux on Raspberry Pis to our expectations.

			USAGE:
			\`setup-linux-raspi [install|update]\`
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item action=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') __help ;;
		'--'*) __help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*)
			if [[ -z $action ]]; then
				action="$item"
			else
				__help 'An unrecognised argument was provided: ' --variable-value={item}
			fi
			;;
		esac
	done

	# =====================================
	# Checks

	# check that an accident has not occurred
	if ! is-raspi; then
		__help 'This command is only purposeful on Raspberry Pi, which you are not running.' || :
		return 46 # EPFNOSUPPORT 46 Protocol family not supported
	fi

	# =====================================
	# Action

	# log
	__print_style --h1='Raspberry Pi Essentials'

	# ensure raspi firmware is up to date
	# otherwise newer operating system releases can cause issues

	# install necessary packages
	if is-system --apt; then
		setup-util --name='Raspberry Pi Firmware' \
			APT='rpi-eeprom'
		setup-util --name='Raspberry Pi Configurator' \
			APT='raspi-config'

		# get the latest raspberry pi kernel, however this could introduce bugs
		# use to be necessary to fix this issue, but that is now in the stable kernel
		# https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1946368/comments/48
		if [[ $action == 'install' ]] && confirm --linger --negative --ppid="$$" -- 'Install the proposed Raspberry Pi Kernel?' 'This can fix issues while introducing new issues. Install only if you are currently facing an issue.'; then
			setup-util --name='Proposed Raspberry Pi Kernel' \
				APT='linux-raspi'
		fi

		# Various kernel modules have been moved from the linux-modules-raspi package in order to reduce the initramfs size. This results in several applications (most notably Docker, bug 1947601 1) failing due to missing kernel modules.
		# https://discourse.ubuntu.com/t/impish-indri-release-notes/21951
		# despite docs saying `linux-modules-extra-rapsi`, that doesn't exist, it is actually `linux-modules-extra-raspi` exists
		if [[ $action == 'install' ]] && confirm --linger --negative --ppid="$$" -- 'Install the extra Raspberry Pi Modules?' 'This can fix issues while introducing new issues. Install only if you need them, such as working with Docker.'; then
			# this should coincide with setup-util-docker
			setup-util --optional --name='Raspberry Pi Modules' \
				APT='linux-modules-extra-raspi'
		fi
	fi

	# ensure autoupdates on restart
	# don't actually do --enable, as it is not needed for this for some reason
	service-helper --ignore --unmask -- rpi-eeprom-update

	# prompt an update on next restart
	if eval-helper --elevate -- rpi-eeprom-update -a | grep --fixed-strings --regexp=reboot; then
		__print_lines 'An eeprom update is pending for your Raspberry Pi, to continue further you must reboot your machine.'
		return 1
	fi

	__print_style --g1='Raspberry Pi Essentials'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		setup_linux_raspi_test
	else
		setup_linux_raspi "$@"
	fi
fi
