#!/usr/bin/env bash
source "$BDIR/sources/essentials.sh"
source "$BDIR/sources/strict.bash"

# Check
if ! command-exists go; then
	stderr echo -e '\nPlease install go before running this...'
	exit
fi

# Helper
function goinstall() {
	for ARG in "$@"; do
		ok go get -u -v "$ARG"
	done
}

# Install extensions
if is-present "${GO_INSTALL:-}" && confirm-negative "Install go packages?"; then
	echo -e '\nInstalling go packages...'
	goinstall "${GO_INSTALL[@]}"
	echo '...success'
fi

# Update All
if is-present "${GO_INSTALL:-}" && confirm-negative "Update all go packages?"; then
	ok go get -u -v all
fi

# Linter
if command-exists gometalinter && confirm-negative "Complete gometalinter installation?"; then
	ok gometalinter --install
fi
