#!/usr/bin/env bash

# https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html
# https://forum.manjaro.org/t/howto-reboot-turn-off-your-frozen-computer-reisub-reisuo/3855?u=balupton

function setup_linux_recovery() (
	source "$DOROTHY/sources/bash.bash"

	# assert compatibility
	if ! is-linux; then
		echo-style --stderr --notice="[$0] is only intended to be run on Linux systems, skipping."
		return 0
	fi
	if is-wsl; then
		echo-style --stderr --notice="[$0] is not applicable on WSL, skipping."
		return 0
	fi
	if is-alpine; then
		echo-style --stderr --notice="[$0] is not applicable on Alpine, skipping."
		return 0
	fi

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Configure Linux with Recovery Hotkeys.

			USAGE:
			setup-linux-recovery
		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Action

	echo-style --h1='Update GRUB with Recovery Hotkeys'

	config-helper --elevate --file='/etc/sysctl.d/99-sysctl.conf' -- \
		--field='kernel.sysrq' --no-quote --value=1

	if grub-helper; then
		__print_lines '💁🏼‍♀️ If your Linux machine ever locks up, you can follow the instructions here to safely shutdown/reboot: 💁🏼‍♀️'
		echo-style '    ' --code='https://forum.manjaro.org/t/3855?u=balupton'
	else
		echo-style --stderr --error='Failed to upgrade grub with the recovery options. Please send a PR to Dorothy to add support. Continuing...'
	fi

	echo-style --g1='Update GRUB with Recovery Hotkeys'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_linux_recovery "$@"
fi
