#!/usr/bin/env bash

# <https://www.gnu.org/software/wget/>
# <https://en.wikipedia.org/wiki/Wget>
# `wget2` and `wget` are different projects: <https://gitlab.com/gnuwget/wget2/-/wikis/Home#different-behavior-of-wget2>
# `wget2` fails to return failure exit status, so is not suitable for `down`

# <https://packages.debian.org/sid/amd64/wget/filelist>
# /usr/bin/wget

# <https://repology.org/project/wget/versions>
# <https://repology.org/project/wget1/versions>

# wget [option]... [URL]...
# -t, --tries=NUMBER           set number of retries to NUMBER (0 unlimits)
# -O, --output-document=FILE   write documents to FILE
# -o, --output-file=FILE       log messages to FILE
# -N, --timestamping           don't re-retrieve files unless newer than local
#                              WARNING: timestamping does nothing in combination with -O. See the manual for details.
# -c, --continue               resume getting a partially-downloaded file
# -q, --quiet                  quiet (no output)
# -v, --verbose                be verbose (this is the default)
# -nv, --no-verbose            turn off verbose, without being quiet, keep error messages
# -S, --server-response        Print the headers sent by HTTP servers and responses sent by FTP servers.
# --waitretry=SECONDS          wait 1..SECONDS between retries of a retrieval
# --unlink                     remove file before clobber
# --user=USER                  set both ftp and http user to USER
# --password=PASS              set both ftp and http password to PASS
# --retry-connrefused          Consider "connection refused" a transient error and try again.
# --progress=type              With --progress=dot:giga, each dot represents 1M retrieved (so each line contains 32M).
#                              With --progress=bar:noscroll, Wget can be forced to display as much of the filename as possible without scrolling through it, if you add `:force` it does not fallback to `dot` if output is not the TTY.
# --show-progress              Force wget to display the progress bar in any verbosity.
#                              By default, wget only displays the progress bar in verbose mode.
#                              One may however, want wget to display the progress bar on screen in conjunction with any other verbosity modes like --no-verbose or --quiet.
#                              This is often a desired a property when invoking wget to download several small/large files.
#                              In such a case, wget could simply be invoked with this parameter to get a much cleaner output on the screen.
#                              This option will also force the progress bar to be printed to stderr when used alongside the --output-file option.

# BusyBox v1.37.0 (2025-01-17 18:12:01 UTC) multi-call binary.
# Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR] [--post-data STR | --post-file FILE] [-Y on/off] [-P DIR] [-U AGENT] [-T SEC] URL...
# Retrieve files via HTTP or FTP
# --spider           Only check URL existence: $? is 0 if exists
# --header STR       Add STR (of form 'header: value') to headers
# --post-data STR    Send STR using POST method
# --post-file FILE   Send FILE using POST method
# -c                 Continue retrieval of aborted transfer
# -q                 Quiet
# -P DIR             Save to DIR (default .)
# -S                 Show server response
# -T SEC             Network read timeout is SEC seconds
# -O FILE            Save to FILE ('-' for stdout)
# -o LOGFILE         Log messages to FILE
# -U STR             Use STR for User-Agent header
# -Y on/off          Use proxy

function setup_util_wget() (
	source "$DOROTHY/sources/bash.bash"

	# fedora wget is wget1 so need wget1
	local cli='wget' alt=()
	if is-fedora; then
		cli='wget1'
		alt+=(
			RPM='wget1' # Fedora, fedora aliases wget to wget2, which is broken as wget2 does not return failure exit status, so attempt to enforce wget1
		)
	else
		alt+=(
			DNF='wget' # OpenMandriva, AlmaLinux
		)
	fi

	# setup
	# @todo figure out installers for other platforms
	local options=(
		--name='Wget'
		--cli="$cli"
		"$@"
		"${alt[@]}"
		APK='wget'
		APT='wget'
		AUR='wget'
		BREW='wget'
		EMERGE='net-misc/wget'
		NIX='nixpkgs.wget'
		URPMI='wget'
		WINGET='Wget'
		XBPS='wget'
		ZYPPER='wget'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_wget "$@"
fi
