#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/strict.bash"

# Remove nvm
rm -Rf ~/.nvm

# Reconfigure shells for the lack of brew, by trimming the brew shells
t="$(mktemp)"
sudo bash <<EOF
grep -v "${HOMEBREW_PREFIX:-/usr/local}" /etc/shells > "$t"
cat "$t" > /etc/shells
rm "$t"
EOF

# Set the default shell to a non-brew shell
if command-exists /bin/zsh; then
    usesh /bin/zsh
elif command-exists /bin/bash; then
    usesh /bin/bash
elif command-exists /bin/sh; then
    usesh /bin/sh
fi

# Remove brew
if is-brew; then
    arch -${HOMEBREW_ARCH:-x86_64} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
else
    echo 'brew appears uninstalled already'
fi

# Reconfigure git for the lack of brew
export GIT_PROTOCOL=manual
setup-git
export GIT_PROTOCOL=''
