#!/usr/bin/env bash

# https://github.com/junegunn/fzf
# fuzzy finder

# https://github.com/junegunn/fzf/releases
# fzf-0.60.3-darwin_amd64.tar.gz
# fzf-0.60.3-darwin_arm64.tar.gz
# fzf-0.60.3-freebsd_amd64.tar.gz
# fzf-0.60.3-linux_amd64.tar.gz
# fzf-0.60.3-linux_arm64.tar.gz
# fzf-0.60.3-linux_armv5.tar.gz
# fzf-0.60.3-linux_armv6.tar.gz
# fzf-0.60.3-linux_armv7.tar.gz
# fzf-0.60.3-linux_loong64.tar.gz
# fzf-0.60.3-linux_ppc64le.tar.gz
# fzf-0.60.3-linux_s390x.tar.gz
# fzf-0.60.3-openbsd_amd64.tar.gz
# fzf-0.60.3-windows_amd64.zip
# fzf-0.60.3-windows_arm64.zip
# fzf-0.60.3-windows_armv5.zip
# fzf-0.60.3-windows_armv6.zip
# fzf-0.60.3-windows_armv7.zip

# https://packages.debian.org/sid/amd64/fzf/filelist
# /usr/bin/fzf
# /usr/bin/fzf-tmux

function setup_util_fzf() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='fzf'
		APK='fzf'
		APT='fzf'
		AUR='fzf'
		BREW='fzf'
		RPM='fzf'
		EMERGE='app-shells/fzf'
		NIX='nixpkgs.fzf'
		PKG='fzf'
		PKGADD='fzf'
		PKGIN='fzf'
		SCOOP='fzf'
		WINGET='fzf'
		XBPS='fzf'
		ZYPPER='fzf'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# setup
	local slug='junegunn/fzf' glob='fzf' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-darwin_amd64.tar.gz' "$glob" || :
		elif [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-darwin_arm64.tar.gz' "$glob" || :
		fi
	elif __is_linux; then
		if [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-linux_amd64.tar.gz' "$glob" || :
		elif [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-linux_arm64.tar.gz' "$glob" || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-linux_armv7.tar.gz' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_fzf "$@"
fi
