#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/pemistahl/grex
# regexp builder

setup-util "$@" CLI='grex' \
	BREW='grex' \
	CARGO='grex' \
	CHOCO='grex' \
	HUBER='grex' \
	SCOOP='grex'
