#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/splitlines.bash"
source "$DOROTHY/sources/user.sh"

# Shell
lsh="${1-}"

# Helpers
function vdel {
	if test "$lsh" = "fish"; then
		echo "set --universal --erase $1;"
	else
		echo "export $1=\"\";"
	fi
}
function vadd {
	if test "$lsh" = "fish"; then
		echo "set --export --path --prepend $1 \"$2\";"
	else
		if test -z "${!1-}"; then
			echo "export $1=\"$2\";"
		else
			echo "export $1=\"$2:\$$1\";"
		fi
	fi
}
function vset {
	if test "$lsh" = "fish"; then
		vdel "$1"
		echo "set --export $1 \"$2\";"
	else
		echo "export $1=\"$2\";"
	fi
}
function rubygems {
	vset GEM_HOME "$HOME/.gem"
	if "$DOROTHY/commands/command-exists" "$1"; then
		rubydirs="$("$1" environment gempath | tr ":" "\n")"
		for i in $rubydirs; do
			vadd PATH "$i/bin"
		done
	fi
}

# Reset
vdel PATH
vadd PATH "/bin"
if "$DOROTHY/commands/is-admin"; then
	vadd PATH "/sbin"
fi
vadd PATH "/usr/bin"
if "$DOROTHY/commands/is-admin"; then
	vadd PATH "/usr/sbin"
fi

# Ruby Gem Preparation
vset GEM_HOME "$HOME/.gem"

# Xcode
if "$DOROTHY/commands/is-dir" "/Applications/Xcode.app/Contents/Developer/usr/bin"; then
	vadd PATH "/Applications/Xcode.app/Contents/Developer/usr/bin"
fi

# Snap
if "$DOROTHY/commands/is-dir" "/snap/bin"; then
	vadd PATH "/snap/bin"
fi

# Homebrew, UNIX
if "$DOROTHY/commands/is-dir" "/usr/local/bin"; then
	vadd PATH "/usr/local/bin"
fi
if "$DOROTHY/commands/is-admin" && "$DOROTHY/commands/is-dir" "/usr/local/sbin"; then
	vadd PATH "/usr/local/sbin"
fi
if "$DOROTHY/commands/is-dir" "/usr/local/man"; then
	vadd MANPATH "/usr/local/man"
fi

# Homebrew
if "$DOROTHY/commands/is-brew"; then
	if test -z "${HOMEBREW_PREFIX-}"; then
		export HOMEBREW_PREFIX; HOMEBREW_PREFIX="/usr/local"
		# HOMEBREW_PREFIX="$(brew --prefix)"
	fi
	# if test -z "${HOMEBREW_CELLAR-}"; then
	# 	export HOMEBREW_CELLAR; HOMEBREW_CELLAR="$("$HOMEBREW_PREFIX/bin/brew" --cellar)"
	# fi

	# Build
	# vadd LDFLAGS "-L$HOMEBREW_PREFIX/lib"
	# vadd CPPFLAGS "-I$HOMEBREW_PREFIX/include"
	# vadd PKG_CONFIG_PATH "$HOMEBREW_PREFIX/lib/pkgconfig"

	# Heroku
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/heroku/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/heroku/bin"
	fi

	# Ruby
	if test -n "${RUBY_VERSION-}" && "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/ruby@$RUBY_VERSION/bin"; then
		p="$HOMEBREW_PREFIX/opt/ruby@$RUBY_VERSION"
		vadd PATH "$p/bin"
		rubygems "$p/bin/gem"
	elif "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/ruby/bin"; then
		p="$HOMEBREW_PREFIX/opt/ruby"
		vadd PATH "$p/bin"
		rubygems "$p/bin/gem"
		# for compilers to find ruby
		# vadd LDFLAGS "-L$p/lib"
		# vadd CPPFLAGS "-I$p/include"
		# vadd PKG_CONFIG_PATH "$p/lib/pkgconfig"
	else
		rubydirs="$("$DOROTHY/commands/expand-path" "$HOMEBREW_PREFIX/opt/ruby*/bin")"
		for rubydir in $rubydirs; do
			vadd PATH "$rubydir"
			rubygems "$rubydir/gem"
		done
	fi

	# icu4c (dependency of heroku)
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/icu4c/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/icu4c/bin"
	fi
	if "$DOROTHY/commands/is-admin" && "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/icu4c/sbin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/icu4c/sbin"
	fi

	# Sphinx (dependency of ruby)
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/sphinx-doc/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/sphinx-doc/bin"
	fi

	# GetText (dependency of gpg)
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/gettext/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/gettext/bin"
	fi

	# Node
	nodedirs="$("$DOROTHY/commands/expand-path" "$HOMEBREW_PREFIX/Cellar/node/*/bin")"
	for nodedir in $nodedirs; do
		vadd PATH "$nodedir"
	done

	# Python
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/python/libexec/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/python/libexec/bin"
	fi

	# Python: Pip
	pipdirs="$("$DOROTHY/commands/expand-path" "$HOME/Library/Python/*/bin")"
	for pipdir in $pipdirs; do
		vadd PATH "$pipdir"
	done

	# SQLite (dependency of python)
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/sqlite/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/sqlite/bin"
		# For compilers to find sqlite you may need to set
		# vadd LDFLAGS "-L$HOMEBREW_PREFIX/opt/sqlite/lib"
		# vadd CPPFLAGS "-I$HOMEBREW_PREFIX/opt/sqlite/include"
		# For pkg-config to find sqlite you may need to set
		# vadd PKG_CONFIG_PATH "$HOMEBREW_PREFIX/opt/sqlite/lib/pkgconfig"
	fi

	# OpenSSL (dependency of python, gpg, and node)
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/openssl/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/openssl/bin"
	fi

	# NSS
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/opt/nss/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/opt/nss/bin"
	fi

	# Anaconda
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/anaconda3/bin"; then
		vadd PATH "$HOMEBREW_PREFIX/anaconda3/bin"
	fi

	# guile (dependency of something)
	if "$DOROTHY/commands/is-dir" "$HOMEBREW_PREFIX/share/guile"; then
		vset GUILE_LOAD_PATH "$HOMEBREW_PREFIX/share/guile/site/3.0"
		vset GUILE_LOAD_COMPILED_PATH "$HOMEBREW_PREFIX/lib/guile/3.0/site-ccache"
		vset GUILE_SYSTEM_EXTENSIONS_PATH "$HOMEBREW_PREFIX/lib/guile/3.0/extensions"
	fi
else
	rubygems "gem"
fi

# Ubuntu Python Pip and perhaps other generics
# python get-pip.py --user
if "$DOROTHY/commands/is-dir" "$HOME/.local/bin"; then
	vadd PATH "$HOME/.local/bin"
fi

# NVM
if "$DOROTHY/commands/is-dir" "$HOME/.nvm"; then
	vset NVM_DIR "$HOME/.nvm"
fi

# Rust
if "$DOROTHY/commands/is-dir" "$HOME/.rustup"; then
	vset RUSTUP_HOME  "$HOME/.rustup"
fi
if "$DOROTHY/commands/is-dir" "$HOME/.cargo/bin"; then
	vadd PATH "$HOME/.cargo/bin"
	vset CARGO_HOME "$HOME/.cargo"
fi

# Go
if "$DOROTHY/commands/command-exists" go; then
	# root: where go is installed
	export GOROOT; GOROOT="$("$DOROTHY/commands/echo-or-fail" go env GOROOT || "$DOROTHY/commands/first-path" "${HOMEBREW_CELLAR-}/go")"
	if "$DOROTHY/commands/is-dir" "$GOROOT/libexec"; then
		GOROOT="$GOROOT/libexec"
	fi
	vset GOROOT "$GOROOT"

	# path: where modules are installed
	export GOPATH; GOPATH="$("$DOROTHY/commands/echo-or-fail" go env GOPATH || "$DOROTHY/commands/echo-mkdirp" "$HOME/go")"
	vset GOPATH "$GOPATH"
	if "$DOROTHY/commands/is-dir" "$GOPATH/bin"; then
		vadd PATH "$GOPATH/bin"
	fi

	# bin: where the execs are
	export GOBIN; GOBIN="$("$DOROTHY/commands/echo-or-fail" go env GOBIN || "$DOROTHY/commands/echo-dir" "$GOROOT/bin")"
	vset GOBIN "$GOBIN"
	vadd PATH "$GOBIN"
fi

# Java
vadd CLASSPATH "."

# Clojurescript
if "$DOROTHY/commands/is-dir" "$HOME/.clojure/clojure-1.8"; then
	vadd PATH "$HOME/.clojure/clojure-1.8.0"
	vadd CLASSPATH "$HOME/.clojure/clojure-1.8.0"
fi

# Yarn
if "$DOROTHY/commands/command-exists" yarn; then
	vadd PATH "$(yarn global bin)"
fi

# Flossbank
if "$DOROTHY/commands/is-dir" "$HOME/.flossbank/bin"; then
	vadd PATH "$HOME/.flossbank/bin"
fi

# Scripts
vadd PATH "$DOROTHY/commands"
vadd PATH "$DOROTHY/user/commands"

# Local
if "$DOROTHY/commands/is-dir" "$HOME/.bin"; then
	vadd PATH "$HOME/.bin"
fi
if "$DOROTHY/commands/is-dir" "$HOME/bin"; then
	vadd PATH "$HOME/bin"
fi
