#!/usr/bin/env bash

# https://github.com/greymd/teip
# https://github.com/greymd/teip/releases
# cut alternative

# teip-1.2.1.x86_64-apple-darwin.tar.gz
# teip-1.2.1.x86_64-unknown-linux-musl.deb
# teip-1.2.1.x86_64-unknown-linux-musl.rpm
# teip-1.2.1.x86_64-unknown-linux-musl.tar.gz

# arm64
# https://github.com/greymd/teip/issues/23

function setup-util-teip() (
	source "$DOROTHY/sources/strict.bash"

	# determine github args if github is an option on this platform
	local arch github_asset_filter='' github=()
	arch="$(get-arch)"
	if is-mac; then
		github_asset_filter='.x86_64-apple-darwin.tar.gz'
	elif test "$arch" = 'x64'; then
		github_asset_filter='.x86_64-unknown-linux-musl.tar.gz'
	fi
	if test -n "$github_asset_filter"; then
		github+=(
			GITHUB_SLUG='greymd/teip'
			GITHUB_RELEASE='latest'
			GITHUB_ASSET_FILTER="$github_asset_filter"
			GITHUB_UNZIP_FILTER='**/bin/teip'
			GITHUB_FILENAME='teip'
		)
	fi

	# install, preferring github
	setup-util "$@" --cli='teip' --order='github ...' \
		"${github[@]}" \
		BREW='greymd/tools/teip' \
		CARGO='teip'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-teip "$@"
fi
