#!/usr/bin/env bash

function setup-util-pv() (
	source "$DOROTHY/sources/strict.bash"

	setup-util "$@" --cli='pv' \
		APT='pv' \
		BREW='pv'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-pv "$@"
fi
