#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# Git
env NAME='git' CLI='git' \
	APK='git' \
	APT='git' \
	BREW='git' \
	PACMAN='git' \
	PAMAC='git' \
	setup-util

# https://en.wikipedia.org/wiki/OpenSSH
# @todo figure out the installers for other platforms
env NAME='OpenSSH' CLI='sshd' OPTIONAL='yes' \
	BREW='openssh' \
	setup-util

# Diff/Merge Tool: meld
# http://meldmerge.org
# https://yousseb.github.io/meld/
# https://coderefinery.github.io/installation/difftools/
env NAME='Meld' CLI='meld' OPTIONAL='yes' \
	APT='meld' \
	DNF='meld' \
	CASK='meld' \
	setup-util

# Diff/Merge Tool: delta
setup-util-delta

# Diff/Merge Tool: diff
# https://www.gnu.org/s/diffutils/
env CLI='diff' OPTIONAL='yes' \
	APT='diffutils' \
	BREW='diffutils' \
	setup-util

# Git SSHFS
# https://en.wikipedia.org/wiki/SSHFS
env NAME='SSHFS' CLI='sshfs' OPTIONAL='yes' \
	APT='sshfs' \
	BREW='sshfs' \
	PACMAN='sshfs' \
	setup-util

# Git LFS
# https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md
env NAME='Git Large File Storage' CLI='git-lfs' OPTIONAL='yes' \
	APT='git-lfs' \
	BREW='git-lfs' \
	YUM='git-lfs' \
	setup-util

# GPG
# https://pkgs.org/download/gnupg
# on brew, `gpg`, `gp2`, and `gnupg` are all the same
env NAME='GnuPG' CLI='gpg' OPTIONAL='yes' \
	APT='gnupg' \
	BREW='gnupg' \
	PACMAN='gnupg' \
	setup-util

# Pinentry
# https://www.gnupg.org/related_software/pinentry/
# https://github.com/GPGTools/pinentry
# https://gpgtools.org/
# on brew, `pinentry` replaces `pinentry-mac` and `gpg-suite-pinentry`
env NAME='Pinentry' CLI='pinentry' OPTIONAL='yes' \
	BREW='pinentry' \
	setup-util
# @todo figure out linux options

# Ensure Directories
mkdir -p "$HOME/.ssh" "$HOME/.gnupg"
