#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/ajeetdsouza/zoxide
# z/cd alternative

# apt option is requires debian testing, instead of debian stable

function setup-util-zoxide() (
	setup-util "$@" NAME='zoxide' CLI='z' \
		AUR='zoxide-bin' \
		APK='zoxide' \
		BREW='zoxide' \
		CARGO='zoxide' \
		CONDA_CHANNEL='conda-forge' \
		CONDA='zoxide' \
		DNF_COPR='atim/zoxide' \
		DNF='zoxide' \
		NIX='nixpkgs.zoxide' \
		XBPS='zoxide' \
		EMERGE_EVAL='
		eselect repository enable dm9pZCAq
		emerge --sync dm9pZCAq
		emerge app-shells/zoxide
	'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-zoxide "$@"
fi
