#!/usr/bin/env bash

# https://github.com/astral-sh/uv?tab=readme-ov-file#installation
# pyenv alternative

# https://github.com/astral-sh/uv/releases
# uv-aarch64-apple-darwin.tar.gz
# uv-aarch64-pc-windows-msvc.zip
# uv-aarch64-unknown-linux-gnu.tar.gz
# uv-aarch64-unknown-linux-musl.tar.gz
# uv-arm-unknown-linux-musleabihf.tar.gz
# uv-armv7-unknown-linux-gnueabihf.tar.gz
# uv-armv7-unknown-linux-musleabihf.tar.gz
# uv-i686-pc-windows-msvc.zip
# uv-i686-unknown-linux-gnu.tar.gz
# uv-i686-unknown-linux-musl.tar.gz
# uv-installer.ps1
# uv-installer.sh
# uv-powerpc64-unknown-linux-gnu.tar.gz
# uv-powerpc64le-unknown-linux-gnu.tar.gz
# uv-s390x-unknown-linux-gnu.tar.gz
# uv-x86_64-apple-darwin.tar.gz
# uv-x86_64-pc-windows-msvc.zip
# uv-x86_64-unknown-linux-gnu.tar.gz
# uv-x86_64-unknown-linux-musl.tar.gz

function setup_util_uv() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='uv'
		--cli='uv' --cli='uvx'
		# despite docs, no apk
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='astral-sh/uv' glob='*/{uv,uvx}' arch
	arch="$(__get_arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-apple-darwin.tar.gz' "$glob" || :
		else
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-apple-darwin.tar.gz' "$glob" || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-unknown-linux-musl.tar.gz' "$glob" || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-armv7-unknown-linux-musleabihf.tar.gz' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-unknown-linux-musl.tar.gz' "$glob" || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-i686-unknown-linux-musl.tar.gz' "$glob" || :
		fi
	elif __is_windows; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-pc-windows-msvc.zip' "$glob" || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-pc-windows-msvc.zip' "$glob" || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-i686-pc-windows-msvc.zip' "$glob" || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_uv "$@"
fi
