#!/usr/bin/env bash

# https://github.com/BLAKE3-team/BLAKE3/releases/tag/1.8.2
# b3sum_linux_x64_bin
# b3sum_macos_x64_bin
# b3sum_windows_x64_bin.exe

# https://github.com/rhash/RHash <-- only available via brew, brew version lags behind, only 1.4.6 and above supports blake3, but brew is 1.4.5

# https://repology.org/project/b3sum/versions

function setup_util_b3sum() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=b3sum "$@"; then
		return 0
	fi

	# despite docs, no apk
	local arch options=(
		--cli='b3sum'
		"$@"
		BREW='b3sum' # blake3 is the c implementation
		CARGO='b3sum'
		APK='b3sum'
		AUR='b3sum'
		RPM='b3sum'
		ZYPPER='b3sum'
		SCOOP='b3sum'
		VOID='b3sum'
	)
	function get_github_asset_url {
		github-download \
			--dry \
			--slug='BLAKE3-team/BLAKE3' \
			--latest \
			--asset-regexp="$(echo-escape-regexp -- "$1")$" | echo-first-line || :
	}
	function add_download_option {
		local url
		url="$(get_github_asset_url "$1" || :)"
		options+=(DOWNLOAD="$url")
	}
	arch="$(get-arch)"
	if is-mac; then
		add_download_option '_macos_x64_bin'
	elif is-linux; then
		if [[ $arch == 'x64' ]]; then
			add_download_option '_linux_x64_bin'
		fi
	elif is-windows; then
		if [[ $arch == 'x64' ]]; then
			add_download_option '_windows_x64_bin.exe'
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_b3sum "$@"
fi
