#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/screen/filelist
# /usr/bin/screen

function setup_util_screen() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='screen'
		APK='screen'
		APT='screen'
		BREW='screen'
		RPM='screen'
		ZYPPER='screen'
	)
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_screen "$@"
fi
