#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# =====================================
# Checks

# check that an accident has not occured
if ! is-gnome; then
	echo-style --notice="[$0] is for Linux systems with [gnome] installed, skipping." >/dev/stderr
	exit 0
fi

# =====================================
# Action

setup-util "$@" NAME='Gnome Software' CLI='gnome-software' \
	APT='gnome-software' \
	PAMAC='gnome-software'
