#!/usr/bin/env bash

function setup_util_krypton() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--name='Krypton'
		--cli='krgpg'
		"$@"
		INSTALLER='https://krypt.co/kr'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_krypton "$@"
fi
