#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# Desktop
# https://support.1password.com/install-linux/
# https://support.1password.com/betas/?linux
# https://releases.1password.com/linux/beta/#1password-for-linux-8.6.0-68
# https://1password.community/discussion/comment/631532#Comment_631532

# CLI
# https://app-updates.agilebits.com/product_history/CLI
# https://app-updates.agilebits.com/product_history/CLI2

# Browser
# https://app-updates.agilebits.com/product_history/B5X
# https://support.1password.com/betas/#install-a-beta-release-of-the-1password-extension

# Prefer BETA, as it has less exceptions

# Snap/Flatpak STABLE exceptions:
# You’ll need to lock and unlock 1Password in your browser separately from the app.
# You won’t be able to unlock 1Password or 1Password CLI with system authentication.
# You won’t be able to use the SSH agent.

# Snap/Flatpak BETA exceptions:
# You’ll need to lock and unlock 1Password in your browser separately from the app.
# You won’t be able to unlock 1Password with system authentication.

function setup-util-1password() (
	local temp_dir arch
	arch="$(get-arch)"

	# invoke via setup-util
	if test "${SETUP_UTIL-}" != 'yes'; then
		setup-util "$@" --name='1Password App' --app='1Password' \
			INSTALLER="${BASH_SOURCE:-"$0"}"
		return "$?"
	fi

	# =================================
	# Desktop App

	# install desktop
	set -x # <inform the user of why they are being prompted for a sudo password>
	if is-mac; then
		setup-util "$@" --name='1Password App' \
			CASK_TAP='homebrew/cask-versions' \
			CASK='homebrew/cask-versions/1password-beta'
	elif test "$arch" = 'a64'; then
		temp_dir="$(fs-temp --directory='setup-util-1password' --directory)"
		pushd "$temp_dir" >/dev/null
		curl -sSO https://downloads.1password.com/linux/tar/beta/aarch64/1password-latest.tar.gz
		tar -xf 1password-latest.tar.gz
		sudo mkdir -p /opt/1Password
		sudo mv -fv 1password-*/* /opt/1Password
		sudo /opt/1Password/after-install.sh
		popd >/dev/null
		rm -rf "$temp_dir"
	elif is-apt; then
		sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22 /usr/share/debsig/keyrings/AC2D62742012EA22
		curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
		curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
		setup-util "$@" --name='1Password App' \
			APT='1password' \
			APT_KEY='https://downloads.1password.com/linux/keys/1password.asc' \
			APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://downloads.1password.com/linux/debian/amd64 beta main'
	elif command-exists rpm && command-exists dnf; then
		sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
		cat <<-EOF | sudo tee /etc/yum.repos.d/1password.repo
			[1password]
			name=1Password Beta Channel
			baseurl=https://downloads.1password.com/linux/rpm/beta/\$basearch
			enabled=1
			gpgcheck=1
			repo_gpgcheck=1
			gpgkey="https://downloads.1password.com/linux/keys/1password.asc"
		EOF
		setup-util "$@" --name='1Password App' \
			DNF='1password'
	elif is-arch; then
		temp_dir="$(fs-temp --directory='setup-util-1password' --directory)"
		curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
		git clone https://aur.archlinux.org/1password-beta.git "$temp_dir"
		pushd "$temp_dir" >/dev/null
		makepkg -si
		popd >/dev/null
		rm -rf "$temp_dir"
	elif is-snap; then
		setup-util "$@" --name='1Password App' \
			SNAP='1password --beta'
	elif is-flatpak; then
		setup-util "$@" --name='1Password App' \
			FLATPAK='https://downloads.1password.com/linux/flatpak/1Password-beta.flatpakref'
	else
		temp_dir="$(fs-temp --directory='setup-util-1password' --directory)"
		pushd "$temp_dir" >/dev/null
		curl -sSO https://downloads.1password.com/linux/tar/beta/x86_64/1password-latest.tar.gz
		tar -xf 1password-latest.tar.gz
		sudo mkdir -p /opt/1Password
		sudo mv -fv 1password-*/* /opt/1Password
		sudo /opt/1Password/after-install.sh
		popd >/dev/null
		rm -rf "$temp_dir"
	fi
	set +x # </inform>

	# =================================
	# Browser

	cat <<-EOF
		Install the 1Password Browser extension by vising the following URLs:

		In Brave, Chrome, Edge, visit:
			$(echo-style --code='https://chrome.google.com/webstore/detail/1password-beta-%E2%80%93-password/khgocmkkpikpnmmkgmdnfckapcdkgfaf')

		In Firefox, visit:
			$(echo-style --code='https://1password.com/browsers/beta/firefox/')
	EOF
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-1password "$@"
fi
