#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/sharkdp/bat
# cat alternative

env CLI=bat \
	APT=bat \
	APK=bat \
	BREW=bat \
	CARGO=bat \
	CHOCO=bat \
	DNF=bat \
	NIX=bat \
	PACMAN=bat \
	PKG=bat \
	PORT=bat \
	SCOOP=bat \
	XBPS=bat \
	ZYPPER=bat \
	setup-util
