#!/usr/bin/env bash

# https://repology.org/project/tree/versions <-- missing

function setup_util_tree() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='tree'
		APK='tree'
		APT='tree'
	)
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_tree "$@"
fi
