#!/usr/bin/env bash

# https://github.com/httpie/httpie
# https://httpie.io/docs/cli/installation

# https://github.com/httpie/cli/releases
# httpie-3.2.2.deb

# https://packages.debian.org/sid/amd64/httpie/filelist
# /usr/bin/http
# /usr/bin/httpie
# /usr/bin/https

function setup_util_httpie() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists http; then
		return 0
	fi

	# no apk
	local options=(
		--name='HTTPie'
		--cli='http'
		"$@"
		APT='httpie' # UBUNTU
		AUR='httpie' # ARCH
		BREW='httpie'
		EMERGE='httpie' # GENTOO
		EOPKG='httpie'  # SOLUS
		PIP='httpie'
		PORT='httpie'
		RPM='httpie'    # FEDORA
		ZYPPER='httpie' # SUSE
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_httpie "$@"
fi
