#!/usr/bin/env bash

# https://en.wikipedia.org/wiki/Wget

# https://packages.debian.org/sid/amd64/wget/filelist
# /usr/bin/wget

function setup_util_wget() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists wget; then
		return 0
	fi

	# @todo figure out installers for other platforms
	local options=(
		--name='Wget'
		--cli='wget'
		"$@"
		APK='wget'
		APT='wget'
		BREW='wget'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_wget "$@"
fi
