#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/ogham/exa
# ls alternative

function setup-util-exa() (
	setup-util "$@" CLI='exa' \
		APT='exa' \
		APK='exa' \
		BREW='exa' \
		CARGO='exa' \
		DNF='exa' \
		EMERGE='sys-apps/exa' \
		NIX='exa' \
		PACMAC='exa' \
		PKG='exa' \
		PORT='exa' \
		XBPS='exa' \
		ZYPPER='exa'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-exa "$@"
fi
