#!/usr/bin/env bash

# Vivaldi does not appear to be open-source

# https://vivaldi.com

# https://vivaldi.com/download/
# https://vivaldi.com/wp-content/vivaldi-versions.js?ver=1767772724
# https://vivaldi.com/wp-content/vivaldi-versions.js

# https://flathub.org/en/apps/com.vivaldi.Vivaldi

# https://repology.org/project/vivaldi/versions

function setup_util_vivaldi() (
	source "$DOROTHY/sources/util.bash"
	source "$(type -P setup-util)" # enable *_EVAL
	util_options=(
		--name='Vivaldi'
		--app='Vivaldi'
		--app='vivaldi-stable' # .desktop
		--app='vivaldi-bin'
		--configure-eval='__configure'
		SCOOP_BUCKET='extras'
		SCOOP='vivaldi'
		WINGET='Vivaldi.Vivaldi'
		EMERGE='www-client/vivaldi'
		FLATPAK='com.vivaldi.Vivaldi'
		NIX='vivaldi-stable'
		SNAP='vivaldi'
	)
	function __configure {
		if [[ $SETUP_UTIL__INSTALLED == 'yes' ]]; then
			# 1Password
			if setup-util-1password is-installed; then
				# https://www.1password.community/discussions/1password/browser---desktop-integration-vivaldi-on-linux-doesnt-work/97383
				fs-make --root='/etc/1password' --file='custom_allowed_browsers' --root --append-line='vivaldi-bin' --reason='Your password is required to momentarily grant privileges to enable 1Password Desktop integration with Vivaldi:' || return $?
			fi

			# AdGuard for Linux / AdGuard CLI
			# https://github.com/AdguardTeam/AdGuardCLI/issues/105#issuecomment-3712047838
			if setup-util-adguard-cli is-installed; then
				local browsers_config_path="$XDG_DATA_HOME/adguard-cli/browsers.yaml"
				if [[ -f $browsers_config_path ]]; then
					config-helper --file="$browsers_config_path" -- \
						--find=$'^- name: vivaldi-bin\n  action: default' --replace=$'- name: vivaldi-bin\n  action: default'
				fi
			fi
		fi
	}

	# fetch and use configuration
	if ! __is_windows; then
		# improve performance for detectable utilities when fetching asset configuration
		if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
			return 0
		fi

		# fetch and use configuration
		local arch json
		arch="$(__get_arch)"
		json="$(fetch 'https://vivaldi.com/wp-content/vivaldi-versions.js' | echo-regexp --regexp='^[^{]+' --replace='' || :)"
		if [[ -n $json ]]; then
			function __add_json_property_option {
				local property="$1"
				echo-json decode --property="$property" -- "$json"
			}
			function __add_download_app_option {
				local property="$1" url
				url="$(__add_json_property_option "$property")" || return $?
				util_options+=(
					DOWNLOAD="$url"
					DOWNLOAD_ARCHIVE_GLOB='*/Vivaldi.app'
					DOWNLOAD_FILENAME='Vivaldi.app'
				)
			}
			function __add_deb_option {
				local property="$1" url
				url="$(__add_json_property_option "$property")" || return $?
				util_options+=(DEB="$url")
			}
			function __add_rpm_option {
				local property="$1" url
				url="$(__add_json_property_option "$property")" || return $?
				util_options+=(RPM="$url")
			}
			if __is_macos; then
				__add_download_app_option 'vivaldi_version_mac'
			elif __is_linux; then
				if [[ $arch == 'x64' ]]; then
					__add_deb_option 'vivaldi_version_deb64' || :
					__add_rpm_option 'vivaldi_version_rpm64' || :
				elif [[ $arch == 'a64' ]]; then
					__add_deb_option 'vivaldi_version_arm64' || :
					__add_rpm_option 'vivaldi_version_arm64_rpm' || :
				fi
			fi
		fi
	fi

	# setup
	setup_util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_vivaldi "$@"
fi
