#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# get the latest release
tag="$(github-latest-release 'rfjakob/gocryptfs')"

# setup a temporary directory
tdir="$(mktemp -d)"

# shallow clone the repo, quietly
git clone --quiet --depth 1 --branch "$tag" 'https://github.com/rfjakob/gocryptfs.git' "$tdir"

# enter into it
cd "$tdir" || exit 1

# build from source
chmod +x ./build.bash
./build.bash
# this installs a copy of the binary file to
# "$GOPATH1/bin"

# the go path is not available to sudo, so make a copy that is
sudo mkdir -p '/usr/local/bin'
sudo cp ./gocryptfs '/usr/local/bin/gocryptfs'
sudo chmod +x '/usr/local/bin/gocryptfs'

# cleanup
cd "$HOME" || exit 1
rm -Rf "$tdir"
