#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# check that an accident has not occured
if ! is-mac; then
	echo-color --error='[setup-mac] is only intended to be run on macOS systems...'
	exit 2
fi

# Make sure CLI tools are installed
echo-color --h2='Ensuring Apple Command Line Tool are installed...'
while true; do
	if ! xcode-select --install; then
		echo-color --g2='...Apple Command Line Tool are installed.'
		break
	else
		confirm "Press any key once the Apple Command Line Tool have been installed"
	fi
done

# Make sure Xcode license is accepted
if get-app 'Xcode' || get-app 'Xcode-beta'; then
	echo-color --h2='Ensuring the Xcode license is accepted...'
	sudo xcodebuild -license
	echo-color --g2='...Xcode license accepted.'
fi

# action
echo
action="$(choose-option --question='Do you want to install or update this system?' --filter="${1-}" -- 'install' 'update' || echo "${1:-install}")" # or condition here is for bash v3, which choose-option will fail on, as bash v3 does not yet support arrays

# log
echo-color --h1="The $action of the macOS system has commenced... ⏲"

# dorothy
setup-dorothy "$action"

# mac
setup-mac-brew "$action"                 # setup-util-devel done as part of this
source "$DOROTHY/sources/environment.sh" # ensure the updated bash is available to what comes after
if test "$action" = 'install'; then
	setup-mac-apps
	setup-mac-fonts
fi

# cross-platform
setup-extras "$action"

# cleanup
setup-mac-clean

# log
echo $'\n' --g1="The $action of the macOS system has completed successfully! ✅"

# restore
if test "$action" = 'install'; then
	echo ''
	if confirm-bool "Would you like to also restore from backup?"; then
		macos-state restore
	fi
	echo ''
	if confirm-bool "Would you like to also configure macOS settings?"; then
		macos-settings
	fi
	echo $'\n' --g1='Finished. ✅'
fi
