#!/usr/bin/env bash

# https://developers.cloudflare.com/warp-client/get-started/linux
# https://developers.cloudflare.com/warp-client/setting-up/linux
# https://developers.cloudflare.com/warp-client/setting-up/macOS
# currently only supports apt+yum on amd64:
# https://pkg.cloudflareclient.com/packages/cloudflare-warp
# doesn't support arm64:
# https://community.cloudflare.com/t/cloudflare-warp-linux-client-for-armv8-arm64-aarch64-devices/278777
# doesn't support arch-linux (manjaro):
# https://community.cloudflare.com/t/cloudflare-warp-linux-client-for-arch-linux-manjaro/298649

function setup_util_warp() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--app='Cloudflare WARP'
		--cli='warp-cli'
		"$@"
		APT_KEY='https://pkg.cloudflareclient.com/pubkey.gpg'
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://pkg.cloudflareclient.com/ {RELEASE} main'
		APT='cloudflare-warp' # UBUNTU
		CASK='cloudflare-warp'
		RPM='cloudflare-warp' # FEDORA
	)
	setup-util "${options[@]}"

	# eval-helper --elevate -- rpm -ivh http://pkg.cloudflareclient.com/cloudflare-release-el<VERSION>.rpm
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_warp "$@"
fi
