#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/dandavison/delta
# diff alternative

env CLI='delta' \
	AUR='git-delta-bin' \
	BREW='git-delta' \
	CARGO='git-delta' \
	CHOCO='delta' \
	DNF='git-delta' \
	EMERGE='dev-util/git-delta' \
	NIX='nixpkgs.gitAndTools.delta' \
	PKG='git-delta' \
	PORT='git-delta' \
	SCOOP='delta' \
	XBPS='delta' \
	ZYPPER='git-delta' \
	setup-util
