#!/usr/bin/env bash

# https://github.com/BurntSushi/ripgrep
# https://github.com/BurntSushi/ripgrep/issues/1094
# grep alternative

# https://github.com/BurntSushi/ripgrep/releases
# https://github.com/microsoft/ripgrep-prebuilt/releases
# ripgrep-v13.0.0-10-aarch64-apple-darwin.tar.gz
# ripgrep-v13.0.0-10-aarch64-pc-windows-msvc.zip
# ripgrep-v13.0.0-10-aarch64-unknown-linux-gnu.tar.gz
# ripgrep-v13.0.0-10-aarch64-unknown-linux-musl.tar.gz
# ripgrep-v13.0.0-10-arm-unknown-linux-gnueabihf.tar.gz
# ripgrep-v13.0.0-10-i686-pc-windows-msvc.zip
# ripgrep-v13.0.0-10-i686-unknown-linux-musl.tar.gz
# ripgrep-v13.0.0-10-powerpc64le-unknown-linux-gnu.tar.gz
# ripgrep-v13.0.0-10-s390x-unknown-linux-gnu.tar.gz
# ripgrep-v13.0.0-10-x86_64-apple-darwin.tar.gz
# ripgrep-v13.0.0-10-x86_64-pc-windows-msvc.zip
# ripgrep-v13.0.0-10-x86_64-unknown-linux-musl.tar.gz

# https://packages.debian.org/sid/amd64/ripgrep/filelist
# /usr/bin/rg

# https://repology.org/project/ripgrep/versions

function setup_util_ripgrep() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=rg "$@"; then
		return 0
	fi

	# setup
	local arch options=(
		--name='ripgrep'
		--cli='rg'
		"$@"
		APK='ripgrep' # ALPINE
		APT='ripgrep' # UBUNTU
		AUR='ripgrep' # ARCH
		BREW='ripgrep'
		BSD='ripgrep'
		CARGO='ripgrep'
		CHOCO='ripgrep'
		EMERGE='sys-apps/ripgrep' # GENTOO
		URPMI='ripgrep'           # MAGEIA
		NIX='ripgrep'
		PORT='ripgrep'
		RPM='ripgrep' # FEDORA
		SCOOP='ripgrep'
		ZYPPER='ripgrep' # SUSE
	)
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return $?
		github-download --dry --slug='microsoft/ripgrep-prebuilt' --latest --asset-regexp="$regexp" | echo-first-line || return $?
	}
	function __add_download_option {
		local url
		url="$(__get_github_asset_url "$1")" || return $?
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB="$2"
		)
	}
	arch="$(get-arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-apple-darwin.tar.gz' 'rg' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-apple-darwin.tar.gz' 'rg' || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-unknown-linux-musl.tar.gz' 'rg' || :
		elif [[ $arch == 'a32' ]]; then
			__add_download_option '-arm-unknown-linux-gnueabihf.tar.gz' 'rg' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-unknown-linux-musl.tar.gz' 'rg' || :
		elif [[ $arch == 'x32' ]]; then
			__add_download_option '-i686-unknown-linux-musl.tar.gz' 'rg' || :
		fi
	elif is-windows; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-pc-windows-msvc.zip' 'rg.exe' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-pc-windows-msvc.zip' 'rg.exe' || :
		elif [[ $arch == 'x32' ]]; then
			__add_download_option '-i686-pc-windows-msvc.zip' 'rg.exe' || :
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_ripgrep "$@"
fi
