#!/usr/bin/env bash

# https://github.com/rrthomas/recode
# https://github.com/rrthomas/recode/issues/28

# https://github.com/rrthomas/recode/releases
# releases only provides source code

# https://packages.debian.org/sid/amd64/recode/filelist
# /usr/bin/recode

# https://pkgs.alpinelinux.org/packages?name=recode
# https://repology.org/project/recode/versions
# https://pkgs.org/search/?q=recode&on=name
# https://release-monitoring.org/project/4176/

function setup_util_recode() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--cli='recode'
		"$@"
		APT='recode'
		APK='recode'
		AUR='recode'
		BREW='recode'
		RPM='recode'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_recode "$@"
fi
