#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/nvm.sh"
source "$DOROTHY/sources/strict.bash"

# Wiping nvm
echo -e '\nWiping nvm...'
rm -Rf "$HOME/.nvm"
if test -n "${NVM_DIR-}"; then
	rm -Rf "$NVM_DIR"
else
	export NVM_DIR="$HOME/.nvm"
fi
echo '...nvm wiped!'

# Setup system node for global installs and vscode on mac
if is-brew; then
	echo -e '\nInstalling system node...'
	brew reinstall node
	npm cache clean --force
	brew cleanup
	echo '...system node installed!'
fi

# Reinstalling nvm
echo -e '\nInstalling nvm...'
# install nvm
mkdir -p "$NVM_DIR"
cd "$NVM_DIR" || exit 1
git init
git remote add origin git@github.com:nvm-sh/nvm.git
git fetch --tags origin
# shellcheck disable=SC2006,SC2046
git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
# load nvm
source "$DOROTHY/sources/nvm.sh"
echo '...nvm installed!'

echo -e '\nInstalling nvm node versions...'
nvm install node   # latest active
nvm install --lts  # latest LTS
echo '...nvm node versions installed!'

echo -e '\nConfiguring default node version...'
if is-brew; then
	nvm alias default system
else
	# use latest lts
	nvm alias default stable
	# use current lts: "$(nvm version-remote --lts)"
fi
nvm use default
echo '...success!'

echo -e '\nUpgrading npm...'
npm install -g npm --force
echo '...upgraded npm!'

# https://github.com/yarnpkg/yarn/issues/2993
function act () {
	echo -e "\nInstalling $# global npm packages..."
	env NAME="npm:$*" NPM="$*" setup-util npm
}
if test -v 'NODE_INSTALL'; then
	act "${NODE_INSTALL[@]}"
fi

echo -e '\nConfiguring npm...'
if is-empty-value "$(npm config get init.author.name)"; then
	npm config set init.author.name "$(ask-mandatory "What is your name?")"
fi
if is-empty-value "$(npm config get init.author.email)"; then
	npm config set init.author.email "$(ask-mandatory "What is your email?")"
fi
if is-empty-value "$(npm config get init.author.url)"; then
	npm config set init.author.url "$(ask-mandatory "What is your url?")"
fi
if is-empty-value "$(npm config get init.license)"; then
	npm config set init.license "$(ask-mandatory "What license do you prefer?")"
fi
echo '...configured npm!'

# Done
echo -e '\nInstalled Node.js, its versions, and its packages successfully. ✅'
