#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/httpie/httpie

function setup-util-httpie() (
	setup-util "$@" NAME='HTTPie' CLI='http' \
		APT='httpie' \
		BREW='httpie' \
		DNF='httpie' \
		EMERGE='httpie' \
		EOPKG='httpie' \
		PACMAN='httpie' \
		PIP='httpie' \
		PORT='httpie' \
		YUM='httpie'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-httpie "$@"
fi
