#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/openvpn/filelist
# /usr/sbin/openvpn

function setup_util_openvpn() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if test "$*" = '--quiet' && command-exists openvpn; then
		return 0
	fi

	# setup
	local options=(
		--name='OpenVPN'
		--cli='openvpn'
		"$@"
		APT='openvpn'
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_openvpn "$@"
fi
