#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# ensure git is configured correctly
if ! ssh-test; then
	stderr echo 'Git is not yet configured correctly to access GitHub, which will cause installs and updates to fail.'
	stderr echo 'If you do not have a SSH key yet, run [ssh-new] to create one, then run [setup-git].'
	stderr echo 'If you do have a SSH key, run [setup-git] to make sure your git configuration is correct.'
	exit 1
fi

# ensure pre-requisites are done
env QUIET=y setup-util-realpath
