#!/usr/bin/env bash

function setup_util_node() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='Node.js'
		--cli='node'
		# --dependency='nvm --optional'
		--sources='nvm | ...' # fnm
		APK='nodejs' APK='npm'
		APT_KEY='https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key'
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://deb.nodesource.com/node_24.x nodistro main'
		APT='nodejs' APT='libatomic1'
		AUR='nodejs' AUR='npm'
		BREW='node'
		BSD='nodejs'
		EMERGE='nodejs'
		EOPKG='nodejs'
		# FNM='--lts'
		NVM='--lts --default' # --latest-npm
		RPM='nodejs'
		SCOOP='nodejs'
		SNAP='node --classic'
		WINGET='OpenJS.NodeJS'
		XBPS='nodejs'
		ZYPPER='nodejs'
	)
	function npm_configure {
		if [[ $SETUP_UTIL__INSTALLED == 'yes' ]]; then
			# configure npm
			local configure="$SETUP_UTIL__CONFIGURE"
			if
				is-empty-value -- "$(node-env -- npm config get init-author-name || :)" ||
					is-empty-value -- "$(node-env -- npm config get init-author-email || :)" ||
					is-empty-value -- "$(node-env -- npm config get init-author-url || :)" ||
					is-empty-value -- "$(node-env -- npm config get init-license || :)"
			then
				configure='yes'
			fi
			if [[ $configure == 'yes' ]]; then
				node-env -- npm config set init-author-name "$(
					ask --required --linger \
						--question='What is the profile name that you want to configure npm with?' \
						--default="$(get-profile name -- npm ... || :)"
				)" || return $?
				node-env -- npm config set init-author-email "$(
					ask --required --linger \
						--question='What is the profile email that you want to configure npm with?' \
						--default="$(get-profile email -- npm ... || :)"
				)" || return $?
				node-env -- npm config set init-author-url "$(
					ask --required --linger \
						--question='What is the profile homepage that you want to configure npm with?' \
						--default="$(get-profile url -- npm ... || :)"
				)" || return $?
				node-env -- npm config set init-license "$(
					ask --required --linger \
						--question='What license do you want to configure npm to default to?' \
						--default="$(npm config get init-license)"
				)" || return $?
			fi

			# if extra, load packages to install
			if [[ $SETUP_UTIL__EXTRA == 'yes' ]]; then
				source "$DOROTHY/sources/config.sh"

				# setup.bash provides:
				local NPM_INSTALL=()
				load_dorothy_config 'setup.bash'

				# save changes, with SETUP_UTIL replacement
				__split --target={NPM_INSTALL} --no-zero-length --invoke -- \
					dorothy-config --packages-var='NPM_INSTALL' -- "${NPM_INSTALL[@]}" || return $?

				# ecosystem
				if [[ ${#/NPM_INSTALL[@]/} -ne 0 ]]; then
					setup-util --transpose=NPM -- "${NPM_INSTALL[@]}" || return $?
				fi
			fi
		fi
	}
	setup_util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_node "$@"
fi
