#!/usr/bin/env bash

# https://signal.org/
# https://www.makeuseof.com/install-signal-desktop-linux/

function setup_util_signal() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--app='Signal'
		APT_KEY='https://updates.signal.org/desktop/apt/keys.asc'
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://updates.signal.org/desktop/apt xenial main'
		APT='signal-desktop'
		AUR='signal-desktop'
		CASK='signal'
		FLATPAK='org.signal.Signal'
	)
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_signal "$@"
fi
