#!/usr/bin/env bash

# https://github.com/magic-wormhole/magic-wormhole

# https://github.com/magic-wormhole/magic-wormhole/releases
# no releases

# https://packages.debian.org/sid/amd64/magic-wormhole/filelist
# /usr/bin/wormhole

# https://repology.org/project/magic-wormhole/versions
# https://magic-wormhole.readthedocs.io/en/latest/welcome.html#installation

function setup_util_magic_wormhole() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--cli='wormhole' # another project that uses a different cli from its name, promoting conflicts
		"$@"
		APT='magic-wormhole'
		AUR='magic-wormhole'
		BREW='magic-wormhole'
		CHOCOLATELY='magic-wormhole'
		EMERGE='dev-python/magic-wormhole'
		EOPKG='magic-wormhole'
		NIX='magic-wormhole'
		SCOOP='magic-wormhole'
		SNAP='wormhole'
		UV='magic-wormhole'
		WINGET='magic-wormhole'
		ZYPPER='python-magic-wormhole'
	)
	if ! is-almalinux; then
		options+=(DNF='magic-wormhole')
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_magic_wormhole "$@"
fi
