#!/usr/bin/env bash

function setup_util_apt() (
	source "$DOROTHY/sources/bash.bash"

	# checks
	if ! is-system --apt; then
		__print_style --stderr --notice="[$0] is only intended to be run on aptitude systems, skipping." || return $?
		return 0
	fi

	# setup
	# `apt-add-repository` is missing on Debian, however web search says it is provided by `software-properties-common`, however, at least on Debian that is not available
	local options=(
		--name='APT Essentials'
		"$@"
		APT='apt-transport-https' APT='ca-certificates'
	)
	setup-util "${options[@]}" || return $?
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_apt "$@"
fi
