#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://wiki.manjaro.org/index.php/Snap
# https://packages.ubuntu.com/bionic/gnome/gnome-software-plugin-snap
# https://snapcraft.io/docs/installing-snap-on-opensuse
# https://software.opensuse.org/download/package?package=snapd&project=system:snappy
# https://en.opensuse.org/Snap

function setup-util-snap() (
	# check for compatibility
	if ! is-linux; then
		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
		return 0
	fi

	# install snap
	setup-util "$@" --name='snap' --cli='snap' \
		RPM='snapd' \
		PAMAC='snapd' \
		ZYPPER_REPO="https://download.opensuse.org/repositories/system:snappy/$(get-opensuse-release 2>/dev/null || :)/system:snappy.repo" \
		ZYPPER_REPO_ALIAS='snappy' \
		ZYPPER='snapd'

	# capture exit from --optional and --confirm, as well as WSL in which snap is busted
	if ! is-snap; then
		return 0
	fi

	# log start
	echo-segment --h2='Configure snap'

	# ensure snap is available to the system
	if test ! -d /snap; then
		sudo ln -s /var/lib/snapd/snap /snap
	fi

	# ensure snap service is running
	if ! systemctl status snapd.socket --no-pager >/dev/null; then
		sudo systemctl enable --now snapd.socket
	fi
	if ! systemctl status snapd.apparmor --no-pager >/dev/null; then
		sudo systemctl enable --now snapd.apparmor || :
	fi

	# install snap support for gnome-software (if it exists)
	if command-exists gnome-software; then
		# PAMAC='gnome-software-snap' \
		# Error: target not found: gnome-software-snap
		setup-util "$@" --optional --name='Snap via Gnome Software' \
			APT='gnome-software-plugin-snap'
	fi

	# log success
	echo-segment --g2='Configure snap'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-snap "$@"
fi
