#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/ssh.sh"
source "$DOROTHY/sources/strict.bash"

echo -e '\nAdding ssh keys to authorise updates from servers...'
ssh-start-helper
if is-mac; then
	/usr/bin/ssh-add -A
fi
echo '...success'

echo -e '\nUpdating commenced...'

setup-dorothy update

setup-mac-brew update

setup-extras update

setup-mac-clean

echo -e '\n...updating completed successfully!'