#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/golang/go/wiki/Ubuntu
function setup-util-go() (
	# if is-wsl; then
	# 	echo-style --notice="If golang fails to install, install choco first or install go manually:" $'\n' \
	# 		--code='   https://chocolatey.org/install#individual' $'\n' \
	# 		--code='   https://go.dev/dl/' > /dev/stderr
	# fi

	# despite docs, no apk
	setup-util "$@" --cli='go' \
		APT='golang-go' \
		APT_REPO='ppa:longsleep/golang-backports' \
		CHOCO='go' \
		SNAP='go --classic' \
		BREW='go' \
		-- brew snap apt choco
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-go "$@"
fi
