#!/usr/bin/env bash

function setup-util-nordvpn() (
	source "$DOROTHY/sources/strict.bash"

	# =====================================
	# Arguments

	# help
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Sets up a NordVPN.

			USAGE:
			setup-util-nordvpn [...options]

			OPTIONS:
			--get-service-ids
			    If specified, output service identifiers, ordered by startup preference.

			...
			    All other options are forwarded to $(echo-style --code='setup-util').
		EOF
		return 22 # Invalid argument
	}

	# process
	local item action='install' util=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--get-service-ids') action='get-service-ids' ;;
		'--install') action='install' ;;
		'--uninstall') action='uninstall' ;;
		'--action='*) action="${item#*--action=}" ;;
		*) util+=("$item") ;;
		esac
	done

	# ensure action inside util
	util+=("--action=$action")

	# =====================================
	# Preparation

	local service_title='NordVPN'
	local service_ids=(
		'nordvpnd'
		'nordvpnd.socket'
	)

	# =====================================
	# Simple Actions

	if test "$action" = 'get-service-ids'; then
		echo-lines "${service_ids[@]}"
		return 0
	fi

	# =====================================
	# Setup Utility

	# install utility with forwarded+custom arguments
	setup-util "${util[@]}" --name='NordVPN' --cli='nordvpn' \
		APT_KEY='https://repo.nordvpn.com/gpg/nordvpn_public.asc' \
		APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://repo.nordvpn.com/deb/nordvpn/debian stable main' \
		APT='nordvpn'

	# stop at uninstall?
	if test "$action" = 'uninstall'; then
		return "$?"
	else
		# prevents nordvpn from establishing its virtual network interfaces
		# as it seems like it confuses nordvpn as to
		# which operating system / network stack it is running on
		setup-util-netscript --uninstall
	fi

	# =====================================
	# Setup Service

	# DO not disable autostart for NordVPN
	# As the service is required for the CLI to operate

	# only manage the service if it is supported
	if service-helper --supported; then
		# verify the service was initialised
		if ! service-helper --exists -- "${service_ids[@]}"; then
			# headful/headless, no service
			echo-error "$0: $service_title was installed, however the service was not."
			return 1
		fi
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-nordvpn "$@"
fi
