#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/chmln/sd
# sed/awk alternative

#  sd-v0.7.6-x86_64-apple-darwin
#  sd-v0.7.6-x86_64-unknown-linux-gnu
#  sd-v0.7.6-x86_64-unknown-linux-musl

function setup-util-sd() (
	local arch github_asset_filter
	arch="$(get-arch)"
	github_asset_filter=''
	if is-mac; then
		github_asset_filter='x86_64-apple-darwin'
	elif test "$arch" = 'x64'; then
		github_asset_filter='x86_64-unknown-linux'
	fi

	setup-util "$@" CLI='sd' \
		GITHUB_SLUG='chmln/sd' \
		GITHUB_RELEASE='latest' \
		GITHUB_ASSET_FILTER="$github_asset_filter" \
		GITHUB_FILENAME='sd' \
		APK='sd' \
		BREW='sd' \
		CARGO='sd' \
		CHOCO='sd-cli' \
		DNF='sd' \
		EMERGE='sys-apps/sd' \
		PACMAN='sd' \
		PKG='sd' \
		XBPS='sd' \
		-- github ...

	# ^ these are all out of date compared to master, unfortunately it seems builds are broken:
	# https://github.com/chmln/sd/pull/143
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-sd "$@"
fi
