#!/usr/bin/env bash

function setup-util-transmission() (
	source "$DOROTHY/sources/strict.bash"

	# install transmission
	setup-util "$@" --name='Transmission' --cli='transmission' \
		APT_REPO='ppa:transmissionbt/ppa' \
		APT='transmission-cli' APT='transmission-common' APT='transmission-daemon'

	# configure
	sudo vim /var/lib/transmission-daemon/info/settings.json
	sudo systemctl edit transmission-daemon.service

	# sudo usermod -a -G debian-transmission user
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-transmission "$@"
fi
