#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/XAMPPRocky/tokei
# code stats, wc alternative

setup-util "$@" NAME='Trunk.io' CLI='trunk' \
	DOWNLOAD='https://trunk.io/releases/trunk' \
	DOWNLOAD_FILENAME='trunk'

if test "${1-}" = '--upgrade'; then
	trunk upgrade
fi
