#!/usr/bin/env bash

function setup_util_node() (
	source "$DOROTHY/sources/util.bash"
	source "$(type -P eval-helper)" # enable `install_nvm_node`
	source "$(type -P setup-util)"  # enable *_EVAL
	util_options=(
		--cli='node'
		--configured-eval='node_configure'
		CUSTOM_INSTALL_EVAL='node_install'
		CUSTOM_UNINSTALL_EVAL='node_uninstall'
	)

	function node_configure {
		if [[ $SETUP_UTIL__INSTALLED == 'yes' ]]; then
			source "$DOROTHY/sources/config.sh"

			# environment.bash provides:
			# NVM_DIR
			# but in case it failed to:
			if [[ -z ${NVM_DIR-} ]]; then
				export NVM_DIR="$HOME/.nvm"
			fi

			# setup.bash provides:
			local NPM_INSTALL=()
			local NODE_INSTALL=() # deprecated, use `NPM_INSTALL`
			local NODE_VERSIONS=()
			load_dorothy_config 'setup.bash'

			# deprecations
			if [[ ${#NODE_INSTALL[@]} -ne 0 ]]; then
				NPM_INSTALL+=("${NODE_INSTALL[@]}")
				__unique --source+target={NPM_INSTALL} --ignore-case || return $?
				dorothy-config 'setup.bash' -- \
					--field='NODE_INSTALL' --replace= || return $?
			fi

			# adjustments
			__split --target={NPM_INSTALL} --no-zero-length --invoke -- \
				dorothy-config --packages-var='NPM_INSTALL' -- "${NPM_INSTALL[@]}" || return $?

			# configure npm
			local configure="$SETUP_UTIL__CONFIGURE"
			if
				is-empty-value -- "$(npm config get init-author-name || :)" ||
					is-empty-value -- "$(npm config get init-author-email || :)" ||
					is-empty-value -- "$(npm config get init-author-url || :)" ||
					is-empty-value -- "$(npm config get init-license || :)"
			then
				configure='yes'
			fi
			if [[ $configure == 'yes' ]]; then
				__print_style --h3='Configure npm' || return $?
				nvm-env -- npm config set init-author-name "$(
					ask --required --linger \
						--question='What is the profile name that you want to configure npm with?' \
						--default="$(get-profile name -- npm ... || :)"
				)" || return $?
				nvm-env -- npm config set init-author-email "$(
					ask --required --linger \
						--question='What is the profile email that you want to configure npm with?' \
						--default="$(get-profile email -- npm ... || :)"
				)" || return $?
				nvm-env -- npm config set init-author-url "$(
					ask --required --linger \
						--question='What is the profile homepage that you want to configure npm with?' \
						--default="$(get-profile url -- npm ... || :)"
				)" || return $?
				nvm-env -- npm config set init-license "$(
					ask --required --linger \
						--question='What license do you want to configure npm to default to?' \
						--default="$(npm config get init-license)"
				)" || return $?
				__print_style --g3='Configure npm' || return $?
			fi

			# ecosystem
			if [[ $SETUP_UTIL__EXTRA == 'yes' ]]; then
				# Packages via npm
				if [[ ${#NPM_INSTALL[@]} -ne 0 ]]; then
					__print_style --h3="Install ${#NPM_INSTALL[@]} npm packages" || return $?
					setup-util install --transpose=NODE -- "${NPM_INSTALL[@]}" || return $?
					__print_style --g3="Install ${#NPM_INSTALL[@]} npm packages" || return $?
				fi

				# Additional Node.js versions
				if [[ ${#NODE_VERSIONS[@]} -ne 0 ]]; then
					__print_style --h3="Install ${#NODE_VERSIONS[@]} additional Node.js versions" || return $?
					setup-util install --transpose=NVM -- "${NODE_VERSIONS[@]}" || return $?
					__print_style --g3="Install ${#NODE_VERSIONS[@]} additional Node.js versions" || return $?
				fi
			fi
		fi
	}

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# =====================================
	# Helpers

	function __get_nvm_versions {
		nvm-env -- nvm ls --no-colors --no-alias | echo-regexp -ong --regexp='v([^\s]+)' --replace='$1' || return $?
	}

	function __clean_nvm {
		# swap to system
		nvm-env -- nvm use system || :
		# fetch versions
		local versions=()
		__split --target={versions} --no-zero-length --invoke -- \
			__get_nvm_versions || return $?
		if [[ ${#versions[@]} -eq 0 ]]; then
			# already clean
			return 0
		fi
		# clean versions
		local version
		for version in "${versions[@]}"; do
			nvm-env -- nvm uninstall "$version" | echo-regexp -n 'Uninstalled node ' 'Uninstalled: ' || return $?
		done
		# confirm clean was successful
		__split --target={versions} --no-zero-length --invoke -- \
			__get_nvm_versions || return $?
		[[ ${#versions[@]} -eq 0 ]] || return $?
	}

	function clean_otherwise_wipe_nvm {
		# clean only what is necessary
		__print_style --h3='Clean Node.js versions and packages'
		if __clean_nvm; then
			__print_style --g3='Clean Node.js versions and packages'
		else
			# nvm buggered, clean it all
			__print_style --e3='Clean Node.js versions and packages' --newline \
				--h3='Clean Node.js Version Manager (NVM) instead'
			setup-util-nvm uninstall
			__print_style --g3='Clean Node.js Version Manager (NVM) instead'
		fi
	}

	function install_nvm_node {
		# install
		nvm-env -- nvm install --no-progress node  # latest active
		nvm-env -- nvm install --no-progress --lts # latest LTS

		# set default node version
		if __is_brew; then
			nvm-env -- nvm alias default system
		else
			# use latest lts
			nvm-env -- nvm alias default stable
			# use current lts: "$(nvm version-remote --lts)"
		fi
	}

	function setup_system_node {
		# https://deb.nodesource.com
		# `libatomic1` as otherwise `node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory` when using to fetch version numbers during npm upgrade
		setup-util --name='Node.js via System' --cli=node "$@" \
			APK='nodejs' APK='npm' \
			APT_KEY='https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key' \
			APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://deb.nodesource.com/node_22.x nodistro main' \
			APT='nodejs' APT='libatomic1' \
			AUR='nodejs' AUR='npm' \
			BREW='node' \
			BSD='nodejs' \
			EMERGE='nodejs' \
			EOPKG='nodejs' \
			RPM='nodejs' \
			SCOOP='nodejs' \
			SNAP='node --classic' \
			WINGET='OpenJS.NodeJS' \
			XBPS='nodejs' \
			ZYPPER='nodejs'
	}

	function upgrade_system_or_nvm_npm {
		# ensure the cache is configured correctly
		# to avoid when say a /Users/... cache config is copied to a Linux machine
		local cache_dir
		cache_dir="$(nvm-env -- npm config get cache || :)"
		if [[ -n $cache_dir && ! -d $cache_dir ]]; then
			# try and make it
			__mkdirp "$cache_dir" || {
				__print_style --notice='Unconfiguring the invalid cache directory:' ' ' --code="$cache_dir" || return $?
				nvm-env -- npm config delete cache || return $?
			} || return $?
		fi

		# continue with the upgrade
		__print_style --dim="Before: v$(nvm-env -- npm --version)"
		setup-util upstall --name='npm' --force --quiet \
			NPM='npm' || __print_style --notice='You can ignore the npm upgrade failure, this will resolve after nvm is used.'
		nvm-env -- npm cache clean --force 2>/dev/null # silent --force warning
		__print_lines "After:  v$(nvm-env -- npm --version)"
	}

	# =====================================
	# Actions

	function node_install {
		# =====================================
		# Install Node via System

		# https://nodejs.org/en/download/package-manager/
		# @todo https://github.com/nodejs/unofficial-builds for riscv, but provides tars that include multiple directories
		__print_style --h2='Install Node.js via System'
		setup_system_node --install --force --quiet
		__print_lines "Installed: $(node --version)"
		__print_style --g2='Install Node.js via System'

		# =====================================
		# Clean NVM

		# clean NVM unless configured otherwise
		# the intent of this is to purge unused global Node.js versions and packages
		# we use a configuration variable to change this, as interrupting the flow and asking the user creates too much confusion
		# as such a question is only necessary to experienced users
		if [[ -d ${NVM_DIR-} ]]; then
			clean_otherwise_wipe_nvm
		fi

		# =====================================
		# Install NVM and Node via NVM

		# (arm) alpine does not support nvm, fails with:
		# > mode no such file or directory
		if ! is-system --alpine; then
			# install nvm
			__print_style --h2='Install Node.js Version Manager (NVM)'
			setup-util-nvm upstall
			__print_style --g2='Install Node.js Version Manager (NVM)'

			# nvm node
			__print_style --h2='Install Node.js via NVM'
			__print_style --dim='Installs active and LTS versions.'
			eval_helper --quiet --no-wrap -- \
				install_nvm_node
			local versions=()
			__split --target={versions} --no-zero-length --invoke -- \
				__get_nvm_versions
			for version in "${versions[@]}"; do
				__print_lines "Installed: v$version"
			done
			__print_style --g2='Install Node.js via NVM'
		fi

		# =====================================
		# Upgrade npm

		__print_style --h3='Upgrade npm'
		upgrade_system_or_nvm_npm
		__print_style --g3='Upgrade npm'
	}
	function node_uninstall {
		setup_system_node --uninstall
		__wipe_nvm
	}

	# setup
	setup_util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_node "$@"
fi
