#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://en.wikipedia.org/wiki/Vim_(text_editor)

# https://www.digitalocean.com/community/tutorials/installing-and-using-the-vim-text-editor-on-a-cloud-server
setup-util "$@" NAME='Vim (Vi IMproved)' cli='vim' \
	APT='vim' \
	BREW='vim' \
	PACMAN='vim' \
	YUM='vim'

if test ! -f "$HOME/.vimrc"; then
	cat <<-EOF
		Vim configuration missing, applying the fancy defaults from:
		$(echo-style --dim='https://github.com/amix/vimrc')
	EOF
	github-download \
		--slug='amix/vimrc' \
		--ref='master' \
		--pathname='vimrcs/basic.vim' \
		--path="$HOME/.vimrc"
fi
