#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/BurntSushi/ripgrep
# https://github.com/BurntSushi/ripgrep/releases
# grep alternative

# ripgrep-13.0.0-arm-unknown-linux-gnueabihf.tar.gz
# ripgrep-13.0.0-i686-pc-windows-msvc.zip
# ripgrep-13.0.0-x86_64-apple-darwin.tar.gz
# ripgrep-13.0.0-x86_64-pc-windows-gnu.zip
# ripgrep-13.0.0-x86_64-pc-windows-msvc.zip
# ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz
# ripgrep_13.0.0_amd64.deb

function setup-util-ripgrep() (
	# determine github args if github is an option on this platform
	local arch github_asset_filter='' github=()
	arch="$(get-arch)"
	if is-mac; then
		github_asset_filter='-x86_64-apple-darwin'
	elif test "$arch" = 'a32'; then
		# this is now a aarch64 build
		# https://github.com/BurntSushi/ripgrep/issues/1094
		github_asset_filter='-arm-unknown-linux'
	elif test "$arch" = 'x64'; then
		github_asset_filter='-x86_64-unknown-linux'
	fi
	if test -n "$github_asset_filter"; then
		github+=(
			GITHUB_SLUG='BurntSushi/ripgrep'
			GITHUB_RELEASE='latest'
			GITHUB_ASSET_FILTER="$github_asset_filter"
			GITHUB_UNZIP_FILTER='**/rg'
			GITHUB_FILENAME='rg'
		)
	fi

	# install, preferring github
	setup-util "$@" --name='ripgrep' --cli='rg' \
		"${github[@]}" \
		APT='ripgrep' \
		BREW='ripgrep' \
		CARGO='ripgrep' \
		CHOCO='ripgrep' \
		DNF='ripgrep' \
		DOAS='ripgrep' \
		EMERGE='sys-apps/ripgrep' \
		NIX='ripgrep' \
		PACMAN='ripgrep' \
		PKG='ripgrep' \
		PKGIN='ripgrep' \
		PKGMAN='ripgrep' \
		PORT='ripgrep' \
		SCOOP='ripgrep' \
		ZYPPER='ripgrep' \
		-- github ...
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-ripgrep "$@"
fi
