#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

echo -e '\nInstalling fonts...'

# install dependencies, fixes:
# Error: Download failed on Cask 'font-cantarell' with message: Failure while executing; `svn checkout https://github.com/google/fonts/trunk/ofl/cantarell /Users/balupton/Library/Caches/Homebrew/Cask/font-cantarell--svn --quiet --trust-server-cert --non-interactive` exited with 1. Here's the output:
# You must: brew install svn
ok brew install svn

# install fonts
brew install --cask --force \
	font-cantarell \
	font-cascadia-code \
	font-fira-code \
	font-fira-code-nerd-font \
	font-fira-mono \
	font-fira-mono-nerd-font \
	font-hack \
	font-hasklig \
	font-ibm-plex \
	font-inter \
	font-jetbrains-mono \
	font-lato \
	font-maven-pro \
	font-monoid \
	font-montserrat \
	font-open-sans \
	font-oxygen \
	font-oxygen-mono \
	font-roboto \
	font-roboto-mono \
	font-source-code-pro \
	font-ubuntu \
	;
# failed to install: font-andale-mono font-droid-sans