#!/usr/bin/env bash

# https://github.com/astral-sh/uv?tab=readme-ov-file#installation
# pyenv alternative

# https://github.com/astral-sh/uv/releases
# uv-aarch64-apple-darwin.tar.gz
# uv-aarch64-pc-windows-msvc.zip
# uv-aarch64-unknown-linux-gnu.tar.gz
# uv-aarch64-unknown-linux-musl.tar.gz
# uv-arm-unknown-linux-musleabihf.tar.gz
# uv-armv7-unknown-linux-gnueabihf.tar.gz
# uv-armv7-unknown-linux-musleabihf.tar.gz
# uv-i686-pc-windows-msvc.zip
# uv-i686-unknown-linux-gnu.tar.gz
# uv-i686-unknown-linux-musl.tar.gz
# uv-installer.ps1
# uv-installer.sh
# uv-powerpc64-unknown-linux-gnu.tar.gz
# uv-powerpc64le-unknown-linux-gnu.tar.gz
# uv-s390x-unknown-linux-gnu.tar.gz
# uv-x86_64-apple-darwin.tar.gz
# uv-x86_64-pc-windows-msvc.zip
# uv-x86_64-unknown-linux-gnu.tar.gz
# uv-x86_64-unknown-linux-musl.tar.gz

function setup_util_uv() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=uv "$@"; then
		return 0
	fi

	# despite docs, no apk
	local arch options=(
		--name='uv'
		--cli='uv' --cli='uvx'
		"$@"
	)
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return $?
		github-download --dry --slug='astral-sh/uv' --latest --asset-regexp="$regexp" | echo-first-line || return $?
	}
	function __add_download_option {
		local url
		url="$(__get_github_asset_url "$1")" || return $?
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB="*/{uv,uvx}"
		)
	}
	arch="$(get-arch)"
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-apple-darwin.tar.gz' || :
		else
			__add_download_option '-x86_64-apple-darwin.tar.gz' || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-unknown-linux-musl.tar.gz' || :
		elif [[ $arch == 'a32' ]]; then
			__add_download_option '-armv7-unknown-linux-musleabihf.tar.gz' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-unknown-linux-musl.tar.gz' || :
		elif [[ $arch == 'x32' ]]; then
			__add_download_option '-i686-unknown-linux-musl.tar.gz' || :
		fi
	elif is-windows; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-pc-windows-msvc.zip' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-pc-windows-msvc.zip' || :
		elif [[ $arch == 'x32' ]]; then
			__add_download_option '-i686-pc-windows-msvc.zip' || :
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_uv "$@"
fi
