#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# Prepare
f="$HOME/.fonts"
ft="$f/tmp"
mkdir -p "$f" "$ft"
pushd "$ft" || exit 1

# Roboto
# https://askubuntu.com/a/1161809/22776
sudo wget --content-disposition -P "$f" https://github.com/google/fonts/blob/master/apache/robotomono/static/RobotoMono-{Bold,BoldItalic,Italic,Light,LightItalic,Medium,MediumItalic,Regular,Thin,ThinItalic}.ttf?raw=true

# Monoid
down https://cdn.rawgit.com/larsenwork/monoid/2db2d289f4e61010dd3f44e09918d9bb32fb96fd/Monoid.zip
unziptar Monoid.zip
mv ./*.ttf "$f"

# Source Code Pro
# http://askubuntu.com/a/193073/22776
# https://github.com/adobe-fonts/source-code-pro
down https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.zip
unziptar 1.030R-it.zip
mv source-code-pro-2.010R-ro-1.030R-it/OTF/*.otf "$f"

# Monaco
# https://github.com/showcases/fonts
# https://github.com/todylu/monaco.ttf
down https://github.com/todylu/monaco.ttf/raw/master/monaco.ttf
mv monaco.ttf "$f"

# Fira Code Nerd Fonts
# https://www.nerdfonts.com/font-downloads
down 'hhttps://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip'
unziptar FiraCode.zip
mv ./*.otf "$f"
mv ./*.ttf "$f"

# Refresh
fc-cache -f -v
popd || exit 1
rm -Rf "$ft"