#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/openssh-server/filelist
# /usr/sbin/sshd

function setup_util_sshd() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if is-needle --quiet "$@" && ! is-needle --upgrade "$@" && ! is-needle --uninstall "$@" && command-exists sshd; then
		return 0
	fi

	# setup
	local options=(
		--name='OpenSSH Server'
		--cli='sshd'
		"$@"
		APT='openssh-server' # UBUNTU
		BREW='openssh'
		ZYPPER='openssh' # SUSE
	)
	setup-util "${options[@]}"

	# if installed, configure
	if command-exists sshd; then
		# ubuntu, opensuse
		if service-helper --supported; then
			service-helper --ignore --enable --start -- ssh sshd || :
		fi

		# opensuse
		if command-exists firewall-cmd; then
			eval-helper -- sudo-helper -- firewall-cmd --permanent --add-service=ssh || :
			eval-helper -- sudo-helper -- firewall-cmd --reload || :
		fi
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_sshd "$@"
fi
