#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-netscript() (
	# check for linux
	if ! is-linux; then
		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
		return 0
	fi

	# check for existence
	if test -x /sbin/ifup -a -x /sbin/ifdown; then
		return 0
	fi

	# install
	# no apk
	setup-util "$@" --name='NetScript [ifup/ifdown]' \
		APT='netscript-2.4'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-netscript "$@"
fi
