#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-nano() (
	setup-util "$@" --name='GNU nano' --cli='nano' \
		APT='nano' \
		BREW='nano'

	# fix ubuntus server issue:
	# Unable to create directory /home/ubuntu/.local/share/nano/: No such file or directory
	# It is required for saving/loading search history or cursor positions.
	mkdir -p "$XDG_DATA_HOME/nano"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-nano "$@"
fi
