#!/usr/bin/env bash
source "$BDIR/sources/strict.bash"

if is-apt; then
	setup-linux-apt
	setup-linux-shell
	setup-linux-fonts
	setup-linux-vscode
elif is-apk; then
	setup-linux-apk
fi

if is-snap; then
	setup-linux-snap
fi

setup-extras install