#!/usr/bin/env bash

# https://github.com/tonsky/FiraCode/wiki/Installing
# https://github.com/tonsky/FiraCode/wiki/Linux-instructions#installing-with-a-package-manager

function setup_util_fira_code() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--name='Fira Code'
		--font='FiraCode*'
		CASK='font-fira-code'
		EMERGE='media-fonts/fira-code'
		EOPKG='font-firacode-ttf'
		XBPS='font-firacode'
	)
	if ! is-system --almalinux; then
		# almalinux is not aware of the DNF package
		util_options+=(DNF='fira-code-fonts')
	fi

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${setup_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	__fetch_and_add_download_option_via_slug_regexp_glob 'tonsky/FiraCode' '^Fira_Code_v[0-9.]+\.zip$' '{ttf,variable_ttf}/*.ttf' || :

	# setup
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_fira_code "$@"
fi
