#!/usr/bin/env bash

# https://github.com/raspberrypi/rpi-update

function setup_util_rpi_update() (
	source "$DOROTHY/sources/bash.bash"

	local options=(
		--cli='rpi-update'
		--no-xdg
		--elevate
		"$@"
		APT='rpi-update'                                                                    # RASPBERRY PI OS
		DOWNLOAD='https://raw.githubusercontent.com/raspberrypi/rpi-update/HEAD/rpi-update' # OTHER
	)
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_rpi_update "$@"
fi
