#!/usr/bin/env bash

# /Library/Developer/CommandLineTools/usr/bin/indent
# /Library/Developer/CommandLineTools/usr/bin/xml2man
# /Library/Developer/CommandLineTools/usr/bin/pip3.9
# /Library/Developer/CommandLineTools/usr/bin/cache-build-session
# /Library/Developer/CommandLineTools/usr/bin/xcindex-test
# /Library/Developer/CommandLineTools/usr/bin/libtool
# /Library/Developer/CommandLineTools/usr/bin/Rez
# /Library/Developer/CommandLineTools/usr/bin/ctags
# /Library/Developer/CommandLineTools/usr/bin/strings
# /Library/Developer/CommandLineTools/usr/bin/gm4
# /Library/Developer/CommandLineTools/usr/bin/clang
# /Library/Developer/CommandLineTools/usr/bin/tapi
# /Library/Developer/CommandLineTools/usr/bin/c99
# /Library/Developer/CommandLineTools/usr/bin/llvm-cov
# /Library/Developer/CommandLineTools/usr/bin/swift-demangle
# /Library/Developer/CommandLineTools/usr/bin/strip
# /Library/Developer/CommandLineTools/usr/bin/ld-classic
# /Library/Developer/CommandLineTools/usr/bin/bitcode_strip
# /Library/Developer/CommandLineTools/usr/bin/llvm-objdump
# /Library/Developer/CommandLineTools/usr/bin/clangd
# /Library/Developer/CommandLineTools/usr/bin/lex
# /Library/Developer/CommandLineTools/usr/bin/ctf_insert
# /Library/Developer/CommandLineTools/usr/bin/sourcekit-lsp
# /Library/Developer/CommandLineTools/usr/bin/pip3
# /Library/Developer/CommandLineTools/usr/bin/ld
# /Library/Developer/CommandLineTools/usr/bin/llvm-otool
# /Library/Developer/CommandLineTools/usr/bin/lldb
# /Library/Developer/CommandLineTools/usr/bin/projectInfo
# /Library/Developer/CommandLineTools/usr/bin/size-classic
# /Library/Developer/CommandLineTools/usr/bin/pagestuff
# /Library/Developer/CommandLineTools/usr/bin/headerdoc2html
# /Library/Developer/CommandLineTools/usr/bin/swift-frontend
# /Library/Developer/CommandLineTools/usr/bin/stapler
# /Library/Developer/CommandLineTools/usr/bin/hdxml2manxml
# /Library/Developer/CommandLineTools/usr/bin/resolveLinks
# /Library/Developer/CommandLineTools/usr/bin/gcc
# /Library/Developer/CommandLineTools/usr/bin/segedit
# /Library/Developer/CommandLineTools/usr/bin/llvm-nm
# /Library/Developer/CommandLineTools/usr/bin/swift-plugin-server
# /Library/Developer/CommandLineTools/usr/bin/gperf
# /Library/Developer/CommandLineTools/usr/bin/llvm-size
# /Library/Developer/CommandLineTools/usr/bin/vtool
# /Library/Developer/CommandLineTools/usr/bin/dsymutil
# /Library/Developer/CommandLineTools/usr/bin/SplitForks
# /Library/Developer/CommandLineTools/usr/bin/nm-classic
# /Library/Developer/CommandLineTools/usr/bin/rpcgen
# /Library/Developer/CommandLineTools/usr/bin/llvm-cxxfilt
# /Library/Developer/CommandLineTools/usr/bin/otool-classic
# /Library/Developer/CommandLineTools/usr/bin/DeRez
# /Library/Developer/CommandLineTools/usr/bin/swift-stdlib-tool
# /Library/Developer/CommandLineTools/usr/bin/codesign_allocate
# /Library/Developer/CommandLineTools/usr/bin/cpp
# /Library/Developer/CommandLineTools/usr/bin/make
# /Library/Developer/CommandLineTools/usr/bin/flex++
# /Library/Developer/CommandLineTools/usr/bin/ar
# /Library/Developer/CommandLineTools/usr/bin/unifdef
# /Library/Developer/CommandLineTools/usr/bin/lipo
# /Library/Developer/CommandLineTools/usr/bin/m4
# /Library/Developer/CommandLineTools/usr/bin/asa
# /Library/Developer/CommandLineTools/usr/bin/llvm-dwarfdump
# /Library/Developer/CommandLineTools/usr/bin/as
# /Library/Developer/CommandLineTools/usr/bin/gnumake
# /Library/Developer/CommandLineTools/usr/bin/ResMerger
# /Library/Developer/CommandLineTools/usr/bin/llvm-profdata
# /Library/Developer/CommandLineTools/usr/bin/git-shell
# /Library/Developer/CommandLineTools/usr/bin/unifdefall
# /Library/Developer/CommandLineTools/usr/bin/yacc
# /Library/Developer/CommandLineTools/usr/bin/c89
# /Library/Developer/CommandLineTools/usr/bin/lorder
# /Library/Developer/CommandLineTools/usr/bin/tapi-analyze
# /Library/Developer/CommandLineTools/usr/bin/clang-stat-cache
# /Library/Developer/CommandLineTools/usr/bin/scalar
# /Library/Developer/CommandLineTools/usr/bin/flex
# /Library/Developer/CommandLineTools/usr/bin/SetFile
# /Library/Developer/CommandLineTools/usr/bin/swift-package
# /Library/Developer/CommandLineTools/usr/bin/nmedit
# /Library/Developer/CommandLineTools/usr/bin/bison
# /Library/Developer/CommandLineTools/usr/bin/mig
# /Library/Developer/CommandLineTools/usr/bin/GetFileInfo
# /Library/Developer/CommandLineTools/usr/bin/git
# /Library/Developer/CommandLineTools/usr/bin/unwinddump
# /Library/Developer/CommandLineTools/usr/bin/install_name_tool
# /Library/Developer/CommandLineTools/usr/bin/cmpdylib
# /Library/Developer/CommandLineTools/usr/bin/gatherheaderdoc
# /Library/Developer/CommandLineTools/usr/bin/notarytool

function setup_util_apple_cli_tools() (
	source "$DOROTHY/sources/bash.bash"

	# checks
	if ! is-mac; then
		__print_style --stderr --notice="[$0] is only intended to be run on macOS systems, skipping." || return
		return 0
	fi

	# https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_
	# 1. uninstall xcode
	# 1. delete /Library/Developer/CommandLineTools

	# =====================================
	# Action

	# while not installed
	while ! xcode-select --print-path &>/dev/null; do
		# prompt for installation
		xcode-select --install &>/dev/null || :
		confirm --ppid=$$ -- 'Press <enter> once the Command Line Tools have been installed...' || return
	done

	# success
	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_apple_cli_tools "$@"
fi
