#!/usr/bin/env bash

# https://xon.sh/contents.html#installation

function setup_util_xonsh() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=xonsh "$@"; then
		return 0
	fi

	# xonsh
	local options=(
		--cli='xonsh'
		"$@"
		PIP='xonsh[full]'
	)
	if [[ -z $CI ]]; then
		# ci does not have PIPX env configured
		options+=(
			PIPX='xonsh[full]'
		)
	fi
	setup-util "${options[@]}"

	# language server for IDE support
	if [[ -z $CI ]]; then
		options=(
			--name='Python LSP Server'
			PIP='python-lsp-server'
			PIPX='python-lsp-server'
		)
		setup-util "${options[@]}"
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_xonsh "$@"
fi
