#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# https://github.com/vigna/ne
# https://github.com/vigna/ne/blob/master/INSTALL.md

setup-util "$@" NAME='ne, the nice editor' CLI='ne' \
	APT='ne' \
	BREW='ne'
