#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/pv/filelist
# /usr/bin/pv

function setup_util_pv() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='pv'
		APT='pv'
		BREW='pv'
	)
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_pv "$@"
fi
