#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

setup-util "$@" NAME='Build Essentials' \
	APT='build-essential' \
	BREW='coreutils' \
	PAMAC='base-devel' \
	YUM='coreutils'

# https://apple.stackexchange.com/a/362837
setup-util "$@" CLI='clang' \
	APT='clang' \
	BREW='llvm' \
	PACMAN='clang' \
	YUM='clang'

setup-util "$@" CLI='cmake' \
	APT='cmake' \
	BREW='cmake' \
	PACMAN='cmake' \
	YUM='cmake'

# https://rentes.github.io/unix/utilities/2015/07/27/moreutils-package/
# https://www.putorius.net/moreutils.html
setup-util "$@" --optional CLI='errno' \
	APT='moreutils' \
	BREW='moreutils' \
	PACMAN='moreutils' \
	YUM='moreutils'

if command-missing pacman; then
	# llvm-gcc is bundled with arch it seems, as it is not exposed by the cli yet pacman says it is installed
	setup-util "$@" CLI='llvm-gcc' \
		APT='llvm' \
		BREW='llvm' \
		PACMAN='llvm' \
		YUM='llvm'
fi

setup-util "$@" CLI='pkg-config' \
	APT='pkg-config' \
	BREW='pkg-config' \
	PACMAN='pkg-config' \
	YUM='pkg-config'

setup-util "$@" --optional NAME='openssl/libssl' \
	APT='libssl-dev' \
	BREW='openssl' \
	PACMAN='openssl' \
	YUM='openssl-devel'
