#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function setup-util-gsed() (
	# install [gsed] if [sed] is not [gsed]
	if is-mac; then
		setup-util "$@" NAME='GNU sed' CLI='gsed' \
			BREW='gnu-sed'
	fi

	# if [sed] is [gsed], then make sure [gsed] is available
	if command-missing gsed; then
		symlink-helper --existing="$(which sed)" --symlink="$XDG_BIN_HOME/gsed"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-gsed "$@"
fi
