#!/usr/bin/env bash
source "$BDIR/sources/essentials.sh"
source "$BDIR/sources/strict.bash"

rm -Rf ~/.nvm

t="$(mktemp)"
sudo bash <<EOF
grep -v "${BREW_PREFIX:-/usr/local}" /etc/shells > "$t"
cat "$t" > /etc/shells
rm "$t"
EOF

usesh /bin/bash

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

export GIT_PROTOCOL=manual
setup-git
export GIT_PROTOCOL=''
