#!/usr/bin/env bash

# https://github.com/showcases/fonts
# https://github.com/todylu/monaco.ttf

function setup_util_monaco() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check --font='Monaco.ttf'; then
		return 0
	fi

	# setup
	function __get_github_asset_url {
		github-download --dry --slug='todylu/monaco.ttf' --head --pathname='monaco.ttf' || return $?
	}
	function __add_download_option {
		local url
		url="$(__get_github_asset_url)" || return $?
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_FILENAME='Monaco.ttf'
		)
	}
	local options=(
		--font='Monaco.ttf'
		"$@"
	)
	__add_download_option || :
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_monaco "$@"
fi
