#!/usr/bin/env bash

# https://repology.org/project/dash-shell/versions

function setup_util_dash() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='dash'
		APT='dash' # not on repology but it exists
		APK='dash'
		AUR='dash'
		BREW='dash'
		NIX='dash'
	)
	setup-util "${util_options[@]}" "${setup_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_dash "$@"
fi
