#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# Interpreter for PostScript and PDF
# https://www.ghostscript.com/

function setup-util-ghostscript() (
	setup-util "$@" --name='GhostScript' --cli='gxps' \
		BREW='ghostscript'
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup-util-ghostscript "$@"
fi
