#!/usr/bin/env bash

# https://github.com/chmln/sd
# sed/awk alternative

# https://github.com/chmln/sd/releases
# sd-v1.0.0-aarch64-apple-darwin.tar.gz
# sd-v1.0.0-aarch64-unknown-linux-musl.tar.gz
# sd-v1.0.0-arm-unknown-linux-gnueabihf.tar.gz
# sd-v1.0.0-armv7-unknown-linux-gnueabihf.tar.gz
# sd-v1.0.0-x86_64-apple-darwin.tar.gz
# sd-v1.0.0-x86_64-pc-windows-gnu.zip
# sd-v1.0.0-x86_64-pc-windows-msvc.zip
# sd-v1.0.0-x86_64-unknown-linux-gnu.tar.gz
# sd-v1.0.0-x86_64-unknown-linux-musl.tar.gz

# https://repology.org/project/sd-find-replace/versions

function setup_util_sd() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=sd "$@"; then
		return 0
	fi

	# no urpmi
	local arch options=(
		--cli='sd'
		"$@"
		AUR='sd'
		BREW='sd'
		BSD='sd'
		CARGO='sd'
		EMERGE='sys-apps/sd'
		EOPKG='sd'
		NIX='sd'
		RPM='sd'
		SCOOP='sd'
		XBPS='sd'
		ZYPPER='sd'
	)
	arch="$(__get_arch)"
	function __get_github_asset_url {
		local suffix="$1" regexp
		regexp="$(echo-escape-regexp -- "$suffix")$" || return $?
		github-download --dry --slug='chmln/sd' --latest --asset-regexp="$regexp" | echo-first-line || return $?
	}
	function __add_download_option {
		local suffix="$1" file="$2" url
		url="$(__get_github_asset_url "$suffix")" || return $?
		options+=(
			DOWNLOAD="$url"
			DOWNLOAD_ARCHIVE_GLOB="*/$file"
		)
	}
	if __is_macos; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-apple-darwin.tar.gz' 'sd' || :
		else
			__add_download_option '-x86_64-apple-darwin.tar.gz' 'sd' || :
		fi
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-unknown-linux-musl.tar.gz' 'sd' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-unknown-linux-musl.tar.gz' 'sd' || :
		elif [[ $arch == 'a32' ]]; then
			__add_download_option '-armv7-unknown-linux-gnueabihf.tar.gz' 'sd' || :
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_sd "$@"
fi
