#!/usr/bin/env bash

# @todo add SOAR support to `setup-util`
# https://github.com/pkgforge/soar/discussions/113

# https://github.com/pkgforge/soar

# https://soar.qaidvoid.dev/installation
# CARGO=soar-cli

# https://github.com/pkgforge/soar/releases
# soar-aarch64-linux
# soar-aarch64-linux.tar.gz
# soar-riscv64-linux
# soar-riscv64-linux.tar.gz
# soar-x86_64-linux
# soar-x86_64-linux.tar.gz

# https://repology.org/project/soar/versions
# https://aur.archlinux.org/packages/soar-bin

function setup_util_soar() (
	source "$DOROTHY/sources/bash.bash"

	# checks
	if ! __is_linux; then
		__print_style --stderr --notice="[$0] is only intended to be run on Linux systems, skipping." || return $?
		return 0
	fi

	# improve performance for detectable utilities with conditional assets
	if setup-util --check --cli=soar "$@"; then
		return 0
	fi

	# setup
	local arch options=(
		--cli='soar'
		"$@"
		AUR='soar-bin'
		CARGO='soar-cli'
	)
	function __get_github_asset_url {
		local regexp
		regexp="$(echo-escape-regexp -- "$1")$" || return $?
		github-download --dry --slug='pkgforge/soar' --latest --asset-regexp="$regexp" | echo-first-line || return $?
	}
	function __add_download_option {
		local url
		url="$(__get_github_asset_url "$1")" || return $?
		options+=(DOWNLOAD="$url")
	}
	arch="$(__get_arch)"
	if __is_linux; then
		if [[ $arch == 'r64' ]]; then
			__add_download_option '-riscv64-linux' || :
		elif [[ $arch == 'a64' ]]; then
			__add_download_option '-aarch64-linux' || :
		elif [[ $arch == 'x64' ]]; then
			__add_download_option '-x86_64-linux' || :
		fi
	fi
	setup-util "${options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_soar "$@"
fi
