#!/usr/bin/env bash

# https://github.com/mihaigalos/aim
# curl alternative

# https://github.com/mihaigalos/aim/releases
# aim-1.8.6-aarch64-unknown-linux-gnu.tar.gz
# aim-1.8.6-aarch64-unknown-linux-musl.tar.gz
# aim-1.8.6-arm-unknown-linux-gnueabihf.tar.gz
# aim-1.8.6-i686-unknown-linux-gnu.tar.gz
# aim-1.8.6-x86_64-apple-darwin.tar.gz
# aim-1.8.6-x86_64-unknown-linux-gnu.tar.gz
# aim-1.8.6-x86_64-unknown-linux-musl.tar.gz
# aim-musl_1.8.6_amd64.deb
# aim-musl_1.8.6_arm64.deb
# aim_1.8.6_amd64.deb
# aim_1.8.6_arm64.deb
# aim_1.8.6_armhf.deb
# aim_1.8.6_i386.deb

# Maintained: Last release: 2025-03-15
# https://github.com/mihaigalos/aim
# aim [OPTIONS] [INPUT] [OUTPUT] [SHA256]
# -s, --silent                             Silent or quiet mode. Don't show progress meter or error messages.

function setup_util_aim() (
	source "$DOROTHY/sources/util.bash"
	util_options=(
		--cli='aim'
		CARGO='aim'
	)

	# improve performance for detectable utilities when fetching asset configuration
	if setup-util check "${util_options[@]}" "${user_options[@]}"; then
		return 0
	fi

	# fetch and use configuration
	local slug='mihaigalos/aim' arch
	arch="$(__get_arch)"
	if __is_macos; then
		__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-apple-darwin.tar.gz' 'aim' || :
	elif __is_linux; then
		if [[ $arch == 'a64' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_arm64.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-aarch64-unknown-linux-musl.tar.gz' 'aim' || :
		elif [[ $arch == 'a32' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_armhf.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-arm-unknown-linux-gnueabihf.tar.gz' 'aim' || :
		elif [[ $arch == 'x64' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_amd64.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-x86_64-unknown-linux-musl.tar.gz' 'aim' || :
		elif [[ $arch == 'x32' ]]; then
			__fetch_and_add_deb_option_via_slug_suffix "$slug" '_i686.deb' || :
			__fetch_and_add_download_option_via_slug_suffix_glob "$slug" '-i686-unknown-linux-gnu.tar.gz' 'aim' || :
		fi
	fi

	# setup
	setup-util "${util_options[@]}" "${user_options[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_aim "$@"
fi
