#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if is-linux; then
	# https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/linux#install-linux-prerequisites
	env NAME='VSCode Linux Dependencies' \
		CURL='https://aka.ms/vsls-linux-prereq-script' \
		setup-util curl
fi

env NAME='Visual Studio Code' CLI=code \
	AUR='visual-studio-code-bin' \
	CASK='visual-studio-code' \
	FLATPAK='com.visualstudio.code' \
	NIX='vscode' \
	SNAP_CLASSIC='yes' \
	SNAP='code' \
	setup-util aur cask flatpak nix snap

# flatpak does not get access to fonts, not liveshare dependencies
