#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

action="${1:?"USAGE: sparse-vault <new|open>"}"

if is-either "$action" "new" "create"; then
	name="${2:?"USAGE: sparse-vault new <NAME> <MAXSIZE|100g|1t> [SPARSE|SPARSEBUNDLE]"}"
	size="${3:?"USAGE: sparse-vault new <name> <MAXSIZE|100g|1t> [SPARSE|SPARSEBUNDLE]"}"
	type="${4:-SPARSE}"

	vol=$(basename "$name")
	version=$(sw_vers -productVersion | awk -F '.' '{print $2}')

	if test "$version" -ge "13"; then
		fs="APFS"
	else
		fs="Journaled HFS+"
	fi
	if test "$type" = "SPARSE"; then
		filename="$2.sparseimage"
	else
		filename="$2.sparsebundle"
	fi

	hdiutil create -type "$type" -encryption AES-256 -fs "$fs" -size "$size" -volname "$vol" "$name"
	hdiutil mount "$filename"

elif is-either "$action" "open" "mount"; then
	path="${2:?"SAGE: sparse-vault open <PATH>"}"
	hdiutil compact "$path" || echo 'compact failed, continuing...'
	hdiutil mount "$path"

else
	stderr echo "unknown state"
	exit 1
fi