#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# options
rurl="$(ask --question='Which SSH URI to test the connection to?' --default="${1:-"git@github.com"}" --required)"

# test and fetch exit code
strict_e_pause; eo="$?"
silent ssh -qT "$rurl"
ec="$?"; strict_e_restore "$eo"

# 0 no error
# 1 success but error - this is what github does, as is not a real ssh terminal
# 255 configuration error - this is what we are after
test "$ec" -le 1
