#!/usr/bin/env bash
source "$BDIR/sources/essentials.sh"
source "$BDIR/sources/strict.bash"
source "$BDIR/sources/globstar.bash"
source "$BDIR/sources/nullglob.bash"
source "$BDIR/sources/ssh.sh"
ssh-start-helper

set -x

chmod 700 ~/.ssh
find ~/.ssh/*.pub | while read -r f; do
	chmod 600 "$f"
	ok chmod 600 "${f%.pub}"
done

find ~/.ssh/*.pub | while read -r f; do
	p="${f%.pub}"
	if test -f "$p"; then
		if is-mac; then
			/usr/bin/ssh-add -K "$p"
		else
			ssh-add "$p"
		fi
	fi
done