#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# sudo a command inheriting environment and path
# https://stackoverflow.com/q/257616/130638

while test "$1" = '--'; do
	shift
done

sudo -EH env PATH="$PATH" "$@"
