#!/usr/bin/env bash

function to-png() (
	source "$DOROTHY/sources/strict.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Convert the inputs into png files.

			USAGE:
			to-png ...<input>

			EXAMPLE:
			to-png *.jp*
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item files=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) files+=("$item") ;;
		esac
	done

	# =====================================
	# Act

	local input filename output
	for input in "${files[@]}"; do
		filename="$(fs-filename -- "$input")"
		output="$filename.png"
		sips -s format png "$input" --out "$output"
	done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	to-png "$@"
fi
