#!/usr/bin/env bash
# thanks to http://unix.stackexchange.com/a/358209/50703 for the help on this one
source "$DOROTHY/sources/strict.bash"

id="$(rand)"
config="$(mktemp)"

echo "screen ${1:?"USAGE: together <first command> <second command> <...>"}" >> "$config"

for arg in "${@:2}"; do
	{ echo 'split'; echo 'focus'; echo "screen $arg" ; } >> "$config"
done

screen -AS "$id" -c "$config"
