#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if is-help "$@"; then
	stderr echo-lines \
		'ABOUT:' \
		'Trims empty lines at the start and end of the stdin or arguments.' \
		'' \
		'USAGE:' \
		"echo $'\n\na\n\n' | trim" \
		"trim '' $'\n' 'a' ' ' $'\t'"
	exit 22 # Invalid argument
fi

lines=()
i=0
at='start'
empties_at_start=0  # goes positive
empties_at_end=0    # goes negative
function act {
	lines+=("$1")
	if is-empty-string "$1"; then
		if test "$at" = 'end'; then
			empties_at_end=$((empties_at_end + 1))
		fi
	else
		if test "$at" = 'start'; then
			at='end'
			empties_at_start="$i"
		fi
		empties_at_end=0
	fi
	i=$((i + 1))
}
function finish {
	if test "$i" -ne 0; then
		local z=$((i - empties_at_start - empties_at_end))
		echo-lines "${lines[@]:$empties_at_start:$z}"
	fi
}

source "$DOROTHY/sources/stdinargs.bash"
