#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

usage="USAGE: trim-audio [<audio-stream-to-keep>] ...<input-video-file>"

function convert() {
	local stream input extension filename output

	stream="$1"
	input="${2:?"$usage"}"
	extension="$(fs-extension "$input")"
	filename="$(fs-filename "$input")"

	if test "${stream}" -eq -1; then
		output="${filename} [no audio].${extension}"
	else
		output="${filename} [only audio stream ${stream}].${extension}"
	fi

	rm -f "$output"
	echo "converting $input to $output"

	if test "${stream}" -eq -1; then
		(ffmpeg -i "$input" -c copy -an "$output" && echo "trimmed audio from $input to $output") || fail "failed on $input to $output"
	else
		(ffmpeg -i "$input" -c copy -map 0:v -map 0:a:"${stream}" "$output" && echo "keep audio stream ${stream} from $input to $output") || fail "failed on $input to $output"
	fi
}

if is-integer "${1:?"$usage"}"; then
	for arg in "${@:2}"; do
		convert "$1" "$arg"
	done
else
	for arg in "${@:2}"; do
		convert -1 "$arg"
	done
fi
