#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=y setup-util-jq

# act
twitter-setup

# must use id_str: https://github.com/twitter/twurl/issues/160#issuecomment-757491365
twurl /1.1/statuses/user_timeline.json | jq -r '.[].id_str' | twitter-delete
