#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

twitter-setup

function act {
	echo "Muting: $1"
	twurl -d "screen_name=$1" '/1.1/mutes/users/create.json'
	echo -e '\n'
}

# stdin
stdin="no"
while IFS= read -rt 1 username; do
	stdin="yes"
	act "$username"
done <&0

if test "$stdin" = "no"; then
	# invalid
	if test "$#" -eq 0; then
		stderr echo 'USAGE: twitter-mute <...username>'
		stderr echo 'USAGE: twitter-mute <username-list-file>'
		stderr echo 'USAGE: cat username-list-file | twitter-mute'
		exit 1
	elif test "$#" -eq 1 -a -f "$1"; then
		# file
		while IFS= read -rt 1 username; do
			act "$username"
		done < "$1"
	else
		# usernames
		for username in "$@"; do
			act "$username"
		done
	fi
fi
