#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# help
if is-help-empty "$@"; then
	stderr echo-lines \
		'ABOUT:' \
		'Get the user identifier for a username.' \
		'' \
		'USAGE:' \
		'uid <username>'
	exit 22 # Invalid argument
fi

# options
username="$1"

# act
id -u "$username"
