#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# help
if is-help-empty "$@"; then
	stderr echo 'USAGE: unziptar <file> [--destination=.] [--format=.]'
	exit 1
fi

# options
filename="$(ask --question="Enter the path of the archive to extract." --default="${1-}" --required)"
destination="$(get-flag-value destination -- "$@")" # custom destination
format="$(get-flag-value format -- "$@")" # zip | tar | original filename, say a URL or so, before archive-file became a tmp file
if test -z "$format"; then
	format="$filename"
fi

filepath="$(fs-absolute "$filename")"

if test "$format" = 'zip' || [[ "$format" = *".zip" ]]; then
	if test -n "$destination"; then
		unzip "$filepath" -d "$destination"
	else
		unzip "$filepath"
	fi
else
	if test -n "$destination"; then
		mkdir -p "$destination"
		cd "$destination" || exit 1
		tar -xvzf "$filepath"
	else
		tar -xvzf "$filepath"
	fi
fi
