#!/usr/bin/env bash
source "$BDIR/sources/strict.bash"

if contains-string "${1:?USAGE: unziptar <archive-file> [extraction-destination]}" ".zip"; then
	if test -n "${2:-}"; then
		unzip "$1" -d "$2"
	else
		unzip "$1"
	fi
else
	if test -n "${2:-}"; then
		mkdir -p "$2"
		pushd "$2"
		tar -xvzf "$1"
		popd
	else
		tar -xvzf "$1"
	fi
fi
