#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# =====================================
# Arguments

# help
function help() {
	cat <<-EOF >/dev/stderr
		ABOUT:
		    ????

		USAGE:
		    update-grub-universal
	EOF
	if test "$#" -ne 0; then
		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
	fi
	return 22 # Invalid argument
}

# process
while test "$#" -ne 0; do
	item="$1"
	shift
	case "$item" in
	'--help' | '-h') help ;;
	'--'*) help "An unrecognised flag was provided: $item" ;;
	*) help "An unrecognised argument was provided: $item" ;;
	esac
done

# =====================================
# Act

if command-exists update-grub; then
	# manjaro
	sudo update-grub
elif command-exists grub-mkconfig:; then
	# https://itsfoss.com/update-grub/
	sudo grub-mkconfig -o /boot/grub/grub.cfg
elif is-ubuntu; then
	# https://pkgs.org/download/grub2-common
	# sudo: update-grub: command not found
	# sudo: grub-mkconfig: command not found
	env NAME='Grub Utilities' \
		APT=grub2-common \
		setup-util
	sudo update-grub
else
	# fedora uses grubby it seems, as grub2-common doesn't provide update-grub on fedora
	stderr echo 'Unsupported operating system for updating Grub.'
	exit 1
fi
