#!/usr/bin/env bash

function waiter_() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Take a break.

			USAGE:
			waiter [...options]

			OPTIONS:
			<timeout> | --timeout=<timeout>
			    If provided, will wait for this amount of seconds, and count down.
			    If not provided, will wait indefinitely, and count up.
				If zero, will not wait and will return immediately.

			--message=<message>
			    A custom message where %s will be replaced with the time remaining or the time waited.

			--exists=<path>
			    If the path exists, skip any more waiting, and return success exit status (0).

			--status=<exit-status>
			    If timed out, return this exit status.
			    Defaults to 0, however if --exists is provided, this will default to [ETIMEDOUT 60 Operation timed out] instead.

			--stdout=<stdout>
			    If provided, once done waiting, output this to STDOUT.
			--stderr=<stderr>
			    If provided, once done waiting, output this to STDERR.
			--tty=<tty>
			    If provided, once done waiting, output to this TTY.
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_timeout='' option_message='' option_exists='' option_status='' option_stdout='' option_stderr='' option_tty=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--timeout='*) option_timeout="${item#*=}" ;;
		'--message='*) option_message="${item#*=}" ;;
		'--exists='*) option_exists="${item#*=}" ;;
		'--status='*) option_status="${item#*=}" ;;
		'--stdout='*) option_stdout="${item#*=}" ;;
		'--stderr='*) option_stderr="${item#*=}" ;;
		'--tty='*) option_tty="${item#*=}" ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if [[ -z $option_timeout ]]; then
				option_timeout="$item"
			else
				help "An unrecognised argument was provided: $item"
			fi
			;;
		esac
	done

	# validate
	if [[ -n $option_timeout ]] && ! __is_integer "$option_timeout"; then
		help "If <timeout> is provided, it must be an integer, this is not an integer: $option_timeout"
	fi

	# status
	if [[ -z $option_status ]]; then
		if [[ -n $option_exists ]]; then
			option_status=60 # ETIMEDOUT 60 Operation timed out
		else
			option_status=0
		fi
	fi

	# message
	if [[ -z $option_message ]]; then
		if [[ -n $option_exists ]]; then
			if [[ -n $option_timeout ]]; then
				option_message="$(echo-style --dim='Waiting for path ' --code="$option_exists" --dim=' to become available... %s remaining')"
			else
				option_message="$(echo-style --dim='Waiting for path ' --code="$option_exists" --dim=' to become available... %s elapsed')"
			fi
		else
			if [[ -n $option_timeout ]]; then
				option_message="$(echo-style --dim='Waiting... %s remaining')"
			else
				option_message="$(echo-style --dim='Waiting... %s elapsed')"
			fi
		fi
	fi

	# =====================================
	# Action

	# print helpers
	function __print_plural {
		if [[ $1 -gt 1 ]]; then
			printf '%s' 's'
		fi
	}
	function __print_minutes {
		local plural
		plural="$(__print_plural "$1")"
		printf "$option_message"$'\n' "$1 minute$plural"
	}
	function __print_seconds {
		local plural
		plural="$(__print_plural "$1")"
		printf "$option_message"$'\n' "$1 second$plural"
	}
	function __print_minutes_and_seconds {
		local plural_minutes plural_seconds
		plural_minutes="$(__print_plural "$1")"
		plural_seconds="$(__print_plural "$2")"
		printf "$option_message"$'\n' "$1 minute$plural_minutes and $2 second$plural_seconds"
	}

	# wait
	local -i minutes delta waited=0
	while :; do
		if [[ -n $option_exists && -e $option_exists ]]; then
			option_status=0
			break
		fi
		if [[ -n $option_timeout ]]; then
			if [[ $option_timeout -eq 0 ]]; then
				break
			fi
			if [[ $option_timeout -gt 60 ]]; then
				minutes="$((option_timeout / 60))"
				delta="$((option_timeout % 60))"
				if [[ $delta -eq 0 ]]; then
					__do --redirect-stdout=TTY -- __print_minutes "$minutes"
					delta=60
				else
					__do --redirect-stdout=TTY -- __print_minutes_and_seconds "$minutes" "$delta"
				fi
				option_timeout="$((option_timeout - delta))"
				sleep "$delta"
			else
				__do --redirect-stdout=TTY -- __print_seconds "$option_timeout"
				option_timeout="$((option_timeout - 1))"
				sleep 1
			fi
		elif [[ $waited -gt 60 ]]; then
			minutes="$((waited / 60))"
			delta="$((option_timeout % 60))"
			__do --redirect-stdout=TTY -- __print_minutes "$minutes"
			if [[ $delta -eq 0 ]]; then
				delta=60
			fi
			waited="$((waited + delta))"
			sleep "$delta"
		else
			__do --redirect-stdout=TTY -- __print_seconds "$waited"
			waited="$((waited + 1))"
			sleep 1
		fi
		# erase duration message
		__do --redirect-stdout=TTY -- echo-style --no-trail --delete-line
	done

	# waiting done, do dumps if we have them
	if [[ -n ${option_stdout-} ]]; then
		__print_lines "$option_stdout"
	fi
	if [[ -n ${option_stderr-} ]]; then
		__print_lines "$option_stderr" >&2
	fi
	if [[ -n ${option_tty-} ]]; then
		__do --redirect-stdout=TTY -- __print_lines "$option_tty"
	fi
	return "$option_status"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	waiter_ "$@"
fi
