#!/usr/bin/env bash

function waiter_() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Take a break.

			USAGE:
			waiter [...options]

			OPTIONS:
			<timeout> | --timeout=<timeout>
			    If provided, will wait for this amount of seconds, and count down.
			    If not provided, will wait indefinitely, and count up.

			--message=<message>
			    A custom message where %s will be replaced with the time remaining or the time waited.

			--exists=<path>
			    If the path exists, skip any more waiting, and return success exit status (0).

			--status=<exit-status>
			    If timed out, return this exit status.
			    Defaults to 0, however if --exists is provided, this will default to [ETIMEDOUT 60 Operation timed out] instead.

			--stdout=<stdout>
			    If provided, once done waiting, output this to stdout.

			--stderr=<stderr>
			    If provided, once done waiting, output this to stderr.

			--tty=<tty>
			    If provided, once done waiting, output to this TTY.

			--no-magic
			    If provided, output wait messages to stdout, and do not clear wait messages.
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_timeout='' option_message='' option_exists='' option_status='' option_stdout='' option_stderr='' option_tty='' option_magic='yes'
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--timeout='*) option_timeout="${item#*=}" ;;
		'--message='*) option_message="${item#*=}" ;;
		'--exists='*) option_exists="${item#*=}" ;;
		'--status='*) option_status="${item#*=}" ;;
		'--stdout='*) option_stdout="${item#*=}" ;;
		'--stderr='*) option_stderr="${item#*=}" ;;
		'--tty='*) option_tty="${item#*=}" ;;
		'--no-magic') option_magic='no' ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			if test -z "$option_timeout"; then
				option_timeout="$item"
			else
				help "An unrecognised argument was provided: $item"
			fi
			;;
		esac
	done

	# validate
	if test -n "$option_timeout" && ! is-integer -- "$option_timeout"; then
		help "If <timeout> is provided, it must be an integer, this is not an integer: $option_timeout"
	fi

	# status
	if test -z "$option_status"; then
		if test -n "$option_exists"; then
			option_status=60 # ETIMEDOUT 60 Operation timed out
		else
			option_status=0
		fi
	fi

	# message
	if test -z "$option_message"; then
		if test -n "$option_exists"; then
			if test -n "$option_timeout"; then
				option_message="$(echo-style --dim='Waiting for path ' --code_notice="$option_exists" --dim=' to become available... %s remaining')"
			else
				option_message="$(echo-style --dim='Waiting for path ' --code_notice="$option_exists" --dim=' to become available... %s elapsed')"
			fi
		else
			if test -n "$option_timeout"; then
				option_message="$(echo-style --dim='Waiting... %s remaining')"
			else
				option_message="$(echo-style --dim='Waiting... %s elapsed')"
			fi
		fi
	fi

	# =====================================
	# Action

	local tty_target='/dev/stdout'
	if test "$option_magic" = 'yes'; then
		tty_target="$(is-tty --fallback)"
	fi

	# print helpers
	function print_plural {
		if test "$1" -gt 1; then
			printf '%s' 's'
		fi
	}
	function print_minutes {
		local plural
		plural="$(print_plural "$1")"
		# trunk-ignore(shellcheck/SC2059)
		printf "$option_message"$'\n' "$1 minute$plural" >"$tty_target"
	}
	function print_seconds {
		local plural
		plural="$(print_plural "$1")"
		# trunk-ignore(shellcheck/SC2059)
		printf "$option_message"$'\n' "$1 second$plural" >"$tty_target"
	}
	function print_minutes_and_seconds {
		local plural_minutes plural_seconds
		plural_minutes="$(print_plural "$1")"
		plural_seconds="$(print_plural "$2")"
		# trunk-ignore(shellcheck/SC2059)
		printf "$option_message"$'\n' "$1 minute$plural_minutes and $2 second$plural_seconds" >"$tty_target"
	}

	# wait
	local -i minutes delta waited=0
	while true; do
		if test -n "$option_exists" -a -e "$option_exists"; then
			option_status=0
			break
		fi
		if test -n "$option_timeout"; then
			if test "$option_timeout" -eq 0; then
				break
			fi
			if test "$option_timeout" -gt 60; then
				minutes="$((option_timeout / 60))"
				delta="$((option_timeout % 60))"
				if test "$delta" -eq 0; then
					print_minutes "$minutes"
					delta=60
				else
					print_minutes_and_seconds "$minutes" "$delta"
				fi
				option_timeout="$((option_timeout - delta))"
				sleep "$delta"
			else
				print_seconds "$option_timeout"
				option_timeout="$((option_timeout - 1))"
				sleep 1
			fi
		elif test "$waited" -gt 60; then
			minutes="$((waited / 60))"
			delta="$((option_timeout % 60))"
			print_minutes "$minutes"
			if test "$delta" -eq 0; then
				delta=60
			fi
			waited="$((waited + delta))"
			sleep "$delta"
		else
			print_seconds "$waited"
			waited="$((waited + 1))"
			sleep 1
		fi
		if test "$option_magic" = 'yes'; then
			echo-clear-line >"$tty_target"
		fi
	done

	# waiting done, do dumps if we have them
	if test "${option_stdout-}"; then
		print_line "$option_stdout" >/dev/stdout
	fi
	if test "${option_stderr-}"; then
		print_line "$option_stderr" >/dev/stderr
	fi
	if test "${option_tty-}"; then
		print_line "$option_tty" >"$tty_target"
	fi
	return "$option_status"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	waiter_ "$@"
fi
