#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# help
if is-help "$@"; then
	cat <<-EOF >/dev/stderr
		ABOUT:
		?????
	EOF
	return 22 # Invalid argument
fi

p="${1:-"$(
	choose-option --required \
		--question='Which path to identify users of?' \
		-- /Volumes/*
)"}"
sudo lsof "$p"
