#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function what-is-my-gateway() (
	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Outputs your network gateway.

			USAGE:
			what-is-my-gateway
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # Invalid argument
	}

	# process
	local item
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Dependencies

	source "$DOROTHY/sources/ripgrep.bash"
	setup-util-sd --quiet
	setup-util-netstat --quiet

	# =====================================
	# Act

	if command-exists ip; then
		# shellcheck disable=SC2016
		ip route show dev eth0 | rg -o 'via (.+?) ' --replace '$1' | echo-first
	elif command-exists netstat; then
		# shellcheck disable=SC2016
		netstat -nr | rg ' UG.+?(en0|eth0)' | sd '(0.0.0.0|default) +(.+?) .+' '$2' | echo-first
	else
		echo-style --error='install [ip] or [netstat] and try again' >/dev/stderr
		exit 19 # ENODEV 19 Operation not supported by device
	fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	what-is-my-gateway "$@"
fi
