#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

if command-missing rg; then
	stderr echo 'missing dependency [ripgrep], installing automatically...'
	stderr setup-util-ripgrep
fi

# resolvectl is currently failing with:
# Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found.
# probably because of adguard home disabling it???

# cycle through interfaces
ip address show dev eth0 | rg -o 'inet (.+?)[/ ]' --replace '$1'
