#!/usr/bin/env bash

function what_is_my_subnet() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Outputs your network subnet.

			USAGE:
			what-is-my-subnet
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# =====================================
	# Dependencies

	source "$DOROTHY/sources/ripgrep.bash"
	# @todo update for get-installer --invoke

	# =====================================
	# Act

	if command-exists ip; then
		# `ip route show dev eth0` is too specific, doesn't work on vms among others
		ip route show | rg --only-matching --regexp='(.+?/\d+?) dev e' --replace='$1' | echo-first-line
	else
		echo-style --error='Install [ip] try again' >/dev/stderr
		return 19 # ENODEV 19 Operation not supported by device
	fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	what_is_my_subnet "$@"
fi
