#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# options
what="$(choose-option --question='Which IP do you want?' --filter="${1-}" -- local remote)"

if test "$what" = 'remote'; then
	# does not take into account cloudflare warp
	# fetch https://ipinfo.io/ip

	# does take into account cloudflare warp
	fetch https://whatmyip.bevry.workers.dev
else
	# dependencies
	env QUIET=y setup-util-ripgrep

	# cycle through interfaces
	ip -brief address | rg -o 'UP\s+(.+?)[/ ]' --replace '$1'
fi
