#!/usr/bin/env bash

function what_is_listening() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Discover and display information about network services that are actively listening for incoming connections.

			USAGE:
			what-is-listening [dns|everything]
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_type=''
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'dns' | 'everything') option_type="$item" ;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# ask
	option_type="$(
		choose-option \
			--question='What do you want to check for?' \
			--filter="$option_type" -- dns everything
	)"

	# =====================================
	# Dependencies

	# =====================================
	# Act

	# fetch
	if test "$option_type" = 'dns'; then
		# check
		if command-missing 'ss'; then
			echo-error '[ss] command is required to check what is listening to only DNS'
			return 19 #  ENODEV 19 Operation not supported by device
		fi
		# what is listening on dns port 53
		sudo-helper -- ss -lp 'sport = :domain'
	else
		setup-util-netstat --quiet
		sudo-helper -- netstat -tunl
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	what_is_listening "$@"
fi
