#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=yes setup-util-netstat

# =====================================
# Arguments

# help
function help() {
	cat <<-EOF >/dev/stderr
		ABOUT:
		    Get your local or remote IP address.

		USAGE:
		    what-is-my-ip [local|remote]
	EOF
	if test "$#" -ne 0; then
		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
	fi
	return 22 # Invalid argument
}

# process
what=''
while test "$#" -ne 0; do
	item="$1"
	shift
	case "$item" in
	'dns' | 'everything') what="$item" ;;
	'--'*) help "An unrecognised flag was provided: $item" ;;
	*) help "An unrecognised argument was provided: $item" ;;
	esac
done

# ask
what="$(
	choose-option \
		--question='What do you want to check for?' \
		--filter="${what-}" -- dns everything
)"

# =====================================
# Act

# check
if command-missing 'ss'; then
	echo-style --dim+red='[ss] command missing, cannot just fetch DNS' >/dev/stderr
	what='everything'
fi

# fetch
if test "$what" = 'dns'; then
	# what is listening on dns port 53
	sudo ss -lp 'sport = :domain'
else
	sudo netstat -tunl
fi
