#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# dependencies
env QUIET=y setup-util-netstat

# ask
what="$(choose-option --question='What do you want to check for?' --filter="${1-}" -- dns everything)"
if test "$what" = 'dns'; then
	# what is listening on dns port 53
	sudo ss -lp 'sport = :domain'
else
	sudo netstat -tunl
fi
