#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# XPS to PDF
# https://gist.github.com/balupton/7f15f6627d90426f12b24a12a4ac5975
cwd="$(pwd)"
bin=gxps
if command-missing "$bin"; then
	bin="$HOME/bin/ghostpdl-9.20/bin/gxps"
	if command-missing "$bin"; then
		echo "downloading and compiling gxps dependency to $bin"
		mkdir -p "$HOME/bin"
		cd "$HOME/bin" || exit 1
		down-zip https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs920/ghostpdl-9.20.tar.gz
		cd ./ghostpdl-9.20 || exit 1
		./configure
		make
		cd "$cwd" || exit 1
	fi
fi

echo "converting $# files"
for xps in "$@"; do
	pdf=$(echo "$xps" | sed 's/...$//')pdf

	echo "converting $xps to $pdf"
	$bin -sDEVICE=pdfwrite -sOutputFile="$pdf" -dNOPAUSE "$xps"

	if command-exists GetFileInfo && command-exists SetFile; then
		ctime=$(GetFileInfo -m "$xps")
		SetFile -d "$ctime" "$pdf"
	fi
done
