#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# `--prefer-free-formats` only prefers, it doesn't guarantee

# for thumbnails, no need to embed avif yet (which lacks wide support), as:
# jpeg patent expired in 2006
# jpeg-2000 is free to use
# png is an open-standard

youtube-dl \
	--recode-video webm \
	--merge-output-format webm \
	--format '(bestvideo[vcodec^=av01]/bestvideo[vcodec^=vp9])+bestaudio[acodec=opus]' \
	"$@"
