name: "Dorothy Dependencies"
description: "Installs Dorothy's dependencies, supporting numerous platforms."
runs:
  using: "composite"
  steps:
    - name: "Dorothy Dependencies"
      shell: sh {0} # composite actions require shell
      run: |
        set -x # allow us to know what used what
        # this should somewhat coincide with [commands/dorothy:ensure_prereq_dependencies]
        if command -v apt-get; then
          # for ubuntu/debian/kali
          apt-get update || exit $?
          apt-get install -y bash curl || exit $?
        elif command -v zypper; then
          # for opensuse
          zypper --non-interactive --gpg-auto-import-keys refresh || exit $?
          zypper --non-interactive install bash curl || exit $?
        elif command -v apk; then
          # for alpine
          apk update || exit $?
          apk add bash curl || exit $?
        elif command -v pacman; then
          # for manjaro (manjaro CI image doesn't have pamac installed) and arch
          pacman-key --init || exit $?
          pacman --noconfirm --refresh --sync --sysupgrade || exit $? # resolves version mismatches between git and pcre2, alternative is to `pacman -S pacman-contrib; pacman -S $(pactree -u git)`
          pacman --noconfirm --refresh --sync --needed bash curl || exit $?
        elif command -v urpmi; then
          # for mageia, prefer over fedora as mageia also contains dnf
          # https://wiki.mageia.org/en/Cauldron
          # https://github.com/bevry/dorothy/actions/runs/6033044029/job/16369147940
          # https://github.com/bevry/dorothy/actions/runs/6033557632/job/16370418074
          # urpmi --auto-update --auto
          urpmi.update -a || exit $?
          urpmi --auto bash curl || exit $?
        elif command -v dnf; then
          # for Fedora, AlmaLinux, OpenMandriva, OpenEuler
          dnf makecache --refresh || exit $? # dnf check-update --assumeyes
          dnf install --assumeyes --refresh --best --allowerasing bash curl readline || exit $? # readline to attempt to resolve `bash: symbol lookup error: bash: undefined symbol: rl_completion_rewrite_hook` on `openmandriva/rolling` on arm
        elif command -v xbps-install; then
          # for void linux
          xbps-install --sync --update --yes xbps || exit $?
          xbps-install --sync --yes bash curl || exit $?
        elif command -v nix-env; then
          # for nix
          nix-env --install --attr nixpkgs.bash nixpkgs.curl || exit $?
        elif command -v emerge; then
          # for gentoo
          emerge app-shells/bash net-misc/curl || exit $?
        fi
