name: "Dorothy Test"
description: "Runs Dorothy's test suite via remote invocation."
inputs:
  GITHUB_TOKEN:
    description: "Used to increase rate limits. Should be read-only."
    required: true
  SLUG:
    required: false
    default: "bevry/dorothy"
  COMMIT:
    required: true
  COMMAND:
    required: true
runs:
  using: "composite"
  steps:
    - name: "Dorothy Test"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash -leo pipefail {0} # composite actions require shell
      run: |
        # ensure dorothy is cloned, and run command
        bash -c "$(curl -fsSL 'https://dorothy.bevry.me/run?slug=${{ inputs.SLUG }}&commit=${{ inputs.COMMIT }}')" -- ${{ inputs.COMMAND }}
