name: "Dorothy Remote Action"
description: "Runs a Dorothy action, via remote execution."
inputs:
  GITHUB_TOKEN:
    description: "Used to increase rate limits. Should be read-only."
    required: true
  SLUG:
    required: false
    default: "bevry/dorothy"
  COMMIT:
    required: true
  ACTION:
    required: true
  ARGUMENTS:
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - name: "Dorothy Test"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash -eo pipefail {0} # composite actions require shell, openmandriva fails if this is a login shell
      run: bash -c "$(curl -fsSL "https://dorothy.bevry.me/${{ inputs.ACTION }}?slug=${{ inputs.SLUG }}&commit=${{ inputs.COMMIT }}")" ${{ inputs.ARGUMENTS }}
