#!/usr/bin/env bash
source "$HOME/.scripts/sources/strict.bash"
# https://apple.stackexchange.com/a/326863/15131
# https://stackoverflow.com/a/39208361/130638

vscode="/Users/$(whoami)/Library/Application Support/Code/User/settings.json"
vslight="GitHub Plus"
vsdark="An Old Hope"  # "Adapta Nokto", "An Old Hope", "Dracula", "Monokai++"

function wallpaper {
	path="/Users/balupton/Documents/Media/Media - Wallpapers/High Quality/Time/$1"
	osascript -e 'tell application "System Events" to tell current desktop to set pictures folder to "'"$path"'"'
}

# Dark Mode
if is-affirmative "${1:-}" "yes"; then
	echo 'enabling dark mode...'
	osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'
	wallpaper Night
	replace-inside "$vscode" "$vslight" "$vsdark"

# Light Mode
elif is-affirmative "${1:-}" "no"; then
	echo 'disabling dark mode...'
	osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to false'
	wallpaper Day
	replace-inside "$vscode" "$vsdark" "$vslight"

# Popping
else
	echo 'toggling dark mode...'
	osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to not dark mode'
	wallpaper Popping
	replace-inside "$vscode" "$vsdark" "$vslight"
fi
