#!/usr/bin/env bash
set -e

if test -d "$HOME/bin"; then
	d="$HOME/bin"
elfi test -d "/usr/local/bin"; then
	d="/usr/local/bin"
else
	echo "could not determine bin directory"
	exit 1
fi

u="$1"  # url
f="$(basename "$u")"  # filename
p="$d/$f"  # path

wget -nv -O "$p" "$u"
chmod +x "$p"
