#!/usr/bin/env bash -l
# ^ uses login shell to get access to the edit function
set -e

addscripts

if test -z "$1"; then
	edit "$HOME/.scripts" "$HOME/README.md"
else
	edit "$HOME/.scripts/commands/$1"
fi
