#!/bin/bash

# Download and extract a github repository rather than cloning it, should be faster if you don't need git history
function gitdown {
	set -e
	local repo; repo=$(echo "$1" | sed "s/https:\/\/github.com\///" | sed "s/.git//")
	local file; file=$(basename "$repo")

	# Download the tarball
	rm -Rf "$file" "$file.tar.gz"
	mkdir -p "$file"
	cd "$file"
	down "https://github.com/$repo/archive/master.tar.gz" -O "$file.tar.gz"

	# Extract the tarball
	tar -xvzf "$file.tar.gz"
	mv ./*-master/* .
	rm -Rf ./*-master "$file.tar.gz"
	cd ..
}

gitdown "$@"