#!/usr/bin/env bash
set -e

if test -d "$HOME/.scripts"; then
	echo "skipping clone of dotfiles as they appear to already be there"
else
	echo "cloning the dotfiles into your home directory"
	cd "$HOME"
	git init
	git remote add origin https://github.com/balupton/dotfiles.git
	git pull origin master --force
fi

echo "enforcing correct dotfile permissions"
chmod +x ~/.scripts/commands/*

echo "running dotfile setup command"
~/.scripts/commands/setup-dotfiles

echo "dotfiles installed, open a new terminal to continue..."
exit
