#!/usr/bin/env bash
source "$HOME/.scripts/sources/strict.bash"

# iOS Simulator
app=$(get-app Xcode-beta.app)
if is-dir "$app"; then
	open "$app/Contents/Developer/Applications/Simulator.app"
else
	app=$(get-app Xcode.app)
	if is-dir "$app"; then
		open "$app/Contents/Developer/Applications/Simulator.app"
	else
		echo "Xcode is not installed"
	fi
fi