#!/usr/bin/env bash

if test "$1" = "list" -a "$2" = "public"; then
	gpg --list-keys --keyid-format LONG

elif test "$1" = "list" -a "$2" = "private"; then
	gpg --list-secret-keys --keyid-format LONG

elif test "$1" = "get" -a "$2" = "public"; then
	gpg --list-keys --keyid-format LONG | grep "pub " | sed "s/.*\///g; s/ .*//g"

elif test "$1" = "get" -a "$2" = "private"; then
	gpg --list-secret-keys --keyid-format LONG | grep "sec " | sed "s/.*\///g; s/ .*//g"

elif test "$1" = "new"; then
	gpg --gen-key

elif test "$1" = "export" -a "$2" = "public"; then
	gpg --armor --export "$3"

elif test "$1" = "export" -a "$2" = "private"; then
	gpg --armor --export-secret-keys "$3"

elif test "$1" = "delete" -a "$2" = "public"; then
	gpg --delete-keys "$3"

elif test "$1" = "delete" -a "$2" = "private"; then
	gpg --delete-secret-keys "$3"

elif test "$1" = "trust"; then
	echo "trust" | gpg --edit-key "$2"

elif test "$1" = "extend"; then
	DATE="$(date -v +1y "+%Y-%m-%d")"
	gpg --quick-set-expire "$2" "$DATE"

else
	echo "key <list|get> <public|private>"
	echo "key <export|delete> <public|private> <\$key>"
	echo "key <trust|extend> <\$key>"
fi