#!/usr/bin/env bash
set -e

# Guides
# https://www.gnupg.org/gph/en/manual.html
# https://riseup.net/en/security/message-security/openpgp/best-practices
# https://debian-administration.org/users/dkg/weblog/97
# https://davesteele.github.io/gpg/2014/09/20/anatomy-of-a-gpg-key/
# https://www.void.gr/kargig/blog/2013/12/02/creating-a-new-gpg-key-with-subkeys/

# Codes
# sec => 'SECret key'
# ssb => 'Secret SuBkey'
# pub => 'PUBlic key'
# sub => 'public SUBkey'

if test "$1" = "list"; then
	if test "$2" = "private"; then
		gpg --keyid-format LONG -K
	else
		gpg --keyid-format LONG -k
	fi

elif test "$1" = "get"; then
	if test "$2" = "private"; then
		flag="K"
		type="sec"
	else
		flag="k"
		type="pub"
	fi

	keys="$(gpg --fingerprint --keyid-format LONG -$flag | grep -A1 "$type" | grep "Key fingerprint =" | sed "s/.*=//; s/ *//g")"
	if test -z "$keys"; then
		echo 'no keys yet'
		exit 1
	fi

	count="$(echo "$keys" | wc -l | tr -d ' ')"
	if test "$count" = "1"; then
		echo "$keys"
	else
		select key in $keys; do
			test -n "$key" && break
		done
		echo "$key"
	fi

elif test "$1" = "export" -a -n "$3"; then
	if test "$2" = "private"; then
		gpg --armor --export-secret-keys "$3"
	else
		gpg --armor --export "$3"
	fi

elif test "$1" = "delete" -a -n "$3"; then
	if test "$2" = "private"; then
		gpg --delete-secret-keys "$3"
	else
		gpg --delete-keys "$3"
	fi

elif test "$1" = "new"; then
	gpg --gen-key

elif test "$1" = "edit"; then
	gpg --edit-key "$2"

elif test "$1" = "trust"; then
	echo "trust" | gpg --edit-key "$2"

elif test "$1" = "extend"; then
	if test -n "$3"; then
		DATE="$3"
	else
		DATE="$(date -v +1y "+%Y-%m-%d")"
	fi
	gpg --quick-set-expire "$2" "$DATE"

elif test "$1" = "expire"; then
	DATE="$(date -v +0d "+%Y-%m-%d")"
	gpg --quick-set-expire "$2" "$DATE"

elif test "$1" = "encrypt"; then
	FILE="$2"
	THEM="$3"
	YOU="$4"
	if test -n "$YOU"; then
		gpg -ase -r "$THEM" -u "$YOU" "$FILE"
	else
		gpg -ase -r "$THEM" "$FILE"
	fi

elif test "$1" = "decrypt"; then
	gpg -d "$2"

elif test "$1" = "sencrypt"; then
	gpg -c "$2"

else
	echo "key <list|get> <public|private>"
	echo "key <export|delete> <public|private> <\$key>"
	echo "key <extend> <\$key> [\$date]"
	echo "key <edit|trust|expire> <\$key>"
	echo "key <encrypt> <\$file> <\$recipient> [\$key]"
	echo "key <decrypt|sencrypt> <\$file>"
fi