#!/usr/bin/env bash
set -e

if test "$1" != "backup" -a "$1" != "restore"; then
	echo "USAGE:"
	echo "BACKUP TO CLOUD: macup backup"
	echo "RESTORE FROM TIME MACHINE: macup restore"
	exit 1
fi

echo "Make sure that Time Machine is configured, or you have the Time Machine Backup Volume mounted. Press any key to continue."
read -r -n 1 -p ''
echo -e '\n'

export warnings="";
export action="$1"
export localRoot="$HOME"
export cloudRoot="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Apps/macup"

export timeBackup="$2";
if is_empty_string "$timeBackup"; then
	echo "Fetching latest Time Maching backup..."
	timeBackup="$(expandpath /Volumes/Time\ Machine\ Backups/Backups.backupdb/*/Latest)"
	if ! is_dir "$timeBackup"; then
		timeBackup="$(tmutil latestbackup)"
		if is_empty_string "$timeBackup"; then
			echo "Time Machine backup couldn't be determined automatically"
			exit 1
		fi
	fi
fi

export timeRoot;
if is_dir "$timeBackup/Macintosh HD$HOME"; then
	timeRoot="$timeBackup/Macintosh HD$HOME"
elif is_dir "$timeBackup/System$HOME"; then
	timeRoot="$timeBackup/System$HOME"
elif is_dir "$timeBackup$HOME"; then
	timeRoot="$timeBackup$HOME"
elif is_dir "$(expandpath "$timeBackup/*$HOME")"; then
	timeRoot="$(expandpath "$timeBackup/*$HOME")"
else
	echo "Could not find user directory in time machine backup: $timeBackup"
	exit 1
fi
if is_equal "$action" "restore"; then
	echo "Restoring from: $timeRoot"
fi

function backup {
	echo "backup: $1"
	if is_exists "$localRoot/$1"; then
		sudo rm -Rf "$cloudRoot/$1"
		mkdir -p "$(dirname "$cloudRoot/$1")"
		cp -fpLRv "$localRoot/$1" "$cloudRoot/$1"
	else
		warning="MISSING: $localRoot/$1"
		warnings="$warnings\n$warning"
		echo "$warning"
	fi
}
function restore {
	echo "Restoring: $1"
	if is_exists "$timeRoot/$1"; then
		sudo rm -Rf "$localRoot/$1"
		mkdir -p "$(dirname "$localRoot/$1")"
		if test "$timeRoot" = *"Time Machine Backups"*; then
			tmutil restore -v "$timeRoot/$1" "$localRoot/$1"
		else
			cp -fav "$timeRoot/$1" "$localRoot/$1"
		fi
	else
		warning="MISSING: $timeRoot/$1"
		warnings="$warnings\n$warning"
		echo "$warning"
	fi
}
function remove {
	echo "Removing: $1"
	sudo rm -Rf "$localRoot/$1"
}
function act {
	if is_equal "$action" "backup"; then
		backup "$1"
	elif is_equal "$action" "restore"; then
		restore "$1"
	fi
}
function process {
	if confirm "$1"; then
		for p in "${@:2}"; do
			act "$p"
		done
	else
		echo "Skipping: $1"
	fi
}

process "GPG" ".gnupg"
process "SSH" ".ssh"
process "NPM" ".npmrc"
process "Bash History" ".bash_history"
process "Travis" ".travis/config.yml"
process ".scripts/env" ".scripts/env.sh"

process "Downloads" "Downloads"
process "Projects" "Projects"

process "1Password" "Library/Containers/com.agilebits.onepassword-osx"
process "Amphetamine" "Library/Containers/com.if.Amphetamine"

process "Apple iTunes" \
	"Media" \
	"Music" \
	"Library/iTunes" \
	"Library/Preferences/com.apple.iPod.plist" \
	"Library/Preferences/com.apple.iTunes.plist"

process "Apple Mail" "Library/Containers/com.apple.mail/Data/Library/Preferences"

if confirm "Apple Messages"; then
	# http://apple.stackexchange.com/a/173940/15131
	remove "Library/Caches/com.apple.iChat"
	act "Library/Preferences/com.apple.imessage.bag.plist"
	act "Library/Preferences/com.apple.imservice.ids.FaceTime.plist"
	act "Library/Preferences/com.apple.imservice.ids.iMessage.plist"
	act "Library/Preferences/com.apple.iChat.AIM.plist"
	act "Library/Preferences/com.apple.iChat.Jabber.plist"
	act "Library/Preferences/com.apple.iChat.StatusMessages.plist"
	act "Library/Preferences/com.apple.iChat.Yahoo.plist"
	act "Library/Preferences/com.apple.iChat.plist"
	act "Library/Messages"
	act "Library/Containers/com.apple.iChat"
fi

process "Apple Safari History" \
	"Library/Safari/History.db" \
	"Library/Safari/History.db-lock" \
	"Library/Safari/History.db-shm" \
	"Library/Safari/History.db-wal" \
	"Library/Safari/HistoryIndex.sk"

process "Apple Safari Preferences" "Library/Preferences/com.apple.Safari.plist"
process "Apple Saved Searches" "Library/Saved Searches"
process "Apple Terminal" "Library/Preferences/com.apple.Terminal.plist"

process "AppZapper" "Library/Preferences/com.appzapper.AppZapper.plist"

process "Audio Hijack" \
	"Library/Application Support/Audio Hijack" \
	"Library/Preferences/com.rogueamoeba.audiohijack3.plist"

process "Bartender" "Library/Preferences/com.surteesstudios.Bartender.plist"
process "Boxy" "Library/Containers/com.francescodilorenzo.Mailbro"
process "Brave" "Library/Application Support/brave"

process "Calibre" \
	"Library/Preferences/calibre" \
	"Library/Preferences/net.kovidgoyal.calibre.plist"

process "Context" "Library/Preferences/com.contextsformac.Contexts.plist"
process "Cyberduck" "Library/Preferences/ch.sudo.cyberduck.plist"
process "DevDocs" "Library/Application Support/DevDocs"
process "Firefox" "Library/Application Support/Firefox"
process "Freedom" "Library/Preferences/com.80pct.FreedomPlatform.plist"
process "Hazeover" "Library/Preferences/com.pointum.hazeover.plist"
process "Kodi" "Library/Application Support/Kodi"

process "Little Snitch" \
	"Library/Application Support/Objective Development" \
	"Library/Application Support/Little Snitch" \
	"Library/Preferences/at.obdev.LittleSnitchAgent.plist" \
	"Library/Preferences/at.obdev.LittleSnitchConfiguration.plist" \
	"Library/Preferences/at.obdev.LittleSnitchNetworkMonitor.plist" \
	"Library/Preferences/at.obdev.LittleSnitchSoftwareUpdate.plist"

process "Loopback" \
	"Library/Preferences/com.rogueamoeba.Loopback.plist" \
	"Library/Preferences/com.rogueamoeba.loopbackd.plist"

process "Micro Snitch" "Library/Preferences/at.obdev.MicroSnitch.plist"
process "Opera" "Library/Application Support/com.operasoftware.Opera"

process "Plex" \
	"Library/Preferences/com.plexapp.plexmediaserver.plist" \
	"Library/Application Support/Plex Media Server"

process "Slack" "Library/Containers/com.tinyspeck.slackmacgap"

process "Skype" \
	"Library/Application Support/Skype" \
	"Library/Preferences/com.skype.skype.plist"

process "SoundSource" "Library/Preferences/com.rogueamoeba.soundsource.plist"

process "Spotify" \
	"Library/Preferences/com.spotify.client.plist" \
	"Library/Application Support/Spotify"

process "Spotifree" "Library/Preferences/de.eneas.Spotifree.plist"

process "Teamviewer" "Library/Preferences/com.teamviewer.teamviewer.preferences.plist"
process "Things" "Library/Containers/com.culturedcode.ThingsMac"

process "Tower" \
	"Library/Application Support/com.fournova.Tower2" \
	"Library/Preferences/com.fournova.Tower2.plist"

process "Transmit" \
	"Library/Preferences/com.panic.Transmit.plist" \
	"Library/Application Support/Transmit"

process "Transmission" \
	"Library/Preferences/org.m0k.transmission.plist" \
	"Library/Application Support/Transmission" \
	".config/transmission"

process "Tunnelblick" "Library/Application Support/Tunnelblick"

process "Typora" \
	"Library/Application Support/abnerworks.Typora" \
	"Library/Preferences/abnerworks.Typora.plist"

process "Usage" "Library/Application Support/com.mediaatelier.Usage"
process "Visual Studio Code" "Library/Application Support/Code"

process "VLC" \
	"Library/Application Support/org.videolan.vlc" \
	"Library/Preferences/org.videolan.vlc" \
	"Library/Preferences/org.videolan.vlc.plist"

process "VMware" "Library/Preferences/VMware Fusion"
process "Wire" "Library/Containers/com.wearezeta.zclient.mac"
process "XLD" "Library/Preferences/jp.tmkk.XLD.plist"

# Clean
setup-mac-clean

# Finish
if test -z "$warnings"; then
	echo "Completed successfully"
else
	echo -e "Completed with warnings:\n$warnings"
fi
