#!/bin/bash

set -e

export src; src="$HOME"
# export trg; trg="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Apps/macup"
export trg; trg="$(tmutil latestbackup)/System/Users/balupton"
export arg; arg="$1"

function backup {
	# tmutil startbackup -b
	echo "backup: $1"
	local dir; dir=$(dirname "$1")
	sudo rm -Rf "$trg/$1"
	mkdir -p "$trg/$dir"
	cp -fpLRv "$src/$1" "$trg/$1"
}
function restore {
	echo "restore: $1"
	local dir; dir=$(dirname "$1")
	sudo rm -Rf "$src/$1"
	mkdir -p "$src/$dir"
	# cp -pLRv "$trg/$1" "$src/$1"
	tmutil restore -v "$trg/$1" "$src/$1"
}
function remove {
	echo "remove: $1"
	sudo rm -Rf "$src/$1"
}
function process {
	if is_equal "$arg" "backup"; then
		backup "$1"
	elif is_equal "$arg" "restore"; then
		restore "$1"
	else
		echo "USAGE: macup <restore|backup>"
		exit -1
	fi
}

# transmission
process Library/Preferences/org.m0k.transmission.plist
process "Library/Application Support/Transmission"
# process .config/transmission

# skype
process "Library/Application Support/Skype"
process Library/Preferences/com.skype.skype.plist

# vlc
process "Library/Application Support/org.videolan.vlc"
process Library/Preferences/org.videolan.vlc
process Library/Preferences/org.videolan.vlc.plist

# typora
process "Library/Application Support/abnerworks.Typora"
process Library/Preferences/abnerworks.Typora.plist

# misc
process .gnupg
process .npmrc
process .ssh
process "Library/Application Support/com.mediaatelier.Usage"
process "Library/Application Support/DevDocs"
process Library/Preferences/com.surteesstudios.Bartender.plist
process Library/Preferences/com.spotify.client.plist
process Library/Preferences/com.pointum.hazeover.plist
process Library/Preferences/calibre
process "Library/Preferences/VMware Fusion"
process Library/Preferences/com.80pct.FreedomPlatform.plist
process Library/Preferences/com.agilebits.onepassword-osx.plist

# apple
process Library/Preferences/com.apple.Terminal.plist
process Library/Preferences/com.apple.iPod.plist
process Library/Preferences/com.apple.iTunes.plist

# http://apple.stackexchange.com/a/173940/15131
remove Library/Caches/com.apple.iChat
process Library/Preferences/com.apple.imessage.bag.plist
process Library/Preferences/com.apple.imservice.ids.FaceTime.plist
process Library/Preferences/com.apple.imservice.ids.iMessage.plist
process Library/Preferences/com.apple.iChat.AIM.plist
process Library/Preferences/com.apple.iChat.Jabber.plist
process Library/Preferences/com.apple.iChat.StatusMessages.plist
process Library/Preferences/com.apple.iChat.Yahoo.plist
process Library/Preferences/com.apple.iChat.plist
process Library/Messages
process Library/Containers/com.apple.iChat