#!/usr/bin/env bash -l
set -e

echo -e '\nswitching to system node'
nvm use system

echo -e '\ninstalling package globally'
npm install -g "$@"

echo -e '\nno need to switch back to local node as we are in a subshell'
