#!/usr/bin/env bash
set -e

if command_exists "pip"; then
	echo 'pip already installed'
else
	echo -e "installing pip"
	d="$(mktemp -d)"
	pushd "$d"
	down https://bootstrap.pypa.io/get-pip.py
	chmod +x ./get-pip.py
	./get-pip.py
	popd
	rm -Rf "$d"
fi
