#!/usr/bin/env bash

set -e

echo -e "\nInstalling node.js..."

# Configure nvm
if is_dir "$HOME/.nvm"; then
	echo -e "\nUpdating nvm..."
	cd "$HOME/.nvm"
	git checkout master
	git pull origin master
	cd "$HOME"
else
	echo -e "\nInstalling nvm..."
	git clone git://github.com/creationix/nvm.git "$HOME/.nvm"
fi

# Add nvm to the path of this bash script
# prevents the need for a full login shell
source "$HOME/.scripts/sources/nvm.bash"

echo -e "\nInstalling the latest node.js version and making it the default..."
nvm install node
nvm alias default node
nvm use node

echo -e "\nUpdating and installing npm packages..."
npm install -g npm
npm install -g yarn npm-check-updates live-server ci-watch bevry-base # slap
# https://github.com/yarnpkg/yarn/issues/2993#issuecomment-289703085
