#!/usr/bin/env bash -l
set -e

rm -Rf -Rf ~/.nvm

if test -z "$BREW_PREFIX"; then
	export BREW_PREFIX="/usr/local"
fi
t="$(mktemp)"
sudo bash <<EOF
grep -v "$BREW_PREFIX" /etc/shells > "$t"
cat "$t" > /etc/shells
rm "$t"
EOF

usesh /bin/bash

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

setup-git
pass git config --global --unset url.ssh://git@github.com/.insteadof
