#!/usr/bin/env bash
source "$HOME/.scripts/sources/essentials.sh"
set -e

# apt update
sudo apt-get update -y
sudo apt-get upgrade -y

# apt remove
if test -n "$APT_REMOVE"; then
	sudo apt-get remove -y --purge "${APT_REMOVE[@]}"
fi

# apt install
if test -n "$APT_ADD"; then
	sudo apt-get install -y "${APT_ADD[@]}"
fi

# apt clean
sudo apt-get clean -y
sudo apt-get autoremove -y

# snap update
sudo snap refresh