#!/usr/bin/env bash
set -e

echo -e "\nInstalling commenced..."

echo ''; if confirm "Would you like to restore from backup?"; then
	macup restore
fi
echo ''

setup-mac-settings
setup-mac-brew
setup-mac-apps
setup-mac-fonts

setup-bin
setup-git
setup-node
setup-ruby
setup-python
setup-vscode
setup-atom
setup-bin

setup-mac-clean

setup-shell

echo -e "\nInstallation completed successfully."