#!/usr/bin/env bash
source "$HOME/.scripts/sources/essentials.sh"
source "$HOME/.scripts/sources/ssh.sh"
source "$HOME/.scripts/sources/strict.bash"

echo -e '\nAdding ssh keys to authorise updates from servers...'
ssh-add-all
echo '...success'

echo -e '\nUpdating commenced...'

if confirm-positive "Check for system updates?"; then
	sudo softwareupdate -i -a --restart
fi

setup-base

setup-mac-brew update

setup-extras update

setup-mac-clean

echo -e '\n...updating completed successfully!'