#!/usr/bin/env bash
set -e

cd ~
git clone "git://github.com/sigurdga/gnome-terminal-colors-solarized.git"

cd gnome-terminal-colors-solarized
chmod +x install.sh

cd ~
rm -Rf gnome-terminal-colors-solarized