#!/usr/bin/env bash
set -e

pushd ~/.scripts/commands

echo "Would you like to remove the following files for a cleaner installation?"
./confirm ".profile" && rm -fv "$HOME/.profile"
./confirm ".bash_profile" && rm -fv "$HOME/.bash_profile"
./confirm ".bashrc" && rm -fv "$HOME/.bashrc"
./confirm ".zshrc" && rm -fv "$HOME/.zshrc"

echo "Would you like to use Benjamin Lupton's configuration (this contains things like which apps and packages to install)?"
./confirm "Use his configuration?" && printf '\n\n# Inherit \nsource "$HOME/.scripts/users/balupton.sh"' >> "$HOME/.scripts/users/$(whoami).sh"

echo "Would you like to use Benjamin Lupton's terminal theme?"
./confirm "Use his theme?" && printf '\n\n# Theme\nexport THEME="baltheme"' >> "$HOME/.scripts/env.sh"

if ./confirm "Would you like to configure the dotfiles for bash?"; then
	if ./is_mac; then
		printf '\n\n# Source our custom dotfile configuration\nsource "$HOME/.scripts/init.sh"' >> "$HOME/.bash_profile"
	else
		printf '\n\n# Source our custom dotfile configuration\nsource "$HOME/.scripts/init.sh"' >> "$HOME/.bashrc"
	fi
fi

if ./confirm "Would you like to configure the dotfiles for zsh?"; then
	printf '\n\n# Source our custom dotfile configuration\nsource "$HOME/.scripts/init.sh"' >> "$HOME/.zshrc"
fi

if ./confirm "Would you like to configure the dotfiles for fish?"; then
	mkdir -p "$HOME/.config/fish"
	printf '\n\n# Source our custom dotfile configuration\nsource "$HOME/.scripts/init.fish"' >>  "$HOME/.config/fish/config.fish"
fi

popd
