#!/usr/bin/env bash -l
# uses login shell as otherwise global vars won't exist
set -e

# Editor
echo "Git Configuration: Editor"
if is_string "$TERMINAL_EDITOR_PROMPT"; then
	git config --global core.editor "$TERMINAL_EDITOR_PROMPT"
elif is_string "$TERMINAL_EDITOR"; then
	git config --global core.editor "$TERMINAL_EDITOR"
elif is_string "$EDITOR"; then
	git config --global core.editor "$EDITOR"
fi
