#!/usr/bin/env bash
set -e

echo -e '\nInstalling commenced...'

# Bare minimum requirements for proceeding further
# install command line tools
ok xcode-select --install

# Backup restore
echo ''; if confirm "Would you like to restore from backup?"; then
	mac-state restore
fi
echo ''

# Mac setup
setup-mac-settings
setup-mac-brew install
setup-mac-apps
setup-mac-fonts

# Crossplatform extras
setup-extras install

# Mac clean
setup-mac-clean

echo -e '\nInstallation completed successfully.'
