#!/usr/bin/env bash
set -e

# Clean brew
brew cleanup
brew cask cleanup

# Remove updates that are not cleaned automatically
rm -Rf "$HOME/Library/Application Support/Plex Media Server/Updates"
rm -Rf "$HOME/Library/Application Support/Spotify/PersistentCache/Update"
