#!/usr/bin/env bash
set -e

echo -e '\nUpdating dot files...'

cd "$HOME"

log="$(mktemp)"
git pull origin master > "$log"
cat "$log"
if grep "Already" < "$log"; then
	echo "...dot files up-to-date, continuing!"
	rm "$log"
else
	echo -e '\n\nDot files were updated, open a new terminal and run the earlier command again...'
	rm "$log"
	exit 1
fi