#!/usr/bin/env bash

set -e

# Setup install functions
function brewinstall {
	brew install "$@"
}
function slowbrewinstall {
	# if we are on /usr/local then we are using bottles, which are pre-compiled, and are fast
	if test "$(brew --prefix)" == "/usr/local"; then
		brewinstall "$@"
	else
		# otherwise we are on a custom directory, can't use bottles, so have to compile ourselves, which takes forever
		echo; if confirm "Do you want to install [$*]? These can take hours, so best left overnight..."; then
			echo "$*"
			brewinstall "$@"
		fi
	fi
}
function confirmbrewinstall {
	for ARG in "$@"; do
		if confirm "Do you want to install: $ARG"; then
			brewinstall "$ARG"
		fi
	done
}
function confirmcaskinstall {
	for ARG in "$@"; do
		if confirm "Do you want to install the desktop application: $ARG"; then
			brew cask install "$ARG"
		fi
	done
}

# Setup brew
if command_exists brew; then
	echo -e "\nHomebrew is already installed, great"
else
	# recomended installation method, it is pretty much the only one that works properly
	# https://github.com/balupton/dotfiles/commit/fff6fbc079aaa6ab9bb8438e02c307ebad46fd75
	# https://github.com/balupton/dotfiles/commit/69dbbe81bf30f9e0d9a1dd1d00eca3f3c88b943b
	echo -e "\nInstalling homebrew via its recomended method..."
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Setup any custom brew directories
if is_string "$BREW_APPDIR"; then
	mkdir -p "$BREW_APPDIR"
fi
if is_string "$BREW_CASKROOM"; then
	mkdir -p "$BREW_CASKROOM"
fi

echo -e "\nInitialising homebrew cask..."
brew tap caskroom/cask
brew tap caskroom/fonts

echo -e "\nUpdating homebrew..."
brew update
brew upgrade

echo -e "\nInstalling command line applications via homebrew..."
brewinstall aria2 bash bash-completion heroku hub fish git git-extras python mas micro rmtrash ruby tmux tree wget watchman
slowbrewinstall gpg shellcheck
echo; if confirm "Do you want to install some user facing command line apps?"; then
	brewinstall youtube-dl ffmpeg libav
fi

echo; if confirm "Do you want to be presented with desktop appplications to install via homebrew cask?"; then
	echo "Here are some common desktop apps..."
	confirmcaskinstall appzapper bartender devdocs firefox github-desktop google-hangouts kodi plex-media-server screenflow skype spotify teamviewer tower transmission visual-studio-code vlc
	echo "Here are some less common desktop apps..."
	confirmcaskinstall airparrot atom burn brave calibre caption contexts ccleaner freedom geekbench jaikoz opera pomello toggldesktop spotifree reflector sketch torbrowser tunnelbear typora usage vmware-fusion windscribe xld
fi

echo -e "\nCleaning homebrew..."
brew cleanup
brew cask cleanup