#!/usr/bin/env bash
set -e

if ! command_exists apm; then
	echo -e "\nAtom (apm) does not seem to be installed..."
	exit
fi

if test "$1" == "update"; then
	mode="update"
else
	mode="install"
fi

echo -e "\nUpdating existing Atom plugins..."
apm update --no-confirm

if test "$mode" == "install"; then
	echo -e "\nInstalling Atom plugins..."
	apm install \
		apex/apex-ui-slim \
		atom-beautify \
		editorconfig \
		file-type-icons \
		highlight-selected \
		indentation-indicator \
		language-stylus \
		linter \
		linter-coffeelint \
		linter-csslint \
		linter-eslint \
		linter-flow \
		linter-jsonlint \
		linter-shellcheck \
		react \
		visual-bell \
		;
fi