#!/usr/bin/env bash

set -e

if command_exists brew; then
   echo "brew already installed"
elif is_dir "$HOME/.homebrew"; then
   echo "brew installed but not yet in path, reload your terminal"
else
   echo "installing brew locally..."
   # https://github.com/Homebrew/brew/blob/master/docs/Installation.md#untar-anywhere
   mkdir -p "$HOME/.homebrew"
   curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C "$HOME/.homebrew"
fi

echo "initialising cask..."
brew tap caskroom/cask
brew tap caskroom/fonts

echo "updating brew..."
brew update
brew upgrade
brew cleanup
brew cask cleanup

echo "installing command line applications via brew..."
brew install aria2 bash bash-completion heroku hub fish git git-extras gpg python mas micro rmtrash ruby shellcheck tmux tree wget watchman vim
# as needed
# brew install zsh

if confirm "Do you want to install desktop apps?"; then
   echo "install desktop applications via brew cask..."
   brew cask install appzapper bartender devdocs firefox freedom geekbench github-desktop kodi plex-media-server screenflow skype spotify teamviewer torbrowser tower transmission typora visual-studio-code vlc
   # as needed
   # brew cask install airparrot atom burn brave calibre caption contexts ccleaner jaikoz opera pomello toggldesktop spotifree reflector sketch tunnelbear usage vmware-fusion xld
fi