#!/usr/bin/env bash
set -e

setup-git

if command_exists apt; then
	setup-linux-apt
	setup-linux-shell
	setup-linux-fonts
	setup-linux-atom
	setup-linux-vscode
elif command_exists apk; then
	setup-linux-apk
fi

setup-node

setup-vim
setup-vscode
setup-atom

setup-shell