#!/usr/bin/env bash
set -e

echo; if ! confirm "Do you want to be presented with Mac App Store apps?"; then
	exit
fi

mas signout
read -r -t 60 -p "What is your Apple Store email (is needed to install apps you've already purchased)? " answer
if is_string "$answer"; then
	echo -e "\nLogging you out and then in to the CLI app..."
	mas signout
	mas signin --dialog "$answer"

	if confirm "Install Amphetamine?"; then
		mas install 937984704
	fi
	if confirm "Install HazeOver?"; then
		mas install 430798174
	fi
	if confirm "Install Magnet?"; then
		mas install 441258766
	fi
	if confirm "Install Slack?"; then
		mas install 803453959
	fi
	if confirm "Install Wire?"; then
		mas install 931134707
	fi
	if confirm "Install XCode?"; then
		mas install 497799835
	fi

	echo -e "\nAccepting the XCode license..."
	sudo xcodebuild -license  # XCode license
else
	echo -e "\nSkipped mac app store apps install"
fi