#!/usr/bin/env bash -l
set -e

echo -e "\nAdd ssh keys to authorise updates from servers..."
addsshkeys

echo -e "\nUpdating commenced..."

setup-base
setup-mac-brew update
setup-node
setup-vim
setup-vscode
setup-atom update
setup-mac-clean

echo -e "\nUpdating completed successfully."