#!/usr/bin/env bash
set -e

function vadd {
	echo "var_add $1 \"$2\";"  # ; needed for fish
}
function vset {
	echo "var_set $1 \"$2\";"  # ; needed for fish
}

# Others
if is_dir "/usr/local/bin"; then
	vadd PATH "/usr/local/bin"
fi
if is_dir "/usr/local/man"; then
	vadd MANPATH "/usr/local/man"
fi

# Homebrew core
if is_dir "$HOME/.homebrew"; then
	vadd PATH "$HOME/.homebrew/bin"
	vadd MANPATH "$HOME/.homebrew/man"
fi

# Homebrew libs
if command_exists brew; then
	export BREW_PREFIX; BREW_PREFIX=$(brew --prefix)

	# Heroku
	if is_dir "$BREW_PREFIX/heroku/bin"; then
		vadd PATH "$BREW_PREFIX/heroku/bin"
	fi

	# Ruby
	if is_dir "$BREW_PREFIX/opt/ruby/bin"; then
		vadd PATH "$BREW_PREFIX/opt/ruby/bin"
	fi

	# icu4c (dependency of heroku)
	if is_dir "$BREW_PREFIX/opt/icu4c/bin"; then
		vadd PATH "$BREW_PREFIX/opt/icu4c/bin"
	fi
	if is_dir "$BREW_PREFIX/opt/icu4c/sbin"; then
		vadd PATH "$BREW_PREFIX/opt/icu4c/sbin"
	fi

	# Sphinx (dependency of ruby)
	if is_dir "$BREW_PREFIX/opt/sphinx-doc/bin"; then
		vadd PATH "$BREW_PREFIX/opt/sphinx-doc/bin"
	fi

	# GetText (dependency of gpg)
	if is_dir "$BREW_PREFIX/opt/gettext/bin"; then
		vadd PATH "$BREW_PREFIX/opt/gettext/bin"
	fi

	# SQLite (dependency of python)
	if is_dir "$BREW_PREFIX/opt/sqlite/bin"; then
		vadd PATH "$BREW_PREFIX/opt/sqlite/bin"
	fi

	# OpenSSL (dependency of python, gpg, and node)
	if is_dir "$BREW_PREFIX/opt/openssl/bin"; then
		vadd PATH "$BREW_PREFIX/opt/openssl/bin"
	fi
fi

# Go
if command_exists go; then
	if is_empty_string "$GOPATH"; then
		export GOPATH="$HOME/.go"
		vset GOPATH "$GOPATH"
	fi
	if is_dir "$GOPATH/bin"; then
		vadd PATH "$GOPATH/bin"
	fi
fi

# Ruby
if command_exists ruby; then
	if is_empty_string "$GEM_HOME"; then
		export GEM_HOME="$HOME/.cache/gems"
		vset GEM_HOME "$GEM_HOME"
	fi
	if is_dir "$GEM_HOME/bin"; then
		vadd PATH "$GEM_HOME/bin"
	fi
fi

# Java
vadd CLASSPATH "."

# Clojurescript
if is_dir "$HOME/.clojure/clojure-1.8"; then
	vadd PATH "$HOME/.clojure/clojure-1.8.0"
	vadd CLASSPATH "$HOME/.clojure/clojure-1.8.0"
fi

# Yarn
if command_exists yarn; then
	vadd PATH "$(yarn global bin)"
fi

# Local
if is_dir "$HOME/.bin"; then
	vadd PATH "$HOME/.bin"
fi
if is_dir "$HOME/bin"; then
	vadd PATH "$HOME/bin"
fi
