#!/usr/bin/env bash
set -e

# User
source "$HOME/.scripts/sources/user.sh"

# apt update
sudo apt-get update -y
sudo apt-get upgrade -y

# apt remove
if test -n "$APT_REMOVE"; then
	sudo apt-get remove -y --purge "$APT_REMOVE"
fi

# apt install
if test -n "$APT_ADD"; then
	sudo apt-get install -y "$APT_ADD"
fi

# apt clean
sudo apt-get clean -y
sudo apt-get autoremove -y

# snap update
sudo snap refresh