#!/usr/bin/env bash -l
set -e

# Clean brew
brew cleanup
brew cask cleanup
brew prune

# Remove updates that are not cleaned automatically
rm -Rf "$HOME/Library/Application Support/Plex Media Server/Updates"
rm -Rf "$HOME/Library/Application Support/Spotify/PersistentCache/Update"

# Remove cache
rm -Rf "$HOME/.cache"
mkdir -p "$HOME/Library/Caches"
mkdir -p "$HOME/.cache/gems"
mkdir -p "$HOME/.cache/pip/http"
mkdir -p "$HOME/Library/Caches/pip/http"

# npm
if command_exists npm; then
	nvm use node
	npm cache clean --force
	nvm use system
	npm cache clean --force
fi