#!/usr/bin/env bash -l
# uses login shell as otherwise global vars won't exist
set -e

echo -e '\nConfiguring git...'

# Prepare
if ! is_dir ~/.ssh; then
	mkdir ~/.ssh
fi
if ! is_file ~/.ssh/config; then
	touch ~/.ssh/config
fi

# General
git config --global core.excludesfile ~/.gitignore_global
git config --global push.default simple
git config --global mergetool.keepBackup false
git config --global color.ui auto
git config --global hub.protocol https

# Profile
if test -z "$(git config --global user.name)"; then
	read -r -p "What is your name? " name
	git config --global user.name "$name"
fi
if test -z "$(git config --global user.email)"; then
	read -r -p "What is your email? " email
	git config --global user.email "$email"
fi
if test -z "$(git config --global github.user)"; then
	read -r -p "What is your GitHub username? " github
	git config --global github.user "$github"
fi

# Editor
echo "Git Configuration: Editor"
if is_string "$TERMINAL_EDITOR_PROMPT"; then
	git config --global core.editor "$TERMINAL_EDITOR_PROMPT"
elif is_string "$TERMINAL_EDITOR"; then
	git config --global core.editor "$TERMINAL_EDITOR"
elif is_string "$EDITOR"; then
	git config --global core.editor "$EDITOR"
fi

# Merge tool
if command_exists meld; then
	echo "Git Configuration: Meld"
	git config --global diff.tool meld
	git config --global merge.tool meld
elif is_mac; then
	echo "Git Configuration: OpenDiff"
	git config --global diff.tool opendiff
	git config --global merge.tool opendiff
fi

# Authentication
# Use MacOS Credential Helper if available, otherwise default to time cache
if is_mac; then
	echo "Git Configuration: MacOS"
	git config --global credential.helper osxkeychain
	git config --global difftool.prompt false
	# http://apple.stackexchange.com/a/254619/15131
	if ! silent grep 'AddKeysToAgent yes' < ~/.ssh/config; then
		echo "Git Configuration: AddKeysToAgent"
		printf '\nAddKeysToAgent yes' >> ~/.ssh/config
	fi
else
	echo "Git Configuration: Linux"
	git config --global credential.helper cache
	git config credential.helper 'cache --timeout=86400'
fi

# GPG
if command_exists gpg; then
	echo "Git Configuration: GPG"
	ok killall -c gpg-agent
	ok killall -c gpg
	if command_exists krgpg && test "$KRYPTON_GPG" != "no" && confirm 'Use Krypton for GPG?'; then
		git config --global gpg.program "$(which krgpg)"
		pass git config --global --unset user.signingkey
		USE_GPG="yes"
	else
		if test -z "$GPG_SIGNING_KEY"; then
			echo "Available GPG Keys:"
			key list private
			echo "GPG Key Selection:"
			GPG_SIGNING_KEY="$(key get private)"
		fi
		if test -n "$GPG_SIGNING_KEY"; then
			echo "Git Configuration: GPG: Key: $GPG_SIGNING_KEY"
			git config --global gpg.program "$(which gpg)"
			git config --global user.signingkey "$GPG_SIGNING_KEY"
			if is_mac; then
				echo "Git Configuration: GPG: Pinentry"
				agent_file="$HOME/.gnupg/gpg-agent.conf"
				touch "$agent_file"
				if ! command_exists pinentry-mac; then
					brew install pinentry-mac
				fi
				if grep 'pinentry-program' < "$agent_file"; then
					echo 'already configured'
				else
					echo "pinentry-program $(which pinentry-mac)" >> "$agent_file"
				fi
			fi
			USE_GPG="yes"
		else
			echo "Git Configuration: No GPG signing key found"
		fi
	fi
	if test "$USE_GPG" = "yes"; then
		echo "Git Configuration: Enabling GPG"
		git config --global tag.gpgsign true
		git config --global commit.gpgsign true
		# git config --global push.gpgsign true
		# ^ github doesn’t support this with:
		# fatal: receiving end does not support --signed push
		# fatal: the receiving end does not support --signed push

		if silent grep "no-tty" "$HOME/.gnupg/gpg.conf"; then
			echo "no-tty" >> "$HOME/.gnupg/gpg.conf"
			# ^ http://github.com/isaacs/github/issues/675
		fi
	else
		echo "Git Configuration: Disabling GPG"
		pass git config --global --unset tag.gpgsign
		pass git config --global --unset commit.gpgsign
		pass git config --global --unset user.signingkey
	fi
fi

echo "Git Configuration: Summary"
git config --global --list