#!/usr/bin/env bash

# https://software.com/mac/tweaks/highlight-stacked-items-in-dock
# defaults write com.apple.dock mouse-over-hilite-stack -boolean true

# http://superuser.com/a/176197/32418
# defaults write com.apple.dock workspaces-auto-swoosh -bool false

# https://software.com/mac/tweaks/show-file-extensions-in-finder
if confirm "Show all file extensions?"; then
   defaults write NSGlobalDomain AppleShowAllExtensions -boolean true
else
   defaults delete NSGlobalDomain AppleShowAllExtensions
fi

# https://software.com/mac/tweaks/show-all-files-in-finder
if confirm "Show hidden files?"; then
   defaults write com.apple.finder AppleShowAllFiles -boolean true
else
   defaults delete com.apple.finder AppleShowAllFiles
fi

# https://software.com/mac/tweaks/hide-desktop-icons
if confirm "Hide desktop icons?"; then
   defaults write com.apple.finder CreateDesktop -bool false
else
   defaults delete com.apple.finder CreateDesktop
fi

# http://osxdaily.com/2012/04/11/disable-the-file-extension-change-warning-in-mac-os-x/
if confirm "Disable extension confirm dialog?"; then
   defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
else
   defaults delete com.apple.finder FXEnableExtensionChangeWarning
fi

# https://software.com/mac/tweaks/auto-hide-the-dock
if confirm "Hide the dock automatically?"; then
   defaults write com.apple.dock autohide -boolean true
else
   defaults delete com.apple.dock autohide
fi