#!/usr/bin/env bash
set -e

if test "$1" = "new" -o "$1" = "create"; then
	name="$2"
	size="$3"
	if test -z "$size"; then
		echo "sparse-vault new <NAME> <MAXSIZE|100g|1t>"
		exit 1
	fi
	vol=$(basename "$name")
	version=$(sw_vers -productVersion | awk -F '.' '{print $2}')
	if test "$version" -ge "13"; then
		fs="APFS"
	else
		fs="Journaled HFS+"
	fi
	type="SPARSE" # SPARSEBUNDLE
	if test "$type" = "SPARSE"; then
		filename="$2.sparseimage"
	else
		filename="$2.sparsebundle"
	fi
	hdiutil create -type "$type" -encryption AES-256 -fs "$fs" -size "$size" -volname "$vol" "$name"
	hdiutil mount "$filename"

elif test "$1" = "open" -o "$1" = "mount"; then
	hdiutil compact "$2" || echo "compact failed, continuing..."
	hdiutil mount "$2"

else
	echo "vault <new|open> <PATH>"

fi