#!/usr/bin/env bash
source "$HOME/.scripts/sources/essentials.sh"
source "$HOME/.scripts/sources/strict.bash"
source "$HOME/.scripts/sources/globstar.bash"
source "$HOME/.scripts/sources/nullglob.bash"
source "$HOME/.scripts/sources/ssh.sh"
ssh-start-helper

set -x

chmod 700 ~/.ssh
find ~/.ssh/*.pub | while read -r f; do
	chmod 600 "$f"
	ok chmod 600 "${f%.pub}"
done

find ~/.ssh/*.pub | while read -r f; do
	p="${f%.pub}"
	if test -f "$p"; then
		ssh-add -K "$p"
	fi
done