#!/usr/bin/env bash
set -e

if is-string "$1"; then
	name=$1

	comment=$name
	if is-string "$2"; then
		comment=$2
	fi

	path="$HOME/.ssh/$name"
	rm -f "$path*"
	echo "Creating new ssh-key at $path with comment $comment"
	ssh-keygen -t rsa -b 4096 -C "$comment" -f "$path"

	# add it to ssh configuration
	# http://stackoverflow.com/a/33228296/130638
	printf "\nIdentityFile ~/.ssh/$name" >> "$HOME/.ssh/config"

	# output the public key so the user can add it to the service
	echo "Public key that you can share is outputted below"
	echo "------------------------------------------------"
	cat "$path.pub"
else
	echo "ssh-new KEY_NAME [YOUR_EMAIL]"
fi