#!/usr/bin/env bash
source "$HOME/.scripts/sources/strict.bash"

scale=9
dpi=1200

function _convert {
	out="./${1%.*} [scale=$scale] [dpi=$dpi].$2"
	cairosvg --format "$2" --scale "$scale" --dpi "$dpi" --output "$out" "$1"
}

function convert {
	_convert "$1" "png"
}

if test "$#" -eq 0; then
	find-files svg | while read -r file; do
		convert "$file"
	done
else
	convert "$1"
fi
