#!/usr/bin/env bash
set -e

if is_file "$HOME/.travis/config.yml"; then
	grep access_token < "$HOME/.travis/config.yml" | sed -E 's/.+: //'
else
	stderr echo "$HOME/.travis/config.yml was not found"
	exit 1
fi