#!/bin/bash

set -e
export shell; shell=$(which $1)

if is_empty_string "$shell"; then
	echo "USAGE: usesh <shell>"
	exit -1
fi

echo "adding $shell to the standard shells"
# needed to prevent
# chpass: /Users/balupton/.homebrew/bin/fish: non-standard shell
echo "$shell" | sudo tee -a /etc/shells

echo "setting $shell as your login shell"
# chsh is identical to chpass
chpass -u "$USER" -s "$shell"
