#!/usr/bin/env bash

# don't use contains command, as it won't detect things like
# PATH=a/b
# add PATH a

function path_add {
	echo "varadd \"$1\" \"$2\";"  # ; needed for fish
}

# Others
if is_dir "/usr/local/bin"; then
	path_add PATH "/usr/local/bin"
fi
if is_dir "/usr/local/man"; then
	path_add MANPATH "/usr/local/man"
fi

# Homebrew core
if is_dir "$HOME/.homebrew"; then
	path_add PATH "$HOME/.homebrew/bin"
	path_add MANPATH "$HOME/.homebrew/man"
fi

# Homebrew libs
if command_exists brew; then
	export BREW_PREFIX; BREW_PREFIX=$(brew --prefix)

	# Heroku
	if is_dir "$BREW_PREFIX/heroku/bin"; then
		path_add PATH "$BREW_PREFIX/heroku/bin"
	fi

	# Ruby
	if is_dir "$BREW_PREFIX/opt/ruby/bin"; then
		path_add PATH "$BREW_PREFIX/opt/ruby/bin"
	fi
fi

# Go
if command_exists go; then
	if is_empty_string "$GOPATH"; then
		export GOPATH=$HOME/.go
		mkdir -p "$GOPATH"
	fi
	path_add PATH "$GOPATH/bin"
fi

# Ruby
if command_exists ruby; then
	if is_empty_string "$GEM_HOME"; then
		export GEM_HOME=$HOME/.cache/gems
		mkdir -p "$GEM_HOME"
	fi
	path_add PATH "$GEM_HOME/bin"
fi

# Java
if is_empty_string "$CLASSPATH"; then
	path_add CLASSPATH "."
fi

# Clojurescript
if is_dir "$HOME/.clojure/clojure-1.8"; then
	path_add PATH "$HOME/.clojure/clojure-1.8.0"
	path_add CLASSPATH "$HOME/.clojure/clojure-1.8.0"
fi

# Yarn
if command_exists yarn; then
	path_add PATH "$(yarn global bin)"
fi

# Local
if is_dir "$HOME/bin"; then
	path_add PATH "$HOME/bin"
fi

# Add local npm executables
path_add PATH "./node_modules/.bin"
