#!/bin/bash

# Visual Studio Code Customisations
function vscodeinstall {
	for ARG in "$@"; do
		code --install-extension "$ARG"
	done
}
function vscodesetup {
	# Install extensions
	vscodeinstall EditorConfig.EditorConfig akamud.vscode-caniuse akamud.vscode-theme-onelight bernardodsanderson.theme-material-neutral christian-kohler.npm-intellisense dbaeumer.vscode-eslint flowtype.flow-for-vscode gerane.Theme-IDLE slb235.vscode-coffeelint timonwong.shellcheck

	# Customise settings
	ln -f "$HOME/.vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
	ln -f "$HOME/.vscode/keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"

	# Customise stylesheets
	local app; app=$(getapp Visual Studio Code.app)
	local stylesheet

	# https://github.com/Microsoft/vscode/issues/1896#issuecomment-283858289
	stylesheet="$app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css"
	if is_file "$stylesheet"; then
		if silent grep 'fix font rendering' < "$stylesheet"; then
			echo "setup already completed"
		else
			echo "
			/* fix font rendering */
			.monaco-editor {
				-webkit-font-smoothing: none !important;
				-webkit-font-smoothing: antialiased !important;
				-webkit-font-smoothing: subpixel-antialiased !important;
				text-rendering: auto !important;
				text-rendering: optimizeSpeed !important;
				text-rendering: optimizeLegibility !important;
				text-rendering: geometricPrecision !important;
			}" >> "$stylesheet"
			echo "setup completed"
		fi
	else
		echo "vscode not installed"
	fi

	# https://github.com/akamud/vscode-theme-onelight/pull/2
	stylesheet=$(expandpath "$HOME/.vscode/extensions/akamud.vscode-theme-onelight-*/themes/OneLight.tmTheme")
	if is_file "$stylesheet"; then
		echo "fixing theme"
		sed -e 's/#FAFAFA/#FFFFFF/' -e 's/#F2F2F2/#F5F5F5/' < "$stylesheet" > "$stylesheet.tmp"
		mv -f "$stylesheet.tmp" "$stylesheet"
		echo "fixed theme"
	else
		echo "theme not installed"
	fi
}

vscodesetup