#!/usr/bin/env bash

function choose_menu() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='choose-menu' --bold=' has been deprecated in favor of ' --code='choose --index'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	choose_menu "$@"
fi
