#!/usr/bin/env bash

function choose_option() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='choose-option' --bold=' has been deprecated in favor of ' --code='choose'

	# =====================================
	# Action

	choose "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	choose_option "$@"
fi
