#!/usr/bin/env bash

function echo_filenames() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			For each input, output the filename (basename without extension).

			USAGE:
			echo-filenames [...options] [--] ...<input>
			echo-lines ...<input> | echo-filenames [...options]

			OPTIONS:
			$(__stdinargs__help_options --)

			EXAMPLE:

			echo-filename -- 'a/b/c.d'

			    c
			    # exit status: 0

			echo-lines -- 'a/b/c.d' | echo-filenames --stdin

			    c
			    # exit status: 0
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	function on_line {
		fs-filename --basename -- "$1"
	}

	stdinargs "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_filenames "$@"
fi
