#!/usr/bin/env bash

function echo_title() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='echo-title' --bold=' has been deprecated in favor of ' --code='echo-style --tty --title=...'

	# =====================================
	# Action

	echo-style --tty --title="$*"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_title "$@"
fi
