#!/usr/bin/env bash

function echo_filenames() (
	source "$DOROTHY/sources/stdinargs.bash"
	dorothy-warnings crash --code='echo-filenames' --bold=' has been deprecated in favor of ' --code='fs-path --no-parents --no-extensions'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_filenames "$@"
fi
