#!/usr/bin/env bash

function echo_quiet_enabled() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='echo-quiet-enabled' --bold=' has been deprecated in favor of ' --code='get-terminal-quiet-support'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_quiet_enabled "$@"
fi
