#!/usr/bin/env bash

function echo_if_directory() (
	source "$DOROTHY/sources/stdinargs.bash"
	dorothy-warnings add --code='echo-if-directory' --bold=' has been deprecated in favor of ' --code='is-directory --echo --optional'

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Output <input>s that are a directory, or an unbroken symlink to a directory.
			Companion to: $(__join --style=code --between=', ' -- 'is-directory').

			USAGE:
			\`echo-if-directory [...options] [--] ...<input>\`
			\`echo-lines ...<input> | echo-if-directory [...options]\`

			OPTIONS:
			--elevated=<elevated>
			--elevate=<elevate>
			--user=<user>
			--group=<group>
			--reason=<reason>
			    Forwarded to \`eval-helper\`

			$(__stdinargs__help_options --)

			EXAMPLES:
			\`\`\`
			echo-if-directory -- "$HOME"
			echo-lines -- "$HOME" | echo-if-directory --stdin
			\`\`\`
			Outputs: \`$HOME\`
			Returns: [0]
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_args=() option_elevated='' option_elevate='' option_user='' option_group='' option_reason=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		# <elevate>
		'--elevated='*) option_elevated="${item#*=}" ;;
		'--no-elevate'* | '--elevate'*) __flag --source={item} --target={option_elevate} --affirmative --no-coerce ;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--reason='*) option_reason="${item#*=}" ;;
		# </elevate>
		# forward to stdinargs, however support mixing and matching of our options, with stdinargs options
		'--')
			option_args+=("$item" "$@")
			shift $#
			break
			;;
		*) option_args+=("$item") ;;
		esac
	done

	# =====================================
	# Action

	function __on_piece {
		local path="$1"
		if is-directory --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- "$path"; then
			__print_lines "$path"
		fi
	}

	stdinargs "${option_args[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_if_directory "$@"
fi
