#!/usr/bin/env bash

function echo_checksum() (
	source "$DOROTHY/sources/stdinargs.bash"
	dorothy-warnings add --code='echo-checksum' --bold=' has been deprecated in favor of ' --code='checksum'

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Checksum each <input> string.
			To checksum files or directories, use [checksum] instead.

			USAGE:
			echo-checksum [...options] [--] ...<input>
			echo-lines ...<input> | echo-checksum [...options]

			OPTIONS:
			--algorithm=<algorithm>
			    Force a specific algorithm to be used.

			$(stdinargs_options_help --)
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process our own arguments, delegate everything else to stdinargs
	local item option_algorithm='' option_args=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-color'* | '--color'*) __flag --source={item} --target={COLOR} --affirmative --export ;;
		'--algorithm='*) option_algorithm="${item#*=}" ;;
		# forward to stdinargs, however support mixing and matching of our options, with stdinargs options
		'--')
			option_args+=("$item" "$@")
			shift $#
			break
			;;
		*) option_args+=("$item") ;;
		esac
	done

	# =====================================
	# Action

	function on_line {
		checksum --algorithm="$option_algorithm" --string="$1"
	}

	stdinargs "${option_args[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_checksum "$@"
fi
