#!/usr/bin/env bash

function echo_quier_enabled() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='echo-quier-enabled' --bold=' has been deprecated in favor of ' --code='get-terminal-quier-support'

	# =====================================
	# Action

	get-terminal-quier-support
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo_quier_enabled "$@"
fi
