#!/usr/bin/env bash

function fs_ln() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='fs-ln' --bold=' has been renamed to ' --code='fs-link'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	fs_ln "$@"
fi
