#!/usr/bin/env bash

function fs_mv() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='fs-mv' --bold=' has been renamed to ' --code='fs-move'

	# =====================================
	# Action

	fs-move "$@"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	fs_mv "$@"
fi
