#!/usr/bin/env bash

function fs_parents() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='fs-parents' --bold=' has been deprecated in favor of ' --code='[[ $(pwd) == "$path"* ]]'

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Output all parent paths of a <path>.

			USAGE:
			fs-parents [...options] [--] ...<path>

			OPTIONS:
			--self
			    If specified, include the <path> in the output.
			--root
			    If specified, include the root directory in the output.

			--elevated=<elevated>
			--elevate=<elevate>
			--user=<user>
			--group=<group>
			--reason=<reason>
			    Forwarded to [fs-path --absolute].

			QUIRKS:
			Use [fs-path] if you want symlinks resolved.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_paths=() option_self='no' option_root='no' option_elevated='' option_elevate='' option_user='' option_group='' option_reason=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--no-self'* | '--self'*) __flag --source={item} --target={option_self} --affirmative ;;
		'--no-root'* | '--root'*) __flag --source={item} --target={option_root} --affirmative ;;
		# <elevate>
		'--elevated='*) option_elevated="${item#*=}" ;;
		'--no-elevate'* | '--elevate'*) __flag --source={item} --target={option_elevate} --affirmative --no-coerce ;;
		'--user='*) option_user="${item#*=}" ;;
		'--group='*) option_group="${item#*=}" ;;
		'--reason='*) option_reason="${item#*=}" ;;
		# </elevate>
		'--')
			option_paths+=("$@")
			shift $#
			break
			;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) option_paths+=("$item") ;;
		esac
	done

	# check
	if [[ ${#option_paths[@]} -eq 0 ]]; then
		help 'No <path>s provided.'
	fi

	# =====================================
	# Act

	local path temp paths i
	for path in "${option_paths[@]}"; do
		paths=()
		path="$(fs-path --absolute --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- "$path")"
		if [[ $option_self == 'yes' ]]; then
			paths+=("$path")
		fi
		while [[ $path != '/' ]]; do
			temp="$(fs-path --absolute --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- "$path/..")"
			if [[ $temp == "$path" || ($temp == '/' && $option_root == 'no') ]]; then
				break
			fi
			paths+=("$temp")
			path="$temp"
		done
		# out paths in reverse order, so topmost first
		for ((i = "${#paths[@]}" - 1; i >= 0; i--)); do
			__print_lines "${paths[i]}"
		done
	done
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	fs_parents "$@"
fi
