#!/usr/bin/env bash

function get_git_active_branch() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='get-git-active-branch' --bold=' has been deprecated in favor of ' --code='git-helper active-branch'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	get_git_active_branch "$@"
fi
