#!/usr/bin/env bash

function get_git_active_branch() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='get-git-active-branch' --bold=' has been deprecated in favor of ' --code='git-helper active-branch'

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Get the active branch of the local repository.

			USAGE:
			\`get-git-active-branch\`
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*) help 'An unrecognised argument was provided: ' --variable-value={item} ;;
		esac
	done

	# =======================================================
	# Action

	git-helper current-branch
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	get_git_active_branch "$@"
fi
