#!/usr/bin/env bash

function is_array_count_ge() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='is-array-count-ge' --bold=' has been deprecated in favor of ' --code='echo-trim-empty-lines'

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Check if the array contains greater than or equal to the specified number of elements.
			If the array contains empty elements, [2] will be returned.

			USAGE:
			is-array-count-ge <size> [--] ...<element>

			OPTIONS:
			<size> | --size=<size>
			    How many elements to expect at a minimum.

			<element>
			    An element of the array.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_size='' option_inputs=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--size='*) option_size="${item#*=}" ;;
		'--')
			option_inputs+=("$@")
			shift "$#"
			break
			;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*)
			if [[ -z $option_size ]]; then
				option_size="$item"
			else
				option_inputs+=("$item" "$@")
				shift "$#"
				break
			fi
			;;
		esac
	done

	# check
	if [[ -z $option_size ]]; then
		help '<size> is required'
	fi
	if ! __is_integer "$option_size"; then
		help '<size> was not an integer'
	fi

	# =====================================
	# Action

	if [[ "$(get-array-count -- "${option_inputs[@]}")" -ge $option_size ]]; then
		return 0
	else
		return 1
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_array_count_ge "$@"
fi
