#!/usr/bin/env bash

function is_array_partial() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='is-array-partial' --bold=' has been deprecated in favor of ' --code='is-whitespace' --bold=' and ' --code='is-not-whitespace'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_array_partial "$@"
fi
