#!/usr/bin/env bash

function is_array_count() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='is-array-count' --bold=' has been deprecated in favor of ' --code='echo-trim-empty-lines'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_array_count "$@"
fi
