#!/usr/bin/env bash

# is the array full / complete?

# failure if any value is empty
# pass if all values are truthy

function is_array_full() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='is-array-full' --bold=' has been deprecated in favor of ' --code='is-not-whitespace'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_array_full "$@"
fi
