#!/usr/bin/env bash

function is_color_enabled() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='is-color-enabled' --bold=' has been deprecated in favor of ' --code='get-terminal-color-support --quiet'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	is_color_enabled "$@"
fi
