#!/usr/bin/env bash

function is_match_test() (
	source "$DOROTHY/sources/bash.bash"
	eval-tester --ignore-stderr --status=22 -- is-match --help

	eval-tester --name='match works' -- \
		is-match 'a +haystack ?' 'a  haystack'

	eval-tester --name='match works' -- \
		is-match -i 'Z|B' 'abc'

	eval-tester --name='no match works' --status=1 -- \
		is-match -i 'Z|Y' 'abc'

	return 0
)
function is_match() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings add --code='is-match --pattern=<pattern> --input=<input>' --bold=' has been deprecated in favor of ' --code='echo-regexp -q --regexp=<regexp> - <input>'

	# =====================================
	# Arguments

	function help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Checks if the input matches the pattern.

			USAGE:
			\`is-match [...options]\`
			\`is-match [...options] <pattern> <input>\`

			OPTIONS:
			<pattern> | --pattern=<pattern>
			    The rust regular expression to use.

			<input> | --input=<input>
			    The input to check against the pattern.

			-i | --ignore-case
			    Ignore case when matching.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_pattern='' option_input='' option_ignore_case='no'
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--pattern='*) option_pattern="${item#*=}" ;;
		'--input='*) option_input="${item#*=}" ;;
		'-i') option_ignore_case='yes' ;;
		'--no-ignore-case'* | '--ignore-case'*) __flag --source={item} --target={option_ignore_case} --affirmative ;;
		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
		*)
			if [[ -z $option_pattern ]]; then
				option_pattern="$item"
			elif [[ -z $option_input ]]; then
				option_input="$item"
			else
				help 'An unrecognised argument was provided: ' --variable-value={item}
			fi
			;;
		esac
	done

	# =====================================
	# Action

	local cmd=(
		echo-regexp -q --regexp="$option_pattern"
	)
	if [[ $option_ignore_case == 'yes' ]]; then
		cmd+=('--ignore-case')
	fi
	"${cmd[@]}" -- "$option_input"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	if [[ $* == '--test' ]]; then
		is_match_test
	else
		is_match "$@"
	fi
fi
