#!/usr/bin/env bash

function rm_junk() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='rm-junk' --bold=' has been deprecated in favor of ' --code='fs-trim --cache')

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	rm_junk "$@"
fi
