#!/usr/bin/env bash

function rm_modules() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='rm-modules' --bold=' has been deprecated in favor of ' --code='fs-trim --module'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	rm_modules "$@"
fi
