#!/usr/bin/env bash

# https://packages.debian.org/sid/amd64/openssh-server/filelist

function setup_util_sshd() (
	source "$DOROTHY/sources/bash.bash"
	dorothy-warnings crash --code='setup-util-sshd' --bold=' has been deprecated in favor of ' --code='setup-util-ssh'
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	setup_util_sshd "$@"
fi
