#!/usr/bin/env bash

# Prior version here: https://gist.github.com/balupton/fba72b246ec65aa5fc8a9588e35f1125

function twitter_helper() (
	source "$DOROTHY/sources/bash.bash"
	__print_error --help='The `twitter-helper` command has been deprecated and removed, as X no longer provides reasonable API access.'
	return 105 # EOWNERDEAD 105 Previous owner died
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	twitter_helper "$@"
fi
