name: "Dorothy Test"
description: "Runs Dorothy's test suite via remote invocation."
inputs:
  GITHUB_TOKEN:
    description: "Used to increase rate limits. Should be read-only."
    required: true
runs:
  using: "composite"
  steps:
    - name: "Dorothy Test"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        # ensure dorothy is cloned, and run command
        bash -c "$(curl -fsSL 'https://dorothy.bevry.me/test?slug=${{ github.event.pull_request.head.repo.full_name || github.repository }}&commit=${{ github.event.pull_request.head.sha || github.sha }}')"
# outputs:
#   example-output:
#     description: "An example output"r
#     value: ${{ steps.set-output.outputs.example-output }}
